dataprobes_data = ["Basic Probe", #https://xenoblade.github.io/xbx/bdat/common_local_us/ITM_BeaconList.html
"Mining Probe G1",
"Mining Probe G2",
"Mining Probe G3",
"Mining Probe G4",
"Mining Probe G5",
"Mining Probe G6",
"Mining Probe G7",
"Mining Probe G8",
"Mining Probe G9",
"Mining Probe G10",
"ITM_BCN_MINE_011_name",
"ITM_BCN_MINE_012_name",
"Research Probe G1",
"Research Probe G2",
"Research Probe G3",
"Research Probe G4",
"Research Probe G5",
"Research Probe G6",
"ITM_BCN_TOUR_007_name",
"ITM_BCN_TOUR_008_name",
"Booster Probe G1",
"Booster Probe G2",
"ITM_BCN_RAISE_003_name",
"ITM_BCN_RAISE_004_name",
"Storage Probe",
"ITM_BCN_STORAGE_002_name",
"ITM_BCN_STORAGE_003_name",
"Duplicator Probe",
"Fuel Recovery Probe",
"Melee Attack Probe",
"Ranged Attack Probe",
"EZ Debuff Probe",
"Attribute Resistance Probe",
"ITM_BCN_BTL_006_name",
"ITM_BCN_BTL_007_name",
"ITM_BCN_BTL_008_name",
"ITM_BCN_BTL_009_name",
"ITM_BCN_BTL_010_name",
]