ground_weapons_data = ["Combat Assault Rifle", #https://xenoblade.github.io/xbx/bdat/common_local_us/WPN_PcList.html
"Combat Sniper Rifle",
"Combat Dual Guns",
"Combat Gatling Gun",
"Combat Raygun",
"Combat Psycho Launchers",
"Combat Longsword",
"Combat Javelin",
"Combat Dual Swords",
"Combat Shield",
"Combat Knife",
"Combat Photon Saber",
"Busted Rifle",
"Busted Knife",
"Ramjet Rifle",
"Ramjet Rifle",
"Sparkjet Rifle",
"Adelbert",
"Grette",
"Unbreakable Sword",
"Hundred Devil Sword",
"Scrap Duo",
"Diagonal Twins",
"Hyde Dyads",
"Savage Ziyse",
"Iron Sword",
"Iron Sword",
"Iron Sword",
"Titanium Sword",
"Titanium Sword",
"Titanium Sword",
"Chrome Sword",
"Chrome Sword",
"Chrome Sword",
"Cobalt Sword",
"Cobalt Sword",
"Cobalt Sword",
"Chromoly Sword",
"Chromoly Sword",
"Chromoly Sword",
"Cermet Sword",
"Cermet Sword",
"Cermet Sword",
"Carbide Sword",
"Carbide Sword",
"Carbide Sword",
"Iron Sword II",
"Iron Sword II",
"Iron Sword II",
"Titanium Sword II",
"Titanium Sword II",
"Titanium Sword II",
"Chrome Sword II",
"Chrome Sword II",
"Chrome Sword II",
"Cobalt Sword II",
"Cobalt Sword II",
"Cobalt Sword II",
"Chromoly Sword II",
"Chromoly Sword II",
"Chromoly Sword II",
"Cermet Sword II",
"Cermet Sword II",
"Cermet Sword II",
"Carbide Sword II",
"Carbide Sword II",
"Carbide Sword II",
"Iron Slair",
"Iron Slair",
"Iron Slair",
"Titanium Slair",
"Titanium Slair",
"Titanium Slair",
"Chrome Slair",
"Chrome Slair",
"Chrome Slair",
"Cobalt Slair",
"Cobalt Slair",
"Cobalt Slair",
"Chromoly Slair",
"Chromoly Slair",
"Chromoly Slair",
"Cermet Slair",
"Cermet Slair",
"Cermet Slair",
"Carbide Slair",
"Carbide Slair",
"Carbide Slair",
"Iron Slair II",
"Iron Slair II",
"Iron Slair II",
"Titanium Slair II",
"Titanium Slair II",
"Titanium Slair II",
"Chrome Slair II",
"Chrome Slair II",
"Chrome Slair II",
"Cobalt Slair II",
"Cobalt Slair II",
"Cobalt Slair II",
"Chromoly Slair II",
"Chromoly Slair II",
"Chromoly Slair II",
"Cermet Slair II",
"Cermet Slair II",
"Cermet Slair II",
"Carbide Slair II",
"Carbide Slair II",
"Carbide Slair II",
"Iron Spatha",
"Iron Spatha",
"Iron Spatha",
"Titanium Spatha",
"Titanium Spatha",
"Titanium Spatha",
"Chrome Spatha",
"Chrome Spatha",
"Chrome Spatha",
"Cobalt Spatha",
"Cobalt Spatha",
"Cobalt Spatha",
"Chromoly Spatha",
"Chromoly Spatha",
"Chromoly Spatha",
"Cermet Spatha",
"Cermet Spatha",
"Cermet Spatha",
"Carbide Spatha",
"Carbide Spatha",
"Carbide Spatha",
"Iron Pride",
"Iron Pride",
"Iron Pride",
"Titanium Pride",
"Titanium Pride",
"Titanium Pride",
"Chrome Pride",
"Chrome Pride",
"Chrome Pride",
"Cobalt Pride",
"Cobalt Pride",
"Cobalt Pride",
"Chromoly Pride",
"Chromoly Pride",
"Chromoly Pride",
"Cermet Pride",
"Cermet Pride",
"Cermet Pride",
"Carbide Pride",
"Carbide Pride",
"Carbide Pride",
"IW_MU_F_SWORD_A06_0101_name",
"IW_MU_F_SWORD_A06_0101_name",
"IW_MU_F_SWORD_A06_0101_name",
"IW_MU_F_SWORD_A05_1001_name",
"IW_MU_F_SWORD_A05_1001_name",
"IW_MU_F_SWORD_A05_1001_name",
"Faithful Glaive",
"Faithful Glaive",
"Faithful Glaive",
"Steelbreaker Glaive",
"Steelbreaker Glaive",
"Steelbreaker Glaive",
"Pulverizing Glaive",
"Pulverizing Glaive",
"Pulverizing Glaive",
"Intrepid Glaive",
"Intrepid Glaive",
"Intrepid Glaive",
"Audacious Glaive",
"Audacious Glaive",
"Audacious Glaive",
"IW_MU_F_SWORD_B04_0101_name",
"IW_MU_F_SWORD_B04_0101_name",
"IW_MU_F_SWORD_B04_0101_name",
"IW_MU_F_SWORD_B05_1001_name",
"IW_MU_F_SWORD_B05_1001_name",
"IW_MU_F_SWORD_B05_1001_name",
"Faithful Glaive II",
"Faithful Glaive II",
"Faithful Glaive II",
"Steelbreaker Glaive II",
"Steelbreaker Glaive II",
"Steelbreaker Glaive II",
"Pulverizing Glaive II",
"Pulverizing Glaive II",
"Pulverizing Glaive II",
"Intrepid Glaive II",
"Intrepid Glaive II",
"Intrepid Glaive II",
"Audacious Glaive II",
"Audacious Glaive II",
"Audacious Glaive II",
"Advanced Iron Sword",
"Worn Titanium Sword",
"Advanced Titanium Sword",
"Worn Chrome Sword",
"Advanced Chrome Sword",
"Worn Cobalt Sword",
"Advanced Cobalt Sword",
"Worn Chromoly Sword",
"Advanced Chromoly Sword",
"Worn Cermet Sword",
"Advanced Cermet Sword",
"Worn Carbide Sword",
"Advanced Iron Sword II",
"Worn Titanium Sword II",
"Advanced Titanium Sword II",
"Worn Chrome Sword II",
"Advanced Chrome Sword II",
"Worn Cobalt Sword II",
"Advanced Cobalt Sword II",
"Worn Chromoly Sword II",
"Advanced Chromoly Sword II",
"Worn Cermet Sword II",
"Advanced Cermet Sword II",
"Worn Carbide Sword II",
"Advanced Iron Slair",
"Worn Titanium Slair",
"Advanced Titanium Slair",
"Worn Chrome Slair",
"Advanced Chrome Slair",
"Worn Cobalt Slair",
"Advanced Cobalt Slair",
"Worn Chromoly Slair",
"Advanced Chromoly Slair",
"Worn Cermet Slair",
"Advanced Cermet Slair",
"Worn Carbide Slair",
"Advanced Iron Slair II",
"Worn Titanium Slair II",
"Advanced Titanium Slair II",
"Worn Chrome Slair II",
"Advanced Chrome Slair II",
"Worn Cobalt Slair II",
"Advanced Cobalt Slair II",
"Worn Chromoly Slair II",
"Advanced Chromoly Slair II",
"Worn Cermet Slair II",
"Advanced Cermet Slair II",
"Worn Carbide Slair II",
"Worn Chrome Spatha",
"Advanced Chrome Spatha",
"Worn Cobalt Spatha",
"Advanced Cobalt Spatha",
"Worn Chromoly Spatha",
"Advanced Chromoly Spatha",
"Worn Cermet Spatha",
"Advanced Cermet Spatha",
"Worn Carbide Spatha",
"Advanced Chrome Pride",
"Worn Cobalt Pride",
"Advanced Cobalt Pride",
"Worn Chromoly Pride",
"Advanced Chromoly Pride",
"Worn Cermet Pride",
"Advanced Cermet Pride",
"Worn Carbide Pride",
"Advanced Steelbreaker Glaive",
"Worn Pulverizing Glaive",
"Advanced Pulverizing Glaive",
"Worn Intrepid Glaive",
"Advanced Intrepid Glaive",
"Worn Audacious Glaive",
"Advanced Steelbreaker Glaive II",
"Worn Pulverizing Glaive II",
"Advanced Pulverizing Glaive II",
"Worn Intrepid Glaive II",
"Advanced Intrepid Glaive II",
"Worn Audacious Glaive II",
"Ultra Ceramic Sword",
"Ultra Diamond Sword",
"Ultra Ceramic Sword II",
"Ultra Diamond Sword II",
"Ultra Ceramic Slair",
"Ultra Diamond Slair",
"Ultra Ceramic Slair II",
"Ultra Diamond Slair II",
"Ultra Ceramic Spatha",
"Ultra Diamond Spatha",
"Ultra Ceramic Pride",
"Ultra Diamond Pride",
"Ultra Godbreaker Glaive",
"Ultra Phenomenon Glaive",
"Ultra Godbreaker Glaive II",
"Ultra Phenomenon Glaive II",
"Iron Blades",
"Iron Blades",
"Iron Blades",
"Titanium Blades",
"Titanium Blades",
"Titanium Blades",
"Chrome Blades",
"Chrome Blades",
"Chrome Blades",
"Cobalt Blades",
"Cobalt Blades",
"Cobalt Blades",
"Chromoly Blades",
"Chromoly Blades",
"Chromoly Blades",
"Cermet Blades",
"Cermet Blades",
"Cermet Blades",
"Carbide Blades",
"Carbide Blades",
"Carbide Blades",
"Iron Blades II",
"Iron Blades II",
"Iron Blades II",
"Titanium Blades II",
"Titanium Blades II",
"Titanium Blades II",
"Chrome Blades II",
"Chrome Blades II",
"Chrome Blades II",
"Cobalt Blades II",
"Cobalt Blades II",
"Cobalt Blades II",
"Chromoly Blades II",
"Chromoly Blades II",
"Chromoly Blades II",
"Cermet Blades II",
"Cermet Blades II",
"Cermet Blades II",
"Carbide Blades II",
"Carbide Blades II",
"Carbide Blades II",
"Iron Ralzes",
"Iron Ralzes",
"Iron Ralzes",
"Titanium Ralzes",
"Titanium Ralzes",
"Titanium Ralzes",
"Chrome Ralzes",
"Chrome Ralzes",
"Chrome Ralzes",
"Cobalt Ralzes",
"Cobalt Ralzes",
"Cobalt Ralzes",
"Chromoly Ralzes",
"Chromoly Ralzes",
"Chromoly Ralzes",
"Cermet Ralzes",
"Cermet Ralzes",
"Cermet Ralzes",
"Carbide Ralzes",
"Carbide Ralzes",
"Carbide Ralzes",
"Iron Gladiis",
"Iron Gladiis",
"Iron Gladiis",
"Titanium Gladiis",
"Titanium Gladiis",
"Titanium Gladiis",
"Chrome Gladiis",
"Chrome Gladiis",
"Chrome Gladiis",
"Cobalt Gladiis",
"Cobalt Gladiis",
"Cobalt Gladiis",
"Chromoly Gladiis",
"Chromoly Gladiis",
"Chromoly Gladiis",
"Cermet Gladiis",
"Cermet Gladiis",
"Cermet Gladiis",
"Carbide Gladiis",
"Carbide Gladiis",
"Carbide Gladiis",
"Iron Twins",
"Iron Twins",
"Iron Twins",
"Titanium Twins",
"Titanium Twins",
"Titanium Twins",
"Chrome Twins",
"Chrome Twins",
"Chrome Twins",
"Cobalt Twins",
"Cobalt Twins",
"Cobalt Twins",
"Chromoly Twins",
"Chromoly Twins",
"Chromoly Twins",
"Cermet Twins",
"Cermet Twins",
"Cermet Twins",
"Carbide Twins",
"Carbide Twins",
"Carbide Twins",
"Iron Watxes",
"Iron Watxes",
"Iron Watxes",
"Titanium Watxes",
"Titanium Watxes",
"Titanium Watxes",
"Chrome Watxes",
"Chrome Watxes",
"Chrome Watxes",
"Cobalt Watxes",
"Cobalt Watxes",
"Cobalt Watxes",
"Chromoly Watxes",
"Chromoly Watxes",
"Chromoly Watxes",
"Cermet Watxes",
"Cermet Watxes",
"Cermet Watxes",
"Carbide Watxes",
"Carbide Watxes",
"Carbide Watxes",
"IW_MU_F_DUALBLADE_A04_0101_name",
"IW_MU_F_DUALBLADE_A04_0101_name",
"IW_MU_F_DUALBLADE_A04_0101_name",
"IW_MU_F_DUALBLADE_A05_1001_name",
"IW_MU_F_DUALBLADE_A05_1001_name",
"IW_MU_F_DUALBLADE_A05_1001_name",
"Faithful Edges II",
"Faithful Edges II",
"Faithful Edges II",
"Steelbreaker Edges II",
"Steelbreaker Edges II",
"Steelbreaker Edges II",
"Pulverizing Edges II",
"Pulverizing Edges II",
"Pulverizing Edges II",
"Intrepid Edges II",
"Intrepid Edges II",
"Intrepid Edges II",
"Audacious Edges II",
"Audacious Edges II",
"Audacious Edges II",
"IW_MU_F_DUALBLADE_B04_0101_name",
"IW_MU_F_DUALBLADE_B04_0101_name",
"IW_MU_F_DUALBLADE_B04_0101_name",
"IW_MU_F_DUALBLADE_B05_1001_name",
"IW_MU_F_DUALBLADE_B05_1001_name",
"IW_MU_F_DUALBLADE_B05_1001_name",
"Faithful Edges",
"Faithful Edges",
"Faithful Edges",
"Steelbreaker Edges",
"Steelbreaker Edges",
"Steelbreaker Edges",
"Pulverizing Edges",
"Pulverizing Edges",
"Pulverizing Edges",
"Intrepid Edges",
"Intrepid Edges",
"Intrepid Edges",
"Audacious Edges",
"Audacious Edges",
"Audacious Edges",
"Advanced Iron Blades",
"Worn Titanium Blades",
"Advanced Titanium Blades",
"Worn Chrome Blades",
"Advanced Chrome Blades",
"Worn Cobalt Blades",
"Advanced Cobalt Blades",
"Worn Chromoly Blades",
"Advanced Chromoly Blades",
"Worn Cermet Blades",
"Advanced Cermet Blades",
"Worn Carbide Blades",
"Advanced Iron Blades II",
"Worn Titanium Blades II",
"Advanced Titanium Blades II",
"Worn Chrome Blades II",
"Advanced Chrome Blades II",
"Worn Cobalt Blades II",
"Advanced Cobalt Blades II",
"Worn Chromoly Blades II",
"Advanced Chromoly Blades II",
"Worn Cermet Blades II",
"Advanced Cermet Blades II",
"Worn Carbide Blades II",
"Advanced Iron Ralzes",
"Worn Titanium Ralzes",
"Advanced Titanium Ralzes",
"Worn Chrome Ralzes",
"Advanced Chrome Ralzes",
"Worn Cobalt Ralzes",
"Advanced Cobalt Ralzes",
"Worn Chromoly Ralzes",
"Advanced Chromoly Ralzes",
"Worn Cermet Ralzes",
"Advanced Cermet Ralzes",
"Worn Carbide Ralzes",
"Worn Chrome Gladiis",
"Advanced Chrome Gladiis",
"Worn Cobalt Gladiis",
"Advanced Cobalt Gladiis",
"Worn Chromoly Gladiis",
"Advanced Chromoly Gladiis",
"Worn Cermet Gladiis",
"Advanced Cermet Gladiis",
"Worn Carbide Gladiis",
"Advanced Chrome Twins",
"Worn Cobalt Twins",
"Advanced Cobalt Twins",
"Worn Chromoly Twins",
"Advanced Chromoly Twins",
"Worn Cermet Twins",
"Advanced Cermet Twins",
"Worn Carbide Twins",
"Worn Cobalt Watxes",
"Advanced Cobalt Watxes",
"Worn Chromoly Watxes",
"Advanced Chromoly Watxes",
"Worn Cermet Watxes",
"Advanced Cermet Watxes",
"Worn Carbide Watxes",
"Advanced Steelbreaker Edges II",
"Worn Pulverizing Edges II",
"Advanced Pulverizing Edges II",
"Worn Intrepid Edges II",
"Advanced Intrepid Edges II",
"Worn Audacious Edges II",
"Advanced Steelbreaker Edges",
"Worn Pulverizing Edges",
"Advanced Pulverizing Edges",
"Worn Intrepid Edges",
"Advanced Intrepid Edges",
"Worn Audacious Edges",
"Ultra Ceramic Blades",
"Ultra Diamond Blades",
"Ultra Ceramic Blades II",
"Ultra Diamond Blades II",
"Ultra Ceramic Ralzes",
"Ultra Diamond Ralzes",
"Ultra Ceramic Gladiis",
"Ultra Diamond Gladiis",
"Ultra Ceramic Twins",
"Ultra Diamond Twins",
"Ultra Ceramic Watxes",
"Ultra Diamond Watxes",
"Ultra Godbreaker Edges II",
"Ultra Phenomenon Edges II",
"Ultra Godbreaker Edges",
"Ultra Phenomenon Edges",
"Proto Knife",
"Iron Knife",
"Iron Knife",
"Iron Knife",
"Titanium Knife",
"Titanium Knife",
"Titanium Knife",
"Chrome Knife",
"Chrome Knife",
"Chrome Knife",
"Cobalt Knife",
"Cobalt Knife",
"Cobalt Knife",
"Chromoly Knife",
"Chromoly Knife",
"Chromoly Knife",
"Cermet Knife",
"Cermet Knife",
"Cermet Knife",
"Carbide Knife",
"Carbide Knife",
"Carbide Knife",
"Iron Knife III",
"Iron Knife III",
"Iron Knife III",
"Titanium Knife III",
"Titanium Knife III",
"Titanium Knife III",
"Chrome Knife III",
"Chrome Knife III",
"Chrome Knife III",
"Cobalt Knife III",
"Cobalt Knife III",
"Cobalt Knife III",
"Chromoly Knife III",
"Chromoly Knife III",
"Chromoly Knife III",
"Cermet Knife III",
"Cermet Knife III",
"Cermet Knife III",
"Carbide Knife III",
"Carbide Knife III",
"Carbide Knife III",
"Iron Knife II",
"Iron Knife II",
"Iron Knife II",
"Titanium Knife II",
"Titanium Knife II",
"Titanium Knife II",
"Chrome Knife II",
"Chrome Knife II",
"Chrome Knife II",
"Cobalt Knife II",
"Cobalt Knife II",
"Cobalt Knife II",
"Chromoly Knife II",
"Chromoly Knife II",
"Chromoly Knife II",
"Cermet Knife II",
"Cermet Knife II",
"Cermet Knife II",
"Carbide Knife II",
"Carbide Knife II",
"Carbide Knife II",
"Iron Riv",
"Iron Riv",
"Iron Riv",
"Titanium Riv",
"Titanium Riv",
"Titanium Riv",
"Chrome Riv",
"Chrome Riv",
"Chrome Riv",
"Cobalt Riv",
"Cobalt Riv",
"Cobalt Riv",
"Chromoly Riv",
"Chromoly Riv",
"Chromoly Riv",
"Cermet Riv",
"Cermet Riv",
"Cermet Riv",
"Carbide Riv",
"Carbide Riv",
"Carbide Riv",
"Iron Pugio",
"Iron Pugio",
"Iron Pugio",
"Titanium Pugio",
"Titanium Pugio",
"Titanium Pugio",
"Chrome Pugio",
"Chrome Pugio",
"Chrome Pugio",
"Cobalt Pugio",
"Cobalt Pugio",
"Cobalt Pugio",
"Chromoly Pugio",
"Chromoly Pugio",
"Chromoly Pugio",
"Cermet Pugio",
"Cermet Pugio",
"Cermet Pugio",
"Carbide Pugio",
"Carbide Pugio",
"Carbide Pugio",
"Iron Pokepoke",
"Iron Pokepoke",
"Iron Pokepoke",
"Titanium Pokepoke",
"Titanium Pokepoke",
"Titanium Pokepoke",
"Chrome Pokepoke",
"Chrome Pokepoke",
"Chrome Pokepoke",
"Cobalt Pokepoke",
"Cobalt Pokepoke",
"Cobalt Pokepoke",
"Chromoly Pokepoke",
"Chromoly Pokepoke",
"Chromoly Pokepoke",
"Cermet Pokepoke",
"Cermet Pokepoke",
"Cermet Pokepoke",
"Carbide Pokepoke",
"Carbide Pokepoke",
"Carbide Pokepoke",
"Iron Iyst",
"Iron Iyst",
"Iron Iyst",
"Titanium Iyst",
"Titanium Iyst",
"Titanium Iyst",
"Chrome Iyst",
"Chrome Iyst",
"Chrome Iyst",
"Cobalt Iyst",
"Cobalt Iyst",
"Cobalt Iyst",
"Chromoly Iyst",
"Chromoly Iyst",
"Chromoly Iyst",
"Cermet Iyst",
"Cermet Iyst",
"Cermet Iyst",
"Carbide Iyst",
"Carbide Iyst",
"Carbide Iyst",
"Iron Iyst II",
"Iron Iyst II",
"Iron Iyst II",
"Titanium Iyst II",
"Titanium Iyst II",
"Titanium Iyst II",
"Chrome Iyst II",
"Chrome Iyst II",
"Chrome Iyst II",
"Cobalt Iyst II",
"Cobalt Iyst II",
"Cobalt Iyst II",
"Chromoly Iyst II",
"Chromoly Iyst II",
"Chromoly Iyst II",
"Cermet Iyst II",
"Cermet Iyst II",
"Cermet Iyst II",
"Carbide Iyst II",
"Carbide Iyst II",
"Carbide Iyst II",
"Advanced Iron Knife",
"Worn Titanium Knife",
"Advanced Titanium Knife",
"Worn Chrome Knife",
"Advanced Chrome Knife",
"Worn Cobalt Knife",
"Advanced Cobalt Knife",
"Worn Chromoly Knife",
"Advanced Chromoly Knife",
"Worn Cermet Knife",
"Advanced Cermet Knife",
"Worn Carbide Knife",
"Advanced Iron Knife III",
"Worn Titanium Knife III",
"Advanced Titanium Knife III",
"Worn Chrome Knife III",
"Advanced Chrome Knife III",
"Worn Cobalt Knife III",
"Advanced Cobalt Knife III",
"Worn Chromoly Knife III",
"Advanced Chromoly Knife III",
"Worn Cermet Knife III",
"Advanced Cermet Knife III",
"Worn Carbide Knife III",
"Advanced Iron Knife II",
"Worn Titanium Knife II",
"Advanced Titanium Knife II",
"Worn Chrome Knife II",
"Advanced Chrome Knife II",
"Worn Cobalt Knife II",
"Advanced Cobalt Knife II",
"Worn Chromoly Knife II",
"Advanced Chromoly Knife II",
"Worn Cermet Knife II",
"Advanced Cermet Knife II",
"Worn Carbide Knife II",
"Advanced Iron Riv",
"Worn Titanium Riv",
"Advanced Titanium Riv",
"Worn Chrome Riv",
"Advanced Chrome Riv",
"Worn Cobalt Riv",
"Advanced Cobalt Riv",
"Worn Chromoly Riv",
"Advanced Chromoly Riv",
"Worn Cermet Riv",
"Advanced Cermet Riv",
"Worn Carbide Riv",
"Worn Chrome Pugio",
"Advanced Chrome Pugio",
"Worn Cobalt Pugio",
"Advanced Cobalt Pugio",
"Worn Chromoly Pugio",
"Advanced Chromoly Pugio",
"Worn Cermet Pugio",
"Advanced Cermet Pugio",
"Worn Carbide Pugio",
"Advanced Chrome Pokepoke",
"Worn Cobalt Pokepoke",
"Advanced Cobalt Pokepoke",
"Worn Chromoly Pokepoke",
"Advanced Chromoly Pokepoke",
"Worn Cermet Pokepoke",
"Advanced Cermet Pokepoke",
"Worn Carbide Pokepoke",
"Worn Cobalt Iyst",
"Advanced Cobalt Iyst",
"Worn Chromoly Iyst",
"Advanced Chromoly Iyst",
"Worn Cermet Iyst",
"Advanced Cermet Iyst",
"Worn Carbide Iyst",
"Worn Cobalt Iyst II",
"Advanced Cobalt Iyst II",
"Worn Chromoly Iyst II",
"Advanced Chromoly Iyst II",
"Worn Cermet Iyst II",
"Advanced Cermet Iyst II",
"Worn Carbide Iyst II",
"Ultra Ceramic Knife",
"Ultra Diamond Knife",
"Ultra Ceramic Knife III",
"Ultra Diamond Knife III",
"Ultra Ceramic Knife II",
"Ultra Diamond Knife II",
"Ultra Ceramic Riv",
"Ultra Diamond Riv",
"Ultra Ceramic Pugio",
"Ultra Diamond Pugio",
"Ultra Ceramic Pokepoke",
"Ultra Diamond Pokepoke",
"Ultra Ceramic Iyst",
"Ultra Diamond Iyst",
"Ultra Ceramic Iyst II",
"Ultra Diamond Iyst II",
"Iron Shield",
"Iron Shield",
"Iron Shield",
"Titanium Shield",
"Titanium Shield",
"Titanium Shield",
"Chrome Shield",
"Chrome Shield",
"Chrome Shield",
"Cobalt Shield",
"Cobalt Shield",
"Cobalt Shield",
"Chromoly Shield",
"Chromoly Shield",
"Chromoly Shield",
"Cermet Shield",
"Cermet Shield",
"Cermet Shield",
"Carbide Shield",
"Carbide Shield",
"Carbide Shield",
"Iron Paive",
"Iron Paive",
"Iron Paive",
"Titanium Paive",
"Titanium Paive",
"Titanium Paive",
"Chrome Paive",
"Chrome Paive",
"Chrome Paive",
"Cobalt Paive",
"Cobalt Paive",
"Cobalt Paive",
"Chromoly Paive",
"Chromoly Paive",
"Chromoly Paive",
"Cermet Paive",
"Cermet Paive",
"Cermet Paive",
"Carbide Paive",
"Carbide Paive",
"Carbide Paive",
"Iron Parma",
"Iron Parma",
"Iron Parma",
"Titanium Parma",
"Titanium Parma",
"Titanium Parma",
"Chrome Parma",
"Chrome Parma",
"Chrome Parma",
"Cobalt Parma",
"Cobalt Parma",
"Cobalt Parma",
"Chromoly Parma",
"Chromoly Parma",
"Chromoly Parma",
"Cermet Parma",
"Cermet Parma",
"Cermet Parma",
"Carbide Parma",
"Carbide Parma",
"Carbide Parma",
"Iron Parma II",
"Iron Parma II",
"Iron Parma II",
"Titanium Parma II",
"Titanium Parma II",
"Titanium Parma II",
"Chrome Parma II",
"Chrome Parma II",
"Chrome Parma II",
"Cobalt Parma II",
"Cobalt Parma II",
"Cobalt Parma II",
"Chromoly Parma II",
"Chromoly Parma II",
"Chromoly Parma II",
"Cermet Parma II",
"Cermet Parma II",
"Cermet Parma II",
"Carbide Parma II",
"Carbide Parma II",
"Carbide Parma II",
"Iron Haven",
"Iron Haven",
"Iron Haven",
"Titanium Haven",
"Titanium Haven",
"Titanium Haven",
"Chrome Haven",
"Chrome Haven",
"Chrome Haven",
"Cobalt Haven",
"Cobalt Haven",
"Cobalt Haven",
"Chromoly Haven",
"Chromoly Haven",
"Chromoly Haven",
"Cermet Haven",
"Cermet Haven",
"Cermet Haven",
"Carbide Haven",
"Carbide Haven",
"Carbide Haven",
"Iron Haven II",
"Iron Haven II",
"Iron Haven II",
"Titanium Haven II",
"Titanium Haven II",
"Titanium Haven II",
"Chrome Haven II",
"Chrome Haven II",
"Chrome Haven II",
"Cobalt Haven II",
"Cobalt Haven II",
"Cobalt Haven II",
"Chromoly Haven II",
"Chromoly Haven II",
"Chromoly Haven II",
"Cermet Haven II",
"Cermet Haven II",
"Cermet Haven II",
"Carbide Haven II",
"Carbide Haven II",
"Carbide Haven II",
"Iron Thudclang",
"Iron Thudclang",
"Iron Thudclang",
"Titanium Thudclang",
"Titanium Thudclang",
"Titanium Thudclang",
"Chrome Thudclang",
"Chrome Thudclang",
"Chrome Thudclang",
"Cobalt Thudclang",
"Cobalt Thudclang",
"Cobalt Thudclang",
"Chromoly Thudclang",
"Chromoly Thudclang",
"Chromoly Thudclang",
"Cermet Thudclang",
"Cermet Thudclang",
"Cermet Thudclang",
"Carbide Thudclang",
"Carbide Thudclang",
"Carbide Thudclang",
"Iron Honor",
"Iron Honor",
"Iron Honor",
"Titanium Honor",
"Titanium Honor",
"Titanium Honor",
"Chrome Honor",
"Chrome Honor",
"Chrome Honor",
"Cobalt Honor",
"Cobalt Honor",
"Cobalt Honor",
"Chromoly Honor",
"Chromoly Honor",
"Chromoly Honor",
"Cermet Honor",
"Cermet Honor",
"Cermet Honor",
"Carbide Honor",
"Carbide Honor",
"Carbide Honor",
"Advanced Iron Shield",
"Worn Titanium Shield",
"Advanced Titanium Shield",
"Worn Chrome Shield",
"Advanced Chrome Shield",
"Worn Cobalt Shield",
"Advanced Cobalt Shield",
"Worn Chromoly Shield",
"Advanced Chromoly Shield",
"Worn Cermet Shield",
"Advanced Cermet Shield",
"Worn Carbide Shield",
"Advanced Iron Paive",
"Worn Titanium Paive",
"Advanced Titanium Paive",
"Worn Chrome Paive",
"Advanced Chrome Paive",
"Worn Cobalt Paive",
"Advanced Cobalt Paive",
"Worn Chromoly Paive",
"Advanced Chromoly Paive",
"Worn Cermet Paive",
"Advanced Cermet Paive",
"Worn Carbide Paive",
"Worn Chrome Parma",
"Advanced Chrome Parma",
"Worn Cobalt Parma",
"Advanced Cobalt Parma",
"Worn Chromoly Parma",
"Advanced Chromoly Parma",
"Worn Cermet Parma",
"Advanced Cermet Parma",
"Worn Carbide Parma",
"Worn Chrome Parma II",
"Advanced Chrome Parma II",
"Worn Cobalt Parma II",
"Advanced Cobalt Parma II",
"Worn Chromoly Parma II",
"Advanced Chromoly Parma II",
"Worn Cermet Parma II",
"Advanced Cermet Parma II",
"Worn Carbide Parma II",
"Advanced Chrome Haven",
"Worn Cobalt Haven",
"Advanced Cobalt Haven",
"Worn Chromoly Haven",
"Advanced Chromoly Haven",
"Worn Cermet Haven",
"Advanced Cermet Haven",
"Worn Carbide Haven",
"Advanced Chrome Haven II",
"Worn Cobalt Haven II",
"Advanced Cobalt Haven II",
"Worn Chromoly Haven II",
"Advanced Chromoly Haven II",
"Worn Cermet Haven II",
"Advanced Cermet Haven II",
"Worn Carbide Haven II",
"Advanced Chrome Thudclang",
"Worn Cobalt Thudclang",
"Advanced Cobalt Thudclang",
"Worn Chromoly Thudclang",
"Advanced Chromoly Thudclang",
"Worn Cermet Thudclang",
"Advanced Cermet Thudclang",
"Worn Carbide Thudclang",
"Advanced Chrome Honor",
"Worn Cobalt Honor",
"Advanced Cobalt Honor",
"Worn Chromoly Honor",
"Advanced Chromoly Honor",
"Worn Cermet Honor",
"Advanced Cermet Honor",
"Worn Carbide Honor",
"Ultra Ceramic Shield",
"Ultra Diamond Shield",
"Ultra Ceramic Paive",
"Ultra Diamond Paive",
"Ultra Ceramic Parma",
"Ultra Diamond Parma",
"Ultra Ceramic Parma II",
"Ultra Diamond Parma II",
"Ultra Ceramic Haven",
"Ultra Diamond Haven",
"Ultra Ceramic Haven II",
"Ultra Diamond Haven II",
"Ultra Ceramic Thudclang",
"Ultra Diamond Thudclang",
"Ultra Ceramic Honor",
"Ultra Diamond Honor",
"Iron Spear",
"Iron Spear",
"Iron Spear",
"Titanium Spear",
"Titanium Spear",
"Titanium Spear",
"Chrome Spear",
"Chrome Spear",
"Chrome Spear",
"Cobalt Spear",
"Cobalt Spear",
"Cobalt Spear",
"Chromoly Spear",
"Chromoly Spear",
"Chromoly Spear",
"Cermet Spear",
"Cermet Spear",
"Cermet Spear",
"Carbide Spear",
"Carbide Spear",
"Carbide Spear",
"Iron Spear II",
"Iron Spear II",
"Iron Spear II",
"Titanium Spear II",
"Titanium Spear II",
"Titanium Spear II",
"Chrome Spear II",
"Chrome Spear II",
"Chrome Spear II",
"Cobalt Spear II",
"Cobalt Spear II",
"Cobalt Spear II",
"Chromoly Spear II",
"Chromoly Spear II",
"Chromoly Spear II",
"Cermet Spear II",
"Cermet Spear II",
"Cermet Spear II",
"Carbide Spear II",
"Carbide Spear II",
"Carbide Spear II",
"Iron Parce",
"Iron Parce",
"Iron Parce",
"Titanium Parce",
"Titanium Parce",
"Titanium Parce",
"Chrome Parce",
"Chrome Parce",
"Chrome Parce",
"Cobalt Parce",
"Cobalt Parce",
"Cobalt Parce",
"Chromoly Parce",
"Chromoly Parce",
"Chromoly Parce",
"Cermet Parce",
"Cermet Parce",
"Cermet Parce",
"Carbide Parce",
"Carbide Parce",
"Carbide Parce",
"Iron Pilum",
"Iron Pilum",
"Iron Pilum",
"Titanium Pilum",
"Titanium Pilum",
"Titanium Pilum",
"Chrome Pilum",
"Chrome Pilum",
"Chrome Pilum",
"Cobalt Pilum",
"Cobalt Pilum",
"Cobalt Pilum",
"Chromoly Pilum",
"Chromoly Pilum",
"Chromoly Pilum",
"Cermet Pilum",
"Cermet Pilum",
"Cermet Pilum",
"Carbide Pilum",
"Carbide Pilum",
"Carbide Pilum",
"Iron Pilum II",
"Iron Pilum II",
"Iron Pilum II",
"Titanium Pilum II",
"Titanium Pilum II",
"Titanium Pilum II",
"Chrome Pilum II",
"Chrome Pilum II",
"Chrome Pilum II",
"Cobalt Pilum II",
"Cobalt Pilum II",
"Cobalt Pilum II",
"Chromoly Pilum II",
"Chromoly Pilum II",
"Chromoly Pilum II",
"Cermet Pilum II",
"Cermet Pilum II",
"Cermet Pilum II",
"Carbide Pilum II",
"Carbide Pilum II",
"Carbide Pilum II",
"Iron Bolide",
"Iron Bolide",
"Iron Bolide",
"Titanium Bolide",
"Titanium Bolide",
"Titanium Bolide",
"Chrome Bolide",
"Chrome Bolide",
"Chrome Bolide",
"Cobalt Bolide",
"Cobalt Bolide",
"Cobalt Bolide",
"Chromoly Bolide",
"Chromoly Bolide",
"Chromoly Bolide",
"Cermet Bolide",
"Cermet Bolide",
"Cermet Bolide",
"Carbide Bolide",
"Carbide Bolide",
"Carbide Bolide",
"Iron Jyth",
"Iron Jyth",
"Iron Jyth",
"Titanium Jyth",
"Titanium Jyth",
"Titanium Jyth",
"Chrome Jyth",
"Chrome Jyth",
"Chrome Jyth",
"Cobalt Jyth",
"Cobalt Jyth",
"Cobalt Jyth",
"Chromoly Jyth",
"Chromoly Jyth",
"Chromoly Jyth",
"Cermet Jyth",
"Cermet Jyth",
"Cermet Jyth",
"Carbide Jyth",
"Carbide Jyth",
"Carbide Jyth",
"IW_MU_F_JAVELIN_A02_0101_name",
"IW_MU_F_JAVELIN_A02_0101_name",
"IW_MU_F_JAVELIN_A02_0101_name",
"IW_MU_F_JAVELIN_A03_1001_name",
"IW_MU_F_JAVELIN_A03_1001_name",
"IW_MU_F_JAVELIN_A03_1001_name",
"Faithful Lance",
"Faithful Lance",
"Faithful Lance",
"Steelbreaker Lance",
"Steelbreaker Lance",
"Steelbreaker Lance",
"Pulverizing Lance",
"Pulverizing Lance",
"Pulverizing Lance",
"Intrepid Lance",
"Intrepid Lance",
"Intrepid Lance",
"Audacious Lance",
"Audacious Lance",
"Audacious Lance",
"Advanced Iron Spear",
"Worn Titanium Spear",
"Advanced Titanium Spear",
"Worn Chrome Spear",
"Advanced Chrome Spear",
"Worn Cobalt Spear",
"Advanced Cobalt Spear",
"Worn Chromoly Spear",
"Advanced Chromoly Spear",
"Worn Cermet Spear",
"Advanced Cermet Spear",
"Worn Carbide Spear",
"Advanced Iron Spear II",
"Worn Titanium Spear II",
"Advanced Titanium Spear II",
"Worn Chrome Spear II",
"Advanced Chrome Spear II",
"Worn Cobalt Spear II",
"Advanced Cobalt Spear II",
"Worn Chromoly Spear II",
"Advanced Chromoly Spear II",
"Worn Cermet Spear II",
"Advanced Cermet Spear II",
"Worn Carbide Spear II",
"Advanced Iron Parce",
"Worn Titanium Parce",
"Advanced Titanium Parce",
"Worn Chrome Parce",
"Advanced Chrome Parce",
"Worn Cobalt Parce",
"Advanced Cobalt Parce",
"Worn Chromoly Parce",
"Advanced Chromoly Parce",
"Worn Cermet Parce",
"Advanced Cermet Parce",
"Worn Carbide Parce",
"Worn Chrome Pilum",
"Advanced Chrome Pilum",
"Worn Cobalt Pilum",
"Advanced Cobalt Pilum",
"Worn Chromoly Pilum",
"Advanced Chromoly Pilum",
"Worn Cermet Pilum",
"Advanced Cermet Pilum",
"Worn Carbide Pilum",
"Worn Chrome Pilum II",
"Advanced Chrome Pilum II",
"Worn Cobalt Pilum II",
"Advanced Cobalt Pilum II",
"Worn Chromoly Pilum II",
"Advanced Chromoly Pilum II",
"Worn Cermet Pilum II",
"Advanced Cermet Pilum II",
"Worn Carbide Pilum II",
"Advanced Chrome Bolide",
"Worn Cobalt Bolide",
"Advanced Cobalt Bolide",
"Worn Chromoly Bolide",
"Advanced Chromoly Bolide",
"Worn Cermet Bolide",
"Advanced Cermet Bolide",
"Worn Carbide Bolide",
"Worn Cobalt Jyth",
"Advanced Cobalt Jyth",
"Worn Chromoly Jyth",
"Advanced Chromoly Jyth",
"Worn Cermet Jyth",
"Advanced Cermet Jyth",
"Worn Carbide Jyth",
"Advanced Steelbreaker Lance",
"Worn Pulverizing Lance",
"Advanced Pulverizing Lance",
"Worn Intrepid Lance",
"Advanced Intrepid Lance",
"Worn Audacious Lance",
"Ultra Ceramic Spear",
"Ultra Diamond Spear",
"Ultra Ceramic Spear II",
"Ultra Diamond Spear II",
"Ultra Ceramic Parce",
"Ultra Diamond Parce",
"Ultra Ceramic Pilum",
"Ultra Diamond Pilum",
"Ultra Ceramic Pilum II",
"Ultra Diamond Pilum II",
"Ultra Ceramic Bolide",
"Ultra Diamond Bolide",
"Ultra Ceramic Jyth",
"Ultra Diamond Jyth",
"Ultra Godbreaker Lance",
"Ultra Phenomenon Lance",
"Iron Saber",
"Iron Saber",
"Iron Saber",
"Titanium Saber",
"Titanium Saber",
"Titanium Saber",
"Chrome Saber",
"Chrome Saber",
"Chrome Saber",
"Cobalt Saber",
"Cobalt Saber",
"Cobalt Saber",
"Chromoly Saber",
"Chromoly Saber",
"Chromoly Saber",
"Cermet Saber",
"Cermet Saber",
"Cermet Saber",
"Carbide Saber",
"Carbide Saber",
"Carbide Saber",
"Iron Fulge",
"Iron Fulge",
"Iron Fulge",
"Titanium Fulge",
"Titanium Fulge",
"Titanium Fulge",
"Chrome Fulge",
"Chrome Fulge",
"Chrome Fulge",
"Cobalt Fulge",
"Cobalt Fulge",
"Cobalt Fulge",
"Chromoly Fulge",
"Chromoly Fulge",
"Chromoly Fulge",
"Cermet Fulge",
"Cermet Fulge",
"Cermet Fulge",
"Carbide Fulge",
"Carbide Fulge",
"Carbide Fulge",
"Iron Fulge II",
"Iron Fulge II",
"Iron Fulge II",
"Titanium Fulge II",
"Titanium Fulge II",
"Titanium Fulge II",
"Chrome Fulge II",
"Chrome Fulge II",
"Chrome Fulge II",
"Cobalt Fulge II",
"Cobalt Fulge II",
"Cobalt Fulge II",
"Chromoly Fulge II",
"Chromoly Fulge II",
"Chromoly Fulge II",
"Cermet Fulge II",
"Cermet Fulge II",
"Cermet Fulge II",
"Carbide Fulge II",
"Carbide Fulge II",
"Carbide Fulge II",
"Iron Candela",
"Iron Candela",
"Iron Candela",
"Titanium Candela",
"Titanium Candela",
"Titanium Candela",
"Chrome Candela",
"Chrome Candela",
"Chrome Candela",
"Cobalt Candela",
"Cobalt Candela",
"Cobalt Candela",
"Chromoly Candela",
"Chromoly Candela",
"Chromoly Candela",
"Cermet Candela",
"Cermet Candela",
"Cermet Candela",
"Carbide Candela",
"Carbide Candela",
"Carbide Candela",
"Iron Candela II",
"Iron Candela II",
"Iron Candela II",
"Titanium Candela II",
"Titanium Candela II",
"Titanium Candela II",
"Chrome Candela II",
"Chrome Candela II",
"Chrome Candela II",
"Cobalt Candela II",
"Cobalt Candela II",
"Cobalt Candela II",
"Chromoly Candela II",
"Chromoly Candela II",
"Chromoly Candela II",
"Cermet Candela II",
"Cermet Candela II",
"Cermet Candela II",
"Carbide Candela II",
"Carbide Candela II",
"Carbide Candela II",
"Iron Candela III",
"Iron Candela III",
"Iron Candela III",
"Titanium Candela III",
"Titanium Candela III",
"Titanium Candela III",
"Chrome Candela III",
"Chrome Candela III",
"Chrome Candela III",
"Cobalt Candela III",
"Cobalt Candela III",
"Cobalt Candela III",
"Chromoly Candela III",
"Chromoly Candela III",
"Chromoly Candela III",
"Cermet Candela III",
"Cermet Candela III",
"Cermet Candela III",
"Carbide Candela III",
"Carbide Candela III",
"Carbide Candela III",
"IW_MU_F_PHOTON_A04_0101_name",
"IW_MU_F_PHOTON_A04_0101_name",
"IW_MU_F_PHOTON_A04_0101_name",
"IW_MU_F_PHOTON_A05_1001_name",
"IW_MU_F_PHOTON_A05_1001_name",
"IW_MU_F_PHOTON_A05_1001_name",
"Faithful Lightblade",
"Faithful Lightblade",
"Faithful Lightblade",
"Steelbreaker Lightblade",
"Steelbreaker Lightblade",
"Steelbreaker Lightblade",
"Pulverizing Lightblade",
"Pulverizing Lightblade",
"Pulverizing Lightblade",
"Intrepid Lightblade",
"Intrepid Lightblade",
"Intrepid Lightblade",
"Audacious Lightblade",
"Audacious Lightblade",
"Audacious Lightblade",
"IW_MU_F_PHOTON_B04_0101_name",
"IW_MU_F_PHOTON_B04_0101_name",
"IW_MU_F_PHOTON_B04_0101_name",
"IW_MU_F_PHOTON_B05_1001_name",
"IW_MU_F_PHOTON_B05_1001_name",
"IW_MU_F_PHOTON_B05_1001_name",
"Faithful Lightblade II",
"Faithful Lightblade II",
"Faithful Lightblade II",
"Steelbreaker Lightblade II",
"Steelbreaker Lightblade II",
"Steelbreaker Lightblade II",
"Pulverizing Lightblade II",
"Pulverizing Lightblade II",
"Pulverizing Lightblade II",
"Intrepid Lightblade II",
"Intrepid Lightblade II",
"Intrepid Lightblade II",
"Audacious Lightblade II",
"Audacious Lightblade II",
"Audacious Lightblade II",
"Advanced Iron Saber",
"Worn Titanium Saber",
"Advanced Titanium Saber",
"Worn Chrome Saber",
"Advanced Chrome Saber",
"Worn Cobalt Saber",
"Advanced Cobalt Saber",
"Worn Chromoly Saber",
"Advanced Chromoly Saber",
"Worn Cermet Saber",
"Advanced Cermet Saber",
"Worn Carbide Saber",
"Advanced Iron Fulge",
"Worn Titanium Fulge",
"Advanced Titanium Fulge",
"Worn Chrome Fulge",
"Advanced Chrome Fulge",
"Worn Cobalt Fulge",
"Advanced Cobalt Fulge",
"Worn Chromoly Fulge",
"Advanced Chromoly Fulge",
"Worn Cermet Fulge",
"Advanced Cermet Fulge",
"Worn Carbide Fulge",
"Advanced Iron Fulge II",
"Worn Titanium Fulge II",
"Advanced Titanium Fulge II",
"Worn Chrome Fulge II",
"Advanced Chrome Fulge II",
"Worn Cobalt Fulge II",
"Advanced Cobalt Fulge II",
"Worn Chromoly Fulge II",
"Advanced Chromoly Fulge II",
"Worn Cermet Fulge II",
"Advanced Cermet Fulge II",
"Worn Carbide Fulge II",
"Worn Chrome Candela",
"Advanced Chrome Candela",
"Worn Cobalt Candela",
"Advanced Cobalt Candela",
"Worn Chromoly Candela",
"Advanced Chromoly Candela",
"Worn Cermet Candela",
"Advanced Cermet Candela",
"Worn Carbide Candela",
"Worn Chrome Candela II",
"Advanced Chrome Candela II",
"Worn Cobalt Candela II",
"Advanced Cobalt Candela II",
"Worn Chromoly Candela II",
"Advanced Chromoly Candela II",
"Worn Cermet Candela II",
"Advanced Cermet Candela II",
"Worn Carbide Candela II",
"Worn Chrome Candela III",
"Advanced Chrome Candela III",
"Worn Cobalt Candela III",
"Advanced Cobalt Candela III",
"Worn Chromoly Candela III",
"Advanced Chromoly Candela III",
"Worn Cermet Candela III",
"Advanced Cermet Candela III",
"Worn Carbide Candela III",
"Advanced Steelbreaker Lightblade",
"Worn Pulverizing Lightblade",
"Advanced Pulverizing Lightblade",
"Worn Intrepid Lightblade",
"Advanced Intrepid Lightblade",
"Worn Audacious Lightblade",
"Advanced Steelbreaker Lightblade II",
"Worn Pulverizing Lightblade II",
"Advanced Pulverizing Lightblade II",
"Worn Intrepid Lightblade II",
"Advanced Intrepid Lightblade II",
"Worn Audacious Lightblade II",
"Ultra Ceramic Saber",
"Ultra Diamond Saber",
"Ultra Ceramic Fulge",
"Ultra Diamond Fulge",
"Ultra Ceramic Fulge II",
"Ultra Diamond Fulge II",
"Ultra Ceramic Candela",
"Ultra Diamond Candela",
"Ultra Ceramic Candela II",
"Ultra Diamond Candela II",
"Ultra Ceramic Candela III",
"Ultra Diamond Candela III",
"Ultra Godbreaker Lightblade",
"Ultra Phenomenon Lightblade",
"Ultra Godbreaker Lightblade II",
"Ultra Phenomenon Lightblade II",
"Proto Assault Rifle",
"Storm Assault Rifle",
"Storm Assault Rifle",
"Storm Assault Rifle",
"Soldier Assault Rifle",
"Soldier Assault Rifle",
"Soldier Assault Rifle",
"Warrior Assault Rifle",
"Warrior Assault Rifle",
"Warrior Assault Rifle",
"Ophidian Assault Rifle",
"Ophidian Assault Rifle",
"Ophidian Assault Rifle",
"Destroyer Assault Rifle",
"Destroyer Assault Rifle",
"Destroyer Assault Rifle",
"Striker Assault Rifle",
"Striker Assault Rifle",
"Striker Assault Rifle",
"Delta Assault Rifle",
"Delta Assault Rifle",
"Delta Assault Rifle",
"Storm Assault Rifle III",
"Storm Assault Rifle III",
"Storm Assault Rifle III",
"Soldier Assault Rifle III",
"Soldier Assault Rifle III",
"Soldier Assault Rifle III",
"Warrior Assault Rifle III",
"Warrior Assault Rifle III",
"Warrior Assault Rifle III",
"Ophidian Assault Rifle III",
"Ophidian Assault Rifle III",
"Ophidian Assault Rifle III",
"Destroyer Assault Rifle III",
"Destroyer Assault Rifle III",
"Destroyer Assault Rifle III",
"Striker Assault Rifle III",
"Striker Assault Rifle III",
"Striker Assault Rifle III",
"Delta Assault Rifle III",
"Delta Assault Rifle III",
"Delta Assault Rifle III",
"Storm Assault Rifle II",
"Storm Assault Rifle II",
"Storm Assault Rifle II",
"Soldier Assault Rifle II",
"Soldier Assault Rifle II",
"Soldier Assault Rifle II",
"Warrior Assault Rifle II",
"Warrior Assault Rifle II",
"Warrior Assault Rifle II",
"Ophidian Assault Rifle II",
"Ophidian Assault Rifle II",
"Ophidian Assault Rifle II",
"Destroyer Assault Rifle II",
"Destroyer Assault Rifle II",
"Destroyer Assault Rifle II",
"Striker Assault Rifle II",
"Striker Assault Rifle II",
"Striker Assault Rifle II",
"Delta Assault Rifle II",
"Delta Assault Rifle II",
"Delta Assault Rifle II",
"Storm Avagar",
"Storm Avagar",
"Storm Avagar",
"Soldier Avagar",
"Soldier Avagar",
"Soldier Avagar",
"Warrior Avagar",
"Warrior Avagar",
"Warrior Avagar",
"Ophidian Avagar",
"Ophidian Avagar",
"Ophidian Avagar",
"Destroyer Avagar",
"Destroyer Avagar",
"Destroyer Avagar",
"Striker Avagar",
"Striker Avagar",
"Striker Avagar",
"Delta Avagar",
"Delta Avagar",
"Delta Avagar",
"Storm Sclopetum",
"Storm Sclopetum",
"Storm Sclopetum",
"Soldier Sclopetum",
"Soldier Sclopetum",
"Soldier Sclopetum",
"Warrior Sclopetum",
"Warrior Sclopetum",
"Warrior Sclopetum",
"Ophidian Sclopetum",
"Ophidian Sclopetum",
"Ophidian Sclopetum",
"Destroyer Sclopetum",
"Destroyer Sclopetum",
"Destroyer Sclopetum",
"Striker Sclopetum",
"Striker Sclopetum",
"Striker Sclopetum",
"Delta Sclopetum",
"Delta Sclopetum",
"Delta Sclopetum",
"Storm Assailer",
"Storm Assailer",
"Storm Assailer",
"Soldier Assailer",
"Soldier Assailer",
"Soldier Assailer",
"Warrior Assailer",
"Warrior Assailer",
"Warrior Assailer",
"Ophidian Assailer",
"Ophidian Assailer",
"Ophidian Assailer",
"Destroyer Assailer",
"Destroyer Assailer",
"Destroyer Assailer",
"Striker Assailer",
"Striker Assailer",
"Striker Assailer",
"Delta Assailer",
"Delta Assailer",
"Delta Assailer",
"Storm Rapture",
"Storm Rapture",
"Storm Rapture",
"Soldier Rapture",
"Soldier Rapture",
"Soldier Rapture",
"Warrior Rapture",
"Warrior Rapture",
"Warrior Rapture",
"Ophidian Rapture",
"Ophidian Rapture",
"Ophidian Rapture",
"Destroyer Rapture",
"Destroyer Rapture",
"Destroyer Rapture",
"Striker Rapture",
"Striker Rapture",
"Striker Rapture",
"Delta Rapture",
"Delta Rapture",
"Delta Rapture",
"IW_MU_S_ASSAULT_A04_0101_name",
"IW_MU_S_ASSAULT_A04_0101_name",
"IW_MU_S_ASSAULT_A04_0101_name",
"IW_MU_S_ASSAULT_A05_1001_name",
"IW_MU_S_ASSAULT_A05_1001_name",
"IW_MU_S_ASSAULT_A05_1001_name",
"Rugged Raidrifle",
"Rugged Raidrifle",
"Rugged Raidrifle",
"Devastator Raidrifle",
"Devastator Raidrifle",
"Devastator Raidrifle",
"Sparrow Raidrifle",
"Sparrow Raidrifle",
"Sparrow Raidrifle",
"Foxfire Raidrifle",
"Foxfire Raidrifle",
"Foxfire Raidrifle",
"Rectifier Raidrifle",
"Rectifier Raidrifle",
"Rectifier Raidrifle",
"Advanced Storm Assault Rifle",
"Worn Soldier Assault Rifle",
"Advanced Soldier Assault Rifle",
"Worn Warrior Assault Rifle",
"Advanced Warrior Assault Rifle",
"Worn Ophidian Assault Rifle",
"Advanced Ophidian Assault Rifle",
"Worn Destroyer Assault Rifle",
"Advanced Destroyer Assault Rifle",
"Worn Striker Assault Rifle",
"Advanced Striker Assault Rifle",
"Worn Delta Assault Rifle",
"Advanced Storm Assault Rifle III",
"Worn Soldier Assault Rifle III",
"Advanced Soldier Assault Rifle III",
"Worn Warrior Assault Rifle III",
"Advanced Warrior Assault Rifle III",
"Worn Ophidian Assault Rifle III",
"Advanced Ophidian Assault Rifle III",
"Worn Destroyer Assault Rifle III",
"Advanced Destroyer Assault Rifle III",
"Worn Striker Assault Rifle III",
"Advanced Striker Assault Rifle III",
"Worn Delta Assault Rifle III",
"Advanced Storm Assault Rifle II",
"Worn Soldier Assault Rifle II",
"Advanced Soldier Assault Rifle II",
"Worn Warrior Assault Rifle II",
"Advanced Warrior Assault Rifle II",
"Worn Ophidian Assault Rifle II",
"Advanced Ophidian Assault Rifle II",
"Worn Destroyer Assault Rifle II",
"Advanced Destroyer Assault Rifle II",
"Worn Striker Assault Rifle II",
"Advanced Striker Assault Rifle II",
"Worn Delta Assault Rifle II",
"Advanced Storm Avagar",
"Worn Soldier Avagar",
"Advanced Soldier Avagar",
"Worn Warrior Avagar",
"Advanced Warrior Avagar",
"Worn Ophidian Avagar",
"Advanced Ophidian Avagar",
"Worn Destroyer Avagar",
"Advanced Destroyer Avagar",
"Worn Striker Avagar",
"Advanced Striker Avagar",
"Worn Delta Avagar",
"Worn Warrior Sclopetum",
"Advanced Warrior Sclopetum",
"Worn Ophidian Sclopetum",
"Advanced Ophidian Sclopetum",
"Worn Destroyer Sclopetum",
"Advanced Destroyer Sclopetum",
"Worn Striker Sclopetum",
"Advanced Striker Sclopetum",
"Worn Delta Sclopetum",
"Advanced Warrior Assailer",
"Worn Ophidian Assailer",
"Advanced Ophidian Assailer",
"Worn Destroyer Assailer",
"Advanced Destroyer Assailer",
"Worn Striker Assailer",
"Advanced Striker Assailer",
"Worn Delta Assailer",
"Advanced Warrior Rapture",
"Worn Ophidian Rapture",
"Advanced Ophidian Rapture",
"Worn Destroyer Rapture",
"Advanced Destroyer Rapture",
"Worn Striker Rapture",
"Advanced Striker Rapture",
"Worn Delta Rapture",
"Advanced Devastator Raidrifle",
"Worn Sparrow Raidrifle",
"Advanced Sparrow Raidrifle",
"Worn Foxfire Raidrifle",
"Advanced Foxfire Raidrifle",
"Worn Rectifier Raidrifle",
"Ultra Cosmic Assault Rifle",
"Ultra Nebulan Assault Rifle",
"Ultra Cosmic Assault Rifle III",
"Ultra Nebulan Assault Rifle III",
"Ultra Cosmic Assault Rifle II",
"Ultra Nebulan Assault Rifle II",
"Ultra Cosmic Avagar",
"Ultra Nebulan Avagar",
"Ultra Cosmic Sclopetum",
"Ultra Nebulan Sclopetum",
"Ultra Cosmic Assailer",
"Ultra Nebulan Assailer",
"Ultra Cosmic Rapture",
"Ultra Nebulan Rapture",
"Ultra Virtue Raidrifle",
"Ultra Transience Raidrifle",
"Storm Dual Guns",
"Storm Dual Guns",
"Storm Dual Guns",
"Soldier Dual Guns",
"Soldier Dual Guns",
"Soldier Dual Guns",
"Warrior Dual Guns",
"Warrior Dual Guns",
"Warrior Dual Guns",
"Ophidian Dual Guns",
"Ophidian Dual Guns",
"Ophidian Dual Guns",
"Destroyer Dual Guns",
"Destroyer Dual Guns",
"Destroyer Dual Guns",
"Striker Dual Guns",
"Striker Dual Guns",
"Striker Dual Guns",
"Delta Dual Guns",
"Delta Dual Guns",
"Delta Dual Guns",
"Storm Dual Guns II",
"Storm Dual Guns II",
"Storm Dual Guns II",
"Soldier Dual Guns II",
"Soldier Dual Guns II",
"Soldier Dual Guns II",
"Warrior Dual Guns II",
"Warrior Dual Guns II",
"Warrior Dual Guns II",
"Ophidian Dual Guns II",
"Ophidian Dual Guns II",
"Ophidian Dual Guns II",
"Destroyer Dual Guns II",
"Destroyer Dual Guns II",
"Destroyer Dual Guns II",
"Striker Dual Guns II",
"Striker Dual Guns II",
"Striker Dual Guns II",
"Delta Dual Guns II",
"Delta Dual Guns II",
"Delta Dual Guns II",
"Storm Gemels",
"Storm Gemels",
"Storm Gemels",
"Soldier Gemels",
"Soldier Gemels",
"Soldier Gemels",
"Warrior Gemels",
"Warrior Gemels",
"Warrior Gemels",
"Ophidian Gemels",
"Ophidian Gemels",
"Ophidian Gemels",
"Destroyer Gemels",
"Destroyer Gemels",
"Destroyer Gemels",
"Striker Gemels",
"Striker Gemels",
"Striker Gemels",
"Delta Gemels",
"Delta Gemels",
"Delta Gemels",
"Storm Pistolia",
"Storm Pistolia",
"Storm Pistolia",
"Soldier Pistolia",
"Soldier Pistolia",
"Soldier Pistolia",
"Warrior Pistolia",
"Warrior Pistolia",
"Warrior Pistolia",
"Ophidian Pistolia",
"Ophidian Pistolia",
"Ophidian Pistolia",
"Destroyer Pistolia",
"Destroyer Pistolia",
"Destroyer Pistolia",
"Striker Pistolia",
"Striker Pistolia",
"Striker Pistolia",
"Delta Pistolia",
"Delta Pistolia",
"Delta Pistolia",
"Storm Dyads",
"Storm Dyads",
"Storm Dyads",
"Soldier Dyads",
"Soldier Dyads",
"Soldier Dyads",
"Warrior Dyads",
"Warrior Dyads",
"Warrior Dyads",
"Ophidian Dyads",
"Ophidian Dyads",
"Ophidian Dyads",
"Destroyer Dyads",
"Destroyer Dyads",
"Destroyer Dyads",
"Striker Dyads",
"Striker Dyads",
"Striker Dyads",
"Delta Dyads",
"Delta Dyads",
"Delta Dyads",
"Storm Dyads III",
"Storm Dyads III",
"Storm Dyads III",
"Soldier Dyads III",
"Soldier Dyads III",
"Soldier Dyads III",
"Warrior Dyads III",
"Warrior Dyads III",
"Warrior Dyads III",
"Ophidian Dyads III",
"Ophidian Dyads III",
"Ophidian Dyads III",
"Destroyer Dyads III",
"Destroyer Dyads III",
"Destroyer Dyads III",
"Striker Dyads III",
"Striker Dyads III",
"Striker Dyads III",
"Delta Dyads III",
"Delta Dyads III",
"Delta Dyads III",
"Storm Dyads II",
"Storm Dyads II",
"Storm Dyads II",
"Soldier Dyads II",
"Soldier Dyads II",
"Soldier Dyads II",
"Warrior Dyads II",
"Warrior Dyads II",
"Warrior Dyads II",
"Ophidian Dyads II",
"Ophidian Dyads II",
"Ophidian Dyads II",
"Destroyer Dyads II",
"Destroyer Dyads II",
"Destroyer Dyads II",
"Striker Dyads II",
"Striker Dyads II",
"Striker Dyads II",
"Delta Dyads II",
"Delta Dyads II",
"Delta Dyads II",
"Storm Bangbangs",
"Storm Bangbangs",
"Storm Bangbangs",
"Soldier Bangbangs",
"Soldier Bangbangs",
"Soldier Bangbangs",
"Warrior Bangbangs",
"Warrior Bangbangs",
"Warrior Bangbangs",
"Ophidian Bangbangs",
"Ophidian Bangbangs",
"Ophidian Bangbangs",
"Destroyer Bangbangs",
"Destroyer Bangbangs",
"Destroyer Bangbangs",
"Striker Bangbangs",
"Striker Bangbangs",
"Striker Bangbangs",
"Delta Bangbangs",
"Delta Bangbangs",
"Delta Bangbangs",
"IW_MU_S_DUALGUN_A03_0101_name",
"IW_MU_S_DUALGUN_A03_0101_name",
"IW_MU_S_DUALGUN_A03_0101_name",
"IW_MU_S_DUALGUN_A05_1001_name",
"IW_MU_S_DUALGUN_A05_1001_name",
"IW_MU_S_DUALGUN_A05_1001_name",
"Rugged Sidearm",
"Rugged Sidearm",
"Rugged Sidearm",
"Devastator Sidearm",
"Devastator Sidearm",
"Devastator Sidearm",
"Sparrow Sidearm",
"Sparrow Sidearm",
"Sparrow Sidearm",
"Foxfire Sidearm",
"Foxfire Sidearm",
"Foxfire Sidearm",
"Rectifier Sidearm",
"Rectifier Sidearm",
"Rectifier Sidearm",
"Advanced Storm Dual Guns",
"Worn Soldier Dual Guns",
"Advanced Soldier Dual Guns",
"Worn Warrior Dual Guns",
"Advanced Warrior Dual Guns",
"Worn Ophidian Dual Guns",
"Advanced Ophidian Dual Guns",
"Worn Destroyer Dual Guns",
"Advanced Destroyer Dual Guns",
"Worn Striker Dual Guns",
"Advanced Striker Dual Guns",
"Worn Delta Dual Guns",
"Advanced Storm Dual Guns II",
"Worn Soldier Dual Guns II",
"Advanced Soldier Dual Guns II",
"Worn Warrior Dual Guns II",
"Advanced Warrior Dual Guns II",
"Worn Ophidian Dual Guns II",
"Advanced Ophidian Dual Guns II",
"Worn Destroyer Dual Guns II",
"Advanced Destroyer Dual Guns II",
"Worn Striker Dual Guns II",
"Advanced Striker Dual Guns II",
"Worn Delta Dual Guns II",
"Advanced Storm Gemels",
"Worn Soldier Gemels",
"Advanced Soldier Gemels",
"Worn Warrior Gemels",
"Advanced Warrior Gemels",
"Worn Ophidian Gemels",
"Advanced Ophidian Gemels",
"Worn Destroyer Gemels",
"Advanced Destroyer Gemels",
"Worn Striker Gemels",
"Advanced Striker Gemels",
"Worn Delta Gemels",
"Worn Warrior Pistolia",
"Advanced Warrior Pistolia",
"Worn Ophidian Pistolia",
"Advanced Ophidian Pistolia",
"Worn Destroyer Pistolia",
"Advanced Destroyer Pistolia",
"Worn Striker Pistolia",
"Advanced Striker Pistolia",
"Worn Delta Pistolia",
"Advanced Warrior Dyads",
"Worn Ophidian Dyads",
"Advanced Ophidian Dyads",
"Worn Destroyer Dyads",
"Advanced Destroyer Dyads",
"Worn Striker Dyads",
"Advanced Striker Dyads",
"Worn Delta Dyads",
"Advanced Warrior Dyads III",
"Worn Ophidian Dyads III",
"Advanced Ophidian Dyads III",
"Worn Destroyer Dyads III",
"Advanced Destroyer Dyads III",
"Worn Striker Dyads III",
"Advanced Striker Dyads III",
"Worn Delta Dyads III",
"Advanced Warrior Dyads II",
"Worn Ophidian Dyads II",
"Advanced Ophidian Dyads II",
"Worn Destroyer Dyads II",
"Advanced Destroyer Dyads II",
"Worn Striker Dyads II",
"Advanced Striker Dyads II",
"Worn Delta Dyads II",
"Advanced Warrior Bangbangs",
"Worn Ophidian Bangbangs",
"Advanced Ophidian Bangbangs",
"Worn Destroyer Bangbangs",
"Advanced Destroyer Bangbangs",
"Worn Striker Bangbangs",
"Advanced Striker Bangbangs",
"Worn Delta Bangbangs",
"Advanced Devastator Sidearm",
"Worn Sparrow Sidearm",
"Advanced Sparrow Sidearm",
"Worn Foxfire Sidearm",
"Advanced Foxfire Sidearm",
"Worn Rectifier Sidearm",
"Ultra Cosmic Dual Guns",
"Ultra Nebulan Dual Guns",
"Ultra Cosmic Dual Guns II",
"Ultra Nebulan Dual Guns II",
"Ultra Cosmic Gemels",
"Ultra Nebulan Gemels",
"Ultra Cosmic Pistolia",
"Ultra Nebulan Pistolia",
"Ultra Cosmic Dyads",
"Ultra Nebulan Dyads",
"Ultra Cosmic Dyads III",
"Ultra Nebulan Dyads III",
"Ultra Cosmic Dyads II",
"Ultra Nebulan Dyads II",
"Ultra Cosmic Bangbangs",
"Ultra Nebulan Bangbangs",
"Ultra Virtue Sidearm",
"Ultra Transience Sidearm",
"Storm Raygun",
"Storm Raygun",
"Storm Raygun",
"Soldier Raygun",
"Soldier Raygun",
"Soldier Raygun",
"Warrior Raygun",
"Warrior Raygun",
"Warrior Raygun",
"Ophidian Raygun",
"Ophidian Raygun",
"Ophidian Raygun",
"Destroyer Raygun",
"Destroyer Raygun",
"Destroyer Raygun",
"Striker Raygun",
"Striker Raygun",
"Striker Raygun",
"Delta Raygun",
"Delta Raygun",
"Delta Raygun",
"Storm Lastyr",
"Storm Lastyr",
"Storm Lastyr",
"Soldier Lastyr",
"Soldier Lastyr",
"Soldier Lastyr",
"Warrior Lastyr",
"Warrior Lastyr",
"Warrior Lastyr",
"Ophidian Lastyr",
"Ophidian Lastyr",
"Ophidian Lastyr",
"Destroyer Lastyr",
"Destroyer Lastyr",
"Destroyer Lastyr",
"Striker Lastyr",
"Striker Lastyr",
"Striker Lastyr",
"Delta Lastyr",
"Delta Lastyr",
"Delta Lastyr",
"Storm Lastyr II",
"Storm Lastyr II",
"Storm Lastyr II",
"Soldier Lastyr II",
"Soldier Lastyr II",
"Soldier Lastyr II",
"Warrior Lastyr II",
"Warrior Lastyr II",
"Warrior Lastyr II",
"Ophidian Lastyr II",
"Ophidian Lastyr II",
"Ophidian Lastyr II",
"Destroyer Lastyr II",
"Destroyer Lastyr II",
"Destroyer Lastyr II",
"Striker Lastyr II",
"Striker Lastyr II",
"Striker Lastyr II",
"Delta Lastyr II",
"Delta Lastyr II",
"Delta Lastyr II",
"Storm Lastyr III",
"Storm Lastyr III",
"Storm Lastyr III",
"Soldier Lastyr III",
"Soldier Lastyr III",
"Soldier Lastyr III",
"Warrior Lastyr III",
"Warrior Lastyr III",
"Warrior Lastyr III",
"Ophidian Lastyr III",
"Ophidian Lastyr III",
"Ophidian Lastyr III",
"Destroyer Lastyr III",
"Destroyer Lastyr III",
"Destroyer Lastyr III",
"Striker Lastyr III",
"Striker Lastyr III",
"Striker Lastyr III",
"Delta Lastyr III",
"Delta Lastyr III",
"Delta Lastyr III",
"Storm Radius",
"Storm Radius",
"Storm Radius",
"Soldier Radius",
"Soldier Radius",
"Soldier Radius",
"Warrior Radius",
"Warrior Radius",
"Warrior Radius",
"Ophidian Radius",
"Ophidian Radius",
"Ophidian Radius",
"Destroyer Radius",
"Destroyer Radius",
"Destroyer Radius",
"Striker Radius",
"Striker Radius",
"Striker Radius",
"Delta Radius",
"Delta Radius",
"Delta Radius",
"Storm Radius II",
"Storm Radius II",
"Storm Radius II",
"Soldier Radius II",
"Soldier Radius II",
"Soldier Radius II",
"Warrior Radius II",
"Warrior Radius II",
"Warrior Radius II",
"Ophidian Radius II",
"Ophidian Radius II",
"Ophidian Radius II",
"Destroyer Radius II",
"Destroyer Radius II",
"Destroyer Radius II",
"Striker Radius II",
"Striker Radius II",
"Striker Radius II",
"Delta Radius II",
"Delta Radius II",
"Delta Radius II",
"Storm Strobe",
"Storm Strobe",
"Storm Strobe",
"Soldier Strobe",
"Soldier Strobe",
"Soldier Strobe",
"Warrior Strobe",
"Warrior Strobe",
"Warrior Strobe",
"Ophidian Strobe",
"Ophidian Strobe",
"Ophidian Strobe",
"Destroyer Strobe",
"Destroyer Strobe",
"Destroyer Strobe",
"Striker Strobe",
"Striker Strobe",
"Striker Strobe",
"Delta Strobe",
"Delta Strobe",
"Delta Strobe",
"Storm Faith",
"Storm Faith",
"Storm Faith",
"Soldier Faith",
"Soldier Faith",
"Soldier Faith",
"Warrior Faith",
"Warrior Faith",
"Warrior Faith",
"Ophidian Faith",
"Ophidian Faith",
"Ophidian Faith",
"Destroyer Faith",
"Destroyer Faith",
"Destroyer Faith",
"Striker Faith",
"Striker Faith",
"Striker Faith",
"Delta Faith",
"Delta Faith",
"Delta Faith",
"Advanced Storm Raygun",
"Worn Soldier Raygun",
"Advanced Soldier Raygun",
"Worn Warrior Raygun",
"Advanced Warrior Raygun",
"Worn Ophidian Raygun",
"Advanced Ophidian Raygun",
"Worn Destroyer Raygun",
"Advanced Destroyer Raygun",
"Worn Striker Raygun",
"Advanced Striker Raygun",
"Worn Delta Raygun",
"Advanced Storm Lastyr",
"Worn Soldier Lastyr",
"Advanced Soldier Lastyr",
"Worn Warrior Lastyr",
"Advanced Warrior Lastyr",
"Worn Ophidian Lastyr",
"Advanced Ophidian Lastyr",
"Worn Destroyer Lastyr",
"Advanced Destroyer Lastyr",
"Worn Striker Lastyr",
"Advanced Striker Lastyr",
"Worn Delta Lastyr",
"Advanced Storm Lastyr II",
"Worn Soldier Lastyr II",
"Advanced Soldier Lastyr II",
"Worn Warrior Lastyr II",
"Advanced Warrior Lastyr II",
"Worn Ophidian Lastyr II",
"Advanced Ophidian Lastyr II",
"Worn Destroyer Lastyr II",
"Advanced Destroyer Lastyr II",
"Worn Striker Lastyr II",
"Advanced Striker Lastyr II",
"Worn Delta Lastyr II",
"Advanced Storm Lastyr III",
"Worn Soldier Lastyr III",
"Advanced Soldier Lastyr III",
"Worn Warrior Lastyr III",
"Advanced Warrior Lastyr III",
"Worn Ophidian Lastyr III",
"Advanced Ophidian Lastyr III",
"Worn Destroyer Lastyr III",
"Advanced Destroyer Lastyr III",
"Worn Striker Lastyr III",
"Advanced Striker Lastyr III",
"Worn Delta Lastyr III",
"Worn Warrior Radius",
"Advanced Warrior Radius",
"Worn Ophidian Radius",
"Advanced Ophidian Radius",
"Worn Destroyer Radius",
"Advanced Destroyer Radius",
"Worn Striker Radius",
"Advanced Striker Radius",
"Worn Delta Radius",
"Worn Warrior Radius II",
"Advanced Warrior Radius II",
"Worn Ophidian Radius II",
"Advanced Ophidian Radius II",
"Worn Destroyer Radius II",
"Advanced Destroyer Radius II",
"Worn Striker Radius II",
"Advanced Striker Radius II",
"Worn Delta Radius II",
"Advanced Warrior Strobe",
"Worn Ophidian Strobe",
"Advanced Ophidian Strobe",
"Worn Destroyer Strobe",
"Advanced Destroyer Strobe",
"Worn Striker Strobe",
"Advanced Striker Strobe",
"Worn Delta Strobe",
"Advanced Warrior Faith",
"Worn Ophidian Faith",
"Advanced Ophidian Faith",
"Worn Destroyer Faith",
"Advanced Destroyer Faith",
"Worn Striker Faith",
"Advanced Striker Faith",
"Worn Delta Faith",
"Ultra Cosmic Raygun",
"Ultra Nebulan Raygun",
"Ultra Cosmic Lastyr",
"Ultra Nebulan Lastyr",
"Ultra Cosmic Lastyr II",
"Ultra Nebulan Lastyr II",
"Ultra Cosmic Lastyr III",
"Ultra Nebulan Lastyr III",
"Ultra Cosmic Radius",
"Ultra Nebulan Radius",
"Ultra Cosmic Radius II",
"Ultra Nebulan Radius II",
"Ultra Cosmic Strobe",
"Ultra Nebulan Strobe",
"Ultra Cosmic Faith",
"Ultra Nebulan Faith",
"Storm Machine",
"Storm Machine",
"Storm Machine",
"Soldier Machine",
"Soldier Machine",
"Soldier Machine",
"Warrior Machine",
"Warrior Machine",
"Warrior Machine",
"Ophidian Machine",
"Ophidian Machine",
"Ophidian Machine",
"Destroyer Machine",
"Destroyer Machine",
"Destroyer Machine",
"Striker Machine",
"Striker Machine",
"Striker Machine",
"Delta Machine",
"Delta Machine",
"Delta Machine",
"Storm Machine II",
"Storm Machine II",
"Storm Machine II",
"Soldier Machine II",
"Soldier Machine II",
"Soldier Machine II",
"Warrior Machine II",
"Warrior Machine II",
"Warrior Machine II",
"Ophidian Machine II",
"Ophidian Machine II",
"Ophidian Machine II",
"Destroyer Machine II",
"Destroyer Machine II",
"Destroyer Machine II",
"Striker Machine II",
"Striker Machine II",
"Striker Machine II",
"Delta Machine II",
"Delta Machine II",
"Delta Machine II",
"Storm Repethe",
"Storm Repethe",
"Storm Repethe",
"Soldier Repethe",
"Soldier Repethe",
"Soldier Repethe",
"Warrior Repethe",
"Warrior Repethe",
"Warrior Repethe",
"Ophidian Repethe",
"Ophidian Repethe",
"Ophidian Repethe",
"Destroyer Repethe",
"Destroyer Repethe",
"Destroyer Repethe",
"Striker Repethe",
"Striker Repethe",
"Striker Repethe",
"Delta Repethe",
"Delta Repethe",
"Delta Repethe",
"Storm Grando II",
"Storm Grando II",
"Storm Grando II",
"Soldier Grando II",
"Soldier Grando II",
"Soldier Grando II",
"Warrior Grando II",
"Warrior Grando II",
"Warrior Grando II",
"Ophidian Grando II",
"Ophidian Grando II",
"Ophidian Grando II",
"Destroyer Grando II",
"Destroyer Grando II",
"Destroyer Grando II",
"Striker Grando II",
"Striker Grando II",
"Striker Grando II",
"Delta Grando II",
"Delta Grando II",
"Delta Grando II",
"Storm Grando",
"Storm Grando",
"Storm Grando",
"Soldier Grando",
"Soldier Grando",
"Soldier Grando",
"Warrior Grando",
"Warrior Grando",
"Warrior Grando",
"Ophidian Grando",
"Ophidian Grando",
"Ophidian Grando",
"Destroyer Grando",
"Destroyer Grando",
"Destroyer Grando",
"Striker Grando",
"Striker Grando",
"Striker Grando",
"Delta Grando",
"Delta Grando",
"Delta Grando",
"Storm Crank",
"Storm Crank",
"Storm Crank",
"Soldier Crank",
"Soldier Crank",
"Soldier Crank",
"Warrior Crank",
"Warrior Crank",
"Warrior Crank",
"Ophidian Crank",
"Ophidian Crank",
"Ophidian Crank",
"Destroyer Crank",
"Destroyer Crank",
"Destroyer Crank",
"Striker Crank",
"Striker Crank",
"Striker Crank",
"Delta Crank",
"Delta Crank",
"Delta Crank",
"Storm Ratatatta",
"Storm Ratatatta",
"Storm Ratatatta",
"Soldier Ratatatta",
"Soldier Ratatatta",
"Soldier Ratatatta",
"Warrior Ratatatta",
"Warrior Ratatatta",
"Warrior Ratatatta",
"Ophidian Ratatatta",
"Ophidian Ratatatta",
"Ophidian Ratatatta",
"Destroyer Ratatatta",
"Destroyer Ratatatta",
"Destroyer Ratatatta",
"Striker Ratatatta",
"Striker Ratatatta",
"Striker Ratatatta",
"Delta Ratatatta",
"Delta Ratatatta",
"Delta Ratatatta",
"Storm Ziyse",
"Storm Ziyse",
"Storm Ziyse",
"Soldier Ziyse",
"Soldier Ziyse",
"Soldier Ziyse",
"Warrior Ziyse",
"Warrior Ziyse",
"Warrior Ziyse",
"Ophidian Ziyse",
"Ophidian Ziyse",
"Ophidian Ziyse",
"Destroyer Ziyse",
"Destroyer Ziyse",
"Destroyer Ziyse",
"Striker Ziyse",
"Striker Ziyse",
"Striker Ziyse",
"Delta Ziyse",
"Delta Ziyse",
"Delta Ziyse",
"Advanced Storm Machine",
"Worn Soldier Machine",
"Advanced Soldier Machine",
"Worn Warrior Machine",
"Advanced Warrior Machine",
"Worn Ophidian Machine",
"Advanced Ophidian Machine",
"Worn Destroyer Machine",
"Advanced Destroyer Machine",
"Worn Striker Machine",
"Advanced Striker Machine",
"Worn Delta Machine",
"Advanced Storm Machine II",
"Worn Soldier Machine II",
"Advanced Soldier Machine II",
"Worn Warrior Machine II",
"Advanced Warrior Machine II",
"Worn Ophidian Machine II",
"Advanced Ophidian Machine II",
"Worn Destroyer Machine II",
"Advanced Destroyer Machine II",
"Worn Striker Machine II",
"Advanced Striker Machine II",
"Worn Delta Machine II",
"Advanced Storm Repethe",
"Worn Soldier Repethe",
"Advanced Soldier Repethe",
"Worn Warrior Repethe",
"Advanced Warrior Repethe",
"Worn Ophidian Repethe",
"Advanced Ophidian Repethe",
"Worn Destroyer Repethe",
"Advanced Destroyer Repethe",
"Worn Striker Repethe",
"Advanced Striker Repethe",
"Worn Delta Repethe",
"Worn Warrior Grando II",
"Advanced Warrior Grando II",
"Worn Ophidian Grando II",
"Advanced Ophidian Grando II",
"Worn Destroyer Grando II",
"Advanced Destroyer Grando II",
"Worn Striker Grando II",
"Advanced Striker Grando II",
"Worn Delta Grando II",
"Worn Warrior Grando",
"Advanced Warrior Grando",
"Worn Ophidian Grando",
"Advanced Ophidian Grando",
"Worn Destroyer Grando",
"Advanced Destroyer Grando",
"Worn Striker Grando",
"Advanced Striker Grando",
"Worn Delta Grando",
"Advanced Warrior Crank",
"Worn Ophidian Crank",
"Advanced Ophidian Crank",
"Worn Destroyer Crank",
"Advanced Destroyer Crank",
"Worn Striker Crank",
"Advanced Striker Crank",
"Worn Delta Crank",
"Advanced Warrior Ratatatta",
"Worn Ophidian Ratatatta",
"Advanced Ophidian Ratatatta",
"Worn Destroyer Ratatatta",
"Advanced Destroyer Ratatatta",
"Worn Striker Ratatatta",
"Advanced Striker Ratatatta",
"Worn Delta Ratatatta",
"Worn Ophidian Ziyse",
"Advanced Ophidian Ziyse",
"Worn Destroyer Ziyse",
"Advanced Destroyer Ziyse",
"Worn Striker Ziyse",
"Advanced Striker Ziyse",
"Worn Delta Ziyse",
"Ultra Cosmic Machine",
"Ultra Nebulan Machine",
"Ultra Cosmic Machine II",
"Ultra Nebulan Machine II",
"Ultra Cosmic Repethe",
"Ultra Nebulan Repethe",
"Ultra Cosmic Grando II",
"Ultra Nebulan Grando II",
"Ultra Cosmic Grando",
"Ultra Nebulan Grando",
"Ultra Cosmic Crank",
"Ultra Nebulan Crank",
"Ultra Cosmic Ratatatta",
"Ultra Nebulan Ratatatta",
"Ultra Cosmic Ziyse",
"Ultra Nebulan Ziyse",
"Storm Sniper Rifle",
"Storm Sniper Rifle",
"Storm Sniper Rifle",
"Soldier Sniper Rifle",
"Soldier Sniper Rifle",
"Soldier Sniper Rifle",
"Warrior Sniper Rifle",
"Warrior Sniper Rifle",
"Warrior Sniper Rifle",
"Ophidian Sniper Rifle",
"Ophidian Sniper Rifle",
"Ophidian Sniper Rifle",
"Destroyer Sniper Rifle",
"Destroyer Sniper Rifle",
"Destroyer Sniper Rifle",
"Striker Sniper Rifle",
"Striker Sniper Rifle",
"Striker Sniper Rifle",
"Delta Sniper Rifle",
"Delta Sniper Rifle",
"Delta Sniper Rifle",
"Storm Sniper Rifle II",
"Storm Sniper Rifle II",
"Storm Sniper Rifle II",
"Soldier Sniper Rifle II",
"Soldier Sniper Rifle II",
"Soldier Sniper Rifle II",
"Warrior Sniper Rifle II",
"Warrior Sniper Rifle II",
"Warrior Sniper Rifle II",
"Ophidian Sniper Rifle II",
"Ophidian Sniper Rifle II",
"Ophidian Sniper Rifle II",
"Destroyer Sniper Rifle II",
"Destroyer Sniper Rifle II",
"Destroyer Sniper Rifle II",
"Striker Sniper Rifle II",
"Striker Sniper Rifle II",
"Striker Sniper Rifle II",
"Delta Sniper Rifle II",
"Delta Sniper Rifle II",
"Delta Sniper Rifle II",
"Storm Retic",
"Storm Retic",
"Storm Retic",
"Soldier Retic",
"Soldier Retic",
"Soldier Retic",
"Warrior Retic",
"Warrior Retic",
"Warrior Retic",
"Ophidian Retic",
"Ophidian Retic",
"Ophidian Retic",
"Destroyer Retic",
"Destroyer Retic",
"Destroyer Retic",
"Striker Retic",
"Striker Retic",
"Striker Retic",
"Delta Retic",
"Delta Retic",
"Delta Retic",
"Storm Sicarius",
"Storm Sicarius",
"Storm Sicarius",
"Soldier Sicarius",
"Soldier Sicarius",
"Soldier Sicarius",
"Warrior Sicarius",
"Warrior Sicarius",
"Warrior Sicarius",
"Ophidian Sicarius",
"Ophidian Sicarius",
"Ophidian Sicarius",
"Destroyer Sicarius",
"Destroyer Sicarius",
"Destroyer Sicarius",
"Striker Sicarius",
"Striker Sicarius",
"Striker Sicarius",
"Delta Sicarius",
"Delta Sicarius",
"Delta Sicarius",
"Storm Trigger",
"Storm Trigger",
"Storm Trigger",
"Soldier Trigger",
"Soldier Trigger",
"Soldier Trigger",
"Warrior Trigger",
"Warrior Trigger",
"Warrior Trigger",
"Ophidian Trigger",
"Ophidian Trigger",
"Ophidian Trigger",
"Destroyer Trigger",
"Destroyer Trigger",
"Destroyer Trigger",
"Striker Trigger",
"Striker Trigger",
"Striker Trigger",
"Delta Trigger",
"Delta Trigger",
"Delta Trigger",
"Storm Thwipper",
"Storm Thwipper",
"Storm Thwipper",
"Soldier Thwipper",
"Soldier Thwipper",
"Soldier Thwipper",
"Warrior Thwipper",
"Warrior Thwipper",
"Warrior Thwipper",
"Ophidian Thwipper",
"Ophidian Thwipper",
"Ophidian Thwipper",
"Destroyer Thwipper",
"Destroyer Thwipper",
"Destroyer Thwipper",
"Striker Thwipper",
"Striker Thwipper",
"Striker Thwipper",
"Delta Thwipper",
"Delta Thwipper",
"Delta Thwipper",
"IW_MU_S_SNIPER_A04_0101_name",
"IW_MU_S_SNIPER_A04_0101_name",
"IW_MU_S_SNIPER_A04_0101_name",
"IW_MU_S_SNIPER_A05_1001_name",
"IW_MU_S_SNIPER_A05_1001_name",
"IW_MU_S_SNIPER_A05_1001_name",
"Rugged Deadsight",
"Rugged Deadsight",
"Rugged Deadsight",
"Devastator Deadsight",
"Devastator Deadsight",
"Devastator Deadsight",
"Sparrow Deadsight",
"Sparrow Deadsight",
"Sparrow Deadsight",
"Foxfire Deadsight",
"Foxfire Deadsight",
"Foxfire Deadsight",
"Rectifier Deadsight",
"Rectifier Deadsight",
"Rectifier Deadsight",
"IW_MU_S_SNIPER_B05_0101_name",
"IW_MU_S_SNIPER_B05_0101_name",
"IW_MU_S_SNIPER_B05_0101_name",
"IW_MU_S_SNIPER_B07_1001_name",
"IW_MU_S_SNIPER_B07_1001_name",
"IW_MU_S_SNIPER_B07_1001_name",
"Rugged Deadsight II",
"Rugged Deadsight II",
"Rugged Deadsight II",
"Devastator Deadsight II",
"Devastator Deadsight II",
"Devastator Deadsight II",
"Sparrow Deadsight II",
"Sparrow Deadsight II",
"Sparrow Deadsight II",
"Foxfire Deadsight II",
"Foxfire Deadsight II",
"Foxfire Deadsight II",
"Rectifier Deadsight II",
"Rectifier Deadsight II",
"Rectifier Deadsight II",
"Advanced Storm Sniper Rifle",
"Worn Soldier Sniper Rifle",
"Advanced Soldier Sniper Rifle",
"Worn Warrior Sniper Rifle",
"Advanced Warrior Sniper Rifle",
"Worn Ophidian Sniper Rifle",
"Advanced Ophidian Sniper Rifle",
"Worn Destroyer Sniper Rifle",
"Advanced Destroyer Sniper Rifle",
"Worn Striker Sniper Rifle",
"Advanced Striker Sniper Rifle",
"Worn Delta Sniper Rifle",
"Advanced Storm Sniper Rifle II",
"Worn Soldier Sniper Rifle II",
"Advanced Soldier Sniper Rifle II",
"Worn Warrior Sniper Rifle II",
"Advanced Warrior Sniper Rifle II",
"Worn Ophidian Sniper Rifle II",
"Advanced Ophidian Sniper Rifle II",
"Worn Destroyer Sniper Rifle II",
"Advanced Destroyer Sniper Rifle II",
"Worn Striker Sniper Rifle II",
"Advanced Striker Sniper Rifle II",
"Worn Delta Sniper Rifle II",
"Advanced Storm Retic",
"Worn Soldier Retic",
"Advanced Soldier Retic",
"Worn Warrior Retic",
"Advanced Warrior Retic",
"Worn Ophidian Retic",
"Advanced Ophidian Retic",
"Worn Destroyer Retic",
"Advanced Destroyer Retic",
"Worn Striker Retic",
"Advanced Striker Retic",
"Worn Delta Retic",
"Worn Warrior Sicarius",
"Advanced Warrior Sicarius",
"Worn Ophidian Sicarius",
"Advanced Ophidian Sicarius",
"Worn Destroyer Sicarius",
"Advanced Destroyer Sicarius",
"Worn Striker Sicarius",
"Advanced Striker Sicarius",
"Worn Delta Sicarius",
"Advanced Warrior Trigger",
"Worn Ophidian Trigger",
"Advanced Ophidian Trigger",
"Worn Destroyer Trigger",
"Advanced Destroyer Trigger",
"Worn Striker Trigger",
"Advanced Striker Trigger",
"Worn Delta Trigger",
"Advanced Warrior Thwipper",
"Worn Ophidian Thwipper",
"Advanced Ophidian Thwipper",
"Worn Destroyer Thwipper",
"Advanced Destroyer Thwipper",
"Worn Striker Thwipper",
"Advanced Striker Thwipper",
"Worn Delta Thwipper",
"Advanced Devastator Deadsight",
"Worn Sparrow Deadsight",
"Advanced Sparrow Deadsight",
"Worn Foxfire Deadsight",
"Advanced Foxfire Deadsight",
"Worn Rectifier Deadsight",
"Advanced Devastator Deadsight II",
"Worn Sparrow Deadsight II",
"Advanced Sparrow Deadsight II",
"Worn Foxfire Deadsight II",
"Advanced Foxfire Deadsight II",
"Worn Rectifier Deadsight II",
"Ultra Cosmic Sniper Rifle",
"Ultra Nebulan Sniper Rifle",
"Ultra Cosmic Sniper Rifle II",
"Ultra Nebulan Sniper Rifle II",
"Ultra Cosmic Retic",
"Ultra Nebulan Retic",
"Ultra Cosmic Sicarius",
"Ultra Nebulan Sicarius",
"Ultra Cosmic Trigger",
"Ultra Nebulan Trigger",
"Ultra Cosmic Thwipper",
"Ultra Nebulan Thwipper",
"Ultra Virtue Deadsight",
"Ultra Transience Deadsight",
"Ultra Virtue Deadsight II",
"Ultra Transience Deadsight II",
"Storm Launchers",
"Storm Launchers",
"Storm Launchers",
"Soldier Launchers",
"Soldier Launchers",
"Soldier Launchers",
"Warrior Launchers",
"Warrior Launchers",
"Warrior Launchers",
"Ophidian Launchers",
"Ophidian Launchers",
"Ophidian Launchers",
"Destroyer Launchers",
"Destroyer Launchers",
"Destroyer Launchers",
"Striker Launchers",
"Striker Launchers",
"Striker Launchers",
"Delta Launchers",
"Delta Launchers",
"Delta Launchers",
"Storm Psylans",
"Storm Psylans",
"Storm Psylans",
"Soldier Psylans",
"Soldier Psylans",
"Soldier Psylans",
"Warrior Psylans",
"Warrior Psylans",
"Warrior Psylans",
"Ophidian Psylans",
"Ophidian Psylans",
"Ophidian Psylans",
"Destroyer Psylans",
"Destroyer Psylans",
"Destroyer Psylans",
"Striker Psylans",
"Striker Psylans",
"Striker Psylans",
"Delta Psylans",
"Delta Psylans",
"Delta Psylans",
"Storm Ruina",
"Storm Ruina",
"Storm Ruina",
"Soldier Ruina",
"Soldier Ruina",
"Soldier Ruina",
"Warrior Ruina",
"Warrior Ruina",
"Warrior Ruina",
"Ophidian Ruina",
"Ophidian Ruina",
"Ophidian Ruina",
"Destroyer Ruina",
"Destroyer Ruina",
"Destroyer Ruina",
"Striker Ruina",
"Striker Ruina",
"Striker Ruina",
"Delta Ruina",
"Delta Ruina",
"Delta Ruina",
"Storm Ruina II",
"Storm Ruina II",
"Storm Ruina II",
"Soldier Ruina II",
"Soldier Ruina II",
"Soldier Ruina II",
"Warrior Ruina II",
"Warrior Ruina II",
"Warrior Ruina II",
"Ophidian Ruina II",
"Ophidian Ruina II",
"Ophidian Ruina II",
"Destroyer Ruina II",
"Destroyer Ruina II",
"Destroyer Ruina II",
"Striker Ruina II",
"Striker Ruina II",
"Striker Ruina II",
"Delta Ruina II",
"Delta Ruina II",
"Delta Ruina II",
"Storm Ruina III",
"Storm Ruina III",
"Storm Ruina III",
"Soldier Ruina III",
"Soldier Ruina III",
"Soldier Ruina III",
"Warrior Ruina III",
"Warrior Ruina III",
"Warrior Ruina III",
"Ophidian Ruina III",
"Ophidian Ruina III",
"Ophidian Ruina III",
"Destroyer Ruina III",
"Destroyer Ruina III",
"Destroyer Ruina III",
"Striker Ruina III",
"Striker Ruina III",
"Striker Ruina III",
"Delta Ruina III",
"Delta Ruina III",
"Delta Ruina III",
"Storm Saboteurs",
"Storm Saboteurs",
"Storm Saboteurs",
"Soldier Saboteurs",
"Soldier Saboteurs",
"Soldier Saboteurs",
"Warrior Saboteurs",
"Warrior Saboteurs",
"Warrior Saboteurs",
"Ophidian Saboteurs",
"Ophidian Saboteurs",
"Ophidian Saboteurs",
"Destroyer Saboteurs",
"Destroyer Saboteurs",
"Destroyer Saboteurs",
"Striker Saboteurs",
"Striker Saboteurs",
"Striker Saboteurs",
"Delta Saboteurs",
"Delta Saboteurs",
"Delta Saboteurs",
"Storm Fwooshers",
"Storm Fwooshers",
"Storm Fwooshers",
"Soldier Fwooshers",
"Soldier Fwooshers",
"Soldier Fwooshers",
"Warrior Fwooshers",
"Warrior Fwooshers",
"Warrior Fwooshers",
"Ophidian Fwooshers",
"Ophidian Fwooshers",
"Ophidian Fwooshers",
"Destroyer Fwooshers",
"Destroyer Fwooshers",
"Destroyer Fwooshers",
"Striker Fwooshers",
"Striker Fwooshers",
"Striker Fwooshers",
"Delta Fwooshers",
"Delta Fwooshers",
"Delta Fwooshers",
"Storm Zorcyses",
"Storm Zorcyses",
"Storm Zorcyses",
"Soldier Zorcyses",
"Soldier Zorcyses",
"Soldier Zorcyses",
"Warrior Zorcyses",
"Warrior Zorcyses",
"Warrior Zorcyses",
"Ophidian Zorcyses",
"Ophidian Zorcyses",
"Ophidian Zorcyses",
"Destroyer Zorcyses",
"Destroyer Zorcyses",
"Destroyer Zorcyses",
"Striker Zorcyses",
"Striker Zorcyses",
"Striker Zorcyses",
"Delta Zorcyses",
"Delta Zorcyses",
"Delta Zorcyses",
"Advanced Storm Launchers",
"Worn Soldier Launchers",
"Advanced Soldier Launchers",
"Worn Warrior Launchers",
"Advanced Warrior Launchers",
"Worn Ophidian Launchers",
"Advanced Ophidian Launchers",
"Worn Destroyer Launchers",
"Advanced Destroyer Launchers",
"Worn Striker Launchers",
"Advanced Striker Launchers",
"Worn Delta Launchers",
"Advanced Storm Psylans",
"Worn Soldier Psylans",
"Advanced Soldier Psylans",
"Worn Warrior Psylans",
"Advanced Warrior Psylans",
"Worn Ophidian Psylans",
"Advanced Ophidian Psylans",
"Worn Destroyer Psylans",
"Advanced Destroyer Psylans",
"Worn Striker Psylans",
"Advanced Striker Psylans",
"Worn Delta Psylans",
"Worn Warrior Ruina",
"Advanced Warrior Ruina",
"Worn Ophidian Ruina",
"Advanced Ophidian Ruina",
"Worn Destroyer Ruina",
"Advanced Destroyer Ruina",
"Worn Striker Ruina",
"Advanced Striker Ruina",
"Worn Delta Ruina",
"Worn Warrior Ruina II",
"Advanced Warrior Ruina II",
"Worn Ophidian Ruina II",
"Advanced Ophidian Ruina II",
"Worn Destroyer Ruina II",
"Advanced Destroyer Ruina II",
"Worn Striker Ruina II",
"Advanced Striker Ruina II",
"Worn Delta Ruina II",
"Worn Warrior Ruina III",
"Advanced Warrior Ruina III",
"Worn Ophidian Ruina III",
"Advanced Ophidian Ruina III",
"Worn Destroyer Ruina III",
"Advanced Destroyer Ruina III",
"Worn Striker Ruina III",
"Advanced Striker Ruina III",
"Worn Delta Ruina III",
"Advanced Warrior Saboteurs",
"Worn Ophidian Saboteurs",
"Advanced Ophidian Saboteurs",
"Worn Destroyer Saboteurs",
"Advanced Destroyer Saboteurs",
"Worn Striker Saboteurs",
"Advanced Striker Saboteurs",
"Worn Delta Saboteurs",
"Advanced Warrior Fwooshers",
"Worn Ophidian Fwooshers",
"Advanced Ophidian Fwooshers",
"Worn Destroyer Fwooshers",
"Advanced Destroyer Fwooshers",
"Worn Striker Fwooshers",
"Advanced Striker Fwooshers",
"Worn Delta Fwooshers",
"Worn Ophidian Zorcyses",
"Advanced Ophidian Zorcyses",
"Worn Destroyer Zorcyses",
"Advanced Destroyer Zorcyses",
"Worn Striker Zorcyses",
"Advanced Striker Zorcyses",
"Worn Delta Zorcyses",
"Ultra Cosmic Launchers",
"Ultra Nebulan Launchers",
"Ultra Cosmic Psylans",
"Ultra Nebulan Psylans",
"Ultra Cosmic Ruina",
"Ultra Nebulan Ruina",
"Ultra Cosmic Ruina II",
"Ultra Nebulan Ruina II",
"Ultra Cosmic Ruina III",
"Ultra Nebulan Ruina III",
"Ultra Cosmic Saboteurs",
"Ultra Nebulan Saboteurs",
"Ultra Cosmic Fwooshers",
"Ultra Nebulan Fwooshers",
"Ultra Cosmic Zorcyses",
"Ultra Nebulan Zorcyses",
"Warrior Bliss",
"Warrior Bliss",
"Warrior Bliss",
"Ophidian Bliss",
"Ophidian Bliss",
"Ophidian Bliss",
"Destroyer Bliss",
"Destroyer Bliss",
"Destroyer Bliss",
"Striker Bliss",
"Striker Bliss",
"Striker Bliss",
"Delta Bliss",
"Delta Bliss",
"Delta Bliss",
"Advanced Warrior Bliss",
"Worn Ophidian Bliss",
"Advanced Ophidian Bliss",
"Worn Destroyer Bliss",
"Advanced Destroyer Bliss",
"Worn Striker Bliss",
"Advanced Striker Bliss",
"Worn Delta Bliss",
"Cosmic Bliss",
"Nebulan Bliss",
"Masterstroke Glaive",
"Masterstroke Glaive II",
"Original Twins",
"Original Watxes",
"Masterstroke Edges II",
"Masterstroke Edges",
"Original Pokepoke",
"Original Iyst",
"Original Iyst II",
"Original Haven",
"Original Haven II",
"Original Thudclang",
"Original Bolide",
"Original Jyth",
"Masterstroke Lance",
"Masterstroke Lightblade",
"Masterstroke Lightblade II",
"Original Assailer",
"Masterstroke Raidrifle",
"Original Dyads",
"Original Dyads III",
"Original Dyads II",
"Original Bangbangs",
"Masterstroke Sidearm",
"Original Strobe",
"Original Crank",
"Original Ratatatta",
"Original Ziyse",
"Original Trigger",
"Original Thwipper",
"Masterstroke Deadsight",
"Masterstroke Deadsight II",
"Original Saboteurs",
"Original Fwooshers",
"Original Zorcyses",
"Archetype Sword",
"Archetype Slair II",
"Archetype Sword II",
"Archetype Blades",
"Archetype Ralzes",
"Archetype Blades II",
"Archetype Knife III",
"Archetype Riv",
"Archetype Knife II",
"Archetype Paive",
"Archetype Shield",
"Advanced Archetype Paive",
"Archetype Spear",
"Archetype Parce",
"Archetype Spear II",
"Archetype Fulge",
"Archetype Saber",
"Archetype Fulge II",
"Archetype Assault Rifle III",
"Archetype Avagar",
"Archetype Assault Rifle II",
"Archetype Dual Guns",
"Archetype Gemels",
"Archetype Dual Guns II",
"Archetype Lastyr II",
"Archetype Raygun",
"Archetype Lastyr III",
"Archetype Machine",
"Archetype Repethe",
"Archetype Machine II",
"Archetype Sniper Rifle",
"Archetype Retic",
"Archetype Sniper Rifle II",
"Archetype Psylans",
"Archetype Launchers",
"Advanced Archetype Psylans",
"Signature Glaive: Fledgling",
"Signature Glaive: Four Virtues",
"Ethereal Glaive: Helldragon",
"Bewitched Glaive: Blood Dance",
"Signature Glaive: Allegiance",
"Mighty Glaive: Galaxy Chief",
"Bewitched Glaive: Receding Rust",
"Legendary Nopopopopon",
"Trial Knife",
"Trial Assault Rifle",
"Trial Sword",
"Titanium Knife",
"Advanced Soldier Assault Rifle",
]