from ..Items import Itm as Data

#https://xenoblade.github.io/xbx/bdat/common_local_us/AMR_PcList.html
ground_armor_data:list[Data] = [
Data("UNUSED", valid=False), 
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("Prototype Headset"),
Data("Prototype Shirt"),
Data("Prototype Sleeve R"),
Data("Prototype Sleeve L"),
Data("Prototype Pants"),
Data("Clover Headset"),
Data("Clover Shirt"),
Data("Clover Sleeve R"),
Data("Clover Sleeve L"),
Data("Clover Pants"),
Data("Clover Headset"),
Data("Clover Shirt"),
Data("Clover Sleeve R"),
Data("Clover Sleeve L"),
Data("Clover Pants"),
Data("Clover Headset"),
Data("Clover Shirt"),
Data("Clover Sleeve R"),
Data("Clover Sleeve L"),
Data("Clover Pants"),
Data("Survival Headset"),
Data("Survival Shirt"),
Data("Survival Sleeve R"),
Data("Survival Sleeve L"),
Data("Survival Pants"),
Data("Survival Headset"),
Data("Survival Shirt"),
Data("Survival Sleeve R"),
Data("Survival Sleeve L"),
Data("Survival Pants"),
Data("Survival Headset"),
Data("Survival Shirt"),
Data("Survival Sleeve R"),
Data("Survival Sleeve L"),
Data("Survival Pants"),
Data("Combat Headset"),
Data("Combat Shirt"),
Data("Combat Sleeve R"),
Data("Combat Sleeve L"),
Data("Combat Pants"),
Data("Combat Headset"),
Data("Combat Shirt"),
Data("Combat Sleeve R"),
Data("Combat Sleeve L"),
Data("Combat Pants"),
Data("Combat Headset"),
Data("Combat Shirt"),
Data("Combat Sleeve R"),
Data("Combat Sleeve L"),
Data("Combat Pants"),
Data("Vivid Headset"),
Data("Vivid Shirt"),
Data("Vivid Sleeve R"),
Data("Vivid Sleeve L"),
Data("Vivid Pants"),
Data("Vivid Headset"),
Data("Vivid Shirt"),
Data("Vivid Sleeve R"),
Data("Vivid Sleeve L"),
Data("Vivid Pants"),
Data("Vivid Headset"),
Data("Vivid Shirt"),
Data("Vivid Sleeve R"),
Data("Vivid Sleeve L"),
Data("Vivid Pants"),
Data("Valor Headset"),
Data("Valor Shirt"),
Data("Valor Sleeve R"),
Data("Valor Sleeve L"),
Data("Valor Pants"),
Data("Valor Headset"),
Data("Valor Shirt"),
Data("Valor Sleeve R"),
Data("Valor Sleeve L"),
Data("Valor Pants"),
Data("Valor Headset"),
Data("Valor Shirt"),
Data("Valor Sleeve R"),
Data("Valor Sleeve L"),
Data("Valor Pants"),
Data("Forza Headset"),
Data("Forza Shirt"),
Data("Forza Sleeve R"),
Data("Forza Sleeve L"),
Data("Forza Pants"),
Data("Forza Headset"),
Data("Forza Shirt"),
Data("Forza Sleeve R"),
Data("Forza Sleeve L"),
Data("Forza Pants"),
Data("Forza Headset"),
Data("Forza Shirt"),
Data("Forza Sleeve R"),
Data("Forza Sleeve L"),
Data("Forza Pants"),
Data("Reginal Headset"),
Data("Reginal Shirt"),
Data("Reginal Sleeve R"),
Data("Reginal Sleeve L"),
Data("Reginal Pants"),
Data("Reginal Headset"),
Data("Reginal Shirt"),
Data("Reginal Sleeve R"),
Data("Reginal Sleeve L"),
Data("Reginal Pants"),
Data("Reginal Headset"),
Data("Reginal Shirt"),
Data("Reginal Sleeve R"),
Data("Reginal Sleeve L"),
Data("Reginal Pants"),
Data("Prototype Visor"),
Data("Prototype Vest"),
Data("Prototype Guard R"),
Data("Prototype Guard L"),
Data("Prototype Boots"),
Data("Survival Visor"),
Data("Survival Vest"),
Data("Survival Guard R"),
Data("Survival Guard L"),
Data("Survival Boots"),
Data("Survival Visor"),
Data("Survival Vest"),
Data("Survival Guard R"),
Data("Survival Guard L"),
Data("Survival Boots"),
Data("Survival Visor"),
Data("Survival Vest"),
Data("Survival Guard R"),
Data("Survival Guard L"),
Data("Survival Boots"),
Data("Combat Visor"),
Data("Combat Vest"),
Data("Combat Guard R"),
Data("Combat Guard L"),
Data("Combat Boots"),
Data("Combat Visor"),
Data("Combat Vest"),
Data("Combat Guard R"),
Data("Combat Guard L"),
Data("Combat Boots"),
Data("Combat Visor"),
Data("Combat Vest"),
Data("Combat Guard R"),
Data("Combat Guard L"),
Data("Combat Boots"),
Data("Vivid Visor"),
Data("Vivid Vest"),
Data("Vivid Guard R"),
Data("Vivid Guard L"),
Data("Vivid Boots"),
Data("Vivid Visor"),
Data("Vivid Vest"),
Data("Vivid Guard R"),
Data("Vivid Guard L"),
Data("Vivid Boots"),
Data("Vivid Visor"),
Data("Vivid Vest"),
Data("Vivid Guard R"),
Data("Vivid Guard L"),
Data("Vivid Boots"),
Data("Valor Visor"),
Data("Valor Vest"),
Data("Valor Guard R"),
Data("Valor Guard L"),
Data("Valor Boots"),
Data("Valor Visor"),
Data("Valor Vest"),
Data("Valor Guard R"),
Data("Valor Guard L"),
Data("Valor Boots"),
Data("Valor Visor"),
Data("Valor Vest"),
Data("Valor Guard R"),
Data("Valor Guard L"),
Data("Valor Boots"),
Data("Forza Visor"),
Data("Forza Vest"),
Data("Forza Guard R"),
Data("Forza Guard L"),
Data("Forza Boots"),
Data("Forza Visor"),
Data("Forza Vest"),
Data("Forza Guard R"),
Data("Forza Guard L"),
Data("Forza Boots"),
Data("Forza Visor"),
Data("Forza Vest"),
Data("Forza Guard R"),
Data("Forza Guard L"),
Data("Forza Boots"),
Data("Reginal Visor"),
Data("Reginal Vest"),
Data("Reginal Guard R"),
Data("Reginal Guard L"),
Data("Reginal Boots"),
Data("Reginal Visor"),
Data("Reginal Vest"),
Data("Reginal Guard R"),
Data("Reginal Guard L"),
Data("Reginal Boots"),
Data("Reginal Visor"),
Data("Reginal Vest"),
Data("Reginal Guard R"),
Data("Reginal Guard L"),
Data("Reginal Boots"),
Data("Prototype Goggles"),
Data("Prototype Bodywear"),
Data("Prototype Glove R"),
Data("Prototype Glove L"),
Data("Prototype Footwear"),
Data("Clover Goggles"),
Data("Clover Bodywear"),
Data("Clover Glove R"),
Data("Clover Glove L"),
Data("Clover Footwear"),
Data("Clover Goggles"),
Data("Clover Bodywear"),
Data("Clover Glove R"),
Data("Clover Glove L"),
Data("Clover Footwear"),
Data("Clover Goggles"),
Data("Clover Bodywear"),
Data("Clover Glove R"),
Data("Clover Glove L"),
Data("Clover Footwear"),
Data("Survival Goggles"),
Data("Survival Bodywear"),
Data("Survival Glove R"),
Data("Survival Glove L"),
Data("Survival Footwear"),
Data("Survival Goggles"),
Data("Survival Bodywear"),
Data("Survival Glove R"),
Data("Survival Glove L"),
Data("Survival Footwear"),
Data("Survival Goggles"),
Data("Survival Bodywear"),
Data("Survival Glove R"),
Data("Survival Glove L"),
Data("Survival Footwear"),
Data("Combat Goggles"),
Data("Combat Bodywear"),
Data("Combat Glove R"),
Data("Combat Glove L"),
Data("Combat Footwear"),
Data("Combat Goggles"),
Data("Combat Bodywear"),
Data("Combat Glove R"),
Data("Combat Glove L"),
Data("Combat Footwear"),
Data("Combat Goggles"),
Data("Combat Bodywear"),
Data("Combat Glove R"),
Data("Combat Glove L"),
Data("Combat Footwear"),
Data("Vivid Goggles"),
Data("Vivid Bodywear"),
Data("Vivid Glove R"),
Data("Vivid Glove L"),
Data("Vivid Footwear"),
Data("Vivid Goggles"),
Data("Vivid Bodywear"),
Data("Vivid Glove R"),
Data("Vivid Glove L"),
Data("Vivid Footwear"),
Data("Vivid Goggles"),
Data("Vivid Bodywear"),
Data("Vivid Glove R"),
Data("Vivid Glove L"),
Data("Vivid Footwear"),
Data("Valor Goggles"),
Data("Valor Bodywear"),
Data("Valor Glove R"),
Data("Valor Glove L"),
Data("Valor Footwear"),
Data("Valor Goggles"),
Data("Valor Bodywear"),
Data("Valor Glove R"),
Data("Valor Glove L"),
Data("Valor Footwear"),
Data("Valor Goggles"),
Data("Valor Bodywear"),
Data("Valor Glove R"),
Data("Valor Glove L"),
Data("Valor Footwear"),
Data("Forza Goggles"),
Data("Forza Bodywear"),
Data("Forza Glove R"),
Data("Forza Glove L"),
Data("Forza Footwear"),
Data("Forza Goggles"),
Data("Forza Bodywear"),
Data("Forza Glove R"),
Data("Forza Glove L"),
Data("Forza Footwear"),
Data("Forza Goggles"),
Data("Forza Bodywear"),
Data("Forza Glove R"),
Data("Forza Glove L"),
Data("Forza Footwear"),
Data("Reginal Goggles"),
Data("Reginal Bodywear"),
Data("Reginal Glove R"),
Data("Reginal Glove L"),
Data("Reginal Footwear"),
Data("Reginal Goggles"),
Data("Reginal Bodywear"),
Data("Reginal Glove R"),
Data("Reginal Glove L"),
Data("Reginal Footwear"),
Data("Reginal Goggles"),
Data("Reginal Bodywear"),
Data("Reginal Glove R"),
Data("Reginal Glove L"),
Data("Reginal Footwear"),
Data("Prototype Headwear"),
Data("Prototype Armor"),
Data("Prototype Armwear R"),
Data("Prototype Armwear L"),
Data("Prototype Legwear"),
Data("Combat Headwear"),
Data("Combat Armor"),
Data("Combat Armwear R"),
Data("Combat Armwear L"),
Data("Combat Legwear"),
Data("Combat Headwear"),
Data("Combat Armor"),
Data("Combat Armwear R"),
Data("Combat Armwear L"),
Data("Combat Legwear"),
Data("Combat Headwear"),
Data("Combat Armor"),
Data("Combat Armwear R"),
Data("Combat Armwear L"),
Data("Combat Legwear"),
Data("Vivid Headwear"),
Data("Vivid Armor"),
Data("Vivid Armwear R"),
Data("Vivid Armwear L"),
Data("Vivid Legwear"),
Data("Vivid Headwear"),
Data("Vivid Armor"),
Data("Vivid Armwear R"),
Data("Vivid Armwear L"),
Data("Vivid Legwear"),
Data("Vivid Headwear"),
Data("Vivid Armor"),
Data("Vivid Armwear R"),
Data("Vivid Armwear L"),
Data("Vivid Legwear"),
Data("Valor Headwear"),
Data("Valor Armor"),
Data("Valor Armwear R"),
Data("Valor Armwear L"),
Data("Valor Legwear"),
Data("Valor Headwear"),
Data("Valor Armor"),
Data("Valor Armwear R"),
Data("Valor Armwear L"),
Data("Valor Legwear"),
Data("Valor Headwear"),
Data("Valor Armor"),
Data("Valor Armwear R"),
Data("Valor Armwear L"),
Data("Valor Legwear"),
Data("Forza Headwear"),
Data("Forza Armor"),
Data("Forza Armwear R"),
Data("Forza Armwear L"),
Data("Forza Legwear"),
Data("Forza Headwear"),
Data("Forza Armor"),
Data("Forza Armwear R"),
Data("Forza Armwear L"),
Data("Forza Legwear"),
Data("Forza Headwear"),
Data("Forza Armor"),
Data("Forza Armwear R"),
Data("Forza Armwear L"),
Data("Forza Legwear"),
Data("Reginal Headwear"),
Data("Reginal Armor"),
Data("Reginal Armwear R"),
Data("Reginal Armwear L"),
Data("Reginal Legwear"),
Data("Reginal Headwear"),
Data("Reginal Armor"),
Data("Reginal Armwear R"),
Data("Reginal Armwear L"),
Data("Reginal Legwear"),
Data("Reginal Headwear"),
Data("Reginal Armor"),
Data("Reginal Armwear R"),
Data("Reginal Armwear L"),
Data("Reginal Legwear"),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("Combat Helmet"),
Data("Combat Suit"),
Data("Combat Mitt R"),
Data("Combat Mitt L"),
Data("Combat Leggings"),
Data("Combat Helmet"),
Data("Combat Suit"),
Data("Combat Mitt R"),
Data("Combat Mitt L"),
Data("Combat Leggings"),
Data("Combat Helmet"),
Data("Combat Suit"),
Data("Combat Mitt R"),
Data("Combat Mitt L"),
Data("Combat Leggings"),
Data("Vivid Helmet"),
Data("Vivid Suit"),
Data("Vivid Mitt R"),
Data("Vivid Mitt L"),
Data("Vivid Leggings"),
Data("Vivid Helmet"),
Data("Vivid Suit"),
Data("Vivid Mitt R"),
Data("Vivid Mitt L"),
Data("Vivid Leggings"),
Data("Vivid Helmet"),
Data("Vivid Suit"),
Data("Vivid Mitt R"),
Data("Vivid Mitt L"),
Data("Vivid Leggings"),
Data("Valor Helmet"),
Data("Valor Suit"),
Data("Valor Mitt R"),
Data("Valor Mitt L"),
Data("Valor Leggings"),
Data("Valor Helmet"),
Data("Valor Suit"),
Data("Valor Mitt R"),
Data("Valor Mitt L"),
Data("Valor Leggings"),
Data("Valor Helmet"),
Data("Valor Suit"),
Data("Valor Mitt R"),
Data("Valor Mitt L"),
Data("Valor Leggings"),
Data("Forza Helmet"),
Data("Forza Suit"),
Data("Forza Mitt R"),
Data("Forza Mitt L"),
Data("Forza Leggings"),
Data("Forza Helmet"),
Data("Forza Suit"),
Data("Forza Mitt R"),
Data("Forza Mitt L"),
Data("Forza Leggings"),
Data("Forza Helmet"),
Data("Forza Suit"),
Data("Forza Mitt R"),
Data("Forza Mitt L"),
Data("Forza Leggings"),
Data("Reginal Helmet"),
Data("Reginal Suit"),
Data("Reginal Mitt R"),
Data("Reginal Mitt L"),
Data("Reginal Leggings"),
Data("Reginal Helmet"),
Data("Reginal Suit"),
Data("Reginal Mitt R"),
Data("Reginal Mitt L"),
Data("Reginal Leggings"),
Data("Reginal Helmet"),
Data("Reginal Suit"),
Data("Reginal Mitt R"),
Data("Reginal Mitt L"),
Data("Reginal Leggings"),
Data("Survival Veyes"),
Data("Survival Norak"),
Data("Survival Tecta R"),
Data("Survival Tecta L"),
Data("Survival Brogs"),
Data("Survival Veyes"),
Data("Survival Norak"),
Data("Survival Tecta R"),
Data("Survival Tecta L"),
Data("Survival Brogs"),
Data("Survival Veyes"),
Data("Survival Norak"),
Data("Survival Tecta R"),
Data("Survival Tecta L"),
Data("Survival Brogs"),
Data("Combat Veyes"),
Data("Combat Norak"),
Data("Combat Tecta R"),
Data("Combat Tecta L"),
Data("Combat Brogs"),
Data("Combat Veyes"),
Data("Combat Norak"),
Data("Combat Tecta R"),
Data("Combat Tecta L"),
Data("Combat Brogs"),
Data("Combat Veyes"),
Data("Combat Norak"),
Data("Combat Tecta R"),
Data("Combat Tecta L"),
Data("Combat Brogs"),
Data("Vivid Veyes"),
Data("Vivid Norak"),
Data("Vivid Tecta R"),
Data("Vivid Tecta L"),
Data("Vivid Brogs"),
Data("Vivid Veyes"),
Data("Vivid Norak"),
Data("Vivid Tecta R"),
Data("Vivid Tecta L"),
Data("Vivid Brogs"),
Data("Vivid Veyes"),
Data("Vivid Norak"),
Data("Vivid Tecta R"),
Data("Vivid Tecta L"),
Data("Vivid Brogs"),
Data("Valor Veyes"),
Data("Valor Norak"),
Data("Valor Tecta R"),
Data("Valor Tecta L"),
Data("Valor Brogs"),
Data("Valor Veyes"),
Data("Valor Norak"),
Data("Valor Tecta R"),
Data("Valor Tecta L"),
Data("Valor Brogs"),
Data("Valor Veyes"),
Data("Valor Norak"),
Data("Valor Tecta R"),
Data("Valor Tecta L"),
Data("Valor Brogs"),
Data("Forza Veyes"),
Data("Forza Norak"),
Data("Forza Tecta R"),
Data("Forza Tecta L"),
Data("Forza Brogs"),
Data("Forza Veyes"),
Data("Forza Norak"),
Data("Forza Tecta R"),
Data("Forza Tecta L"),
Data("Forza Brogs"),
Data("Forza Veyes"),
Data("Forza Norak"),
Data("Forza Tecta R"),
Data("Forza Tecta L"),
Data("Forza Brogs"),
Data("Reginal Veyes"),
Data("Reginal Norak"),
Data("Reginal Tecta R"),
Data("Reginal Tecta L"),
Data("Reginal Brogs"),
Data("Reginal Veyes"),
Data("Reginal Norak"),
Data("Reginal Tecta R"),
Data("Reginal Tecta L"),
Data("Reginal Brogs"),
Data("Reginal Veyes"),
Data("Reginal Norak"),
Data("Reginal Tecta R"),
Data("Reginal Tecta L"),
Data("Reginal Brogs"),
Data("Clover Spex"),
Data("Clover Torse"),
Data("Clover Quantlet R"),
Data("Clover Quantlet L"),
Data("Clover Soales"),
Data("Clover Spex"),
Data("Clover Torse"),
Data("Clover Quantlet R"),
Data("Clover Quantlet L"),
Data("Clover Soales"),
Data("Clover Spex"),
Data("Clover Torse"),
Data("Clover Quantlet R"),
Data("Clover Quantlet L"),
Data("Clover Soales"),
Data("Survival Spex"),
Data("Survival Torse"),
Data("Survival Quantlet R"),
Data("Survival Quantlet L"),
Data("Survival Soales"),
Data("Survival Spex"),
Data("Survival Torse"),
Data("Survival Quantlet R"),
Data("Survival Quantlet L"),
Data("Survival Soales"),
Data("Survival Spex"),
Data("Survival Torse"),
Data("Survival Quantlet R"),
Data("Survival Quantlet L"),
Data("Survival Soales"),
Data("Combat Spex"),
Data("Combat Torse"),
Data("Combat Quantlet R"),
Data("Combat Quantlet L"),
Data("Combat Soales"),
Data("Combat Spex"),
Data("Combat Torse"),
Data("Combat Quantlet R"),
Data("Combat Quantlet L"),
Data("Combat Soales"),
Data("Combat Spex"),
Data("Combat Torse"),
Data("Combat Quantlet R"),
Data("Combat Quantlet L"),
Data("Combat Soales"),
Data("Vivid Spex"),
Data("Vivid Torse"),
Data("Vivid Quantlet R"),
Data("Vivid Quantlet L"),
Data("Vivid Soales"),
Data("Vivid Spex"),
Data("Vivid Torse"),
Data("Vivid Quantlet R"),
Data("Vivid Quantlet L"),
Data("Vivid Soales"),
Data("Vivid Spex"),
Data("Vivid Torse"),
Data("Vivid Quantlet R"),
Data("Vivid Quantlet L"),
Data("Vivid Soales"),
Data("Valor Spex"),
Data("Valor Torse"),
Data("Valor Quantlet R"),
Data("Valor Quantlet L"),
Data("Valor Soales"),
Data("Valor Spex"),
Data("Valor Torse"),
Data("Valor Quantlet R"),
Data("Valor Quantlet L"),
Data("Valor Soales"),
Data("Valor Spex"),
Data("Valor Torse"),
Data("Valor Quantlet R"),
Data("Valor Quantlet L"),
Data("Valor Soales"),
Data("Forza Spex"),
Data("Forza Torse"),
Data("Forza Quantlet R"),
Data("Forza Quantlet L"),
Data("Forza Soales"),
Data("Forza Spex"),
Data("Forza Torse"),
Data("Forza Quantlet R"),
Data("Forza Quantlet L"),
Data("Forza Soales"),
Data("Forza Spex"),
Data("Forza Torse"),
Data("Forza Quantlet R"),
Data("Forza Quantlet L"),
Data("Forza Soales"),
Data("Reginal Spex"),
Data("Reginal Torse"),
Data("Reginal Quantlet R"),
Data("Reginal Quantlet L"),
Data("Reginal Soales"),
Data("Reginal Spex"),
Data("Reginal Torse"),
Data("Reginal Quantlet R"),
Data("Reginal Quantlet L"),
Data("Reginal Soales"),
Data("Reginal Spex"),
Data("Reginal Torse"),
Data("Reginal Quantlet R"),
Data("Reginal Quantlet L"),
Data("Reginal Soales"),
Data("Combat Tuesta"),
Data("Combat Ryg"),
Data("Combat Brax R"),
Data("Combat Brax L"),
Data("Combat Traves"),
Data("Combat Tuesta"),
Data("Combat Ryg"),
Data("Combat Brax R"),
Data("Combat Brax L"),
Data("Combat Traves"),
Data("Combat Tuesta"),
Data("Combat Ryg"),
Data("Combat Brax R"),
Data("Combat Brax L"),
Data("Combat Traves"),
Data("Vivid Tuesta"),
Data("Vivid Ryg"),
Data("Vivid Brax R"),
Data("Vivid Brax L"),
Data("Vivid Traves"),
Data("Vivid Tuesta"),
Data("Vivid Ryg"),
Data("Vivid Brax R"),
Data("Vivid Brax L"),
Data("Vivid Traves"),
Data("Vivid Tuesta"),
Data("Vivid Ryg"),
Data("Vivid Brax R"),
Data("Vivid Brax L"),
Data("Vivid Traves"),
Data("Valor Tuesta"),
Data("Valor Ryg"),
Data("Valor Brax R"),
Data("Valor Brax L"),
Data("Valor Traves"),
Data("Valor Tuesta"),
Data("Valor Ryg"),
Data("Valor Brax R"),
Data("Valor Brax L"),
Data("Valor Traves"),
Data("Valor Tuesta"),
Data("Valor Ryg"),
Data("Valor Brax R"),
Data("Valor Brax L"),
Data("Valor Traves"),
Data("Forza Tuesta"),
Data("Forza Ryg"),
Data("Forza Brax R"),
Data("Forza Brax L"),
Data("Forza Traves"),
Data("Forza Tuesta"),
Data("Forza Ryg"),
Data("Forza Brax R"),
Data("Forza Brax L"),
Data("Forza Traves"),
Data("Forza Tuesta"),
Data("Forza Ryg"),
Data("Forza Brax R"),
Data("Forza Brax L"),
Data("Forza Traves"),
Data("Reginal Tuesta"),
Data("Reginal Ryg"),
Data("Reginal Brax R"),
Data("Reginal Brax L"),
Data("Reginal Traves"),
Data("Reginal Tuesta"),
Data("Reginal Ryg"),
Data("Reginal Brax R"),
Data("Reginal Brax L"),
Data("Reginal Traves"),
Data("Reginal Tuesta"),
Data("Reginal Ryg"),
Data("Reginal Brax R"),
Data("Reginal Brax L"),
Data("Reginal Traves"),
Data("Combat Casca"),
Data("Combat Raim"),
Data("Combat Guante R"),
Data("Combat Guante L"),
Data("Combat Tythes"),
Data("Combat Casca"),
Data("Combat Raim"),
Data("Combat Guante R"),
Data("Combat Guante L"),
Data("Combat Tythes"),
Data("Combat Casca"),
Data("Combat Raim"),
Data("Combat Guante R"),
Data("Combat Guante L"),
Data("Combat Tythes"),
Data("Vivid Casca"),
Data("Vivid Raim"),
Data("Vivid Guante R"),
Data("Vivid Guante L"),
Data("Vivid Tythes"),
Data("Vivid Casca"),
Data("Vivid Raim"),
Data("Vivid Guante R"),
Data("Vivid Guante L"),
Data("Vivid Tythes"),
Data("Vivid Casca"),
Data("Vivid Raim"),
Data("Vivid Guante R"),
Data("Vivid Guante L"),
Data("Vivid Tythes"),
Data("Valor Casca"),
Data("Valor Raim"),
Data("Valor Guante R"),
Data("Valor Guante L"),
Data("Valor Tythes"),
Data("Valor Casca"),
Data("Valor Raim"),
Data("Valor Guante R"),
Data("Valor Guante L"),
Data("Valor Tythes"),
Data("Valor Casca"),
Data("Valor Raim"),
Data("Valor Guante R"),
Data("Valor Guante L"),
Data("Valor Tythes"),
Data("Forza Casca"),
Data("Forza Raim"),
Data("Forza Guante R"),
Data("Forza Guante L"),
Data("Forza Tythes"),
Data("Forza Casca"),
Data("Forza Raim"),
Data("Forza Guante R"),
Data("Forza Guante L"),
Data("Forza Tythes"),
Data("Forza Casca"),
Data("Forza Raim"),
Data("Forza Guante R"),
Data("Forza Guante L"),
Data("Forza Tythes"),
Data("Reginal Casca"),
Data("Reginal Raim"),
Data("Reginal Guante R"),
Data("Reginal Guante L"),
Data("Reginal Tythes"),
Data("Reginal Casca"),
Data("Reginal Raim"),
Data("Reginal Guante R"),
Data("Reginal Guante L"),
Data("Reginal Tythes"),
Data("Reginal Casca"),
Data("Reginal Raim"),
Data("Reginal Guante R"),
Data("Reginal Guante L"),
Data("Reginal Tythes"),
Data("Combat Vizard"),
Data("Combat Vestis"),
Data("Combat Armilla R"),
Data("Combat Armilla L"),
Data("Combat Ocreis"),
Data("Combat Vizard"),
Data("Combat Vestis"),
Data("Combat Armilla R"),
Data("Combat Armilla L"),
Data("Combat Ocreis"),
Data("Combat Vizard"),
Data("Combat Vestis"),
Data("Combat Armilla R"),
Data("Combat Armilla L"),
Data("Combat Ocreis"),
Data("Vivid Vizard"),
Data("Vivid Vestis"),
Data("Vivid Armilla R"),
Data("Vivid Armilla L"),
Data("Vivid Ocreis"),
Data("Vivid Vizard"),
Data("Vivid Vestis"),
Data("Vivid Armilla R"),
Data("Vivid Armilla L"),
Data("Vivid Ocreis"),
Data("Vivid Vizard"),
Data("Vivid Vestis"),
Data("Vivid Armilla R"),
Data("Vivid Armilla L"),
Data("Vivid Ocreis"),
Data("Valor Vizard"),
Data("Valor Vestis"),
Data("Valor Armilla R"),
Data("Valor Armilla L"),
Data("Valor Ocreis"),
Data("Valor Vizard"),
Data("Valor Vestis"),
Data("Valor Armilla R"),
Data("Valor Armilla L"),
Data("Valor Ocreis"),
Data("Valor Vizard"),
Data("Valor Vestis"),
Data("Valor Armilla R"),
Data("Valor Armilla L"),
Data("Valor Ocreis"),
Data("Forza Vizard"),
Data("Forza Vestis"),
Data("Forza Armilla R"),
Data("Forza Armilla L"),
Data("Forza Ocreis"),
Data("Forza Vizard"),
Data("Forza Vestis"),
Data("Forza Armilla R"),
Data("Forza Armilla L"),
Data("Forza Ocreis"),
Data("Forza Vizard"),
Data("Forza Vestis"),
Data("Forza Armilla R"),
Data("Forza Armilla L"),
Data("Forza Ocreis"),
Data("Reginal Vizard"),
Data("Reginal Vestis"),
Data("Reginal Armilla R"),
Data("Reginal Armilla L"),
Data("Reginal Ocreis"),
Data("Reginal Vizard"),
Data("Reginal Vestis"),
Data("Reginal Armilla R"),
Data("Reginal Armilla L"),
Data("Reginal Ocreis"),
Data("Reginal Vizard"),
Data("Reginal Vestis"),
Data("Reginal Armilla R"),
Data("Reginal Armilla L"),
Data("Reginal Ocreis"),
Data("Combat Vitra"),
Data("Combat Corpus"),
Data("Combat Chiro R"),
Data("Combat Chiro L"),
Data("Combat Plantars"),
Data("Combat Vitra"),
Data("Combat Corpus"),
Data("Combat Chiro R"),
Data("Combat Chiro L"),
Data("Combat Plantars"),
Data("Combat Vitra"),
Data("Combat Corpus"),
Data("Combat Chiro R"),
Data("Combat Chiro L"),
Data("Combat Plantars"),
Data("Vivid Vitra"),
Data("Vivid Corpus"),
Data("Vivid Chiro R"),
Data("Vivid Chiro L"),
Data("Vivid Plantars"),
Data("Vivid Vitra"),
Data("Vivid Corpus"),
Data("Vivid Chiro R"),
Data("Vivid Chiro L"),
Data("Vivid Plantars"),
Data("Vivid Vitra"),
Data("Vivid Corpus"),
Data("Vivid Chiro R"),
Data("Vivid Chiro L"),
Data("Vivid Plantars"),
Data("Valor Vitra"),
Data("Valor Corpus"),
Data("Valor Chiro R"),
Data("Valor Chiro L"),
Data("Valor Plantars"),
Data("Valor Vitra"),
Data("Valor Corpus"),
Data("Valor Chiro R"),
Data("Valor Chiro L"),
Data("Valor Plantars"),
Data("Valor Vitra"),
Data("Valor Corpus"),
Data("Valor Chiro R"),
Data("Valor Chiro L"),
Data("Valor Plantars"),
Data("Forza Vitra"),
Data("Forza Corpus"),
Data("Forza Chiro R"),
Data("Forza Chiro L"),
Data("Forza Plantars"),
Data("Forza Vitra"),
Data("Forza Corpus"),
Data("Forza Chiro R"),
Data("Forza Chiro L"),
Data("Forza Plantars"),
Data("Forza Vitra"),
Data("Forza Corpus"),
Data("Forza Chiro R"),
Data("Forza Chiro L"),
Data("Forza Plantars"),
Data("Reginal Vitra"),
Data("Reginal Corpus"),
Data("Reginal Chiro R"),
Data("Reginal Chiro L"),
Data("Reginal Plantars"),
Data("Reginal Vitra"),
Data("Reginal Corpus"),
Data("Reginal Chiro R"),
Data("Reginal Chiro L"),
Data("Reginal Plantars"),
Data("Reginal Vitra"),
Data("Reginal Corpus"),
Data("Reginal Chiro R"),
Data("Reginal Chiro L"),
Data("Reginal Plantars"),
Data("Combat Cassida"),
Data("Combat Arma"),
Data("Combat Manus R"),
Data("Combat Manus L"),
Data("Combat Crura"),
Data("Combat Cassida"),
Data("Combat Arma"),
Data("Combat Manus R"),
Data("Combat Manus L"),
Data("Combat Crura"),
Data("Combat Cassida"),
Data("Combat Arma"),
Data("Combat Manus R"),
Data("Combat Manus L"),
Data("Combat Crura"),
Data("Vivid Cassida"),
Data("Vivid Arma"),
Data("Vivid Manus R"),
Data("Vivid Manus L"),
Data("Vivid Crura"),
Data("Vivid Cassida"),
Data("Vivid Arma"),
Data("Vivid Manus R"),
Data("Vivid Manus L"),
Data("Vivid Crura"),
Data("Vivid Cassida"),
Data("Vivid Arma"),
Data("Vivid Manus R"),
Data("Vivid Manus L"),
Data("Vivid Crura"),
Data("Valor Cassida"),
Data("Valor Arma"),
Data("Valor Manus R"),
Data("Valor Manus L"),
Data("Valor Crura"),
Data("Valor Cassida"),
Data("Valor Arma"),
Data("Valor Manus R"),
Data("Valor Manus L"),
Data("Valor Crura"),
Data("Valor Cassida"),
Data("Valor Arma"),
Data("Valor Manus R"),
Data("Valor Manus L"),
Data("Valor Crura"),
Data("Forza Cassida"),
Data("Forza Arma"),
Data("Forza Manus R"),
Data("Forza Manus L"),
Data("Forza Crura"),
Data("Forza Cassida"),
Data("Forza Arma"),
Data("Forza Manus R"),
Data("Forza Manus L"),
Data("Forza Crura"),
Data("Forza Cassida"),
Data("Forza Arma"),
Data("Forza Manus R"),
Data("Forza Manus L"),
Data("Forza Crura"),
Data("Reginal Cassida"),
Data("Reginal Arma"),
Data("Reginal Manus R"),
Data("Reginal Manus L"),
Data("Reginal Crura"),
Data("Reginal Cassida"),
Data("Reginal Arma"),
Data("Reginal Manus R"),
Data("Reginal Manus L"),
Data("Reginal Crura"),
Data("Reginal Cassida"),
Data("Reginal Arma"),
Data("Reginal Manus R"),
Data("Reginal Manus L"),
Data("Reginal Crura"),
Data("Combat Screen"),
Data("Combat Breaker"),
Data("Combat Ward R"),
Data("Combat Ward L"),
Data("Combat Trudgers"),
Data("Combat Screen"),
Data("Combat Breaker"),
Data("Combat Ward R"),
Data("Combat Ward L"),
Data("Combat Trudgers"),
Data("Combat Screen"),
Data("Combat Breaker"),
Data("Combat Ward R"),
Data("Combat Ward L"),
Data("Combat Trudgers"),
Data("Vivid Screen"),
Data("Vivid Breaker"),
Data("Vivid Ward R"),
Data("Vivid Ward L"),
Data("Vivid Trudgers"),
Data("Vivid Screen"),
Data("Vivid Breaker"),
Data("Vivid Ward R"),
Data("Vivid Ward L"),
Data("Vivid Trudgers"),
Data("Vivid Screen"),
Data("Vivid Breaker"),
Data("Vivid Ward R"),
Data("Vivid Ward L"),
Data("Vivid Trudgers"),
Data("Valor Screen"),
Data("Valor Breaker"),
Data("Valor Ward R"),
Data("Valor Ward L"),
Data("Valor Trudgers"),
Data("Valor Screen"),
Data("Valor Breaker"),
Data("Valor Ward R"),
Data("Valor Ward L"),
Data("Valor Trudgers"),
Data("Valor Screen"),
Data("Valor Breaker"),
Data("Valor Ward R"),
Data("Valor Ward L"),
Data("Valor Trudgers"),
Data("Forza Screen"),
Data("Forza Breaker"),
Data("Forza Ward R"),
Data("Forza Ward L"),
Data("Forza Trudgers"),
Data("Forza Screen"),
Data("Forza Breaker"),
Data("Forza Ward R"),
Data("Forza Ward L"),
Data("Forza Trudgers"),
Data("Forza Screen"),
Data("Forza Breaker"),
Data("Forza Ward R"),
Data("Forza Ward L"),
Data("Forza Trudgers"),
Data("Reginal Screen"),
Data("Reginal Breaker"),
Data("Reginal Ward R"),
Data("Reginal Ward L"),
Data("Reginal Trudgers"),
Data("Reginal Screen"),
Data("Reginal Breaker"),
Data("Reginal Ward R"),
Data("Reginal Ward L"),
Data("Reginal Trudgers"),
Data("Reginal Screen"),
Data("Reginal Breaker"),
Data("Reginal Ward R"),
Data("Reginal Ward L"),
Data("Reginal Trudgers"),
Data("Combat Sights"),
Data("Combat Encaser"),
Data("Combat Grip R"),
Data("Combat Grip L"),
Data("Combat Distancers"),
Data("Combat Sights"),
Data("Combat Encaser"),
Data("Combat Grip R"),
Data("Combat Grip L"),
Data("Combat Distancers"),
Data("Combat Sights"),
Data("Combat Encaser"),
Data("Combat Grip R"),
Data("Combat Grip L"),
Data("Combat Distancers"),
Data("Vivid Sights"),
Data("Vivid Encaser"),
Data("Vivid Grip R"),
Data("Vivid Grip L"),
Data("Vivid Distancers"),
Data("Vivid Sights"),
Data("Vivid Encaser"),
Data("Vivid Grip R"),
Data("Vivid Grip L"),
Data("Vivid Distancers"),
Data("Vivid Sights"),
Data("Vivid Encaser"),
Data("Vivid Grip R"),
Data("Vivid Grip L"),
Data("Vivid Distancers"),
Data("Valor Sights"),
Data("Valor Encaser"),
Data("Valor Grip R"),
Data("Valor Grip L"),
Data("Valor Distancers"),
Data("Valor Sights"),
Data("Valor Encaser"),
Data("Valor Grip R"),
Data("Valor Grip L"),
Data("Valor Distancers"),
Data("Valor Sights"),
Data("Valor Encaser"),
Data("Valor Grip R"),
Data("Valor Grip L"),
Data("Valor Distancers"),
Data("Forza Sights"),
Data("Forza Encaser"),
Data("Forza Grip R"),
Data("Forza Grip L"),
Data("Forza Distancers"),
Data("Forza Sights"),
Data("Forza Encaser"),
Data("Forza Grip R"),
Data("Forza Grip L"),
Data("Forza Distancers"),
Data("Forza Sights"),
Data("Forza Encaser"),
Data("Forza Grip R"),
Data("Forza Grip L"),
Data("Forza Distancers"),
Data("Reginal Sights"),
Data("Reginal Encaser"),
Data("Reginal Grip R"),
Data("Reginal Grip L"),
Data("Reginal Distancers"),
Data("Reginal Sights"),
Data("Reginal Encaser"),
Data("Reginal Grip R"),
Data("Reginal Grip L"),
Data("Reginal Distancers"),
Data("Reginal Sights"),
Data("Reginal Encaser"),
Data("Reginal Grip R"),
Data("Reginal Grip L"),
Data("Reginal Distancers"),
Data("Combat Armet"),
Data("Combat Bulwark"),
Data("Combat Wrest R"),
Data("Combat Wrest L"),
Data("Combat Stabilizers"),
Data("Combat Armet"),
Data("Combat Bulwark"),
Data("Combat Wrest R"),
Data("Combat Wrest L"),
Data("Combat Stabilizers"),
Data("Combat Armet"),
Data("Combat Bulwark"),
Data("Combat Wrest R"),
Data("Combat Wrest L"),
Data("Combat Stabilizers"),
Data("Vivid Armet"),
Data("Vivid Bulwark"),
Data("Vivid Wrest R"),
Data("Vivid Wrest L"),
Data("Vivid Stabilizers"),
Data("Vivid Armet"),
Data("Vivid Bulwark"),
Data("Vivid Wrest R"),
Data("Vivid Wrest L"),
Data("Vivid Stabilizers"),
Data("Vivid Armet"),
Data("Vivid Bulwark"),
Data("Vivid Wrest R"),
Data("Vivid Wrest L"),
Data("Vivid Stabilizers"),
Data("Valor Armet"),
Data("Valor Bulwark"),
Data("Valor Wrest R"),
Data("Valor Wrest L"),
Data("Valor Stabilizers"),
Data("Valor Armet"),
Data("Valor Bulwark"),
Data("Valor Wrest R"),
Data("Valor Wrest L"),
Data("Valor Stabilizers"),
Data("Valor Armet"),
Data("Valor Bulwark"),
Data("Valor Wrest R"),
Data("Valor Wrest L"),
Data("Valor Stabilizers"),
Data("Forza Armet"),
Data("Forza Bulwark"),
Data("Forza Wrest R"),
Data("Forza Wrest L"),
Data("Forza Stabilizers"),
Data("Forza Armet"),
Data("Forza Bulwark"),
Data("Forza Wrest R"),
Data("Forza Wrest L"),
Data("Forza Stabilizers"),
Data("Forza Armet"),
Data("Forza Bulwark"),
Data("Forza Wrest R"),
Data("Forza Wrest L"),
Data("Forza Stabilizers"),
Data("Reginal Armet"),
Data("Reginal Bulwark"),
Data("Reginal Wrest R"),
Data("Reginal Wrest L"),
Data("Reginal Stabilizers"),
Data("Reginal Armet"),
Data("Reginal Bulwark"),
Data("Reginal Wrest R"),
Data("Reginal Wrest L"),
Data("Reginal Stabilizers"),
Data("Reginal Armet"),
Data("Reginal Bulwark"),
Data("Reginal Wrest R"),
Data("Reginal Wrest L"),
Data("Reginal Stabilizers"),
Data("Vivid Yii"),
Data("Vivid Yimsel"),
Data("Vivid Yiys R"),
Data("Vivid Yiys L"),
Data("Vivid Yiym"),
Data("Vivid Yii"),
Data("Vivid Yimsel"),
Data("Vivid Yiys R"),
Data("Vivid Yiys L"),
Data("Vivid Yiym"),
Data("Vivid Yii"),
Data("Vivid Yimsel"),
Data("Vivid Yiys R"),
Data("Vivid Yiys L"),
Data("Vivid Yiym"),
Data("Valor Yii"),
Data("Valor Yimsel"),
Data("Valor Yiys R"),
Data("Valor Yiys L"),
Data("Valor Yiym"),
Data("Valor Yii"),
Data("Valor Yimsel"),
Data("Valor Yiys R"),
Data("Valor Yiys L"),
Data("Valor Yiym"),
Data("Valor Yii"),
Data("Valor Yimsel"),
Data("Valor Yiys R"),
Data("Valor Yiys L"),
Data("Valor Yiym"),
Data("Forza Yii"),
Data("Forza Yimsel"),
Data("Forza Yiys R"),
Data("Forza Yiys L"),
Data("Forza Yiym"),
Data("Forza Yii"),
Data("Forza Yimsel"),
Data("Forza Yiys R"),
Data("Forza Yiys L"),
Data("Forza Yiym"),
Data("Forza Yii"),
Data("Forza Yimsel"),
Data("Forza Yiys R"),
Data("Forza Yiys L"),
Data("Forza Yiym"),
Data("Reginal Yii"),
Data("Reginal Yimsel"),
Data("Reginal Yiys R"),
Data("Reginal Yiys L"),
Data("Reginal Yiym"),
Data("Reginal Yii"),
Data("Reginal Yimsel"),
Data("Reginal Yiys R"),
Data("Reginal Yiys L"),
Data("Reginal Yiym"),
Data("Reginal Yii"),
Data("Reginal Yimsel"),
Data("Reginal Yiys R"),
Data("Reginal Yiys L"),
Data("Reginal Yiym"),
Data("Vivid Ayx"),
Data("Vivid Mayx"),
Data("Vivid Mayx R"),
Data("Vivid Mayx L"),
Data("Vivid Nyx"),
Data("Vivid Ayx"),
Data("Vivid Mayx"),
Data("Vivid Mayx R"),
Data("Vivid Mayx L"),
Data("Vivid Nyx"),
Data("Vivid Ayx"),
Data("Vivid Mayx"),
Data("Vivid Mayx R"),
Data("Vivid Mayx L"),
Data("Vivid Nyx"),
Data("Valor Ayx"),
Data("Valor Mayx"),
Data("Valor Mayx R"),
Data("Valor Mayx L"),
Data("Valor Nyx"),
Data("Valor Ayx"),
Data("Valor Mayx"),
Data("Valor Mayx R"),
Data("Valor Mayx L"),
Data("Valor Nyx"),
Data("Valor Ayx"),
Data("Valor Mayx"),
Data("Valor Mayx R"),
Data("Valor Mayx L"),
Data("Valor Nyx"),
Data("Forza Ayx"),
Data("Forza Mayx"),
Data("Forza Mayx R"),
Data("Forza Mayx L"),
Data("Forza Nyx"),
Data("Forza Ayx"),
Data("Forza Mayx"),
Data("Forza Mayx R"),
Data("Forza Mayx L"),
Data("Forza Nyx"),
Data("Forza Ayx"),
Data("Forza Mayx"),
Data("Forza Mayx R"),
Data("Forza Mayx L"),
Data("Forza Nyx"),
Data("Reginal Ayx"),
Data("Reginal Mayx"),
Data("Reginal Mayx R"),
Data("Reginal Mayx L"),
Data("Reginal Nyx"),
Data("Reginal Ayx"),
Data("Reginal Mayx"),
Data("Reginal Mayx R"),
Data("Reginal Mayx L"),
Data("Reginal Nyx"),
Data("Reginal Ayx"),
Data("Reginal Mayx"),
Data("Reginal Mayx R"),
Data("Reginal Mayx L"),
Data("Reginal Nyx"),
Data("Vivid Zyi"),
Data("Vivid Zyua"),
Data("Vivid Zyua R"),
Data("Vivid Zyua L"),
Data("Vivid Zyum"),
Data("Vivid Zyi"),
Data("Vivid Zyua"),
Data("Vivid Zyua R"),
Data("Vivid Zyua L"),
Data("Vivid Zyum"),
Data("Vivid Zyi"),
Data("Vivid Zyua"),
Data("Vivid Zyua R"),
Data("Vivid Zyua L"),
Data("Vivid Zyum"),
Data("Valor Zyi"),
Data("Valor Zyua"),
Data("Valor Zyua R"),
Data("Valor Zyua L"),
Data("Valor Zyum"),
Data("Valor Zyi"),
Data("Valor Zyua"),
Data("Valor Zyua R"),
Data("Valor Zyua L"),
Data("Valor Zyum"),
Data("Valor Zyi"),
Data("Valor Zyua"),
Data("Valor Zyua R"),
Data("Valor Zyua L"),
Data("Valor Zyum"),
Data("Forza Zyi"),
Data("Forza Zyua"),
Data("Forza Zyua R"),
Data("Forza Zyua L"),
Data("Forza Zyum"),
Data("Forza Zyi"),
Data("Forza Zyua"),
Data("Forza Zyua R"),
Data("Forza Zyua L"),
Data("Forza Zyum"),
Data("Forza Zyi"),
Data("Forza Zyua"),
Data("Forza Zyua R"),
Data("Forza Zyua L"),
Data("Forza Zyum"),
Data("Reginal Zyi"),
Data("Reginal Zyua"),
Data("Reginal Zyua R"),
Data("Reginal Zyua L"),
Data("Reginal Zyum"),
Data("Reginal Zyi"),
Data("Reginal Zyua"),
Data("Reginal Zyua R"),
Data("Reginal Zyua L"),
Data("Reginal Zyum"),
Data("Reginal Zyi"),
Data("Reginal Zyua"),
Data("Reginal Zyua R"),
Data("Reginal Zyua L"),
Data("Reginal Zyum"),
Data("Warrior's Mask"),
Data("Light Warrior's Plate"),
Data("Warrior's Bracer R"),
Data("Warrior's Bracer L"),
Data("Warrior's Sabatons"),
Data("Warrior's Mask"),
Data("Light Warrior's Plate"),
Data("Warrior's Bracer R"),
Data("Warrior's Bracer L"),
Data("Warrior's Sabatons"),
Data("Warrior's Mask"),
Data("Light Warrior's Plate"),
Data("Warrior's Bracer R"),
Data("Warrior's Bracer L"),
Data("Warrior's Sabatons"),
Data("Vanquisher's Mask"),
Data("Light Vanquisher's Plate"),
Data("Vanquisher's Bracer R"),
Data("Vanquisher's Bracer L"),
Data("Vanquisher's Sabatons"),
Data("Vanquisher's Mask"),
Data("Light Vanquisher's Plate"),
Data("Vanquisher's Bracer R"),
Data("Vanquisher's Bracer L"),
Data("Vanquisher's Sabatons"),
Data("Vanquisher's Mask"),
Data("Light Vanquisher's Plate"),
Data("Vanquisher's Bracer R"),
Data("Vanquisher's Bracer L"),
Data("Vanquisher's Sabatons"),
Data("Overlord's Mask"),
Data("Light Overlord's Plate"),
Data("Overlord's Bracer R"),
Data("Overlord's Bracer L"),
Data("Overlord's Sabatons"),
Data("Overlord's Mask"),
Data("Light Overlord's Plate"),
Data("Overlord's Bracer R"),
Data("Overlord's Bracer L"),
Data("Overlord's Sabatons"),
Data("Overlord's Mask"),
Data("Light Overlord's Plate"),
Data("Overlord's Bracer R"),
Data("Overlord's Bracer L"),
Data("Overlord's Sabatons"),
Data("Mother God's Mask"),
Data("Light Mother God's Plate"),
Data("Mother God's Bracer R"),
Data("Mother God's Bracer L"),
Data("Mother God's Sabatons"),
Data("Mother God's Mask"),
Data("Light Mother God's Plate"),
Data("Mother God's Bracer R"),
Data("Mother God's Bracer L"),
Data("Mother God's Sabatons"),
Data("Mother God's Mask"),
Data("Light Mother God's Plate"),
Data("Mother God's Bracer R"),
Data("Mother God's Bracer L"),
Data("Mother God's Sabatons"),
Data("Warrior's Crest"),
Data("Warrior's Plate"),
Data("Warrior's Gauntlet R"),
Data("Warrior's Gauntlet L"),
Data("Warrior's Greaves"),
Data("Warrior's Crest"),
Data("Warrior's Plate"),
Data("Warrior's Gauntlet R"),
Data("Warrior's Gauntlet L"),
Data("Warrior's Greaves"),
Data("Warrior's Crest"),
Data("Warrior's Plate"),
Data("Warrior's Gauntlet R"),
Data("Warrior's Gauntlet L"),
Data("Warrior's Greaves"),
Data("Vanquisher's Crest"),
Data("Vanquisher's Plate"),
Data("Vanquisher's Gauntlet R"),
Data("Vanquisher's Gauntlet L"),
Data("Vanquisher's Greaves"),
Data("Vanquisher's Crest"),
Data("Vanquisher's Plate"),
Data("Vanquisher's Gauntlet R"),
Data("Vanquisher's Gauntlet L"),
Data("Vanquisher's Greaves"),
Data("Vanquisher's Crest"),
Data("Vanquisher's Plate"),
Data("Vanquisher's Gauntlet R"),
Data("Vanquisher's Gauntlet L"),
Data("Vanquisher's Greaves"),
Data("Overlord's Crest"),
Data("Overlord's Plate"),
Data("Overlord's Gauntlet R"),
Data("Overlord's Gauntlet L"),
Data("Overlord's Greaves"),
Data("Overlord's Crest"),
Data("Overlord's Plate"),
Data("Overlord's Gauntlet R"),
Data("Overlord's Gauntlet L"),
Data("Overlord's Greaves"),
Data("Overlord's Crest"),
Data("Overlord's Plate"),
Data("Overlord's Gauntlet R"),
Data("Overlord's Gauntlet L"),
Data("Overlord's Greaves"),
Data("Mother God's Crest"),
Data("Mother God's Plate"),
Data("Mother God's Gauntlet R"),
Data("Mother God's Gauntlet L"),
Data("Mother God's Greaves"),
Data("Mother God's Crest"),
Data("Mother God's Plate"),
Data("Mother God's Gauntlet R"),
Data("Mother God's Gauntlet L"),
Data("Mother God's Greaves"),
Data("Mother God's Crest"),
Data("Mother God's Plate"),
Data("Mother God's Gauntlet R"),
Data("Mother God's Gauntlet L"),
Data("Mother God's Greaves"),
Data("Warrior's Helm"),
Data("Heavy Warrior's Plate"),
Data("Warrior's Vambrace R"),
Data("Warrior's Vambrace L"),
Data("Heavy Warrior's Greaves"),
Data("Warrior's Helm"),
Data("Heavy Warrior's Plate"),
Data("Warrior's Vambrace R"),
Data("Warrior's Vambrace L"),
Data("Heavy Warrior's Greaves"),
Data("Warrior's Helm"),
Data("Heavy Warrior's Plate"),
Data("Warrior's Vambrace R"),
Data("Warrior's Vambrace L"),
Data("Heavy Warrior's Greaves"),
Data("Vanquisher's Helm"),
Data("Heavy Vanquisher's Plate"),
Data("Vanquisher's Vambrace R"),
Data("Vanquisher's Vambrace L"),
Data("Heavy Vanquisher's Greaves"),
Data("Vanquisher's Helm"),
Data("Heavy Vanquisher's Plate"),
Data("Vanquisher's Vambrace R"),
Data("Vanquisher's Vambrace L"),
Data("Heavy Vanquisher's Greaves"),
Data("Vanquisher's Helm"),
Data("Heavy Vanquisher's Plate"),
Data("Vanquisher's Vambrace R"),
Data("Vanquisher's Vambrace L"),
Data("Heavy Vanquisher's Greaves"),
Data("Overlord's Helm"),
Data("Heavy Overlord's Plate"),
Data("Overlord's Vambrace R"),
Data("Overlord's Vambrace L"),
Data("Heavy Overlord's Greaves"),
Data("Overlord's Helm"),
Data("Heavy Overlord's Plate"),
Data("Overlord's Vambrace R"),
Data("Overlord's Vambrace L"),
Data("Heavy Overlord's Greaves"),
Data("Overlord's Helm"),
Data("Heavy Overlord's Plate"),
Data("Overlord's Vambrace R"),
Data("Overlord's Vambrace L"),
Data("Heavy Overlord's Greaves"),
Data("Mother God's Helm"),
Data("Heavy Mother God's Plate"),
Data("Mother God's Vambrace R"),
Data("Mother God's Vambrace L"),
Data("Heavy Mother God's Greaves"),
Data("Mother God's Helm"),
Data("Heavy Mother God's Plate"),
Data("Mother God's Vambrace R"),
Data("Mother God's Vambrace L"),
Data("Heavy Mother God's Greaves"),
Data("Mother God's Helm"),
Data("Heavy Mother God's Plate"),
Data("Mother God's Vambrace R"),
Data("Mother God's Vambrace L"),
Data("Heavy Mother God's Greaves"),
Data("Worn Survival Headset"),
Data("Worn Survival Shirt"),
Data("Worn Survival Sleeve R"),
Data("Worn Survival Sleeve L"),
Data("Worn Survival Pants"),
Data("Advanced Survival Headset"),
Data("Advanced Survival Shirt"),
Data("Advanced Survival Sleeve R"),
Data("Advanced Survival Sleeve L"),
Data("Advanced Survival Pants"),
Data("Worn Combat Headset"),
Data("Worn Combat Shirt"),
Data("Worn Combat Sleeve R"),
Data("Worn Combat Sleeve L"),
Data("Worn Combat Pants"),
Data("Advanced Combat Headset"),
Data("Advanced Combat Shirt"),
Data("Advanced Combat Sleeve R"),
Data("Advanced Combat Sleeve L"),
Data("Advanced Combat Pants"),
Data("Worn Vivid Headset"),
Data("Worn Vivid Shirt"),
Data("Worn Vivid Sleeve R"),
Data("Worn Vivid Sleeve L"),
Data("Worn Vivid Pants"),
Data("Advanced Vivid Headset"),
Data("Advanced Vivid Shirt"),
Data("Advanced Vivid Sleeve R"),
Data("Advanced Vivid Sleeve L"),
Data("Advanced Vivid Pants"),
Data("Worn Valor Headset"),
Data("Worn Valor Shirt"),
Data("Worn Valor Sleeve R"),
Data("Worn Valor Sleeve L"),
Data("Worn Valor Pants"),
Data("Advanced Valor Headset"),
Data("Advanced Valor Shirt"),
Data("Advanced Valor Sleeve R"),
Data("Advanced Valor Sleeve L"),
Data("Advanced Valor Pants"),
Data("Worn Forza Headset"),
Data("Worn Forza Shirt"),
Data("Worn Forza Sleeve R"),
Data("Worn Forza Sleeve L"),
Data("Worn Forza Pants"),
Data("Advanced Forza Headset"),
Data("Advanced Forza Shirt"),
Data("Advanced Forza Sleeve R"),
Data("Advanced Forza Sleeve L"),
Data("Advanced Forza Pants"),
Data("Worn Reginal Headset"),
Data("Worn Reginal Shirt"),
Data("Worn Reginal Sleeve R"),
Data("Worn Reginal Sleeve L"),
Data("Worn Reginal Pants"),
Data("Advanced Reginal Headset"),
Data("Advanced Reginal Shirt"),
Data("Advanced Reginal Sleeve R"),
Data("Advanced Reginal Sleeve L"),
Data("Advanced Reginal Pants"),
Data("Advanced Survival Visor"),
Data("Advanced Survival Vest"),
Data("Advanced Survival Guard R"),
Data("Advanced Survival Guard L"),
Data("Advanced Survival Boots"),
Data("Worn Combat Visor"),
Data("Worn Combat Vest"),
Data("Worn Combat Guard R"),
Data("Worn Combat Guard L"),
Data("Worn Combat Boots"),
Data("Advanced Combat Visor"),
Data("Advanced Combat Vest"),
Data("Advanced Combat Guard R"),
Data("Advanced Combat Guard L"),
Data("Advanced Combat Boots"),
Data("Worn Vivid Visor"),
Data("Worn Vivid Vest"),
Data("Worn Vivid Guard R"),
Data("Worn Vivid Guard L"),
Data("Worn Vivid Boots"),
Data("Advanced Vivid Visor"),
Data("Advanced Vivid Vest"),
Data("Advanced Vivid Guard R"),
Data("Advanced Vivid Guard L"),
Data("Advanced Vivid Boots"),
Data("Worn Valor Visor"),
Data("Worn Valor Vest"),
Data("Worn Valor Guard R"),
Data("Worn Valor Guard L"),
Data("Worn Valor Boots"),
Data("Advanced Valor Visor"),
Data("Advanced Valor Vest"),
Data("Advanced Valor Guard R"),
Data("Advanced Valor Guard L"),
Data("Advanced Valor Boots"),
Data("Worn Forza Visor"),
Data("Worn Forza Vest"),
Data("Worn Forza Guard R"),
Data("Worn Forza Guard L"),
Data("Worn Forza Boots"),
Data("Advanced Forza Visor"),
Data("Advanced Forza Vest"),
Data("Advanced Forza Guard R"),
Data("Advanced Forza Guard L"),
Data("Advanced Forza Boots"),
Data("Worn Reginal Visor"),
Data("Worn Reginal Vest"),
Data("Worn Reginal Guard R"),
Data("Worn Reginal Guard L"),
Data("Worn Reginal Boots"),
Data("Advanced Reginal Visor"),
Data("Advanced Reginal Vest"),
Data("Advanced Reginal Guard R"),
Data("Advanced Reginal Guard L"),
Data("Advanced Reginal Boots"),
Data("Worn Survival Goggles"),
Data("Worn Survival Bodywear"),
Data("Worn Survival Glove R"),
Data("Worn Survival Glove L"),
Data("Worn Survival Footwear"),
Data("Advanced Survival Goggles"),
Data("Advanced Survival Bodywear"),
Data("Advanced Survival Glove R"),
Data("Advanced Survival Glove L"),
Data("Advanced Survival Footwear"),
Data("Worn Combat Goggles"),
Data("Worn Combat Bodywear"),
Data("Worn Combat Glove R"),
Data("Worn Combat Glove L"),
Data("Worn Combat Footwear"),
Data("Advanced Combat Goggles"),
Data("Advanced Combat Bodywear"),
Data("Advanced Combat Glove R"),
Data("Advanced Combat Glove L"),
Data("Advanced Combat Footwear"),
Data("Worn Vivid Goggles"),
Data("Worn Vivid Bodywear"),
Data("Worn Vivid Glove R"),
Data("Worn Vivid Glove L"),
Data("Worn Vivid Footwear"),
Data("Advanced Vivid Goggles"),
Data("Advanced Vivid Bodywear"),
Data("Advanced Vivid Glove R"),
Data("Advanced Vivid Glove L"),
Data("Advanced Vivid Footwear"),
Data("Worn Valor Goggles"),
Data("Worn Valor Bodywear"),
Data("Worn Valor Glove R"),
Data("Worn Valor Glove L"),
Data("Worn Valor Footwear"),
Data("Advanced Valor Goggles"),
Data("Advanced Valor Bodywear"),
Data("Advanced Valor Glove R"),
Data("Advanced Valor Glove L"),
Data("Advanced Valor Footwear"),
Data("Worn Forza Goggles"),
Data("Worn Forza Bodywear"),
Data("Worn Forza Glove R"),
Data("Worn Forza Glove L"),
Data("Worn Forza Footwear"),
Data("Advanced Forza Goggles"),
Data("Advanced Forza Bodywear"),
Data("Advanced Forza Glove R"),
Data("Advanced Forza Glove L"),
Data("Advanced Forza Footwear"),
Data("Worn Reginal Goggles"),
Data("Worn Reginal Bodywear"),
Data("Worn Reginal Glove R"),
Data("Worn Reginal Glove L"),
Data("Worn Reginal Footwear"),
Data("Advanced Reginal Goggles"),
Data("Advanced Reginal Bodywear"),
Data("Advanced Reginal Glove R"),
Data("Advanced Reginal Glove L"),
Data("Advanced Reginal Footwear"),
Data("Advanced Combat Headwear"),
Data("Advanced Combat Armor"),
Data("Advanced Combat Armwear R"),
Data("Advanced Combat Armwear L"),
Data("Advanced Combat Legwear"),
Data("Worn Vivid Headwear"),
Data("Worn Vivid Armor"),
Data("Worn Vivid Armwear R"),
Data("Worn Vivid Armwear L"),
Data("Worn Vivid Legwear"),
Data("Advanced Vivid Headwear"),
Data("Advanced Vivid Armor"),
Data("Advanced Vivid Armwear R"),
Data("Advanced Vivid Armwear L"),
Data("Advanced Vivid Legwear"),
Data("Worn Valor Headwear"),
Data("Worn Valor Armor"),
Data("Worn Valor Armwear R"),
Data("Worn Valor Armwear L"),
Data("Worn Valor Legwear"),
Data("Advanced Valor Headwear"),
Data("Advanced Valor Armor"),
Data("Advanced Valor Armwear R"),
Data("Advanced Valor Armwear L"),
Data("Advanced Valor Legwear"),
Data("Worn Forza Headwear"),
Data("Worn Forza Armor"),
Data("Worn Forza Armwear R"),
Data("Worn Forza Armwear L"),
Data("Worn Forza Legwear"),
Data("Advanced Forza Headwear"),
Data("Advanced Forza Armor"),
Data("Advanced Forza Armwear R"),
Data("Advanced Forza Armwear L"),
Data("Advanced Forza Legwear"),
Data("Worn Reginal Headwear"),
Data("Worn Reginal Armor"),
Data("Worn Reginal Armwear R"),
Data("Worn Reginal Armwear L"),
Data("Worn Reginal Legwear"),
Data("Advanced Reginal Headwear"),
Data("Advanced Reginal Armor"),
Data("Advanced Reginal Armwear R"),
Data("Advanced Reginal Armwear L"),
Data("Advanced Reginal Legwear"),
Data("Advanced Combat Helmet"),
Data("Advanced Combat Suit"),
Data("Advanced Combat Mitt R"),
Data("Advanced Combat Mitt L"),
Data("Advanced Combat Leggings"),
Data("Worn Vivid Helmet"),
Data("Worn Vivid Suit"),
Data("Worn Vivid Mitt R"),
Data("Worn Vivid Mitt L"),
Data("Worn Vivid Leggings"),
Data("Advanced Vivid Helmet"),
Data("Advanced Vivid Suit"),
Data("Advanced Vivid Mitt R"),
Data("Advanced Vivid Mitt L"),
Data("Advanced Vivid Leggings"),
Data("Worn Valor Helmet"),
Data("Worn Valor Suit"),
Data("Worn Valor Mitt R"),
Data("Worn Valor Mitt L"),
Data("Worn Valor Leggings"),
Data("Advanced Valor Helmet"),
Data("Advanced Valor Suit"),
Data("Advanced Valor Mitt R"),
Data("Advanced Valor Mitt L"),
Data("Advanced Valor Leggings"),
Data("Worn Forza Helmet"),
Data("Worn Forza Suit"),
Data("Worn Forza Mitt R"),
Data("Worn Forza Mitt L"),
Data("Worn Forza Leggings"),
Data("Advanced Forza Helmet"),
Data("Advanced Forza Suit"),
Data("Advanced Forza Mitt R"),
Data("Advanced Forza Mitt L"),
Data("Advanced Forza Leggings"),
Data("Worn Reginal Helmet"),
Data("Worn Reginal Suit"),
Data("Worn Reginal Mitt R"),
Data("Worn Reginal Mitt L"),
Data("Worn Reginal Leggings"),
Data("Advanced Reginal Helmet"),
Data("Advanced Reginal Suit"),
Data("Advanced Reginal Mitt R"),
Data("Advanced Reginal Mitt L"),
Data("Advanced Reginal Leggings"),
Data("Advanced Survival Veyes"),
Data("Advanced Survival Norak"),
Data("Advanced Survival Tecta R"),
Data("Advanced Survival Tecta L"),
Data("Advanced Survival Brogs"),
Data("Worn Combat Veyes"),
Data("Worn Combat Norak"),
Data("Worn Combat Tecta R"),
Data("Worn Combat Tecta L"),
Data("Worn Combat Brogs"),
Data("Advanced Combat Veyes"),
Data("Advanced Combat Norak"),
Data("Advanced Combat Tecta R"),
Data("Advanced Combat Tecta L"),
Data("Advanced Combat Brogs"),
Data("Worn Vivid Veyes"),
Data("Worn Vivid Norak"),
Data("Worn Vivid Tecta R"),
Data("Worn Vivid Tecta L"),
Data("Worn Vivid Brogs"),
Data("Advanced Vivid Veyes"),
Data("Advanced Vivid Norak"),
Data("Advanced Vivid Tecta R"),
Data("Advanced Vivid Tecta L"),
Data("Advanced Vivid Brogs"),
Data("Worn Valor Veyes"),
Data("Worn Valor Norak"),
Data("Worn Valor Tecta R"),
Data("Worn Valor Tecta L"),
Data("Worn Valor Brogs"),
Data("Advanced Valor Veyes"),
Data("Advanced Valor Norak"),
Data("Advanced Valor Tecta R"),
Data("Advanced Valor Tecta L"),
Data("Advanced Valor Brogs"),
Data("Worn Forza Veyes"),
Data("Worn Forza Norak"),
Data("Worn Forza Tecta R"),
Data("Worn Forza Tecta L"),
Data("Worn Forza Brogs"),
Data("Advanced Forza Veyes"),
Data("Advanced Forza Norak"),
Data("Advanced Forza Tecta R"),
Data("Advanced Forza Tecta L"),
Data("Advanced Forza Brogs"),
Data("Worn Reginal Veyes"),
Data("Worn Reginal Norak"),
Data("Worn Reginal Tecta R"),
Data("Worn Reginal Tecta L"),
Data("Worn Reginal Brogs"),
Data("Advanced Reginal Veyes"),
Data("Advanced Reginal Norak"),
Data("Advanced Reginal Tecta R"),
Data("Advanced Reginal Tecta L"),
Data("Advanced Reginal Brogs"),
Data("Worn Survival Spex"),
Data("Worn Survival Torse"),
Data("Worn Survival Quantlet R"),
Data("Worn Survival Quantlet L"),
Data("Worn Survival Soales"),
Data("Advanced Survival Spex"),
Data("Advanced Survival Torse"),
Data("Advanced Survival Quantlet R"),
Data("Advanced Survival Quantlet L"),
Data("Advanced Survival Soales"),
Data("Worn Combat Spex"),
Data("Worn Combat Torse"),
Data("Worn Combat Quantlet R"),
Data("Worn Combat Quantlet L"),
Data("Worn Combat Soales"),
Data("Advanced Combat Spex"),
Data("Advanced Combat Torse"),
Data("Advanced Combat Quantlet R"),
Data("Advanced Combat Quantlet L"),
Data("Advanced Combat Soales"),
Data("Worn Vivid Spex"),
Data("Worn Vivid Torse"),
Data("Worn Vivid Quantlet R"),
Data("Worn Vivid Quantlet L"),
Data("Worn Vivid Soales"),
Data("Advanced Vivid Spex"),
Data("Advanced Vivid Torse"),
Data("Advanced Vivid Quantlet R"),
Data("Advanced Vivid Quantlet L"),
Data("Advanced Vivid Soales"),
Data("Worn Valor Spex"),
Data("Worn Valor Torse"),
Data("Worn Valor Quantlet R"),
Data("Worn Valor Quantlet L"),
Data("Worn Valor Soales"),
Data("Advanced Valor Spex"),
Data("Advanced Valor Torse"),
Data("Advanced Valor Quantlet R"),
Data("Advanced Valor Quantlet L"),
Data("Advanced Valor Soales"),
Data("Worn Forza Spex"),
Data("Worn Forza Torse"),
Data("Worn Forza Quantlet R"),
Data("Worn Forza Quantlet L"),
Data("Worn Forza Soales"),
Data("Advanced Forza Spex"),
Data("Advanced Forza Torse"),
Data("Advanced Forza Quantlet R"),
Data("Advanced Forza Quantlet L"),
Data("Advanced Forza Soales"),
Data("Worn Reginal Spex"),
Data("Worn Reginal Torse"),
Data("Worn Reginal Quantlet R"),
Data("Worn Reginal Quantlet L"),
Data("Worn Reginal Soales"),
Data("Advanced Reginal Spex"),
Data("Advanced Reginal Torse"),
Data("Advanced Reginal Quantlet R"),
Data("Advanced Reginal Quantlet L"),
Data("Advanced Reginal Soales"),
Data("Advanced Combat Tuesta"),
Data("Advanced Combat Ryg"),
Data("Advanced Combat Brax R"),
Data("Advanced Combat Brax L"),
Data("Advanced Combat Traves"),
Data("Worn Vivid Tuesta"),
Data("Worn Vivid Ryg"),
Data("Worn Vivid Brax R"),
Data("Worn Vivid Brax L"),
Data("Worn Vivid Traves"),
Data("Advanced Vivid Tuesta"),
Data("Advanced Vivid Ryg"),
Data("Advanced Vivid Brax R"),
Data("Advanced Vivid Brax L"),
Data("Advanced Vivid Traves"),
Data("Worn Valor Tuesta"),
Data("Worn Valor Ryg"),
Data("Worn Valor Brax R"),
Data("Worn Valor Brax L"),
Data("Worn Valor Traves"),
Data("Advanced Valor Tuesta"),
Data("Advanced Valor Ryg"),
Data("Advanced Valor Brax R"),
Data("Advanced Valor Brax L"),
Data("Advanced Valor Traves"),
Data("Worn Forza Tuesta"),
Data("Worn Forza Ryg"),
Data("Worn Forza Brax R"),
Data("Worn Forza Brax L"),
Data("Worn Forza Traves"),
Data("Advanced Forza Tuesta"),
Data("Advanced Forza Ryg"),
Data("Advanced Forza Brax R"),
Data("Advanced Forza Brax L"),
Data("Advanced Forza Traves"),
Data("Worn Reginal Tuesta"),
Data("Worn Reginal Ryg"),
Data("Worn Reginal Brax R"),
Data("Worn Reginal Brax L"),
Data("Worn Reginal Traves"),
Data("Advanced Reginal Tuesta"),
Data("Advanced Reginal Ryg"),
Data("Advanced Reginal Brax R"),
Data("Advanced Reginal Brax L"),
Data("Advanced Reginal Traves"),
Data("Advanced Combat Casca"),
Data("Advanced Combat Raim"),
Data("Advanced Combat Guante R"),
Data("Advanced Combat Guante L"),
Data("Advanced Combat Tythes"),
Data("Worn Vivid Casca"),
Data("Worn Vivid Raim"),
Data("Worn Vivid Guante R"),
Data("Worn Vivid Guante L"),
Data("Worn Vivid Tythes"),
Data("Advanced Vivid Casca"),
Data("Advanced Vivid Raim"),
Data("Advanced Vivid Guante R"),
Data("Advanced Vivid Guante L"),
Data("Advanced Vivid Tythes"),
Data("Worn Valor Casca"),
Data("Worn Valor Raim"),
Data("Worn Valor Guante R"),
Data("Worn Valor Guante L"),
Data("Worn Valor Tythes"),
Data("Advanced Valor Casca"),
Data("Advanced Valor Raim"),
Data("Advanced Valor Guante R"),
Data("Advanced Valor Guante L"),
Data("Advanced Valor Tythes"),
Data("Worn Forza Casca"),
Data("Worn Forza Raim"),
Data("Worn Forza Guante R"),
Data("Worn Forza Guante L"),
Data("Worn Forza Tythes"),
Data("Advanced Forza Casca"),
Data("Advanced Forza Raim"),
Data("Advanced Forza Guante R"),
Data("Advanced Forza Guante L"),
Data("Advanced Forza Tythes"),
Data("Worn Reginal Casca"),
Data("Worn Reginal Raim"),
Data("Worn Reginal Guante R"),
Data("Worn Reginal Guante L"),
Data("Worn Reginal Tythes"),
Data("Advanced Reginal Casca"),
Data("Advanced Reginal Raim"),
Data("Advanced Reginal Guante R"),
Data("Advanced Reginal Guante L"),
Data("Advanced Reginal Tythes"),
Data("Advanced Combat Vizard"),
Data("Advanced Combat Vestis"),
Data("Advanced Combat Armilla R"),
Data("Advanced Combat Armilla L"),
Data("Advanced Combat Ocreis"),
Data("Worn Vivid Vizard"),
Data("Worn Vivid Vestis"),
Data("Worn Vivid Armilla R"),
Data("Worn Vivid Armilla L"),
Data("Worn Vivid Ocreis"),
Data("Advanced Vivid Vizard"),
Data("Advanced Vivid Vestis"),
Data("Advanced Vivid Armilla R"),
Data("Advanced Vivid Armilla L"),
Data("Advanced Vivid Ocreis"),
Data("Worn Valor Vizard"),
Data("Worn Valor Vestis"),
Data("Worn Valor Armilla R"),
Data("Worn Valor Armilla L"),
Data("Worn Valor Ocreis"),
Data("Advanced Valor Vizard"),
Data("Advanced Valor Vestis"),
Data("Advanced Valor Armilla R"),
Data("Advanced Valor Armilla L"),
Data("Advanced Valor Ocreis"),
Data("Worn Forza Vizard"),
Data("Worn Forza Vestis"),
Data("Worn Forza Armilla R"),
Data("Worn Forza Armilla L"),
Data("Worn Forza Ocreis"),
Data("Advanced Forza Vizard"),
Data("Advanced Forza Vestis"),
Data("Advanced Forza Armilla R"),
Data("Advanced Forza Armilla L"),
Data("Advanced Forza Ocreis"),
Data("Worn Reginal Vizard"),
Data("Worn Reginal Vestis"),
Data("Worn Reginal Armilla R"),
Data("Worn Reginal Armilla L"),
Data("Worn Reginal Ocreis"),
Data("Advanced Reginal Vizard"),
Data("Advanced Reginal Vestis"),
Data("Advanced Reginal Armilla R"),
Data("Advanced Reginal Armilla L"),
Data("Advanced Reginal Ocreis"),
Data("Advanced Combat Vitra"),
Data("Advanced Combat Corpus"),
Data("Advanced Combat Chiro R"),
Data("Advanced Combat Chiro L"),
Data("Advanced Combat Plantars"),
Data("Worn Vivid Vitra"),
Data("Worn Vivid Corpus"),
Data("Worn Vivid Chiro R"),
Data("Worn Vivid Chiro L"),
Data("Worn Vivid Plantars"),
Data("Advanced Vivid Vitra"),
Data("Advanced Vivid Corpus"),
Data("Advanced Vivid Chiro R"),
Data("Advanced Vivid Chiro L"),
Data("Advanced Vivid Plantars"),
Data("Worn Valor Vitra"),
Data("Worn Valor Corpus"),
Data("Worn Valor Chiro R"),
Data("Worn Valor Chiro L"),
Data("Worn Valor Plantars"),
Data("Advanced Valor Vitra"),
Data("Advanced Valor Corpus"),
Data("Advanced Valor Chiro R"),
Data("Advanced Valor Chiro L"),
Data("Advanced Valor Plantars"),
Data("Worn Forza Vitra"),
Data("Worn Forza Corpus"),
Data("Worn Forza Chiro R"),
Data("Worn Forza Chiro L"),
Data("Worn Forza Plantars"),
Data("Advanced Forza Vitra"),
Data("Advanced Forza Corpus"),
Data("Advanced Forza Chiro R"),
Data("Advanced Forza Chiro L"),
Data("Advanced Forza Plantars"),
Data("Worn Reginal Vitra"),
Data("Worn Reginal Corpus"),
Data("Worn Reginal Chiro R"),
Data("Worn Reginal Chiro L"),
Data("Worn Reginal Plantars"),
Data("Advanced Reginal Vitra"),
Data("Advanced Reginal Corpus"),
Data("Advanced Reginal Chiro R"),
Data("Advanced Reginal Chiro L"),
Data("Advanced Reginal Plantars"),
Data("Advanced Combat Cassida"),
Data("Advanced Combat Arma"),
Data("Advanced Combat Manus R"),
Data("Advanced Combat Manus L"),
Data("Advanced Combat Crura"),
Data("Worn Vivid Cassida"),
Data("Worn Vivid Arma"),
Data("Worn Vivid Manus R"),
Data("Worn Vivid Manus L"),
Data("Worn Vivid Crura"),
Data("Advanced Vivid Cassida"),
Data("Advanced Vivid Arma"),
Data("Advanced Vivid Manus R"),
Data("Advanced Vivid Manus L"),
Data("Advanced Vivid Crura"),
Data("Worn Valor Cassida"),
Data("Worn Valor Arma"),
Data("Worn Valor Manus R"),
Data("Worn Valor Manus L"),
Data("Worn Valor Crura"),
Data("Advanced Valor Cassida"),
Data("Advanced Valor Arma"),
Data("Advanced Valor Manus R"),
Data("Advanced Valor Manus L"),
Data("Advanced Valor Crura"),
Data("Worn Forza Cassida"),
Data("Worn Forza Arma"),
Data("Worn Forza Manus R"),
Data("Worn Forza Manus L"),
Data("Worn Forza Crura"),
Data("Advanced Forza Cassida"),
Data("Advanced Forza Arma"),
Data("Advanced Forza Manus R"),
Data("Advanced Forza Manus L"),
Data("Advanced Forza Crura"),
Data("Worn Reginal Cassida"),
Data("Worn Reginal Arma"),
Data("Worn Reginal Manus R"),
Data("Worn Reginal Manus L"),
Data("Worn Reginal Crura"),
Data("Advanced Reginal Cassida"),
Data("Advanced Reginal Arma"),
Data("Advanced Reginal Manus R"),
Data("Advanced Reginal Manus L"),
Data("Advanced Reginal Crura"),
Data("Advanced Combat Screen"),
Data("Advanced Combat Breaker"),
Data("Advanced Combat Ward R"),
Data("Advanced Combat Ward L"),
Data("Advanced Combat Trudgers"),
Data("Worn Vivid Screen"),
Data("Worn Vivid Breaker"),
Data("Worn Vivid Ward R"),
Data("Worn Vivid Ward L"),
Data("Worn Vivid Trudgers"),
Data("Advanced Vivid Screen"),
Data("Advanced Vivid Breaker"),
Data("Advanced Vivid Ward R"),
Data("Advanced Vivid Ward L"),
Data("Advanced Vivid Trudgers"),
Data("Worn Valor Screen"),
Data("Worn Valor Breaker"),
Data("Worn Valor Ward R"),
Data("Worn Valor Ward L"),
Data("Worn Valor Trudgers"),
Data("Advanced Valor Screen"),
Data("Advanced Valor Breaker"),
Data("Advanced Valor Ward R"),
Data("Advanced Valor Ward L"),
Data("Advanced Valor Trudgers"),
Data("Worn Forza Screen"),
Data("Worn Forza Breaker"),
Data("Worn Forza Ward R"),
Data("Worn Forza Ward L"),
Data("Worn Forza Trudgers"),
Data("Advanced Forza Screen"),
Data("Advanced Forza Breaker"),
Data("Advanced Forza Ward R"),
Data("Advanced Forza Ward L"),
Data("Advanced Forza Trudgers"),
Data("Worn Reginal Screen"),
Data("Worn Reginal Breaker"),
Data("Worn Reginal Ward R"),
Data("Worn Reginal Ward L"),
Data("Worn Reginal Trudgers"),
Data("Advanced Reginal Screen"),
Data("Advanced Reginal Breaker"),
Data("Advanced Reginal Ward R"),
Data("Advanced Reginal Ward L"),
Data("Advanced Reginal Trudgers"),
Data("Advanced Combat Sights"),
Data("Advanced Combat Encaser"),
Data("Advanced Combat Grip R"),
Data("Advanced Combat Grip L"),
Data("Advanced Combat Distancers"),
Data("Worn Vivid Sights"),
Data("Worn Vivid Encaser"),
Data("Worn Vivid Grip R"),
Data("Worn Vivid Grip L"),
Data("Worn Vivid Distancers"),
Data("Advanced Vivid Sights"),
Data("Advanced Vivid Encaser"),
Data("Advanced Vivid Grip R"),
Data("Advanced Vivid Grip L"),
Data("Advanced Vivid Distancers"),
Data("Worn Valor Sights"),
Data("Worn Valor Encaser"),
Data("Worn Valor Grip R"),
Data("Worn Valor Grip L"),
Data("Worn Valor Distancers"),
Data("Advanced Valor Sights"),
Data("Advanced Valor Encaser"),
Data("Advanced Valor Grip R"),
Data("Advanced Valor Grip L"),
Data("Advanced Valor Distancers"),
Data("Worn Forza Sights"),
Data("Worn Forza Encaser"),
Data("Worn Forza Grip R"),
Data("Worn Forza Grip L"),
Data("Worn Forza Distancers"),
Data("Advanced Forza Sights"),
Data("Advanced Forza Encaser"),
Data("Advanced Forza Grip R"),
Data("Advanced Forza Grip L"),
Data("Advanced Forza Distancers"),
Data("Worn Reginal Sights"),
Data("Worn Reginal Encaser"),
Data("Worn Reginal Grip R"),
Data("Worn Reginal Grip L"),
Data("Worn Reginal Distancers"),
Data("Advanced Reginal Sights"),
Data("Advanced Reginal Encaser"),
Data("Advanced Reginal Grip R"),
Data("Advanced Reginal Grip L"),
Data("Advanced Reginal Distancers"),
Data("Advanced Combat Armet"),
Data("Advanced Combat Bulwark"),
Data("Advanced Combat Wrest R"),
Data("Advanced Combat Wrest L"),
Data("Advanced Combat Stabilizers"),
Data("Worn Vivid Armet"),
Data("Worn Vivid Bulwark"),
Data("Worn Vivid Wrest R"),
Data("Worn Vivid Wrest L"),
Data("Worn Vivid Stabilizers"),
Data("Advanced Vivid Armet"),
Data("Advanced Vivid Bulwark"),
Data("Advanced Vivid Wrest R"),
Data("Advanced Vivid Wrest L"),
Data("Advanced Vivid Stabilizers"),
Data("Worn Valor Armet"),
Data("Worn Valor Bulwark"),
Data("Worn Valor Wrest R"),
Data("Worn Valor Wrest L"),
Data("Worn Valor Stabilizers"),
Data("Advanced Valor Armet"),
Data("Advanced Valor Bulwark"),
Data("Advanced Valor Wrest R"),
Data("Advanced Valor Wrest L"),
Data("Advanced Valor Stabilizers"),
Data("Worn Forza Armet"),
Data("Worn Forza Bulwark"),
Data("Worn Forza Wrest R"),
Data("Worn Forza Wrest L"),
Data("Worn Forza Stabilizers"),
Data("Advanced Forza Armet"),
Data("Advanced Forza Bulwark"),
Data("Advanced Forza Wrest R"),
Data("Advanced Forza Wrest L"),
Data("Advanced Forza Stabilizers"),
Data("Worn Reginal Armet"),
Data("Worn Reginal Bulwark"),
Data("Worn Reginal Wrest R"),
Data("Worn Reginal Wrest L"),
Data("Worn Reginal Stabilizers"),
Data("Advanced Reginal Armet"),
Data("Advanced Reginal Bulwark"),
Data("Advanced Reginal Wrest R"),
Data("Advanced Reginal Wrest L"),
Data("Advanced Reginal Stabilizers"),
Data("Advanced Vivid Yii"),
Data("Advanced Vivid Yimsel"),
Data("Advanced Vivid Yiys R"),
Data("Advanced Vivid Yiys L"),
Data("Advanced Vivid Yiym"),
Data("Worn Valor Yii"),
Data("Worn Valor Yimsel"),
Data("Worn Valor Yiys R"),
Data("Worn Valor Yiys L"),
Data("Worn Valor Yiym"),
Data("Advanced Valor Yii"),
Data("Advanced Valor Yimsel"),
Data("Advanced Valor Yiys R"),
Data("Advanced Valor Yiys L"),
Data("Advanced Valor Yiym"),
Data("Worn Forza Yii"),
Data("Worn Forza Yimsel"),
Data("Worn Forza Yiys R"),
Data("Worn Forza Yiys L"),
Data("Worn Forza Yiym"),
Data("Advanced Forza Yii"),
Data("Advanced Forza Yimsel"),
Data("Advanced Forza Yiys R"),
Data("Advanced Forza Yiys L"),
Data("Advanced Forza Yiym"),
Data("Worn Reginal Yii"),
Data("Worn Reginal Yimsel"),
Data("Worn Reginal Yiys R"),
Data("Worn Reginal Yiys L"),
Data("Worn Reginal Yiym"),
Data("Advanced Reginal Yii"),
Data("Advanced Reginal Yimsel"),
Data("Advanced Reginal Yiys R"),
Data("Advanced Reginal Yiys L"),
Data("Advanced Reginal Yiym"),
Data("Advanced Vivid Ayx"),
Data("Advanced Vivid Mayx"),
Data("Advanced Vivid Mayx R"),
Data("Advanced Vivid Mayx L"),
Data("Advanced Vivid Nyx"),
Data("Worn Valor Ayx"),
Data("Worn Valor Mayx"),
Data("Worn Valor Mayx R"),
Data("Worn Valor Mayx L"),
Data("Worn Valor Nyx"),
Data("Advanced Valor Ayx"),
Data("Advanced Valor Mayx"),
Data("Advanced Valor Mayx R"),
Data("Advanced Valor Mayx L"),
Data("Advanced Valor Nyx"),
Data("Worn Forza Ayx"),
Data("Worn Forza Mayx"),
Data("Worn Forza Mayx R"),
Data("Worn Forza Mayx L"),
Data("Worn Forza Nyx"),
Data("Advanced Forza Ayx"),
Data("Advanced Forza Mayx"),
Data("Advanced Forza Mayx R"),
Data("Advanced Forza Mayx L"),
Data("Advanced Forza Nyx"),
Data("Worn Reginal Ayx"),
Data("Worn Reginal Mayx"),
Data("Worn Reginal Mayx R"),
Data("Worn Reginal Mayx L"),
Data("Worn Reginal Nyx"),
Data("Advanced Reginal Ayx"),
Data("Advanced Reginal Mayx"),
Data("Advanced Reginal Mayx R"),
Data("Advanced Reginal Mayx L"),
Data("Advanced Reginal Nyx"),
Data("Advanced Vivid Zyi"),
Data("Advanced Vivid Zyua"),
Data("Advanced Vivid Zyua R"),
Data("Advanced Vivid Zyua L"),
Data("Advanced Vivid Zyum"),
Data("Worn Valor Zyi"),
Data("Worn Valor Zyua"),
Data("Worn Valor Zyua R"),
Data("Worn Valor Zyua L"),
Data("Worn Valor Zyum"),
Data("Advanced Valor Zyi"),
Data("Advanced Valor Zyua"),
Data("Advanced Valor Zyua R"),
Data("Advanced Valor Zyua L"),
Data("Advanced Valor Zyum"),
Data("Worn Forza Zyi"),
Data("Worn Forza Zyua"),
Data("Worn Forza Zyua R"),
Data("Worn Forza Zyua L"),
Data("Worn Forza Zyum"),
Data("Advanced Forza Zyi"),
Data("Advanced Forza Zyua"),
Data("Advanced Forza Zyua R"),
Data("Advanced Forza Zyua L"),
Data("Advanced Forza Zyum"),
Data("Worn Reginal Zyi"),
Data("Worn Reginal Zyua"),
Data("Worn Reginal Zyua R"),
Data("Worn Reginal Zyua L"),
Data("Worn Reginal Zyum"),
Data("Advanced Reginal Zyi"),
Data("Advanced Reginal Zyua"),
Data("Advanced Reginal Zyua R"),
Data("Advanced Reginal Zyua L"),
Data("Advanced Reginal Zyum"),
Data("Advanced Warrior's Mask"),
Data("Advanced Light Warrior's Plate"),
Data("Advanced Warrior's Bracer R"),
Data("Advanced Warrior's Bracer L"),
Data("Advanced Warrior's Sabatons"),
Data("Worn Vanquisher's Mask"),
Data("Worn Light Vanquisher's Plate"),
Data("Worn Vanquisher's Bracer R"),
Data("Worn Vanquisher's Bracer L"),
Data("Worn Vanquisher's Sabatons"),
Data("Advanced Vanquisher's Mask"),
Data("Advanced Light Vanquisher's Plate"),
Data("Advanced Vanquisher's Bracer R"),
Data("Advanced Vanquisher's Bracer L"),
Data("Advanced Vanquisher's Sabatons"),
Data("Worn Overlord's Mask"),
Data("Worn Light Overlord's Plate"),
Data("Worn Overlord's Bracer R"),
Data("Worn Overlord's Bracer L"),
Data("Worn Overlord's Sabatons"),
Data("Advanced Overlord's Mask"),
Data("Advanced Light Overlord's Plate"),
Data("Advanced Overlord's Bracer R"),
Data("Advanced Overlord's Bracer L"),
Data("Advanced Overlord's Sabatons"),
Data("Worn Mother God's Mask"),
Data("Worn Light Mother God's Plate"),
Data("Worn Mother God's Bracer R"),
Data("Worn Mother God's Bracer L"),
Data("Worn Mother God's Sabatons"),
Data("Advanced Mother God's Mask"),
Data("Advanced Light Mother God's Plate"),
Data("Advanced Mother God's Bracer R"),
Data("Advanced Mother God's Bracer L"),
Data("Advanced Mother God's Sabatons"),
Data("Advanced Warrior's Crest"),
Data("Advanced Warrior's Plate"),
Data("Advanced Warrior's Gauntlet R"),
Data("Advanced Warrior's Gauntlet L"),
Data("Advanced Warrior's Greaves"),
Data("Worn Vanquisher's Crest"),
Data("Worn Vanquisher's Plate"),
Data("Worn Vanquisher's Gauntlet R"),
Data("Worn Vanquisher's Gauntlet L"),
Data("Worn Vanquisher's Greaves"),
Data("Advanced Vanquisher's Crest"),
Data("Advanced Vanquisher's Plate"),
Data("Advanced Vanquisher's Gauntlet R"),
Data("Advanced Vanquisher's Gauntlet L"),
Data("Advanced Vanquisher's Greaves"),
Data("Worn Overlord's Crest"),
Data("Worn Overlord's Plate"),
Data("Worn Overlord's Gauntlet R"),
Data("Worn Overlord's Gauntlet L"),
Data("Worn Overlord's Greaves"),
Data("Advanced Overlord's Crest"),
Data("Advanced Overlord's Plate"),
Data("Advanced Overlord's Gauntlet R"),
Data("Advanced Overlord's Gauntlet L"),
Data("Advanced Overlord's Greaves"),
Data("Worn Mother God's Crest"),
Data("Worn Mother God's Plate"),
Data("Worn Mother God's Gauntlet R"),
Data("Worn Mother God's Gauntlet L"),
Data("Worn Mother God's Greaves"),
Data("Advanced Mother God's Crest"),
Data("Advanced Mother God's Plate"),
Data("Advanced Mother God's Gauntlet R"),
Data("Advanced Mother God's Gauntlet L"),
Data("Advanced Mother God's Greaves"),
Data("Advanced Warrior's Helm"),
Data("Advanced Heavy Warrior's Plate"),
Data("Advanced Warrior's Vambrace R"),
Data("Advanced Warrior's Vambrace L"),
Data("Advanced Heavy Warrior's Greaves"),
Data("Worn Vanquisher's Helm"),
Data("Worn Heavy Vanquisher's Plate"),
Data("Worn Vanquisher's Vambrace R"),
Data("Worn Vanquisher's Vambrace L"),
Data("Worn Heavy Vanquisher's Greaves"),
Data("Advanced Vanquisher's Helm"),
Data("Advanced Heavy Vanquisher's Plate"),
Data("Advanced Vanquisher's Vambrace R"),
Data("Advanced Vanquisher's Vambrace L"),
Data("Advanced Heavy Vanquisher's Greaves"),
Data("Worn Overlord's Helm"),
Data("Worn Heavy Overlord's Plate"),
Data("Worn Overlord's Vambrace R"),
Data("Worn Overlord's Vambrace L"),
Data("Worn Heavy Overlord's Greaves"),
Data("Advanced Overlord's Helm"),
Data("Advanced Heavy Overlord's Plate"),
Data("Advanced Overlord's Vambrace R"),
Data("Advanced Overlord's Vambrace L"),
Data("Advanced Heavy Overlord's Greaves"),
Data("Worn Mother God's Helm"),
Data("Worn Heavy Mother God's Plate"),
Data("Worn Mother God's Vambrace R"),
Data("Worn Mother God's Vambrace L"),
Data("Worn Heavy Mother God's Greaves"),
Data("Advanced Mother God's Helm"),
Data("Advanced Heavy Mother God's Plate"),
Data("Advanced Mother God's Vambrace R"),
Data("Advanced Mother God's Vambrace L"),
Data("Advanced Heavy Mother God's Greaves"),
Data("Ultra Regal Headset"),
Data("Ultra Regal Shirt"),
Data("Ultra Regal Sleeve R"),
Data("Ultra Regal Sleeve L"),
Data("Ultra Regal Pants"),
Data("Ultra Infinite Headset"),
Data("Ultra Infinite Shirt"),
Data("Ultra Infinite Sleeve R"),
Data("Ultra Infinite Sleeve L"),
Data("Ultra Infinite Pants"),
Data("Ultra Regal Visor"),
Data("Ultra Regal Vest"),
Data("Ultra Regal Guard R"),
Data("Ultra Regal Guard L"),
Data("Ultra Regal Boots"),
Data("Ultra Infinite Visor"),
Data("Ultra Infinite Vest"),
Data("Ultra Infinite Guard R"),
Data("Ultra Infinite Guard L"),
Data("Ultra Infinite Boots"),
Data("Ultra Regal Goggles"),
Data("Ultra Regal Bodywear"),
Data("Ultra Regal Glove R"),
Data("Ultra Regal Glove L"),
Data("Ultra Regal Footwear"),
Data("Ultra Infinite Goggles"),
Data("Ultra Infinite Bodywear"),
Data("Ultra Infinite Glove R"),
Data("Ultra Infinite Glove L"),
Data("Ultra Infinite Footwear"),
Data("Ultra Regal Headwear"),
Data("Ultra Regal Armor"),
Data("Ultra Regal Armwear R"),
Data("Ultra Regal Armwear L"),
Data("Ultra Regal Legwear"),
Data("Ultra Infinite Headwear"),
Data("Ultra Infinite Armor"),
Data("Ultra Infinite Armwear R"),
Data("Ultra Infinite Armwear L"),
Data("Ultra Infinite Legwear"),
Data("Ultra Regal Helmet"),
Data("Ultra Regal Suit"),
Data("Ultra Regal Mitt R"),
Data("Ultra Regal Mitt L"),
Data("Ultra Regal Leggings"),
Data("Ultra Infinite Helmet"),
Data("Ultra Infinite Suit"),
Data("Ultra Infinite Mitt R"),
Data("Ultra Infinite Mitt L"),
Data("Ultra Infinite Leggings"),
Data("Ultra Regal Veyes"),
Data("Ultra Regal Norak"),
Data("Ultra Regal Tecta R"),
Data("Ultra Regal Tecta L"),
Data("Ultra Regal Brogs"),
Data("Ultra Infinite Veyes"),
Data("Ultra Infinite Norak"),
Data("Ultra Infinite Tecta R"),
Data("Ultra Infinite Tecta L"),
Data("Ultra Infinite Brogs"),
Data("Ultra Regal Spex"),
Data("Ultra Regal Torse"),
Data("Ultra Regal Quantlet R"),
Data("Ultra Regal Quantlet L"),
Data("Ultra Regal Soales"),
Data("Ultra Infinite Spex"),
Data("Ultra Infinite Torse"),
Data("Ultra Infinite Quantlet R"),
Data("Ultra Infinite Quantlet L"),
Data("Ultra Infinite Soales"),
Data("Ultra Regal Tuesta"),
Data("Ultra Regal Ryg"),
Data("Ultra Regal Brax R"),
Data("Ultra Regal Brax L"),
Data("Ultra Regal Traves"),
Data("Ultra Infinite Tuesta"),
Data("Ultra Infinite Ryg"),
Data("Ultra Infinite Brax R"),
Data("Ultra Infinite Brax L"),
Data("Ultra Infinite Traves"),
Data("Ultra Regal Casca"),
Data("Ultra Regal Raim"),
Data("Ultra Regal Guante R"),
Data("Ultra Regal Guante L"),
Data("Ultra Regal Tythes"),
Data("Ultra Infinite Casca"),
Data("Ultra Infinite Raim"),
Data("Ultra Infinite Guante R"),
Data("Ultra Infinite Guante L"),
Data("Ultra Infinite Tythes"),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("Ultra Regal Vizard"),
Data("Ultra Regal Vestis"),
Data("Ultra Regal Armilla R"),
Data("Ultra Regal Armilla L"),
Data("Ultra Regal Ocreis"),
Data("Ultra Infinite Vizard"),
Data("Ultra Infinite Vestis"),
Data("Ultra Infinite Armilla R"),
Data("Ultra Infinite Armilla L"),
Data("Ultra Infinite Ocreis"),
Data("Ultra Regal Vitra"),
Data("Ultra Regal Corpus"),
Data("Ultra Regal Chiro R"),
Data("Ultra Regal Chiro L"),
Data("Ultra Regal Plantars"),
Data("Ultra Infinite Vitra"),
Data("Ultra Infinite Corpus"),
Data("Ultra Infinite Chiro R"),
Data("Ultra Infinite Chiro L"),
Data("Ultra Infinite Plantars"),
Data("Ultra Regal Cassida"),
Data("Ultra Regal Arma"),
Data("Ultra Regal Manus R"),
Data("Ultra Regal Manus L"),
Data("Ultra Regal Crura"),
Data("Ultra Infinite Cassida"),
Data("Ultra Infinite Arma"),
Data("Ultra Infinite Manus R"),
Data("Ultra Infinite Manus L"),
Data("Ultra Infinite Crura"),
Data("Ultra Regal Screen"),
Data("Ultra Regal Breaker"),
Data("Ultra Regal Ward R"),
Data("Ultra Regal Ward L"),
Data("Ultra Regal Trudgers"),
Data("Ultra Infinite Screen"),
Data("Ultra Infinite Breaker"),
Data("Ultra Infinite Ward R"),
Data("Ultra Infinite Ward L"),
Data("Ultra Infinite Trudgers"),
Data("Ultra Regal Sights"),
Data("Ultra Regal Encaser"),
Data("Ultra Regal Grip R"),
Data("Ultra Regal Grip L"),
Data("Ultra Regal Distancers"),
Data("Ultra Infinite Sights"),
Data("Ultra Infinite Encaser"),
Data("Ultra Infinite Grip R"),
Data("Ultra Infinite Grip L"),
Data("Ultra Infinite Distancers"),
Data("Ultra Regal Armet"),
Data("Ultra Regal Bulwark"),
Data("Ultra Regal Wrest R"),
Data("Ultra Regal Wrest L"),
Data("Ultra Regal Stabilizers"),
Data("Ultra Infinite Armet"),
Data("Ultra Infinite Bulwark"),
Data("Ultra Infinite Wrest R"),
Data("Ultra Infinite Wrest L"),
Data("Ultra Infinite Stabilizers"),
Data("Ultra Regal Yii"),
Data("Ultra Regal Yimsel"),
Data("Ultra Regal Yiys R"),
Data("Ultra Regal Yiys L"),
Data("Ultra Regal Yiym"),
Data("Ultra Infinite Yii"),
Data("Ultra Infinite Yimsel"),
Data("Ultra Infinite Yiys R"),
Data("Ultra Infinite Yiys L"),
Data("Ultra Infinite Yiym"),
Data("Ultra Regal Ayx"),
Data("Ultra Regal Mayx"),
Data("Ultra Regal Mayx R"),
Data("Ultra Regal Mayx L"),
Data("Ultra Regal Nyx"),
Data("Ultra Infinite Ayx"),
Data("Ultra Infinite Mayx"),
Data("Ultra Infinite Mayx R"),
Data("Ultra Infinite Mayx L"),
Data("Ultra Infinite Nyx"),
Data("Ultra Regal Zyi"),
Data("Ultra Regal Zyua"),
Data("Ultra Regal Zyua R"),
Data("Ultra Regal Zyua L"),
Data("Ultra Regal Zyum"),
Data("Ultra Infinite Zyi"),
Data("Ultra Infinite Zyua"),
Data("Ultra Infinite Zyua R"),
Data("Ultra Infinite Zyua L"),
Data("Ultra Infinite Zyum"),
Data("Ultra Deific Mask"),
Data("Ultra Deific Light Plate"),
Data("Ultra Deific Bracer R"),
Data("Ultra Deific Bracer L"),
Data("Ultra Deific Sabatons"),
Data("Ultra Boundless Mask"),
Data("Ultra Boundless Light Plate"),
Data("Ultra Boundless Bracer R"),
Data("Ultra Boundless Bracer L"),
Data("Ultra Boundless Sabatons"),
Data("Ultra Deific Crest"),
Data("Ultra Deific Plate"),
Data("Ultra Deific Gauntlet R"),
Data("Ultra Deific Gauntlet L"),
Data("Ultra Deific Greaves"),
Data("Ultra Boundless Crest"),
Data("Ultra Boundless Plate"),
Data("Ultra Boundless Gauntlet R"),
Data("Ultra Boundless Gauntlet L"),
Data("Ultra Boundless Greaves"),
Data("Ultra Deific Helm"),
Data("Ultra Heavy Deific Plate"),
Data("Ultra Deific Vambrace R"),
Data("Ultra Deific Vambrace L"),
Data("Ultra Deific Heavy Greaves"),
Data("Ultra Boundless Helm"),
Data("Ultra Boundless Heavy Plate"),
Data("Ultra Boundless Vambrace R"),
Data("Ultra Boundless Vambrace L"),
Data("Ultra Boundless Heavy Greaves"),
Data("Diving Mask"),
Data("Diving Bodywear"),
Data("Diving Band R"),
Data("Diving Band L"),
Data("Diving Bottoms"),
Data("Limited Diving Mask"),
Data("Limited Diving Bodywear"),
Data("Limited Diving Band R"),
Data("Limited Diving Band L"),
Data("Limited Diving Bottoms"),
Data("Upgraded Diving Mask"),
Data("Upgraded Diving Bodywear"),
Data("Upgraded Diving Band R"),
Data("Upgraded Diving Band L"),
Data("Upgraded Diving Bottoms"),
Data("Prime Diving Mask"),
Data("Prime Diving Bodywear"),
Data("Prime Diving Band R"),
Data("Prime Diving Band L"),
Data("Prime Diving Bottoms"),
Data("Upgraded Diving Mask II"),
Data("Upgraded Diving Bodywear II"),
Data("Upgraded Diving Band R II"),
Data("Upgraded Diving Band L II"),
Data("Upgraded Diving Bottoms II"),
Data("Supreme Diving Mask"),
Data("Supreme Diving Bodywear"),
Data("Supreme Diving Band R"),
Data("Supreme Diving Band L"),
Data("Supreme Diving Bottoms"),
Data("Prototype Trekware"),
Data("Prototype Trekpants"),
Data("Trekware"),
Data("Trekpants"),
Data("Limited Trekware"),
Data("Limited Trekpants"),
Data("Upgraded Trekware"),
Data("Upgraded Trekpants"),
Data("Prime Trekware"),
Data("Prime Trekpants"),
Data("Upgraded Trekware II"),
Data("Upgraded Trekpants II"),
Data("Supreme Trekware"),
Data("Supreme Trekpants"),
Data("Prototype Workwear"),
Data("Prototype Workpants"),
Data("Workwear"),
Data("Workpants"),
Data("Limited Workwear"),
Data("Limited Workpants"),
Data("Upgraded Workwear"),
Data("Upgraded Workpants"),
Data("Prime Workwear"),
Data("Prime Workpants"),
Data("Upgraded Workwear II"),
Data("Upgraded Workpants II"),
Data("Supreme Workwear"),
Data("Supreme Workpants"),
Data("Prototype BLADE Wear"),
Data("Prototype BLADE Pants"),
Data("BLADE Wear"),
Data("BLADE Pants"),
Data("Limited BLADE Wear"),
Data("Limited BLADE Pants"),
Data("Upgraded BLADE Wear"),
Data("Upgraded BLADE Pants"),
Data("Prime BLADE Wear"),
Data("Prime BLADE Pants"),
Data("Upgraded BLADE Wear II"),
Data("Upgraded BLADE Pants II"),
Data("Supreme BLADE Wear"),
Data("Supreme BLADE Pants"),
Data("Brand New Uniform"),
Data("Forerunner's Uniform"),
Data("Distinguished Uniform"),
Data("Veteran's Uniform"),
Data("Warhorse's Uniform"),
Data("Ruthless Uniform"),
Data("Supreme Uniform"),
Data("Brand New Blazer"),
Data("School Blazer"),
Data("Dark Suit"),
Data("Formal Suit"),
Data("Party Suit"),
Data("College Blazer"),
Data("Dressy Suit"),
Data("Bargain Turtleneck"),
Data("Bargain Jeans"),
Data("Turtleneck"),
Data("Jeans"),
Data("Limited Turtleneck"),
Data("Limited Jeans"),
Data("Redesigned Turtleneck"),
Data("Redesigned Jeans"),
Data("Prime Turtleneck"),
Data("Prime Jeans"),
Data("Ultra Limited Turtleneck"),
Data("Ultra Limited Jeans"),
Data("Supreme Turtleneck"),
Data("Supreme Jeans"),
Data("Bargain Jacket"),
Data("Bargain Trousers"),
Data("Jacket"),
Data("Trousers"),
Data("Limited Jacket"),
Data("Limited Trousers"),
Data("Redesigned Jacket"),
Data("Redesigned Trousers"),
Data("Prime Jacket"),
Data("Prime Trousers"),
Data("Ultra Limited Jacket"),
Data("Ultra Limited Trousers"),
Data("Supreme Jacket"),
Data("Supreme Trousers"),
Data("Bargain Hoodie"),
Data("Bargain Shorts"),
Data("Hoodie"),
Data("Shorts"),
Data("Limited Hoodie"),
Data("Limited Shorts"),
Data("Redesigned Hoodie"),
Data("Redesigned Shorts"),
Data("Prime Hoodie"),
Data("Prime Shorts"),
Data("Ultra Limited Hoodie"),
Data("Ultra Limited Shorts"),
Data("Supreme Hoodie"),
Data("Supreme Shorts"),
Data("Bargain Tank Top (White)"),
Data("Bargain Tank Top (Black)"),
Data("Bargain Tank Top (Gray)"),
Data("Bargain Tank Top (Navy)"),
Data("Bargain Tank Top (Blue)"),
Data("Bargain Tank Top (Pink)"),
Data("Bargain Tank Top (Red)"),
Data("Bargain Tank Top (Green)"),
Data("Bargain Tank Top (Yellow)"),
Data("Bargain Tank Top (Orange)"),
Data("Bargain Tank Top (Violet)"),
Data("Bargain Tank Top (Army Yellow)"),
Data("Bargain Tank Top (Army Green)"),
Data("Bargain Tank Top (Yellow Camo)"),
Data("Bargain Tank Top (Green Camo)"),
Data("Bargain Tank Top (Black Camo)"),
Data("Bargain Tank Top (Blue Camo)"),
Data("Bargain Tank Top (Pink Camo)"),
Data("Bargain Tee"),
Data("Tee"),
Data("Limited Tee"),
Data("Redesigned Tee"),
Data("Prime Tee"),
Data("Ultra Limited Tee"),
Data("Supreme Tee"),
Data("Snorkel"),
Data("Swimsuit Top"),
Data("Swimmer's Band R"),
Data("Swimmer's Band L"),
Data("Swimsuit Bottoms"),
Data("Limited Snorkel"),
Data("Limited Swimsuit Top"),
Data("Limited Swimmer's Band R"),
Data("Limited Swimmer's Band L"),
Data("Limited Swimsuit Bottoms"),
Data("Upgraded Snorkel"),
Data("Upgraded Swimsuit Top"),
Data("Upgraded Swimmer's Band R"),
Data("Upgraded Swimmer's Band L"),
Data("Upgraded Swimsuit Bottoms"),
Data("Prime Snorkel"),
Data("Prime Swimsuit Top"),
Data("Prime Swimmer's Band R"),
Data("Prime Swimmer's Band L"),
Data("Prime Swimsuit Bottoms"),
Data("Upgraded Snorkel II"),
Data("Upgraded Swimsuit Top II"),
Data("Upgraded Swimmer's Band R II"),
Data("Upgraded Swimmer's Band L II"),
Data("Upgraded Swimsuit Bottoms II"),
Data("Supreme Snorkel"),
Data("Supreme Swimsuit Top"),
Data("Supreme Swimmer's Band R"),
Data("Supreme Swimmer's Band L"),
Data("Supreme Swimsuit Bottoms"),
Data("Bargain Glasses"),
Data("Glasses"),
Data("Limited Glasses"),
Data("Redesigned Glasses"),
Data("Prime Glasses"),
Data("Ultra Limited Glasses"),
Data("Supreme Glasses"),
Data("Bargain Sunglasses"),
Data("Sunglasses"),
Data("Limited Sunglasses"),
Data("Redesigned Sunglasses"),
Data("Prime Sunglasses"),
Data("Ultra Limited Sunglasses"),
Data("Supreme Sunglasses"),
Data("Bargain Heart Glasses"),
Data("Heart Glasses"),
Data("Limited Heart Glasses"),
Data("Redesigned Heart Glasses"),
Data("Prime Heart Glasses"),
Data("Ultra Limited Heart Glasses"),
Data("Supreme Heart Glasses"),
Data("Bargain Sport Glasses"),
Data("Sport Glasses"),
Data("Limited Sport Glasses"),
Data("Redesigned Sport Glasses"),
Data("Prime Sport Glasses"),
Data("Ultra Limited Sport Glasses"),
Data("Supreme Sport Glasses"),
Data("Bargain Round Sunglasses"),
Data("Round Sunglasses"),
Data("Limited Round Sunglasses"),
Data("Redesigned Round Sunglasses"),
Data("Prime Round Sunglasses"),
Data("Ultra Limited Round Sunglasses"),
Data("Supreme Round Sunglasses"),
Data("Bargain Halfrim Glasses"),
Data("Halfrim Glasses"),
Data("Limited Halfrim Glasses"),
Data("Redesigned Halfrim Glasses"),
Data("Prime Halfrim Glasses"),
Data("Ultra Limited Halfrim Glasses"),
Data("Supreme Halfrim Glasses"),
Data("Bargain Browline Glasses"),
Data("Browline Glasses"),
Data("Limited Browline Glasses"),
Data("Redesigned Browline Glasses"),
Data("Prime Browline Glasses"),
Data("Ultra Limited Browline Glasses"),
Data("Supreme Browline Glasses"),
Data("Bargain Round Glasses"),
Data("Round Glasses"),
Data("Limited Round Glasses"),
Data("Redesigned Round Glasses"),
Data("Prime Round Glasses"),
Data("Ultra Limited Round Glasses"),
Data("Supreme Round Glasses"),
Data("Prototype NVD"),
Data("NVD"),
Data("Limited NVD"),
Data("Upgraded NVD"),
Data("High-Spec NVD"),
Data("Upgraded NVD II"),
Data("Supreme NVD"),
Data("Prototype Search Scope"),
Data("Search Scope"),
Data("Limited Search Scope"),
Data("Upgraded Search Scope"),
Data("High-Spec Search Scope"),
Data("Upgraded Search Scope II"),
Data("Supreme Search Scope"),
Data("Prototype Scouter"),
Data("Scouter"),
Data("Limited Scouter"),
Data("Upgraded Scouter"),
Data("High-Spec Scouter"),
Data("Upgraded Scouter II"),
Data("Supreme Scouter"),
Data("Fearsome Facade"),
Data("Jet Black Facade"),
Data("Chilling Facade"),
Data("Ruinous Facade"),
Data("Unfathomable Facade"),
Data("Grotesque Facade"),
Data("Abominable Facade"),
Data("Makeshift Gauze Eyepatch"),
Data("Gauze Eyepatch"),
Data("Reliable Gauze Eyepatch"),
Data("Redesigned Gauze Eyepatch"),
Data("Prime Gauze Eyepatch"),
Data("Sturdy Gauze Eyepatch"),
Data("Supreme Gauze Eyepatch"),
Data("Relaxing Angel Wings"),
Data("Supple Angel Wings"),
Data("Soft Angel Wings"),
Data("Soothing Angel Wings"),
Data("Warm Angel Wings"),
Data("Fluffy Angel Wings"),
Data("Supreme Angel Wings"),
Data("Relaxing Angel Halo"),
Data("Supple Angel Halo"),
Data("Soft Angel Halo"),
Data("Soothing Angel Halo"),
Data("Warm Angel Halo"),
Data("Fluffy Angel Halo"),
Data("Supreme Angel Halo"),
Data("Makeshift Adhesive Bandage"),
Data("Adhesive Bandage"),
Data("Reliable Adhesive Bandage"),
Data("Redesigned Adhesive Bandage"),
Data("Prime Adhesive Bandage"),
Data("Sturdy Adhesive Bandage"),
Data("Supreme Adhesive Bandage"),
Data("Fearsome Devil Wings"),
Data("Jet Black Devil Wings"),
Data("Chilling Devil Wings"),
Data("Ruinous Devil Wings"),
Data("Unfathomable Devil Wings"),
Data("Grotesque Devil Wings"),
Data("Abominable Devil Wings"),
Data("Fearsome Devil Horns"),
Data("Jet Black Devil Horns"),
Data("Chilling Devil Horns"),
Data("Ruinous Devil Horns"),
Data("Unfathomable Devil Horns"),
Data("Grotesque Devil Horns"),
Data("Abominable Devil Horns"),
Data("Relaxing Cat Ears"),
Data("Supple Cat Ears"),
Data("Soft Cat Ears"),
Data("Soothing Cat Ears"),
Data("Warm Cat Ears"),
Data("Fluffy Cat Ears"),
Data("Supreme Cat Ears"),
Data("Relaxing Bunny Ears"),
Data("Supple Bunny Ears"),
Data("Soft Bunny Ears"),
Data("Soothing Bunny Ears"),
Data("Warm Bunny Ears"),
Data("Fluffy Bunny Ears"),
Data("Supreme Bunny Ears"),
Data("Youthful Bunny Whiskers"),
Data("Wild Bunny Whiskers"),
Data("Urbane Bunny Whiskers"),
Data("Vogue Bunny Whiskers"),
Data("Lovestruck Bunny Whiskers"),
Data("Refined Bunny Whiskers"),
Data("Supreme Bunny Whiskers"),
Data("Youthful Kitty Ears"),
Data("Wild Kitty Ears"),
Data("Urbane Kitty Ears"),
Data("Vogue Kitty Ears"),
Data("Lovestruck Kitty Ears"),
Data("Refined Kitty Ears"),
Data("Supreme Kitty Ears"),
Data("Youthful Sheep Horns"),
Data("Wild Sheep Horns"),
Data("Urbane Sheep Horns"),
Data("Vogue Sheep Horns"),
Data("Lovestruck Sheep Horns"),
Data("Refined Sheep Horns"),
Data("Supreme Sheep Horns"),
Data("Foot Soldier's Eyepatch"),
Data("General's Eyepatch"),
Data("Tactician's Eyepatch"),
Data("Warrior's Eyepatch"),
Data("Vanquisher's Eyepatch"),
Data("Overlord's Eyepatch"),
Data("Supreme Eyepatch"),
Data("Diving Mask"),
Data("Diving Bodywear"),
Data("Diving Band R"),
Data("Diving Band L"),
Data("Diving Bottoms"),
Data("Prime Diving Mask"),
Data("Prime Diving Bodywear"),
Data("Prime Diving Band R"),
Data("Prime Diving Band L"),
Data("Prime Diving Bottoms"),
Data("Snorkel"),
Data("Swimsuit Top"),
Data("Swimmer's Band R"),
Data("Swimmer's Band L"),
Data("Swimsuit Bottoms"),
Data("Prime Snorkel"),
Data("Prime Swimsuit Top"),
Data("Prime Swimmer's Band R"),
Data("Prime Swimmer's Band L"),
Data("Prime Swimsuit Bottoms"),
Data("Diving Mask"),
Data("Diving Bodywear"),
Data("Diving Band R"),
Data("Diving Band L"),
Data("Diving Bottoms"),
Data("Prime Diving Mask"),
Data("Prime Diving Bodywear"),
Data("Prime Diving Band R"),
Data("Prime Diving Band L"),
Data("Prime Diving Bottoms"),
Data("Snorkel"),
Data("Swimsuit Top"),
Data("Swimmer's Band R"),
Data("Swimmer's Band L"),
Data("Swimsuit Bottoms"),
Data("Prime Snorkel"),
Data("Prime Swimsuit Top"),
Data("Prime Swimmer's Band R"),
Data("Prime Swimmer's Band L"),
Data("Prime Swimsuit Bottoms"),
Data("Busted Headwear"),
Data("Busted Bodywear"),
Data("Busted Armwear R"),
Data("Busted Armwear L"),
Data("Busted Legwear"),
Data("Nagi's Bodywear"),
Data("L's Bodywear"),
Data("Lao's Bodywear"),
Data("Lao's Armwear R"),
Data("Lao's Armwear L"),
Data("Lao's Legwear"),
Data("H.B.'s Glasses"),
Data("H.B.'s Bodywear"),
Data("H.B.'s Armwear R"),
Data("H.B.'s Armwear L"),
Data("H.B.'s Legwear"),
Data("Gwin's Bodywear"),
Data("Gwin's Armwear R"),
Data("Gwin's Armwear L"),
Data("Gwin's Legwear"),
Data("Frye's Bodywear"),
Data("Frye's Armwear R"),
Data("Frye's Armwear L"),
Data("Frye's Legwear"),
Data("Doug's Bodywear"),
Data("Doug's Armwear R"),
Data("Doug's Armwear L"),
Data("Doug's Legwear"),
Data("Yelv's Bodywear"),
Data("Yelv's Armwear R"),
Data("Yelv's Armwear L"),
Data("Yelv's Legwear"),
Data("Bozé's Bodywear"),
Data("Bozé's Armwear R"),
Data("Bozé's Armwear L"),
Data("Bozé's Legwear"),
Data("Phog's Bodywear"),
Data("Phog's Legwear"),
Data("Elma's Bodywear"),
Data("Elma's Armwear R"),
Data("Elma's Armwear L"),
Data("Elma's Legwear"),
Data("Lin's Bodywear"),
Data("Lin's Armwear R"),
Data("Lin's Armwear L"),
Data("Lin's Legwear"),
Data("Celica's Bodywear"),
Data("Irina's Bodywear"),
Data("Irina's Armwear R"),
Data("Irina's Armwear L"),
Data("Irina's Legwear"),
Data("Murderess's Bodywear"),
Data("Murderess's Legwear"),
Data("Alexa's Bodywear"),
Data("Alexa's Legwear"),
Data("Hope's Bodywear"),
Data("Hope's Legwear"),
Data("Mia's Bodywear"),
Data("Mia's Legwear"),
Data("Tank Top (White)"),
Data("Tank Top (Black)"),
Data("Tank Top (Gray)"),
Data("Tank Top (Navy)"),
Data("Tank Top (Blue)"),
Data("Tank Top (Pink)"),
Data("Tank Top (Red)"),
Data("Tank Top (Green)"),
Data("Tank Top (Yellow)"),
Data("Tank Top (Orange)"),
Data("Tank Top (Violet)"),
Data("Tank Top (Army Yellow)"),
Data("Tank Top (Army Green)"),
Data("Tank Top (Yellow Camo)"),
Data("Tank Top (Green Camo)"),
Data("Tank Top (Black Camo)"),
Data("Tank Top (Blue Camo)"),
Data("Tank Top (Pink Camo)"),
Data("Limited Tank Top (White)"),
Data("Limited Tank Top (Black)"),
Data("Limited Tank Top (Gray)"),
Data("Limited Tank Top (Navy)"),
Data("Limited Tank Top (Blue)"),
Data("Limited Tank Top (Pink)"),
Data("Limited Tank Top (Red)"),
Data("Limited Tank Top (Green)"),
Data("Limited Tank Top (Yellow)"),
Data("Limited Tank Top (Orange)"),
Data("Limited Tank Top (Violet)"),
Data("Limited Tank Top (Army Yellow)"),
Data("Limited Tank Top (Army Green)"),
Data("Limited Tank Top (Yellow Camo)"),
Data("Limited Tank Top (Green Camo)"),
Data("Limited Tank Top (Black Camo)"),
Data("Limited Tank Top (Blue Camo)"),
Data("Limited Tank Top (Pink Camo)"),
Data("Redesigned Tank Top (White)"),
Data("Redesigned Tank Top (Black)"),
Data("Redesigned Tank Top (Gray)"),
Data("Redesigned Tank Top (Navy)"),
Data("Redesigned Tank Top (Blue)"),
Data("Redesigned Tank Top (Pink)"),
Data("Redesigned Tank Top (Red)"),
Data("Redesigned Tank Top (Green)"),
Data("Redesigned Tank Top (Yellow)"),
Data("Redesigned Tank Top (Orange)"),
Data("Redesigned Tank Top (Violet)"),
Data("Redesigned Tank Top (Army Yellow)"),
Data("Redesigned Tank Top (Army Green)"),
Data("Redesigned Tank Top (Yellow Camo)"),
Data("Redesigned Tank Top (Green Camo)"),
Data("Redesigned Tank Top (Black Camo)"),
Data("Redesigned Tank Top (Blue Camo)"),
Data("Redesigned Tank Top (Pink Camo)"),
Data("Prime Tank Top (White)"),
Data("Prime Tank Top (Black)"),
Data("Prime Tank Top (Gray)"),
Data("Prime Tank Top (Navy)"),
Data("Prime Tank Top (Blue)"),
Data("Prime Tank Top (Pink)"),
Data("Prime Tank Top (Red)"),
Data("Prime Tank Top (Green)"),
Data("Prime Tank Top (Yellow)"),
Data("Prime Tank Top (Orange)"),
Data("Prime Tank Top (Violet)"),
Data("Prime Tank Top (Army Yellow)"),
Data("Prime Tank Top (Army Green)"),
Data("Prime Tank Top (Yellow Camo)"),
Data("Prime Tank Top (Green Camo)"),
Data("Prime Tank Top (Black Camo)"),
Data("Prime Tank Top (Blue Camo)"),
Data("Prime Tank Top (Pink Camo)"),
Data("Ultra Limited Tank Top (White)"),
Data("Ultra Limited Tank Top (Black)"),
Data("Ultra Limited Tank Top (Gray)"),
Data("Ultra Limited Tank Top (Navy)"),
Data("Ultra Limited Tank Top (Blue)"),
Data("Ultra Limited Tank Top (Pink)"),
Data("Ultra Limited Tank Top (Red)"),
Data("Ultra Limited Tank Top (Green)"),
Data("Ultra Limited Tank Top (Yellow)"),
Data("Ultra Limited Tank Top (Orange)"),
Data("Ultra Limited Tank Top (Violet)"),
Data("Ultra Limited Tank Top (Army Yellow)"),
Data("Ultra Limited Tank Top (Army Green)"),
Data("Ultra Limited Tank Top (Yellow Camo)"),
Data("Ultra Limited Tank Top (Green Camo)"),
Data("Ultra Limited Tank Top (Black Camo)"),
Data("Ultra Limited Tank Top (Blue Camo)"),
Data("Ultra Limited Tank Top (Pink Camo)"),
Data("Supreme Tank Top (White)"),
Data("Supreme Tank Top (Black)"),
Data("Supreme Tank Top (Gray)"),
Data("Supreme Tank Top (Navy)"),
Data("Supreme Tank Top (Blue)"),
Data("Supreme Tank Top (Pink)"),
Data("Supreme Tank Top (Red)"),
Data("Supreme Tank Top (Green)"),
Data("Supreme Tank Top (Yellow)"),
Data("Supreme Tank Top (Orange)"),
Data("Supreme Tank Top (Violet)"),
Data("Supreme Tank Top (Army Yellow)"),
Data("Supreme Tank Top (Army Green)"),
Data("Supreme Tank Top (Yellow Camo)"),
Data("Supreme Tank Top (Camo Green)"),
Data("Supreme Tank Top (Black Camo)"),
Data("Supreme Tank Top (Blue Camo)"),
Data("Supreme Tank Top (Pink Camo)"),
Data("Custom Tank Top (White)"),
Data("Custom Tank Top (Black)"),
Data("Custom Tank Top (Gray)"),
Data("Custom Tank Top (Navy)"),
Data("Custom Tank Top (Blue)"),
Data("Custom Tank Top (Pink)"),
Data("Custom Tank Top (Red)"),
Data("Custom Tank Top (Green)"),
Data("Custom Tank Top (Yellow)"),
Data("Custom Tank Top (Orange)"),
Data("Custom Tank Top (Violet)"),
Data("Custom Tank Top (Army Yellow)"),
Data("Custom Tank Top (Army Green)"),
Data("Custom Tank Top (Yellow Camo)"),
Data("Custom Tank Top (Green Camo)"),
Data("Custom Tank Top (Black Camo)"),
Data("Custom Tank Top (Blue Camo)"),
Data("Custom Tank Top (Pink Camo)"),
Data("Rare Tank Top (White)"),
Data("Rare Tank Top (Black)"),
Data("Rare Tank Top (Gray)"),
Data("Rare Tank Top (Navy)"),
Data("Rare Tank Top (Blue)"),
Data("Rare Tank Top (Pink)"),
Data("Rare Tank Top (Red)"),
Data("Rare Tank Top (Green)"),
Data("Rare Tank Top (Yellow)"),
Data("Rare Tank Top (Orange)"),
Data("Rare Tank Top (Violet)"),
Data("Rare Tank Top (Army Yellow)"),
Data("Rare Tank Top (Army Green)"),
Data("Rare Tank Top (Yellow Camo)"),
Data("Rare Tank Top (Green Camo)"),
Data("Rare Tank Top (Black Camo)"),
Data("Rare Tank Top (Blue Camo)"),
Data("Rare Tank Top (Pink Camo)"),
Data("Six Stars Ritual Bodywear"),
Data("Six Stars Ritual Band R"),
Data("Six Stars Ritual Band L"),
Data("Six Stars Ritual Legwear"),
Data("Supercivilization Attire"),
Data("Elite Supercivilization Attire"),
Data("Black Bunnyband"),
Data("Red Bunnyband"),
Data("White Bunnyband"),
Data("Bunnytop"),
Data("Bunnycuff R"),
Data("Bunnycuff L"),
Data("Bunnyhoppers"),
Data("Reginal Comm"),
Data("Reginal Plastron"),
Data("Reginal Bangle R"),
Data("Reginal Bangle L"),
Data("Reginal Cords"),
Data("Regal Comm"),
Data("Regal Plastron"),
Data("Regal Bangle R"),
Data("Regal Bangle L"),
Data("Regal Cords"),
Data("Infinite Comm"),
Data("Infinite Plastron"),
Data("Infinite Bangle R"),
Data("Infinite Bangle L"),
Data("Infinite Cords"),
Data("True Comm"),
Data("True Plastron"),
Data("True Bangle R"),
Data("True Bangle L"),
Data("True Cords"),
Data("Youthful Hibiscus"),
Data("Wild Hibiscus"),
Data("Urbane Hibiscus"),
Data("Vogue Hibiscus"),
Data("Lovestruck Hibiscus"),
Data("Refined Hibiscus"),
Data("Supreme Hibiscus"),
Data("Natural Hibiscus"),
Data("Pure Hibiscus"),
Data("Custom Diving Mask"),
Data("Custom Diving Bodywear"),
Data("Custom Diving Band R"),
Data("Custom Diving Band L"),
Data("Custom Diving Pants"),
Data("Custom Trekware"),
Data("Custom Trekpants"),
Data("Rare Trekware"),
Data("Rare Trekpants"),
Data("Custom Workwear"),
Data("Custom Workpants"),
Data("Rare Workwear"),
Data("Rare Workpants"),
Data("Custom BLADE Wear"),
Data("Custom BLADE Pants"),
Data("Rare BLADE Wear"),
Data("Rare BLADE Pants"),
Data("Philosopher's Uniform"),
Data("Transcendent Uniform"),
Data("Disguise"),
Data("Agent's Suit"),
Data("Custom Turtleneck"),
Data("Custom Jeans"),
Data("Rare Turtleneck"),
Data("Rare Jeans"),
Data("Custom Jacket"),
Data("Custom Trousers"),
Data("Rare Jacket"),
Data("Rare Trousers"),
Data("Custom Hoodie"),
Data("Custom Shorts"),
Data("Rare Hoodie"),
Data("Rare Shorts"),
Data("Custom Tee"),
Data("Rare Tee"),
Data("Custom Snorkel"),
Data("Custom Swimsuit Top"),
Data("Custom Swimmer's Band R"),
Data("Custom Swimmer's Band L"),
Data("Custom Swimsuit Bottoms"),
Data("Custom Glasses"),
Data("Rare Glasses"),
Data("Custom Sunglasses"),
Data("Rare Sunglasses"),
Data("Custom Heart Glasses"),
Data("Rare Heart Glasses"),
Data("Custom Sport Glasses"),
Data("Rare Sport Glasses"),
Data("Custom Round Sunglasses"),
Data("Rare Round Sunglasses"),
Data("Custom Halfrim Glasses"),
Data("Rare Halfrim Glasses"),
Data("Custom Browline Glasses"),
Data("Rare Browline Glasses"),
Data("Custom Round Glasses"),
Data("Rare Round Glasses"),
Data("Custom NVD"),
Data("Rare NVD"),
Data("Custom Search Scope"),
Data("Rare Search Scope"),
Data("Custom Scouter"),
Data("Rare Scouter"),
Data("Devious Facade"),
Data("Dread Facade"),
Data("Custom Gauze Eyepatch"),
Data("Rare Gauze Eyepatch"),
Data("Comforting Angel Wings"),
Data("Juvenile Angel Wings"),
Data("Comforting Angel Halo"),
Data("Juvenile Angel Halo"),
Data("Custom Adhesive Bandage"),
Data("Rare Adhesive Bandage"),
Data("Devious Devil Wings"),
Data("Dread Devil Wings"),
Data("Devious Devil Horns"),
Data("Dread Devil Horns"),
Data("Comforting Cat Ears"),
Data("Juvenile Cat Ears"),
Data("Comforting Bunny Ears"),
Data("Juvenile Bunny Ears"),
Data("Natural Bunny Whiskers"),
Data("Pure Bunny Whiskers"),
Data("Natural Kitty Ears"),
Data("Pure Kitty Ears"),
Data("Natural Sheep Horns"),
Data("Pure Sheep Horns"),
Data("Daimyo's Eyepatch"),
Data("Shogun's Eyepatch"),
Data("Mia's Adventure Bodywear"),
Data("Mia's Adventure Glove R"),
Data("Mia's Adventure Glove L"),
Data("Mia's Adventure Footwear"),
Data("Bunnybod"),
Data("Bunnylink R"),
Data("Bunnylink L"),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("UNUSED", valid=False),
Data("Advanced Combat Headwear"),
Data("Advanced Combat Armor"),
]