ground_augments_data = ["Max HP Up I", #https://xenoblade.github.io/xbx/bdat/common_local_us/BTL_ItemSkill_inner.html
"Max HP Up II",
"Max HP Up III",
"Max HP Up IV",
"Max HP Up V",
"Max HP Up VI",
"Max HP Up VII",
"Max HP Up VIII",
"Max HP Up IX",
"Max HP Up X",
"Max HP Up XI",
"Max HP Up XII",
"Max HP Up XIII",
"Max HP Up XIV",
"Max HP Up XV",
"Max HP Up XVI",
"Max HP Up XVII",
"Max HP Up XVIII",
"Max HP Up XIX",
"Max HP Up XX",
"Max TP Up I",
"Max TP Up II",
"Max TP Up III",
"Max TP Up IV",
"Max TP Up V",
"Max TP Up VI",
"Max TP Up VII",
"Max TP Up VIII",
"Max TP Up IX",
"Max TP Up X",
"Max TP Up XI",
"Max TP Up XII",
"Max TP Up XIII",
"Max TP Up XIV",
"Max TP Up XV",
"Max TP Up XVI",
"Max TP Up XVII",
"Max TP Up XVIII",
"Max TP Up XIX",
"Max TP Up XX",
"Melee Accuracy Up I",
"Melee Accuracy Up II",
"Melee Accuracy Up III",
"Melee Accuracy Up IV",
"Melee Accuracy Up V",
"Melee Accuracy Up VI",
"Melee Accuracy Up VII",
"Melee Accuracy Up VIII",
"Melee Accuracy Up IX",
"Melee Accuracy Up X",
"Melee Accuracy Up XI",
"Melee Accuracy Up XII",
"Melee Accuracy Up XIII",
"Melee Accuracy Up XIV",
"Melee Accuracy Up XV",
"Melee Accuracy Up XVI",
"Melee Accuracy Up XVII",
"Melee Accuracy Up XVIII",
"Melee Accuracy Up XIX",
"Melee Accuracy Up XX",
"Ranged Accuracy Up I",
"Ranged Accuracy Up II",
"Ranged Accuracy Up III",
"Ranged Accuracy Up IV",
"Ranged Accuracy Up V",
"Ranged Accuracy Up VI",
"Ranged Accuracy Up VII",
"Ranged Accuracy Up VIII",
"Ranged Accuracy Up IX",
"Ranged Accuracy Up X",
"Ranged Accuracy Up XI",
"Ranged Accuracy Up XII",
"Ranged Accuracy Up XIII",
"Ranged Accuracy Up XIV",
"Ranged Accuracy Up XV",
"Ranged Accuracy Up XVI",
"Ranged Accuracy Up XVII",
"Ranged Accuracy Up XVIII",
"Ranged Accuracy Up XIX",
"Ranged Accuracy Up XX",
"Evasion Up I",
"Evasion Up II",
"Evasion Up III",
"Evasion Up IV",
"Evasion Up V",
"Evasion Up VI",
"Evasion Up VII",
"Evasion Up VIII",
"Evasion Up IX",
"Evasion Up X",
"Evasion Up XI",
"Evasion Up XII",
"Evasion Up XIII",
"Evasion Up XIV",
"Evasion Up XV",
"Evasion Up XVI",
"Evasion Up XVII",
"Evasion Up XVIII",
"Evasion Up XIX",
"Evasion Up XX",
"Melee Attack Up I",
"Melee Attack Up II",
"Melee Attack Up III",
"Melee Attack Up IV",
"Melee Attack Up V",
"Melee Attack Up VI",
"Melee Attack Up VII",
"Melee Attack Up VIII",
"Melee Attack Up IX",
"Melee Attack Up X",
"Melee Attack Up XI",
"Melee Attack Up XII",
"Melee Attack Up XIII",
"Melee Attack Up XIV",
"Melee Attack Up XV",
"Melee Attack Up XVI",
"Melee Attack Up XVII",
"Melee Attack Up XVIII",
"Melee Attack Up XIX",
"Melee Attack Up XX",
"Ranged Attack Up I",
"Ranged Attack Up II",
"Ranged Attack Up III",
"Ranged Attack Up IV",
"Ranged Attack Up V",
"Ranged Attack Up VI",
"Ranged Attack Up VII",
"Ranged Attack Up VIII",
"Ranged Attack Up IX",
"Ranged Attack Up X",
"Ranged Attack Up XI",
"Ranged Attack Up XII",
"Ranged Attack Up XIII",
"Ranged Attack Up XIV",
"Ranged Attack Up XV",
"Ranged Attack Up XVI",
"Ranged Attack Up XVII",
"Ranged Attack Up XVIII",
"Ranged Attack Up XIX",
"Ranged Attack Up XX",
"Potential Up I",
"Potential Up II",
"Potential Up III",
"Potential Up IV",
"Potential Up V",
"Potential Up VI",
"Potential Up VII",
"Potential Up VIII",
"Potential Up IX",
"Potential Up X",
"Potential Up XI",
"Potential Up XII",
"Potential Up XIII",
"Potential Up XIV",
"Potential Up XV",
"Potential Up XVI",
"Potential Up XVII",
"Potential Up XVIII",
"Potential Up XIX",
"Potential Up XX",
"Max HP Boost I",
"Max HP Boost II",
"Max HP Boost III",
"Max HP Boost IV",
"Max HP Boost V",
"Max HP Boost VI",
"Max HP Boost VII",
"Max HP Boost VIII",
"Max HP Boost IX",
"Max HP Boost X",
"Max HP Boost XI",
"Max HP Boost XII",
"Max HP Boost XIII",
"Max HP Boost XIV",
"Max HP Boost XV",
"Max HP Boost XVI",
"Max HP Boost XVII",
"Max HP Boost XVIII",
"Max HP Boost XIX",
"Max HP Boost XX",
"Max TP Boost I",
"Max TP Boost II",
"Max TP Boost III",
"Max TP Boost IV",
"Max TP Boost V",
"Max TP Boost VI",
"Max TP Boost VII",
"Max TP Boost VIII",
"Max TP Boost IX",
"Max TP Boost X",
"Max TP Boost XI",
"Max TP Boost XII",
"Max TP Boost XIII",
"Max TP Boost XIV",
"Max TP Boost XV",
"Max TP Boost XVI",
"Max TP Boost XVII",
"Max TP Boost XVIII",
"Max TP Boost XIX",
"Max TP Boost XX",
"Melee Accuracy Boost I",
"Melee Accuracy Boost II",
"Melee Accuracy Boost III",
"Melee Accuracy Boost IV",
"Melee Accuracy Boost V",
"Melee Accuracy Boost VI",
"Melee Accuracy Boost VII",
"Melee Accuracy Boost VIII",
"Melee Accuracy Boost IX",
"Melee Accuracy Boost X",
"Melee Accuracy Boost XI",
"Melee Accuracy Boost XII",
"Melee Accuracy Boost XIII",
"Melee Accuracy Boost XIV",
"Melee Accuracy Boost XV",
"Melee Accuracy Boost XVI",
"Melee Accuracy Boost XVII",
"Melee Accuracy Boost XVIII",
"Melee Accuracy Boost XIX",
"Melee Accuracy Boost XX",
"Ranged Accuracy Boost I",
"Ranged Accuracy Boost II",
"Ranged Accuracy Boost III",
"Ranged Accuracy Boost IV",
"Ranged Accuracy Boost V",
"Ranged Accuracy Boost VI",
"Ranged Accuracy Boost VII",
"Ranged Accuracy Boost VIII",
"Ranged Accuracy Boost IX",
"Ranged Accuracy Boost X",
"Ranged Accuracy Boost XI",
"Ranged Accuracy Boost XII",
"Ranged Accuracy Boost XIII",
"Ranged Accuracy Boost XIV",
"Ranged Accuracy Boost XV",
"Ranged Accuracy Boost XVI",
"Ranged Accuracy Boost XVII",
"Ranged Accuracy Boost XVIII",
"Ranged Accuracy Boost XIX",
"Ranged Accuracy Boost XX",
"Evasion Boost I",
"Evasion Boost II",
"Evasion Boost III",
"Evasion Boost IV",
"Evasion Boost V",
"Evasion Boost VI",
"Evasion Boost VII",
"Evasion Boost VIII",
"Evasion Boost IX",
"Evasion Boost X",
"Evasion Boost XI",
"Evasion Boost XII",
"Evasion Boost XIII",
"Evasion Boost XIV",
"Evasion Boost XV",
"Evasion Boost XVI",
"Evasion Boost XVII",
"Evasion Boost XVIII",
"Evasion Boost XIX",
"Evasion Boost XX",
"Melee Attack Boost I",
"Melee Attack Boost II",
"Melee Attack Boost III",
"Melee Attack Boost IV",
"Melee Attack Boost V",
"Melee Attack Boost VI",
"Melee Attack Boost VII",
"Melee Attack Boost VIII",
"Melee Attack Boost IX",
"Melee Attack Boost X",
"Melee Attack Boost XI",
"Melee Attack Boost XII",
"Melee Attack Boost XIII",
"Melee Attack Boost XIV",
"Melee Attack Boost XV",
"Melee Attack Boost XVI",
"Melee Attack Boost XVII",
"Melee Attack Boost XVIII",
"Melee Attack Boost XIX",
"Melee Attack Boost XX",
"Ranged Attack Boost I",
"Ranged Attack Boost II",
"Ranged Attack Boost III",
"Ranged Attack Boost IV",
"Ranged Attack Boost V",
"Ranged Attack Boost VI",
"Ranged Attack Boost VII",
"Ranged Attack Boost VIII",
"Ranged Attack Boost IX",
"Ranged Attack Boost X",
"Ranged Attack Boost XI",
"Ranged Attack Boost XII",
"Ranged Attack Boost XIII",
"Ranged Attack Boost XIV",
"Ranged Attack Boost XV",
"Ranged Attack Boost XVI",
"Ranged Attack Boost XVII",
"Ranged Attack Boost XVIII",
"Ranged Attack Boost XIX",
"Ranged Attack Boost XX",
"Potential Boost I",
"Potential Boost II",
"Potential Boost III",
"Potential Boost IV",
"Potential Boost V",
"Potential Boost VI",
"Potential Boost VII",
"Potential Boost VIII",
"Potential Boost IX",
"Potential Boost X",
"Potential Boost XI",
"Potential Boost XII",
"Potential Boost XIII",
"Potential Boost XIV",
"Potential Boost XV",
"Potential Boost XVI",
"Potential Boost XVII",
"Potential Boost XVIII",
"Potential Boost XIX",
"Potential Boost XX",
"Max HP Drive I",
"Max HP Drive II",
"Max HP Drive III",
"Max HP Drive IV",
"Max HP Drive V",
"Max HP Drive VI",
"Max HP Drive VII",
"Max HP Drive VIII",
"Max HP Drive IX",
"Max HP Drive X",
"Max HP Drive XI",
"Max HP Drive XII",
"Max HP Drive XIII",
"Max HP Drive XIV",
"Max HP Drive XV",
"Max HP Drive XVI",
"Max HP Drive XVII",
"Max HP Drive XVIII",
"Max HP Drive XIX",
"Max HP Drive XX",
"Max GP Drive I",
"Max GP Drive II",
"Max GP Drive III",
"Max GP Drive IV",
"Max GP Drive V",
"Max GP Drive VI",
"Max GP Drive VII",
"Max GP Drive VIII",
"Max GP Drive IX",
"Max GP Drive X",
"Max GP Drive XI",
"Max GP Drive XII",
"Max GP Drive XIII",
"Max GP Drive XIV",
"Max GP Drive XV",
"Max GP Drive XVI",
"Max GP Drive XVII",
"Max GP Drive XVIII",
"Max GP Drive XIX",
"Max GP Drive XX",
"Melee Accuracy Drive I",
"Melee Accuracy Drive II",
"Melee Accuracy Drive III",
"Melee Accuracy Drive IV",
"Melee Accuracy Drive V",
"Melee Accuracy Drive VI",
"Melee Accuracy Drive VII",
"Melee Accuracy Drive VIII",
"Melee Accuracy Drive IX",
"Melee Accuracy Drive X",
"Melee Accuracy Drive XI",
"Melee Accuracy Drive XII",
"Melee Accuracy Drive XIII",
"Melee Accuracy Drive XIV",
"Melee Accuracy Drive XV",
"Melee Accuracy Drive XVI",
"Melee Accuracy Drive XVII",
"Melee Accuracy Drive XVIII",
"Melee Accuracy Drive XIX",
"Melee Accuracy Drive XX",
"Ranged Accuracy Drive I",
"Ranged Accuracy Drive II",
"Ranged Accuracy Drive III",
"Ranged Accuracy Drive IV",
"Ranged Accuracy Drive V",
"Ranged Accuracy Drive VI",
"Ranged Accuracy Drive VII",
"Ranged Accuracy Drive VIII",
"Ranged Accuracy Drive IX",
"Ranged Accuracy Drive X",
"Ranged Accuracy Drive XI",
"Ranged Accuracy Drive XII",
"Ranged Accuracy Drive XIII",
"Ranged Accuracy Drive XIV",
"Ranged Accuracy Drive XV",
"Ranged Accuracy Drive XVI",
"Ranged Accuracy Drive XVII",
"Ranged Accuracy Drive XVIII",
"Ranged Accuracy Drive XIX",
"Ranged Accuracy Drive XX",
"Evasion Drive I",
"Evasion Drive II",
"Evasion Drive III",
"Evasion Drive IV",
"Evasion Drive V",
"Evasion Drive VI",
"Evasion Drive VII",
"Evasion Drive VIII",
"Evasion Drive IX",
"Evasion Drive X",
"Evasion Drive XI",
"Evasion Drive XII",
"Evasion Drive XIII",
"Evasion Drive XIV",
"Evasion Drive XV",
"Evasion Drive XVI",
"Evasion Drive XVII",
"Evasion Drive XVIII",
"Evasion Drive XIX",
"Evasion Drive XX",
"Melee Attack Drive I",
"Melee Attack Drive II",
"Melee Attack Drive III",
"Melee Attack Drive IV",
"Melee Attack Drive V",
"Melee Attack Drive VI",
"Melee Attack Drive VII",
"Melee Attack Drive VIII",
"Melee Attack Drive IX",
"Melee Attack Drive X",
"Melee Attack Drive XI",
"Melee Attack Drive XII",
"Melee Attack Drive XIII",
"Melee Attack Drive XIV",
"Melee Attack Drive XV",
"Melee Attack Drive XVI",
"Melee Attack Drive XVII",
"Melee Attack Drive XVIII",
"Melee Attack Drive XIX",
"Melee Attack Drive XX",
"Ranged Attack Drive I",
"Ranged Attack Drive II",
"Ranged Attack Drive III",
"Ranged Attack Drive IV",
"Ranged Attack Drive V",
"Ranged Attack Drive VI",
"Ranged Attack Drive VII",
"Ranged Attack Drive VIII",
"Ranged Attack Drive IX",
"Ranged Attack Drive X",
"Ranged Attack Drive XI",
"Ranged Attack Drive XII",
"Ranged Attack Drive XIII",
"Ranged Attack Drive XIV",
"Ranged Attack Drive XV",
"Ranged Attack Drive XVI",
"Ranged Attack Drive XVII",
"Ranged Attack Drive XVIII",
"Ranged Attack Drive XIX",
"Ranged Attack Drive XX",
"Potential Drive I",
"Potential Drive II",
"Potential Drive III",
"Potential Drive IV",
"Potential Drive V",
"Potential Drive VI",
"Potential Drive VII",
"Potential Drive VIII",
"Potential Drive IX",
"Potential Drive X",
"Potential Drive XI",
"Potential Drive XII",
"Potential Drive XIII",
"Potential Drive XIV",
"Potential Drive XV",
"Potential Drive XVI",
"Potential Drive XVII",
"Potential Drive XVIII",
"Potential Drive XIX",
"Potential Drive XX",
"Bind: Refuel I",
"Bind: Refuel II",
"Bind: Refuel III",
"Bind: Refuel IV",
"Bind: Refuel V",
"Bind: Refuel VI",
"Bind: Refuel VII",
"Bind: Refuel VIII",
"Bind: Refuel IX",
"Bind: Refuel X",
"Bind: Refuel XI",
"Bind: Refuel XII",
"Bind: Refuel XIII",
"Bind: Refuel XIV",
"Bind: Refuel XV",
"Bind: Refuel XVI",
"Bind: Refuel XVII",
"Bind: Refuel XVIII",
"Bind: Refuel XIX",
"Bind: Refuel XX",
"Fuel Efficiency Up I",
"Fuel Efficiency Up II",
"Fuel Efficiency Up III",
"Fuel Efficiency Up IV",
"Fuel Efficiency Up V",
"Fuel Efficiency Up VI",
"Fuel Efficiency Up VII",
"Fuel Efficiency Up VIII",
"Fuel Efficiency Up IX",
"Fuel Efficiency Up X",
"Fuel Efficiency Up XI",
"Fuel Efficiency Up XII",
"Fuel Efficiency Up XIII",
"Fuel Efficiency Up XIV",
"Fuel Efficiency Up XV",
"Fuel Efficiency Up XVI",
"Fuel Efficiency Up XVII",
"Fuel Efficiency Up XVIII",
"Fuel Efficiency Up XIX",
"Fuel Efficiency Up XX",
"Physical Resistance Up I",
"Physical Resistance Up II",
"Physical Resistance Up III",
"Physical Resistance Up IV",
"Physical Resistance Up V",
"Physical Resistance Up VI",
"Physical Resistance Up VII",
"Physical Resistance Up VIII",
"Physical Resistance Up IX",
"Physical Resistance Up X",
"Physical Resistance Up XI",
"Physical Resistance Up XII",
"Physical Resistance Up XIII",
"Physical Resistance Up XIV",
"Physical Resistance Up XV",
"Physical Resistance Up XVI",
"Physical Resistance Up XVII",
"Physical Resistance Up XVIII",
"Physical Resistance Up XIX",
"Physical Resistance Up XX",
"Beam Resistance Up I",
"Beam Resistance Up II",
"Beam Resistance Up III",
"Beam Resistance Up IV",
"Beam Resistance Up V",
"Beam Resistance Up VI",
"Beam Resistance Up VII",
"Beam Resistance Up VIII",
"Beam Resistance Up IX",
"Beam Resistance Up X",
"Beam Resistance Up XI",
"Beam Resistance Up XII",
"Beam Resistance Up XIII",
"Beam Resistance Up XIV",
"Beam Resistance Up XV",
"Beam Resistance Up XVI",
"Beam Resistance Up XVII",
"Beam Resistance Up XVIII",
"Beam Resistance Up XIX",
"Beam Resistance Up XX",
"Electric Resistance Up I",
"Electric Resistance Up II",
"Electric Resistance Up III",
"Electric Resistance Up IV",
"Electric Resistance Up V",
"Electric Resistance Up VI",
"Electric Resistance Up VII",
"Electric Resistance Up VIII",
"Electric Resistance Up IX",
"Electric Resistance Up X",
"Electric Resistance Up XI",
"Electric Resistance Up XII",
"Electric Resistance Up XIII",
"Electric Resistance Up XIV",
"Electric Resistance Up XV",
"Electric Resistance Up XVI",
"Electric Resistance Up XVII",
"Electric Resistance Up XVIII",
"Electric Resistance Up XIX",
"Electric Resistance Up XX",
"Thermal Resistance Up I",
"Thermal Resistance Up II",
"Thermal Resistance Up III",
"Thermal Resistance Up IV",
"Thermal Resistance Up V",
"Thermal Resistance Up VI",
"Thermal Resistance Up VII",
"Thermal Resistance Up VIII",
"Thermal Resistance Up IX",
"Thermal Resistance Up X",
"Thermal Resistance Up XI",
"Thermal Resistance Up XII",
"Thermal Resistance Up XIII",
"Thermal Resistance Up XIV",
"Thermal Resistance Up XV",
"Thermal Resistance Up XVI",
"Thermal Resistance Up XVII",
"Thermal Resistance Up XVIII",
"Thermal Resistance Up XIX",
"Thermal Resistance Up XX",
"Ether Resistance Up I",
"Ether Resistance Up II",
"Ether Resistance Up III",
"Ether Resistance Up IV",
"Ether Resistance Up V",
"Ether Resistance Up VI",
"Ether Resistance Up VII",
"Ether Resistance Up VIII",
"Ether Resistance Up IX",
"Ether Resistance Up X",
"Ether Resistance Up XI",
"Ether Resistance Up XII",
"Ether Resistance Up XIII",
"Ether Resistance Up XIV",
"Ether Resistance Up XV",
"Ether Resistance Up XVI",
"Ether Resistance Up XVII",
"Ether Resistance Up XVIII",
"Ether Resistance Up XIX",
"Ether Resistance Up XX",
"Gravity Resistance Up I",
"Gravity Resistance Up II",
"Gravity Resistance Up III",
"Gravity Resistance Up IV",
"Gravity Resistance Up V",
"Gravity Resistance Up VI",
"Gravity Resistance Up VII",
"Gravity Resistance Up VIII",
"Gravity Resistance Up IX",
"Gravity Resistance Up X",
"Gravity Resistance Up XI",
"Gravity Resistance Up XII",
"Gravity Resistance Up XIII",
"Gravity Resistance Up XIV",
"Gravity Resistance Up XV",
"Gravity Resistance Up XVI",
"Gravity Resistance Up XVII",
"Gravity Resistance Up XVIII",
"Gravity Resistance Up XIX",
"Gravity Resistance Up XX",
"Weapon Attack Power Up I",
"Weapon Attack Power Up II",
"Weapon Attack Power Up III",
"Weapon Attack Power Up IV",
"Weapon Attack Power Up V",
"Weapon Attack Power Up VI",
"Weapon Attack Power Up VII",
"Weapon Attack Power Up VIII",
"Weapon Attack Power Up IX",
"Weapon Attack Power Up X",
"Weapon Attack Power Up XI",
"Weapon Attack Power Up XII",
"Weapon Attack Power Up XIII",
"Weapon Attack Power Up XIV",
"Weapon Attack Power Up XV",
"Weapon Attack Power Up XVI",
"Weapon Attack Power Up XVII",
"Weapon Attack Power Up XVIII",
"Weapon Attack Power Up XIX",
"Weapon Attack Power Up XX",
"Stabilizer I",
"Stabilizer II",
"Stabilizer III",
"Stabilizer IV",
"Stabilizer V",
"Stabilizer VI",
"Stabilizer VII",
"Stabilizer VIII",
"Stabilizer IX",
"Stabilizer X",
"Stabilizer XI",
"Stabilizer XII",
"Stabilizer XIII",
"Stabilizer XIV",
"Stabilizer XV",
"Stabilizer XVI",
"Stabilizer XVII",
"Stabilizer XVIII",
"Stabilizer XIX",
"Stabilizer XX",
"Destabilizer I",
"Destabilizer II",
"Destabilizer III",
"Destabilizer IV",
"Destabilizer V",
"Destabilizer VI",
"Destabilizer VII",
"Destabilizer VIII",
"Destabilizer IX",
"Destabilizer X",
"Destabilizer XI",
"Destabilizer XII",
"Destabilizer XIII",
"Destabilizer XIV",
"Destabilizer XV",
"Destabilizer XVI",
"Destabilizer XVII",
"Destabilizer XVIII",
"Destabilizer XIX",
"Destabilizer XX",
"Magazine Capacity Up I",
"Magazine Capacity Up II",
"Magazine Capacity Up III",
"Magazine Capacity Up IV",
"Magazine Capacity Up V",
"Magazine Capacity Up VI",
"Magazine Capacity Up VII",
"Magazine Capacity Up VIII",
"Magazine Capacity Up IX",
"Magazine Capacity Up X",
"Magazine Capacity Up XI",
"Magazine Capacity Up XII",
"Magazine Capacity Up XIII",
"Magazine Capacity Up XIV",
"Magazine Capacity Up XV",
"Magazine Capacity Up XVI",
"Magazine Capacity Up XVII",
"Magazine Capacity Up XVIII",
"Magazine Capacity Up XIX",
"Magazine Capacity Up XX",
"Melee: TP Gain Up",
"Ranged: TP Gain Up",
"Cooldown Reducer I",
"Cooldown Reducer II",
"Cooldown Reducer III",
"Cooldown Reducer IV",
"Cooldown Reducer V",
"Cooldown Reducer VI",
"Cooldown Reducer VII",
"Cooldown Reducer VIII",
"Cooldown Reducer IX",
"Cooldown Reducer X",
"Cooldown Reducer XI",
"Cooldown Reducer XII",
"Cooldown Reducer XIII",
"Cooldown Reducer XIV",
"Cooldown Reducer XV",
"Cooldown Reducer XVI",
"Cooldown Reducer XVII",
"Cooldown Reducer XVIII",
"Cooldown Reducer XIX",
"Cooldown Reducer XX",
"Firing Range Up I",
"Firing Range Up II",
"Firing Range Up III",
"Firing Range Up IV",
"Firing Range Up V",
"Firing Range Up VI",
"Firing Range Up VII",
"Firing Range Up VIII",
"Firing Range Up IX",
"Firing Range Up X",
"Firing Range Up XI",
"Firing Range Up XII",
"Firing Range Up XIII",
"Firing Range Up XIV",
"Firing Range Up XV",
"Firing Range Up XVI",
"Firing Range Up XVII",
"Firing Range Up XVIII",
"Firing Range Up XIX",
"Firing Range Up XX",
"Resist Stagger I",
"Resist Stagger II",
"Resist Stagger III",
"Resist Stagger IV",
"Resist Stagger V",
"Resist Stagger VI",
"Resist Stagger VII",
"Resist Stagger VIII",
"Resist Stagger IX",
"Resist Stagger X",
"Resist Stagger XI",
"Resist Stagger XII",
"Resist Stagger XIII",
"Resist Stagger XIV",
"Resist Stagger XV",
"Resist Stagger XVI",
"Resist Stagger XVII",
"Resist Stagger XVIII",
"Resist Stagger XIX",
"Resist Stagger XX",
"Resist Flinch I",
"Resist Flinch II",
"Resist Flinch III",
"Resist Flinch IV",
"Resist Flinch V",
"Resist Flinch VI",
"Resist Flinch VII",
"Resist Flinch VIII",
"Resist Flinch IX",
"Resist Flinch X",
"Resist Flinch XI",
"Resist Flinch XII",
"Resist Flinch XIII",
"Resist Flinch XIV",
"Resist Flinch XV",
"Resist Flinch XVI",
"Resist Flinch XVII",
"Resist Flinch XVIII",
"Resist Flinch XIX",
"Resist Flinch XX",
"Resist Topple I",
"Resist Topple II",
"Resist Topple III",
"Resist Topple IV",
"Resist Topple V",
"Resist Topple VI",
"Resist Topple VII",
"Resist Topple VIII",
"Resist Topple IX",
"Resist Topple X",
"Resist Topple XI",
"Resist Topple XII",
"Resist Topple XIII",
"Resist Topple XIV",
"Resist Topple XV",
"Resist Topple XVI",
"Resist Topple XVII",
"Resist Topple XVIII",
"Resist Topple XIX",
"Resist Topple XX",
"Resist Knockback I",
"Resist Knockback II",
"Resist Knockback III",
"Resist Knockback IV",
"Resist Knockback V",
"Resist Knockback VI",
"Resist Knockback VII",
"Resist Knockback VIII",
"Resist Knockback IX",
"Resist Knockback X",
"Resist Knockback XI",
"Resist Knockback XII",
"Resist Knockback XIII",
"Resist Knockback XIV",
"Resist Knockback XV",
"Resist Knockback XVI",
"Resist Knockback XVII",
"Resist Knockback XVIII",
"Resist Knockback XIX",
"Resist Knockback XX",
"Resist Launch I",
"Resist Launch II",
"Resist Launch III",
"Resist Launch IV",
"Resist Launch V",
"Resist Launch VI",
"Resist Launch VII",
"Resist Launch VIII",
"Resist Launch IX",
"Resist Launch X",
"Resist Launch XI",
"Resist Launch XII",
"Resist Launch XIII",
"Resist Launch XIV",
"Resist Launch XV",
"Resist Launch XVI",
"Resist Launch XVII",
"Resist Launch XVIII",
"Resist Launch XIX",
"Resist Launch XX",
"Resist Stun I",
"Resist Stun II",
"Resist Stun III",
"Resist Stun IV",
"Resist Stun V",
"Resist Stun VI",
"Resist Stun VII",
"Resist Stun VIII",
"Resist Stun IX",
"Resist Stun X",
"Resist Stun XI",
"Resist Stun XII",
"Resist Stun XIII",
"Resist Stun XIV",
"Resist Stun XV",
"Resist Stun XVI",
"Resist Stun XVII",
"Resist Stun XVIII",
"Resist Stun XIX",
"Resist Stun XX",
"Resist Sleep I",
"Resist Sleep II",
"Resist Sleep III",
"Resist Sleep IV",
"Resist Sleep V",
"Resist Sleep VI",
"Resist Sleep VII",
"Resist Sleep VIII",
"Resist Sleep IX",
"Resist Sleep X",
"Resist Sleep XI",
"Resist Sleep XII",
"Resist Sleep XIII",
"Resist Sleep XIV",
"Resist Sleep XV",
"Resist Sleep XVI",
"Resist Sleep XVII",
"Resist Sleep XVIII",
"Resist Sleep XIX",
"Resist Sleep XX",
"Resist Taunt I",
"Resist Taunt II",
"Resist Taunt III",
"Resist Taunt IV",
"Resist Taunt V",
"Resist Taunt VI",
"Resist Taunt VII",
"Resist Taunt VIII",
"Resist Taunt IX",
"Resist Taunt X",
"Resist Taunt XI",
"Resist Taunt XII",
"Resist Taunt XIII",
"Resist Taunt XIV",
"Resist Taunt XV",
"Resist Taunt XVI",
"Resist Taunt XVII",
"Resist Taunt XVIII",
"Resist Taunt XIX",
"Resist Taunt XX",
"Resist Control I",
"Resist Control II",
"Resist Control III",
"Resist Control IV",
"Resist Control V",
"Resist Control VI",
"Resist Control VII",
"Resist Control VIII",
"Resist Control IX",
"Resist Control X",
"Resist Control XI",
"Resist Control XII",
"Resist Control XIII",
"Resist Control XIV",
"Resist Control XV",
"Resist Control XVI",
"Resist Control XVII",
"Resist Control XVIII",
"Resist Control XIX",
"Resist Control XX",
"Resist Virus I",
"Resist Virus II",
"Resist Virus III",
"Resist Virus IV",
"Resist Virus V",
"Resist Virus VI",
"Resist Virus VII",
"Resist Virus VIII",
"Resist Virus IX",
"Resist Virus X",
"Resist Virus XI",
"Resist Virus XII",
"Resist Virus XIII",
"Resist Virus XIV",
"Resist Virus XV",
"Resist Virus XVI",
"Resist Virus XVII",
"Resist Virus XVIII",
"Resist Virus XIX",
"Resist Virus XX",
"Resist Blackout I",
"Resist Blackout II",
"Resist Blackout III",
"Resist Blackout IV",
"Resist Blackout V",
"Resist Blackout VI",
"Resist Blackout VII",
"Resist Blackout VIII",
"Resist Blackout IX",
"Resist Blackout X",
"Resist Blackout XI",
"Resist Blackout XII",
"Resist Blackout XIII",
"Resist Blackout XIV",
"Resist Blackout XV",
"Resist Blackout XVI",
"Resist Blackout XVII",
"Resist Blackout XVIII",
"Resist Blackout XIX",
"Resist Blackout XX",
"Resist Fatigue I",
"Resist Fatigue II",
"Resist Fatigue III",
"Resist Fatigue IV",
"Resist Fatigue V",
"Resist Fatigue VI",
"Resist Fatigue VII",
"Resist Fatigue VIII",
"Resist Fatigue IX",
"Resist Fatigue X",
"Resist Fatigue XI",
"Resist Fatigue XII",
"Resist Fatigue XIII",
"Resist Fatigue XIV",
"Resist Fatigue XV",
"Resist Fatigue XVI",
"Resist Fatigue XVII",
"Resist Fatigue XVIII",
"Resist Fatigue XIX",
"Resist Fatigue XX",
"Resist Slow Arts I",
"Resist Slow Arts II",
"Resist Slow Arts III",
"Resist Slow Arts IV",
"Resist Slow Arts V",
"Resist Slow Arts VI",
"Resist Slow Arts VII",
"Resist Slow Arts VIII",
"Resist Slow Arts IX",
"Resist Slow Arts X",
"Resist Slow Arts XI",
"Resist Slow Arts XII",
"Resist Slow Arts XIII",
"Resist Slow Arts XIV",
"Resist Slow Arts XV",
"Resist Slow Arts XVI",
"Resist Slow Arts XVII",
"Resist Slow Arts XVIII",
"Resist Slow Arts XIX",
"Resist Slow Arts XX",
"Resist Physical Res Down I",
"Resist Physical Res Down II",
"Resist Physical Res Down III",
"Resist Physical Res Down IV",
"Resist Physical Res Down V",
"Resist Physical Res Down VI",
"Resist Physical Res Down VII",
"Resist Physical Res Down VIII",
"Resist Physical Res Down IX",
"Resist Physical Res Down X",
"Resist Physical Res Down XI",
"Resist Physical Res Down XII",
"Resist Physical Res Down XIII",
"Resist Physical Res Down XIV",
"Resist Physical Res Down XV",
"Resist Physical Res Down XVI",
"Resist Physical Res Down XVII",
"Resist Physical Res Down XVIII",
"Resist Physical Res Down XIX",
"Resist Physical Res Down XX",
"Resist Beam Res Down I",
"Resist Beam Res Down II",
"Resist Beam Res Down III",
"Resist Beam Res Down IV",
"Resist Beam Res Down V",
"Resist Beam Res Down VI",
"Resist Beam Res Down VII",
"Resist Beam Res Down VIII",
"Resist Beam Res Down IX",
"Resist Beam Res Down X",
"Resist Beam Res Down XI",
"Resist Beam Res Down XII",
"Resist Beam Res Down XIII",
"Resist Beam Res Down XIV",
"Resist Beam Res Down XV",
"Resist Beam Res Down XVI",
"Resist Beam Res Down XVII",
"Resist Beam Res Down XVIII",
"Resist Beam Res Down XIX",
"Resist Beam Res Down XX",
"Resist Thermal Res Down I",
"Resist Thermal Res Down II",
"Resist Thermal Res Down III",
"Resist Thermal Res Down IV",
"Resist Thermal Res Down V",
"Resist Thermal Res Down VI",
"Resist Thermal Res Down VII",
"Resist Thermal Res Down VIII",
"Resist Thermal Res Down IX",
"Resist Thermal Res Down X",
"Resist Thermal Res Down XI",
"Resist Thermal Res Down XII",
"Resist Thermal Res Down XIII",
"Resist Thermal Res Down XIV",
"Resist Thermal Res Down XV",
"Resist Thermal Res Down XVI",
"Resist Thermal Res Down XVII",
"Resist Thermal Res Down XVIII",
"Resist Thermal Res Down XIX",
"Resist Thermal Res Down XX",
"Resist Electric Res Down I",
"Resist Electric Res Down II",
"Resist Electric Res Down III",
"Resist Electric Res Down IV",
"Resist Electric Res Down V",
"Resist Electric Res Down VI",
"Resist Electric Res Down VII",
"Resist Electric Res Down VIII",
"Resist Electric Res Down IX",
"Resist Electric Res Down X",
"Resist Electric Res Down XI",
"Resist Electric Res Down XII",
"Resist Electric Res Down XIII",
"Resist Electric Res Down XIV",
"Resist Electric Res Down XV",
"Resist Electric Res Down XVI",
"Resist Electric Res Down XVII",
"Resist Electric Res Down XVIII",
"Resist Electric Res Down XIX",
"Resist Electric Res Down XX",
"Resist Ether Res Down I",
"Resist Ether Res Down II",
"Resist Ether Res Down III",
"Resist Ether Res Down IV",
"Resist Ether Res Down V",
"Resist Ether Res Down VI",
"Resist Ether Res Down VII",
"Resist Ether Res Down VIII",
"Resist Ether Res Down IX",
"Resist Ether Res Down X",
"Resist Ether Res Down XI",
"Resist Ether Res Down XII",
"Resist Ether Res Down XIII",
"Resist Ether Res Down XIV",
"Resist Ether Res Down XV",
"Resist Ether Res Down XVI",
"Resist Ether Res Down XVII",
"Resist Ether Res Down XVIII",
"Resist Ether Res Down XIX",
"Resist Ether Res Down XX",
"Resist Gravity Res Down I",
"Resist Gravity Res Down II",
"Resist Gravity Res Down III",
"Resist Gravity Res Down IV",
"Resist Gravity Res Down V",
"Resist Gravity Res Down VI",
"Resist Gravity Res Down VII",
"Resist Gravity Res Down VIII",
"Resist Gravity Res Down IX",
"Resist Gravity Res Down X",
"Resist Gravity Res Down XI",
"Resist Gravity Res Down XII",
"Resist Gravity Res Down XIII",
"Resist Gravity Res Down XIV",
"Resist Gravity Res Down XV",
"Resist Gravity Res Down XVI",
"Resist Gravity Res Down XVII",
"Resist Gravity Res Down XVIII",
"Resist Gravity Res Down XIX",
"Resist Gravity Res Down XX",
"Resist Time Bomb I",
"Resist Time Bomb II",
"Resist Time Bomb III",
"Resist Time Bomb IV",
"Resist Time Bomb V",
"Resist Time Bomb VI",
"Resist Time Bomb VII",
"Resist Time Bomb VIII",
"Resist Time Bomb IX",
"Resist Time Bomb X",
"Resist Time Bomb XI",
"Resist Time Bomb XII",
"Resist Time Bomb XIII",
"Resist Time Bomb XIV",
"Resist Time Bomb XV",
"Resist Time Bomb XVI",
"Resist Time Bomb XVII",
"Resist Time Bomb XVIII",
"Resist Time Bomb XIX",
"Resist Time Bomb XX",
"Resist Debuff Res Down I",
"Resist Debuff Res Down II",
"Resist Debuff Res Down III",
"Resist Debuff Res Down IV",
"Resist Debuff Res Down V",
"Resist Debuff Res Down VI",
"Resist Debuff Res Down VII",
"Resist Debuff Res Down VIII",
"Resist Debuff Res Down IX",
"Resist Debuff Res Down X",
"Resist Debuff Res Down XI",
"Resist Debuff Res Down XII",
"Resist Debuff Res Down XIII",
"Resist Debuff Res Down XIV",
"Resist Debuff Res Down XV",
"Resist Debuff Res Down XVI",
"Resist Debuff Res Down XVII",
"Resist Debuff Res Down XVIII",
"Resist Debuff Res Down XIX",
"Resist Debuff Res Down XX",
"Resist HP Recovery Down I",
"Resist HP Recovery Down II",
"Resist HP Recovery Down III",
"Resist HP Recovery Down IV",
"Resist HP Recovery Down V",
"Resist HP Recovery Down VI",
"Resist HP Recovery Down VII",
"Resist HP Recovery Down VIII",
"Resist HP Recovery Down IX",
"Resist HP Recovery Down X",
"Resist HP Recovery Down XI",
"Resist HP Recovery Down XII",
"Resist HP Recovery Down XIII",
"Resist HP Recovery Down XIV",
"Resist HP Recovery Down XV",
"Resist HP Recovery Down XVI",
"Resist HP Recovery Down XVII",
"Resist HP Recovery Down XVIII",
"Resist HP Recovery Down XIX",
"Resist HP Recovery Down XX",
"Resist Blaze I",
"Resist Blaze II",
"Resist Blaze III",
"Resist Blaze IV",
"Resist Blaze V",
"Resist Blaze VI",
"Resist Blaze VII",
"Resist Blaze VIII",
"Resist Blaze IX",
"Resist Blaze X",
"Resist Blaze XI",
"Resist Blaze XII",
"Resist Blaze XIII",
"Resist Blaze XIV",
"Resist Blaze XV",
"Resist Blaze XVI",
"Resist Blaze XVII",
"Resist Blaze XVIII",
"Resist Blaze XIX",
"Resist Blaze XX",
"Resist Shock I",
"Resist Shock II",
"Resist Shock III",
"Resist Shock IV",
"Resist Shock V",
"Resist Shock VI",
"Resist Shock VII",
"Resist Shock VIII",
"Resist Shock IX",
"Resist Shock X",
"Resist Shock XI",
"Resist Shock XII",
"Resist Shock XIII",
"Resist Shock XIV",
"Resist Shock XV",
"Resist Shock XVI",
"Resist Shock XVII",
"Resist Shock XVIII",
"Resist Shock XIX",
"Resist Shock XX",
"Debuff Suppressor I",
"Debuff Suppressor II",
"Debuff Suppressor III",
"Debuff Suppressor IV",
"Debuff Suppressor V",
"Debuff Suppressor VI",
"Debuff Suppressor VII",
"Debuff Suppressor VIII",
"Debuff Suppressor IX",
"Debuff Suppressor X",
"Debuff Suppressor XI",
"Debuff Suppressor XII",
"Debuff Suppressor XIII",
"Debuff Suppressor XIV",
"Debuff Suppressor XV",
"Debuff Suppressor XVI",
"Debuff Suppressor XVII",
"Debuff Suppressor XVIII",
"Debuff Suppressor XIX",
"Debuff Suppressor XX",
"Critical Chance Up I",
"Critical Chance Up II",
"Critical Chance Up III",
"Critical Chance Up IV",
"Critical Chance Up V",
"Critical Chance Up VI",
"Critical Chance Up VII",
"Critical Chance Up VIII",
"Critical Chance Up IX",
"Critical Chance Up X",
"Critical Chance Up XI",
"Critical Chance Up XII",
"Critical Chance Up XIII",
"Critical Chance Up XIV",
"Critical Chance Up XV",
"Critical Chance Up XVI",
"Critical Chance Up XVII",
"Critical Chance Up XVIII",
"Critical Chance Up XIX",
"Critical Chance Up XX",
"Theroid Criticals Up I",
"Theroid Criticals Up II",
"Theroid Criticals Up III",
"Theroid Criticals Up IV",
"Theroid Criticals Up V",
"Theroid Criticals Up VI",
"Theroid Criticals Up VII",
"Theroid Criticals Up VIII",
"Theroid Criticals Up IX",
"Theroid Criticals Up X",
"Theroid Criticals Up XI",
"Theroid Criticals Up XII",
"Theroid Criticals Up XIII",
"Theroid Criticals Up XIV",
"Theroid Criticals Up XV",
"Theroid Criticals Up XVI",
"Theroid Criticals Up XVII",
"Theroid Criticals Up XVIII",
"Theroid Criticals Up XIX",
"Theroid Criticals Up XX",
"Insectoid Criticals Up I",
"Insectoid Criticals Up II",
"Insectoid Criticals Up III",
"Insectoid Criticals Up IV",
"Insectoid Criticals Up V",
"Insectoid Criticals Up VI",
"Insectoid Criticals Up VII",
"Insectoid Criticals Up VIII",
"Insectoid Criticals Up IX",
"Insectoid Criticals Up X",
"Insectoid Criticals Up XI",
"Insectoid Criticals Up XII",
"Insectoid Criticals Up XIII",
"Insectoid Criticals Up XIV",
"Insectoid Criticals Up XV",
"Insectoid Criticals Up XVI",
"Insectoid Criticals Up XVII",
"Insectoid Criticals Up XVIII",
"Insectoid Criticals Up XIX",
"Insectoid Criticals Up XX",
"Piscinoid Criticals Up I",
"Piscinoid Criticals Up II",
"Piscinoid Criticals Up III",
"Piscinoid Criticals Up IV",
"Piscinoid Criticals Up V",
"Piscinoid Criticals Up VI",
"Piscinoid Criticals Up VII",
"Piscinoid Criticals Up VIII",
"Piscinoid Criticals Up IX",
"Piscinoid Criticals Up X",
"Piscinoid Criticals Up XI",
"Piscinoid Criticals Up XII",
"Piscinoid Criticals Up XIII",
"Piscinoid Criticals Up XIV",
"Piscinoid Criticals Up XV",
"Piscinoid Criticals Up XVI",
"Piscinoid Criticals Up XVII",
"Piscinoid Criticals Up XVIII",
"Piscinoid Criticals Up XIX",
"Piscinoid Criticals Up XX",
"Humanoid Criticals Up I",
"Humanoid Criticals Up II",
"Humanoid Criticals Up III",
"Humanoid Criticals Up IV",
"Humanoid Criticals Up V",
"Humanoid Criticals Up VI",
"Humanoid Criticals Up VII",
"Humanoid Criticals Up VIII",
"Humanoid Criticals Up IX",
"Humanoid Criticals Up X",
"Humanoid Criticals Up XI",
"Humanoid Criticals Up XII",
"Humanoid Criticals Up XIII",
"Humanoid Criticals Up XIV",
"Humanoid Criticals Up XV",
"Humanoid Criticals Up XVI",
"Humanoid Criticals Up XVII",
"Humanoid Criticals Up XVIII",
"Humanoid Criticals Up XIX",
"Humanoid Criticals Up XX",
"Mechanoid Criticals Up I",
"Mechanoid Criticals Up II",
"Mechanoid Criticals Up III",
"Mechanoid Criticals Up IV",
"Mechanoid Criticals Up V",
"Mechanoid Criticals Up VI",
"Mechanoid Criticals Up VII",
"Mechanoid Criticals Up VIII",
"Mechanoid Criticals Up IX",
"Mechanoid Criticals Up X",
"Mechanoid Criticals Up XI",
"Mechanoid Criticals Up XII",
"Mechanoid Criticals Up XIII",
"Mechanoid Criticals Up XIV",
"Mechanoid Criticals Up XV",
"Mechanoid Criticals Up XVI",
"Mechanoid Criticals Up XVII",
"Mechanoid Criticals Up XVIII",
"Mechanoid Criticals Up XIX",
"Mechanoid Criticals Up XX",
"Chimeroid Criticals Up I",
"Chimeroid Criticals Up II",
"Chimeroid Criticals Up III",
"Chimeroid Criticals Up IV",
"Chimeroid Criticals Up V",
"Chimeroid Criticals Up VI",
"Chimeroid Criticals Up VII",
"Chimeroid Criticals Up VIII",
"Chimeroid Criticals Up IX",
"Chimeroid Criticals Up X",
"Chimeroid Criticals Up XI",
"Chimeroid Criticals Up XII",
"Chimeroid Criticals Up XIII",
"Chimeroid Criticals Up XIV",
"Chimeroid Criticals Up XV",
"Chimeroid Criticals Up XVI",
"Chimeroid Criticals Up XVII",
"Chimeroid Criticals Up XVIII",
"Chimeroid Criticals Up XIX",
"Chimeroid Criticals Up XX",
"Ultrafauna Criticals Up I",
"Ultrafauna Criticals Up II",
"Ultrafauna Criticals Up III",
"Ultrafauna Criticals Up IV",
"Ultrafauna Criticals Up V",
"Ultrafauna Criticals Up VI",
"Ultrafauna Criticals Up VII",
"Ultrafauna Criticals Up VIII",
"Ultrafauna Criticals Up IX",
"Ultrafauna Criticals Up X",
"Ultrafauna Criticals Up XI",
"Ultrafauna Criticals Up XII",
"Ultrafauna Criticals Up XIII",
"Ultrafauna Criticals Up XIV",
"Ultrafauna Criticals Up XV",
"Ultrafauna Criticals Up XVI",
"Ultrafauna Criticals Up XVII",
"Ultrafauna Criticals Up XVIII",
"Ultrafauna Criticals Up XIX",
"Ultrafauna Criticals Up XX",
"Extend Critical Power I",
"Extend Critical Power II",
"Extend Critical Power III",
"Extend Critical Power IV",
"Extend Critical Power V",
"Extend Critical Power VI",
"Extend Critical Power VII",
"Extend Critical Power VIII",
"Extend Critical Power IX",
"Extend Critical Power X",
"Extend Critical Power XI",
"Extend Critical Power XII",
"Extend Critical Power XIII",
"Extend Critical Power XIV",
"Extend Critical Power XV",
"Extend Critical Power XVI",
"Extend Critical Power XVII",
"Extend Critical Power XVIII",
"Extend Critical Power XIX",
"Extend Critical Power XX",
"Zero Critical",
"Theroid Slayer I",
"Theroid Slayer II",
"Theroid Slayer III",
"Theroid Slayer IV",
"Theroid Slayer V",
"Theroid Slayer VI",
"Theroid Slayer VII",
"Theroid Slayer VIII",
"Theroid Slayer IX",
"Theroid Slayer X",
"Theroid Slayer XI",
"Theroid Slayer XII",
"Theroid Slayer XIII",
"Theroid Slayer XIV",
"Theroid Slayer XV",
"Theroid Slayer XVI",
"Theroid Slayer XVII",
"Theroid Slayer XVIII",
"Theroid Slayer XIX",
"Theroid Slayer XX",
"Insectoid Slayer I",
"Insectoid Slayer II",
"Insectoid Slayer III",
"Insectoid Slayer IV",
"Insectoid Slayer V",
"Insectoid Slayer VI",
"Insectoid Slayer VII",
"Insectoid Slayer VIII",
"Insectoid Slayer IX",
"Insectoid Slayer X",
"Insectoid Slayer XI",
"Insectoid Slayer XII",
"Insectoid Slayer XIII",
"Insectoid Slayer XIV",
"Insectoid Slayer XV",
"Insectoid Slayer XVI",
"Insectoid Slayer XVII",
"Insectoid Slayer XVIII",
"Insectoid Slayer XIX",
"Insectoid Slayer XX",
"Piscinoid Slayer I",
"Piscinoid Slayer II",
"Piscinoid Slayer III",
"Piscinoid Slayer IV",
"Piscinoid Slayer V",
"Piscinoid Slayer VI",
"Piscinoid Slayer VII",
"Piscinoid Slayer VIII",
"Piscinoid Slayer IX",
"Piscinoid Slayer X",
"Piscinoid Slayer XI",
"Piscinoid Slayer XII",
"Piscinoid Slayer XIII",
"Piscinoid Slayer XIV",
"Piscinoid Slayer XV",
"Piscinoid Slayer XVI",
"Piscinoid Slayer XVII",
"Piscinoid Slayer XVIII",
"Piscinoid Slayer XIX",
"Piscinoid Slayer XX",
"Humanoid Slayer I",
"Humanoid Slayer II",
"Humanoid Slayer III",
"Humanoid Slayer IV",
"Humanoid Slayer V",
"Humanoid Slayer VI",
"Humanoid Slayer VII",
"Humanoid Slayer VIII",
"Humanoid Slayer IX",
"Humanoid Slayer X",
"Humanoid Slayer XI",
"Humanoid Slayer XII",
"Humanoid Slayer XIII",
"Humanoid Slayer XIV",
"Humanoid Slayer XV",
"Humanoid Slayer XVI",
"Humanoid Slayer XVII",
"Humanoid Slayer XVIII",
"Humanoid Slayer XIX",
"Humanoid Slayer XX",
"Mechanoid Slayer I",
"Mechanoid Slayer II",
"Mechanoid Slayer III",
"Mechanoid Slayer IV",
"Mechanoid Slayer V",
"Mechanoid Slayer VI",
"Mechanoid Slayer VII",
"Mechanoid Slayer VIII",
"Mechanoid Slayer IX",
"Mechanoid Slayer X",
"Mechanoid Slayer XI",
"Mechanoid Slayer XII",
"Mechanoid Slayer XIII",
"Mechanoid Slayer XIV",
"Mechanoid Slayer XV",
"Mechanoid Slayer XVI",
"Mechanoid Slayer XVII",
"Mechanoid Slayer XVIII",
"Mechanoid Slayer XIX",
"Mechanoid Slayer XX",
"Chimeroid Slayer I",
"Chimeroid Slayer II",
"Chimeroid Slayer III",
"Chimeroid Slayer IV",
"Chimeroid Slayer V",
"Chimeroid Slayer VI",
"Chimeroid Slayer VII",
"Chimeroid Slayer VIII",
"Chimeroid Slayer IX",
"Chimeroid Slayer X",
"Chimeroid Slayer XI",
"Chimeroid Slayer XII",
"Chimeroid Slayer XIII",
"Chimeroid Slayer XIV",
"Chimeroid Slayer XV",
"Chimeroid Slayer XVI",
"Chimeroid Slayer XVII",
"Chimeroid Slayer XVIII",
"Chimeroid Slayer XIX",
"Chimeroid Slayer XX",
"Ultrafauna Slayer I",
"Ultrafauna Slayer II",
"Ultrafauna Slayer III",
"Ultrafauna Slayer IV",
"Ultrafauna Slayer V",
"Ultrafauna Slayer VI",
"Ultrafauna Slayer VII",
"Ultrafauna Slayer VIII",
"Ultrafauna Slayer IX",
"Ultrafauna Slayer X",
"Ultrafauna Slayer XI",
"Ultrafauna Slayer XII",
"Ultrafauna Slayer XIII",
"Ultrafauna Slayer XIV",
"Ultrafauna Slayer XV",
"Ultrafauna Slayer XVI",
"Ultrafauna Slayer XVII",
"Ultrafauna Slayer XVIII",
"Ultrafauna Slayer XIX",
"Ultrafauna Slayer XX",
"Physical Attack Plus I",
"Physical Attack Plus II",
"Physical Attack Plus III",
"Physical Attack Plus IV",
"Physical Attack Plus V",
"Physical Attack Plus VI",
"Physical Attack Plus VII",
"Physical Attack Plus VIII",
"Physical Attack Plus IX",
"Physical Attack Plus X",
"Physical Attack Plus XI",
"Physical Attack Plus XII",
"Physical Attack Plus XIII",
"Physical Attack Plus XIV",
"Physical Attack Plus XV",
"Physical Attack Plus XVI",
"Physical Attack Plus XVII",
"Physical Attack Plus XVIII",
"Physical Attack Plus XIX",
"Physical Attack Plus XX",
"Beam Attack Plus I",
"Beam Attack Plus II",
"Beam Attack Plus III",
"Beam Attack Plus IV",
"Beam Attack Plus V",
"Beam Attack Plus VI",
"Beam Attack Plus VII",
"Beam Attack Plus VIII",
"Beam Attack Plus IX",
"Beam Attack Plus X",
"Beam Attack Plus XI",
"Beam Attack Plus XII",
"Beam Attack Plus XIII",
"Beam Attack Plus XIV",
"Beam Attack Plus XV",
"Beam Attack Plus XVI",
"Beam Attack Plus XVII",
"Beam Attack Plus XVIII",
"Beam Attack Plus XIX",
"Beam Attack Plus XX",
"Ether Attack Plus I",
"Ether Attack Plus II",
"Ether Attack Plus III",
"Ether Attack Plus IV",
"Ether Attack Plus V",
"Ether Attack Plus VI",
"Ether Attack Plus VII",
"Ether Attack Plus VIII",
"Ether Attack Plus IX",
"Ether Attack Plus X",
"Ether Attack Plus XI",
"Ether Attack Plus XII",
"Ether Attack Plus XIII",
"Ether Attack Plus XIV",
"Ether Attack Plus XV",
"Ether Attack Plus XVI",
"Ether Attack Plus XVII",
"Ether Attack Plus XVIII",
"Ether Attack Plus XIX",
"Ether Attack Plus XX",
"Thermal Attack Plus I",
"Thermal Attack Plus II",
"Thermal Attack Plus III",
"Thermal Attack Plus IV",
"Thermal Attack Plus V",
"Thermal Attack Plus VI",
"Thermal Attack Plus VII",
"Thermal Attack Plus VIII",
"Thermal Attack Plus IX",
"Thermal Attack Plus X",
"Thermal Attack Plus XI",
"Thermal Attack Plus XII",
"Thermal Attack Plus XIII",
"Thermal Attack Plus XIV",
"Thermal Attack Plus XV",
"Thermal Attack Plus XVI",
"Thermal Attack Plus XVII",
"Thermal Attack Plus XVIII",
"Thermal Attack Plus XIX",
"Thermal Attack Plus XX",
"Electric Attack Plus I",
"Electric Attack Plus II",
"Electric Attack Plus III",
"Electric Attack Plus IV",
"Electric Attack Plus V",
"Electric Attack Plus VI",
"Electric Attack Plus VII",
"Electric Attack Plus VIII",
"Electric Attack Plus IX",
"Electric Attack Plus X",
"Electric Attack Plus XI",
"Electric Attack Plus XII",
"Electric Attack Plus XIII",
"Electric Attack Plus XIV",
"Electric Attack Plus XV",
"Electric Attack Plus XVI",
"Electric Attack Plus XVII",
"Electric Attack Plus XVIII",
"Electric Attack Plus XIX",
"Electric Attack Plus XX",
"Gravity Attack Plus I",
"Gravity Attack Plus II",
"Gravity Attack Plus III",
"Gravity Attack Plus IV",
"Gravity Attack Plus V",
"Gravity Attack Plus VI",
"Gravity Attack Plus VII",
"Gravity Attack Plus VIII",
"Gravity Attack Plus IX",
"Gravity Attack Plus X",
"Gravity Attack Plus XI",
"Gravity Attack Plus XII",
"Gravity Attack Plus XIII",
"Gravity Attack Plus XIV",
"Gravity Attack Plus XV",
"Gravity Attack Plus XVI",
"Gravity Attack Plus XVII",
"Gravity Attack Plus XVIII",
"Gravity Attack Plus XIX",
"Gravity Attack Plus XX",
"Front Attack Plus I",
"Front Attack Plus II",
"Front Attack Plus III",
"Front Attack Plus IV",
"Front Attack Plus V",
"Front Attack Plus VI",
"Front Attack Plus VII",
"Front Attack Plus VIII",
"Front Attack Plus IX",
"Front Attack Plus X",
"Front Attack Plus XI",
"Front Attack Plus XII",
"Front Attack Plus XIII",
"Front Attack Plus XIV",
"Front Attack Plus XV",
"Front Attack Plus XVI",
"Front Attack Plus XVII",
"Front Attack Plus XVIII",
"Front Attack Plus XIX",
"Front Attack Plus XX",
"Side Attack Plus I",
"Side Attack Plus II",
"Side Attack Plus III",
"Side Attack Plus IV",
"Side Attack Plus V",
"Side Attack Plus VI",
"Side Attack Plus VII",
"Side Attack Plus VIII",
"Side Attack Plus IX",
"Side Attack Plus X",
"Side Attack Plus XI",
"Side Attack Plus XII",
"Side Attack Plus XIII",
"Side Attack Plus XIV",
"Side Attack Plus XV",
"Side Attack Plus XVI",
"Side Attack Plus XVII",
"Side Attack Plus XVIII",
"Side Attack Plus XIX",
"Side Attack Plus XX",
"Back Attack Plus I",
"Back Attack Plus II",
"Back Attack Plus III",
"Back Attack Plus IV",
"Back Attack Plus V",
"Back Attack Plus VI",
"Back Attack Plus VII",
"Back Attack Plus VIII",
"Back Attack Plus IX",
"Back Attack Plus X",
"Back Attack Plus XI",
"Back Attack Plus XII",
"Back Attack Plus XIII",
"Back Attack Plus XIV",
"Back Attack Plus XV",
"Back Attack Plus XVI",
"Back Attack Plus XVII",
"Back Attack Plus XVIII",
"Back Attack Plus XIX",
"Back Attack Plus XX",
"Vantage Attack Plus I",
"Vantage Attack Plus II",
"Vantage Attack Plus III",
"Vantage Attack Plus IV",
"Vantage Attack Plus V",
"Vantage Attack Plus VI",
"Vantage Attack Plus VII",
"Vantage Attack Plus VIII",
"Vantage Attack Plus IX",
"Vantage Attack Plus X",
"Vantage Attack Plus XI",
"Vantage Attack Plus XII",
"Vantage Attack Plus XIII",
"Vantage Attack Plus XIV",
"Vantage Attack Plus XV",
"Vantage Attack Plus XVI",
"Vantage Attack Plus XVII",
"Vantage Attack Plus XVIII",
"Vantage Attack Plus XIX",
"Vantage Attack Plus XX",
"Melee: Blackout I",
"Melee: Blackout II",
"Melee: Blackout III",
"Melee: Blackout IV",
"Melee: Blackout V",
"Melee: Blackout VI",
"Melee: Blackout VII",
"Melee: Blackout VIII",
"Melee: Blackout IX",
"Melee: Blackout X",
"Melee: Blackout XI",
"Melee: Blackout XII",
"Melee: Blackout XIII",
"Melee: Blackout XIV",
"Melee: Blackout XV",
"Melee: Blackout XVI",
"Melee: Blackout XVII",
"Melee: Blackout XVIII",
"Melee: Blackout XIX",
"Melee: Blackout XX",
"Melee: Fatigue I",
"Melee: Fatigue II",
"Melee: Fatigue III",
"Melee: Fatigue IV",
"Melee: Fatigue V",
"Melee: Fatigue VI",
"Melee: Fatigue VII",
"Melee: Fatigue VIII",
"Melee: Fatigue IX",
"Melee: Fatigue X",
"Melee: Fatigue XI",
"Melee: Fatigue XII",
"Melee: Fatigue XIII",
"Melee: Fatigue XIV",
"Melee: Fatigue XV",
"Melee: Fatigue XVI",
"Melee: Fatigue XVII",
"Melee: Fatigue XVIII",
"Melee: Fatigue XIX",
"Melee: Fatigue XX",
"Melee: Physical Res Down I",
"Melee: Physical Res Down II",
"Melee: Physical Res Down III",
"Melee: Physical Res Down IV",
"Melee: Physical Res Down V",
"Melee: Physical Res Down VI",
"Melee: Physical Res Down VII",
"Melee: Physical Res Down VIII",
"Melee: Physical Res Down IX",
"Melee: Physical Res Down X",
"Melee: Physical Res Down XI",
"Melee: Physical Res Down XII",
"Melee: Physical Res Down XIII",
"Melee: Physical Res Down XIV",
"Melee: Physical Res Down XV",
"Melee: Physical Res Down XVI",
"Melee: Physical Res Down XVII",
"Melee: Physical Res Down XVIII",
"Melee: Physical Res Down XIX",
"Melee: Physical Res Down XX",
"Melee: Beam Res Down I",
"Melee: Beam Res Down II",
"Melee: Beam Res Down III",
"Melee: Beam Res Down IV",
"Melee: Beam Res Down V",
"Melee: Beam Res Down VI",
"Melee: Beam Res Down VII",
"Melee: Beam Res Down VIII",
"Melee: Beam Res Down IX",
"Melee: Beam Res Down X",
"Melee: Beam Res Down XI",
"Melee: Beam Res Down XII",
"Melee: Beam Res Down XIII",
"Melee: Beam Res Down XIV",
"Melee: Beam Res Down XV",
"Melee: Beam Res Down XVI",
"Melee: Beam Res Down XVII",
"Melee: Beam Res Down XVIII",
"Melee: Beam Res Down XIX",
"Melee: Beam Res Down XX",
"Melee: Ether Res Down I",
"Melee: Ether Res Down II",
"Melee: Ether Res Down III",
"Melee: Ether Res Down IV",
"Melee: Ether Res Down V",
"Melee: Ether Res Down VI",
"Melee: Ether Res Down VII",
"Melee: Ether Res Down VIII",
"Melee: Ether Res Down IX",
"Melee: Ether Res Down X",
"Melee: Ether Res Down XI",
"Melee: Ether Res Down XII",
"Melee: Ether Res Down XIII",
"Melee: Ether Res Down XIV",
"Melee: Ether Res Down XV",
"Melee: Ether Res Down XVI",
"Melee: Ether Res Down XVII",
"Melee: Ether Res Down XVIII",
"Melee: Ether Res Down XIX",
"Melee: Ether Res Down XX",
"Melee: Thermal Res Down I",
"Melee: Thermal Res Down II",
"Melee: Thermal Res Down III",
"Melee: Thermal Res Down IV",
"Melee: Thermal Res Down V",
"Melee: Thermal Res Down VI",
"Melee: Thermal Res Down VII",
"Melee: Thermal Res Down VIII",
"Melee: Thermal Res Down IX",
"Melee: Thermal Res Down X",
"Melee: Thermal Res Down XI",
"Melee: Thermal Res Down XII",
"Melee: Thermal Res Down XIII",
"Melee: Thermal Res Down XIV",
"Melee: Thermal Res Down XV",
"Melee: Thermal Res Down XVI",
"Melee: Thermal Res Down XVII",
"Melee: Thermal Res Down XVIII",
"Melee: Thermal Res Down XIX",
"Melee: Thermal Res Down XX",
"Melee: Electric Res Down I",
"Melee: Electric Res Down II",
"Melee: Electric Res Down III",
"Melee: Electric Res Down IV",
"Melee: Electric Res Down V",
"Melee: Electric Res Down VI",
"Melee: Electric Res Down VII",
"Melee: Electric Res Down VIII",
"Melee: Electric Res Down IX",
"Melee: Electric Res Down X",
"Melee: Electric Res Down XI",
"Melee: Electric Res Down XII",
"Melee: Electric Res Down XIII",
"Melee: Electric Res Down XIV",
"Melee: Electric Res Down XV",
"Melee: Electric Res Down XVI",
"Melee: Electric Res Down XVII",
"Melee: Electric Res Down XVIII",
"Melee: Electric Res Down XIX",
"Melee: Electric Res Down XX",
"Melee: Gravity Res Down I",
"Melee: Gravity Res Down II",
"Melee: Gravity Res Down III",
"Melee: Gravity Res Down IV",
"Melee: Gravity Res Down V",
"Melee: Gravity Res Down VI",
"Melee: Gravity Res Down VII",
"Melee: Gravity Res Down VIII",
"Melee: Gravity Res Down IX",
"Melee: Gravity Res Down X",
"Melee: Gravity Res Down XI",
"Melee: Gravity Res Down XII",
"Melee: Gravity Res Down XIII",
"Melee: Gravity Res Down XIV",
"Melee: Gravity Res Down XV",
"Melee: Gravity Res Down XVI",
"Melee: Gravity Res Down XVII",
"Melee: Gravity Res Down XVIII",
"Melee: Gravity Res Down XIX",
"Melee: Gravity Res Down XX",
"Melee: Blaze I",
"Melee: Blaze II",
"Melee: Blaze III",
"Melee: Blaze IV",
"Melee: Blaze V",
"Melee: Blaze VI",
"Melee: Blaze VII",
"Melee: Blaze VIII",
"Melee: Blaze IX",
"Melee: Blaze X",
"Melee: Blaze XI",
"Melee: Blaze XII",
"Melee: Blaze XIII",
"Melee: Blaze XIV",
"Melee: Blaze XV",
"Melee: Blaze XVI",
"Melee: Blaze XVII",
"Melee: Blaze XVIII",
"Melee: Blaze XIX",
"Melee: Blaze XX",
"Melee: Shock I",
"Melee: Shock II",
"Melee: Shock III",
"Melee: Shock IV",
"Melee: Shock V",
"Melee: Shock VI",
"Melee: Shock VII",
"Melee: Shock VIII",
"Melee: Shock IX",
"Melee: Shock X",
"Melee: Shock XI",
"Melee: Shock XII",
"Melee: Shock XIII",
"Melee: Shock XIV",
"Melee: Shock XV",
"Melee: Shock XVI",
"Melee: Shock XVII",
"Melee: Shock XVIII",
"Melee: Shock XIX",
"Melee: Shock XX",
"Melee: Recover HP I",
"Melee: Recover HP II",
"Melee: Recover HP III",
"Melee: Recover HP IV",
"Melee: Recover HP V",
"Melee: Recover HP VI",
"Melee: Recover HP VII",
"Melee: Recover HP VIII",
"Melee: Recover HP IX",
"Melee: Recover HP X",
"Melee: Recover HP XI",
"Melee: Recover HP XII",
"Melee: Recover HP XIII",
"Melee: Recover HP XIV",
"Melee: Recover HP XV",
"Melee: Recover HP XVI",
"Melee: Recover HP XVII",
"Melee: Recover HP XVIII",
"Melee: Recover HP XIX",
"Melee: Recover HP XX",
"Soft Touch I",
"Soft Touch II",
"Soft Touch III",
"Soft Touch IV",
"Soft Touch V",
"Soft Touch VI",
"Soft Touch VII",
"Soft Touch VIII",
"Soft Touch IX",
"Soft Touch X",
"Soft Touch XI",
"Soft Touch XII",
"Soft Touch XIII",
"Soft Touch XIV",
"Soft Touch XV",
"Soft Touch XVI",
"Soft Touch XVII",
"Soft Touch XVIII",
"Soft Touch XIX",
"Soft Touch XX",
"HP Rebound I",
"HP Rebound II",
"HP Rebound III",
"HP Rebound IV",
"HP Rebound V",
"HP Rebound VI",
"HP Rebound VII",
"HP Rebound VIII",
"HP Rebound IX",
"HP Rebound X",
"HP Rebound XI",
"HP Rebound XII",
"HP Rebound XIII",
"HP Rebound XIV",
"HP Rebound XV",
"HP Rebound XVI",
"HP Rebound XVII",
"HP Rebound XVIII",
"HP Rebound XIX",
"HP Rebound XX",
"TP Rebound I",
"TP Rebound II",
"TP Rebound III",
"TP Rebound IV",
"TP Rebound V",
"TP Rebound VI",
"TP Rebound VII",
"TP Rebound VIII",
"TP Rebound IX",
"TP Rebound X",
"TP Rebound XI",
"TP Rebound XII",
"TP Rebound XIII",
"TP Rebound XIV",
"TP Rebound XV",
"TP Rebound XVI",
"TP Rebound XVII",
"TP Rebound XVIII",
"TP Rebound XIX",
"TP Rebound XX",
"Taunt: Barrier I",
"Taunt: Barrier II",
"Taunt: Barrier III",
"Taunt: Barrier IV",
"Taunt: Barrier V",
"Taunt: Barrier VI",
"Taunt: Barrier VII",
"Taunt: Barrier VIII",
"Taunt: Barrier IX",
"Taunt: Barrier X",
"Taunt: Barrier XI",
"Taunt: Barrier XII",
"Taunt: Barrier XIII",
"Taunt: Barrier XIV",
"Taunt: Barrier XV",
"Taunt: Barrier XVI",
"Taunt: Barrier XVII",
"Taunt: Barrier XVIII",
"Taunt: Barrier XIX",
"Taunt: Barrier XX",
"Taunt: Decoy I",
"Taunt: Decoy II",
"Taunt: Decoy III",
"Taunt: Decoy IV",
"Taunt: Decoy V",
"Taunt: Decoy VI",
"Taunt: Decoy VII",
"Taunt: Decoy VIII",
"Taunt: Decoy IX",
"Taunt: Decoy X",
"Taunt: Decoy XI",
"Taunt: Decoy XII",
"Taunt: Decoy XIII",
"Taunt: Decoy XIV",
"Taunt: Decoy XV",
"Taunt: Decoy XVI",
"Taunt: Decoy XVII",
"Taunt: Decoy XVIII",
"Taunt: Decoy XIX",
"Taunt: Decoy XX",
"Taunt: Supercharge I",
"Taunt: Supercharge II",
"Taunt: Supercharge III",
"Taunt: Supercharge IV",
"Taunt: Supercharge V",
"Taunt: Supercharge VI",
"Taunt: Supercharge VII",
"Taunt: Supercharge VIII",
"Taunt: Supercharge IX",
"Taunt: Supercharge X",
"Taunt: Supercharge XI",
"Taunt: Supercharge XII",
"Taunt: Supercharge XIII",
"Taunt: Supercharge XIV",
"Taunt: Supercharge XV",
"Taunt: Supercharge XVI",
"Taunt: Supercharge XVII",
"Taunt: Supercharge XVIII",
"Taunt: Supercharge XIX",
"Taunt: Supercharge XX",
"Topple: Barrier I",
"Topple: Barrier II",
"Topple: Barrier III",
"Topple: Barrier IV",
"Topple: Barrier V",
"Topple: Barrier VI",
"Topple: Barrier VII",
"Topple: Barrier VIII",
"Topple: Barrier IX",
"Topple: Barrier X",
"Topple: Barrier XI",
"Topple: Barrier XII",
"Topple: Barrier XIII",
"Topple: Barrier XIV",
"Topple: Barrier XV",
"Topple: Barrier XVI",
"Topple: Barrier XVII",
"Topple: Barrier XVIII",
"Topple: Barrier XIX",
"Topple: Barrier XX",
"Topple: Decoy I",
"Topple: Decoy II",
"Topple: Decoy III",
"Topple: Decoy IV",
"Topple: Decoy V",
"Topple: Decoy VI",
"Topple: Decoy VII",
"Topple: Decoy VIII",
"Topple: Decoy IX",
"Topple: Decoy X",
"Topple: Decoy XI",
"Topple: Decoy XII",
"Topple: Decoy XIII",
"Topple: Decoy XIV",
"Topple: Decoy XV",
"Topple: Decoy XVI",
"Topple: Decoy XVII",
"Topple: Decoy XVIII",
"Topple: Decoy XIX",
"Topple: Decoy XX",
"Stun: Barrier I",
"Stun: Barrier II",
"Stun: Barrier III",
"Stun: Barrier IV",
"Stun: Barrier V",
"Stun: Barrier VI",
"Stun: Barrier VII",
"Stun: Barrier VIII",
"Stun: Barrier IX",
"Stun: Barrier X",
"Stun: Barrier XI",
"Stun: Barrier XII",
"Stun: Barrier XIII",
"Stun: Barrier XIV",
"Stun: Barrier XV",
"Stun: Barrier XVI",
"Stun: Barrier XVII",
"Stun: Barrier XVIII",
"Stun: Barrier XIX",
"Stun: Barrier XX",
"Stun: Decoy I",
"Stun: Decoy II",
"Stun: Decoy III",
"Stun: Decoy IV",
"Stun: Decoy V",
"Stun: Decoy VI",
"Stun: Decoy VII",
"Stun: Decoy VIII",
"Stun: Decoy IX",
"Stun: Decoy X",
"Stun: Decoy XI",
"Stun: Decoy XII",
"Stun: Decoy XIII",
"Stun: Decoy XIV",
"Stun: Decoy XV",
"Stun: Decoy XVI",
"Stun: Decoy XVII",
"Stun: Decoy XVIII",
"Stun: Decoy XIX",
"Stun: Decoy XX",
"Reflect: Physical",
"Reflect: Beam",
"Reflect: Ether",
"Reflect: Thermal",
"Reflect: Electric",
"Reflect: Gravity",
"Reflect Damage Up I",
"Reflect Damage Up II",
"Reflect Damage Up III",
"Reflect Damage Up IV",
"Reflect Damage Up V",
"Reflect Damage Up VI",
"Reflect Damage Up VII",
"Reflect Damage Up VIII",
"Reflect Damage Up IX",
"Reflect Damage Up X",
"Reflect Damage Up XI",
"Reflect Damage Up XII",
"Reflect Damage Up XIII",
"Reflect Damage Up XIV",
"Reflect Damage Up XV",
"Reflect Damage Up XVI",
"Reflect Damage Up XVII",
"Reflect Damage Up XVIII",
"Reflect Damage Up XIX",
"Reflect Damage Up XX",
"Nullify Physical Reflect I",
"Nullify Physical Reflect II",
"Nullify Physical Reflect III",
"Nullify Physical Reflect IV",
"Nullify Physical Reflect V",
"Nullify Physical Reflect VI",
"Nullify Physical Reflect VII",
"Nullify Physical Reflect VIII",
"Nullify Physical Reflect IX",
"Nullify Physical Reflect X",
"Nullify Physical Reflect XI",
"Nullify Physical Reflect XII",
"Nullify Physical Reflect XIII",
"Nullify Physical Reflect XIV",
"Nullify Physical Reflect XV",
"Nullify Physical Reflect XVI",
"Nullify Physical Reflect XVII",
"Nullify Physical Reflect XVIII",
"Nullify Physical Reflect XIX",
"Nullify Physical Reflect XX",
"Nullify Beam Reflect I",
"Nullify Beam Reflect II",
"Nullify Beam Reflect III",
"Nullify Beam Reflect IV",
"Nullify Beam Reflect V",
"Nullify Beam Reflect VI",
"Nullify Beam Reflect VII",
"Nullify Beam Reflect VIII",
"Nullify Beam Reflect IX",
"Nullify Beam Reflect X",
"Nullify Beam Reflect XI",
"Nullify Beam Reflect XII",
"Nullify Beam Reflect XIII",
"Nullify Beam Reflect XIV",
"Nullify Beam Reflect XV",
"Nullify Beam Reflect XVI",
"Nullify Beam Reflect XVII",
"Nullify Beam Reflect XVIII",
"Nullify Beam Reflect XIX",
"Nullify Beam Reflect XX",
"Nullify Ether Reflect I",
"Nullify Ether Reflect II",
"Nullify Ether Reflect III",
"Nullify Ether Reflect IV",
"Nullify Ether Reflect V",
"Nullify Ether Reflect VI",
"Nullify Ether Reflect VII",
"Nullify Ether Reflect VIII",
"Nullify Ether Reflect IX",
"Nullify Ether Reflect X",
"Nullify Ether Reflect XI",
"Nullify Ether Reflect XII",
"Nullify Ether Reflect XIII",
"Nullify Ether Reflect XIV",
"Nullify Ether Reflect XV",
"Nullify Ether Reflect XVI",
"Nullify Ether Reflect XVII",
"Nullify Ether Reflect XVIII",
"Nullify Ether Reflect XIX",
"Nullify Ether Reflect XX",
"Nullify Thermal Reflect I",
"Nullify Thermal Reflect II",
"Nullify Thermal Reflect III",
"Nullify Thermal Reflect IV",
"Nullify Thermal Reflect V",
"Nullify Thermal Reflect VI",
"Nullify Thermal Reflect VII",
"Nullify Thermal Reflect VIII",
"Nullify Thermal Reflect IX",
"Nullify Thermal Reflect X",
"Nullify Thermal Reflect XI",
"Nullify Thermal Reflect XII",
"Nullify Thermal Reflect XIII",
"Nullify Thermal Reflect XIV",
"Nullify Thermal Reflect XV",
"Nullify Thermal Reflect XVI",
"Nullify Thermal Reflect XVII",
"Nullify Thermal Reflect XVIII",
"Nullify Thermal Reflect XIX",
"Nullify Thermal Reflect XX",
"Nullify Electric Reflect I",
"Nullify Electric Reflect II",
"Nullify Electric Reflect III",
"Nullify Electric Reflect IV",
"Nullify Electric Reflect V",
"Nullify Electric Reflect VI",
"Nullify Electric Reflect VII",
"Nullify Electric Reflect VIII",
"Nullify Electric Reflect IX",
"Nullify Electric Reflect X",
"Nullify Electric Reflect XI",
"Nullify Electric Reflect XII",
"Nullify Electric Reflect XIII",
"Nullify Electric Reflect XIV",
"Nullify Electric Reflect XV",
"Nullify Electric Reflect XVI",
"Nullify Electric Reflect XVII",
"Nullify Electric Reflect XVIII",
"Nullify Electric Reflect XIX",
"Nullify Electric Reflect XX",
"Nullify Gravity Reflect I",
"Nullify Gravity Reflect II",
"Nullify Gravity Reflect III",
"Nullify Gravity Reflect IV",
"Nullify Gravity Reflect V",
"Nullify Gravity Reflect VI",
"Nullify Gravity Reflect VII",
"Nullify Gravity Reflect VIII",
"Nullify Gravity Reflect IX",
"Nullify Gravity Reflect X",
"Nullify Gravity Reflect XI",
"Nullify Gravity Reflect XII",
"Nullify Gravity Reflect XIII",
"Nullify Gravity Reflect XIV",
"Nullify Gravity Reflect XV",
"Nullify Gravity Reflect XVI",
"Nullify Gravity Reflect XVII",
"Nullify Gravity Reflect XVIII",
"Nullify Gravity Reflect XIX",
"Nullify Gravity Reflect XX",
"Overdrive: Recover HP I",
"Overdrive: Recover HP II",
"Overdrive: Recover HP III",
"Overdrive: Recover HP IV",
"Overdrive: Recover HP V",
"Overdrive: Recover HP VI",
"Overdrive: Recover HP VII",
"Overdrive: Recover HP VIII",
"Overdrive: Recover HP IX",
"Overdrive: Recover HP X",
"Overdrive: Recover HP XI",
"Overdrive: Recover HP XII",
"Overdrive: Recover HP XIII",
"Overdrive: Recover HP XIV",
"Overdrive: Recover HP XV",
"Overdrive: Recover HP XVI",
"Overdrive: Recover HP XVII",
"Overdrive: Recover HP XVIII",
"Overdrive: Recover HP XIX",
"Overdrive: Recover HP XX",
"Overdrive: Gain TP I",
"Overdrive: Gain TP II",
"Overdrive: Gain TP III",
"Overdrive: Gain TP IV",
"Overdrive: Gain TP V",
"Overdrive: Gain TP VI",
"Overdrive: Gain TP VII",
"Overdrive: Gain TP VIII",
"Overdrive: Gain TP IX",
"Overdrive: Gain TP X",
"Overdrive: Gain TP XI",
"Overdrive: Gain TP XII",
"Overdrive: Gain TP XIII",
"Overdrive: Gain TP XIV",
"Overdrive: Gain TP XV",
"Overdrive: Gain TP XVI",
"Overdrive: Gain TP XVII",
"Overdrive: Gain TP XVIII",
"Overdrive: Gain TP XIX",
"Overdrive: Gain TP XX",
"Overdrive Count Up I",
"Overdrive Count Up II",
"Overdrive Count Up III",
"Overdrive Count Up IV",
"Overdrive Count Up V",
"Overdrive Count Up VI",
"Overdrive Count Up VII",
"Overdrive Count Up VIII",
"Overdrive Count Up IX",
"Overdrive Count Up X",
"Overdrive Count Up XI",
"Overdrive Count Up XII",
"Overdrive Count Up XIII",
"Overdrive Count Up XIV",
"Overdrive Count Up XV",
"Overdrive Count Up XVI",
"Overdrive Count Up XVII",
"Overdrive Count Up XVIII",
"Overdrive Count Up XIX",
"Overdrive Count Up XX",
"Extend Overdrive I",
"Extend Overdrive II",
"Extend Overdrive III",
"Extend Overdrive IV",
"Extend Overdrive V",
"Extend Overdrive VI",
"Extend Overdrive VII",
"Extend Overdrive VIII",
"Extend Overdrive IX",
"Extend Overdrive X",
"Extend Overdrive XI",
"Extend Overdrive XII",
"Extend Overdrive XIII",
"Extend Overdrive XIV",
"Extend Overdrive XV",
"Extend Overdrive XVI",
"Extend Overdrive XVII",
"Extend Overdrive XVIII",
"Extend Overdrive XIX",
"Extend Overdrive XX",
"Overdrive Blue Bonus",
"Overdrive Green Bonus",
"Extend Aura I",
"Extend Aura II",
"Extend Aura III",
"Extend Aura IV",
"Extend Aura V",
"Extend Aura VI",
"Extend Aura VII",
"Extend Aura VIII",
"Extend Aura IX",
"Extend Aura X",
"Extend Aura XI",
"Extend Aura XII",
"Extend Aura XIII",
"Extend Aura XIV",
"Extend Aura XV",
"Extend Aura XVI",
"Extend Aura XVII",
"Extend Aura XVIII",
"Extend Aura XIX",
"Extend Aura XX",
"Aura Rapid Cooldown I",
"Aura Rapid Cooldown II",
"Aura Rapid Cooldown III",
"Aura Rapid Cooldown IV",
"Aura Rapid Cooldown V",
"Aura Rapid Cooldown VI",
"Aura Rapid Cooldown VII",
"Aura Rapid Cooldown VIII",
"Aura Rapid Cooldown IX",
"Aura Rapid Cooldown X",
"Aura Rapid Cooldown XI",
"Aura Rapid Cooldown XII",
"Aura Rapid Cooldown XIII",
"Aura Rapid Cooldown XIV",
"Aura Rapid Cooldown XV",
"Aura Rapid Cooldown XVI",
"Aura Rapid Cooldown XVII",
"Aura Rapid Cooldown XVIII",
"Aura Rapid Cooldown XIX",
"Aura Rapid Cooldown XX",
"Aura: Refuel I",
"Aura: Refuel II",
"Aura: Refuel III",
"Aura: Refuel IV",
"Aura: Refuel V",
"Aura: Refuel VI",
"Aura: Refuel VII",
"Aura: Refuel VIII",
"Aura: Refuel IX",
"Aura: Refuel X",
"Aura: Refuel XI",
"Aura: Refuel XII",
"Aura: Refuel XIII",
"Aura: Refuel XIV",
"Aura: Refuel XV",
"Aura: Refuel XVI",
"Aura: Refuel XVII",
"Aura: Refuel XVIII",
"Aura: Refuel XIX",
"Aura: Refuel XX",
"Arts: Gain TP I",
"Arts: Gain TP II",
"Arts: Gain TP III",
"Arts: Gain TP IV",
"Arts: Gain TP V",
"Arts: Gain TP VI",
"Arts: Gain TP VII",
"Arts: Gain TP VIII",
"Arts: Gain TP IX",
"Arts: Gain TP X",
"Arts: Gain TP XI",
"Arts: Gain TP XII",
"Arts: Gain TP XIII",
"Arts: Gain TP XIV",
"Arts: Gain TP XV",
"Arts: Gain TP XVI",
"Arts: Gain TP XVII",
"Arts: Gain TP XVIII",
"Arts: Gain TP XIX",
"Arts: Gain TP XX",
"Arts: Recover HP I",
"Arts: Recover HP II",
"Arts: Recover HP III",
"Arts: Recover HP IV",
"Arts: Recover HP V",
"Arts: Recover HP VI",
"Arts: Recover HP VII",
"Arts: Recover HP VIII",
"Arts: Recover HP IX",
"Arts: Recover HP X",
"Arts: Recover HP XI",
"Arts: Recover HP XII",
"Arts: Recover HP XIII",
"Arts: Recover HP XIV",
"Arts: Recover HP XV",
"Arts: Recover HP XVI",
"Arts: Recover HP XVII",
"Arts: Recover HP XVIII",
"Arts: Recover HP XIX",
"Arts: Recover HP XX",
"Secondary CD Reducer I",
"Secondary CD Reducer II",
"Secondary CD Reducer III",
"Secondary CD Reducer IV",
"Secondary CD Reducer V",
"Secondary CD Reducer VI",
"Secondary CD Reducer VII",
"Secondary CD Reducer VIII",
"Secondary CD Reducer IX",
"Secondary CD Reducer X",
"Secondary CD Reducer XI",
"Secondary CD Reducer XII",
"Secondary CD Reducer XIII",
"Secondary CD Reducer XIV",
"Secondary CD Reducer XV",
"Secondary CD Reducer XVI",
"Secondary CD Reducer XVII",
"Secondary CD Reducer XVIII",
"Secondary CD Reducer XIX",
"Secondary CD Reducer XX",
"Extend Taunt I",
"Extend Taunt II",
"Extend Taunt III",
"Extend Taunt IV",
"Extend Taunt V",
"Extend Taunt VI",
"Extend Taunt VII",
"Extend Taunt VIII",
"Extend Taunt IX",
"Extend Taunt X",
"Extend Taunt XI",
"Extend Taunt XII",
"Extend Taunt XIII",
"Extend Taunt XIV",
"Extend Taunt XV",
"Extend Taunt XVI",
"Extend Taunt XVII",
"Extend Taunt XVIII",
"Extend Taunt XIX",
"Extend Taunt XX",
"Extend Control I",
"Extend Control II",
"Extend Control III",
"Extend Control IV",
"Extend Control V",
"Extend Control VI",
"Extend Control VII",
"Extend Control VIII",
"Extend Control IX",
"Extend Control X",
"Extend Control XI",
"Extend Control XII",
"Extend Control XIII",
"Extend Control XIV",
"Extend Control XV",
"Extend Control XVI",
"Extend Control XVII",
"Extend Control XVIII",
"Extend Control XIX",
"Extend Control XX",
"Extend Virus I",
"Extend Virus II",
"Extend Virus III",
"Extend Virus IV",
"Extend Virus V",
"Extend Virus VI",
"Extend Virus VII",
"Extend Virus VIII",
"Extend Virus IX",
"Extend Virus X",
"Extend Virus XI",
"Extend Virus XII",
"Extend Virus XIII",
"Extend Virus XIV",
"Extend Virus XV",
"Extend Virus XVI",
"Extend Virus XVII",
"Extend Virus XVIII",
"Extend Virus XIX",
"Extend Virus XX",
"Extend Blackout I",
"Extend Blackout II",
"Extend Blackout III",
"Extend Blackout IV",
"Extend Blackout V",
"Extend Blackout VI",
"Extend Blackout VII",
"Extend Blackout VIII",
"Extend Blackout IX",
"Extend Blackout X",
"Extend Blackout XI",
"Extend Blackout XII",
"Extend Blackout XIII",
"Extend Blackout XIV",
"Extend Blackout XV",
"Extend Blackout XVI",
"Extend Blackout XVII",
"Extend Blackout XVIII",
"Extend Blackout XIX",
"Extend Blackout XX",
"Extend Fatigue I",
"Extend Fatigue II",
"Extend Fatigue III",
"Extend Fatigue IV",
"Extend Fatigue V",
"Extend Fatigue VI",
"Extend Fatigue VII",
"Extend Fatigue VIII",
"Extend Fatigue IX",
"Extend Fatigue X",
"Extend Fatigue XI",
"Extend Fatigue XII",
"Extend Fatigue XIII",
"Extend Fatigue XIV",
"Extend Fatigue XV",
"Extend Fatigue XVI",
"Extend Fatigue XVII",
"Extend Fatigue XVIII",
"Extend Fatigue XIX",
"Extend Fatigue XX",
"Extend Slow Arts I",
"Extend Slow Arts II",
"Extend Slow Arts III",
"Extend Slow Arts IV",
"Extend Slow Arts V",
"Extend Slow Arts VI",
"Extend Slow Arts VII",
"Extend Slow Arts VIII",
"Extend Slow Arts IX",
"Extend Slow Arts X",
"Extend Slow Arts XI",
"Extend Slow Arts XII",
"Extend Slow Arts XIII",
"Extend Slow Arts XIV",
"Extend Slow Arts XV",
"Extend Slow Arts XVI",
"Extend Slow Arts XVII",
"Extend Slow Arts XVIII",
"Extend Slow Arts XIX",
"Extend Slow Arts XX",
"Extend Debuff Res Down I",
"Extend Debuff Res Down II",
"Extend Debuff Res Down III",
"Extend Debuff Res Down IV",
"Extend Debuff Res Down V",
"Extend Debuff Res Down VI",
"Extend Debuff Res Down VII",
"Extend Debuff Res Down VIII",
"Extend Debuff Res Down IX",
"Extend Debuff Res Down X",
"Extend Debuff Res Down XI",
"Extend Debuff Res Down XII",
"Extend Debuff Res Down XIII",
"Extend Debuff Res Down XIV",
"Extend Debuff Res Down XV",
"Extend Debuff Res Down XVI",
"Extend Debuff Res Down XVII",
"Extend Debuff Res Down XVIII",
"Extend Debuff Res Down XIX",
"Extend Debuff Res Down XX",
"ITM_SKL_IN_TIME_EX_HPDN01_name",
"ITM_SKL_IN_TIME_EX_HPDN02_name",
"ITM_SKL_IN_TIME_EX_HPDN03_name",
"ITM_SKL_IN_TIME_EX_HPDN04_name",
"ITM_SKL_IN_TIME_EX_HPDN05_name",
"ITM_SKL_IN_TIME_EX_HPDN06_name",
"ITM_SKL_IN_TIME_EX_HPDN07_name",
"ITM_SKL_IN_TIME_EX_HPDN08_name",
"ITM_SKL_IN_TIME_EX_HPDN09_name",
"ITM_SKL_IN_TIME_EX_HPDN10_name",
"ITM_SKL_IN_TIME_EX_HPDN11_name",
"ITM_SKL_IN_TIME_EX_HPDN12_name",
"ITM_SKL_IN_TIME_EX_HPDN13_name",
"ITM_SKL_IN_TIME_EX_HPDN14_name",
"ITM_SKL_IN_TIME_EX_HPDN15_name",
"ITM_SKL_IN_TIME_EX_HPDN16_name",
"ITM_SKL_IN_TIME_EX_HPDN17_name",
"ITM_SKL_IN_TIME_EX_HPDN18_name",
"ITM_SKL_IN_TIME_EX_HPDN19_name",
"ITM_SKL_IN_TIME_EX_HPDN20_name",
"Extend Blaze I",
"Extend Blaze II",
"Extend Blaze III",
"Extend Blaze IV",
"Extend Blaze V",
"Extend Blaze VI",
"Extend Blaze VII",
"Extend Blaze VIII",
"Extend Blaze IX",
"Extend Blaze X",
"Extend Blaze XI",
"Extend Blaze XII",
"Extend Blaze XIII",
"Extend Blaze XIV",
"Extend Blaze XV",
"Extend Blaze XVI",
"Extend Blaze XVII",
"Extend Blaze XVIII",
"Extend Blaze XIX",
"Extend Blaze XX",
"Extend Shock I",
"Extend Shock II",
"Extend Shock III",
"Extend Shock IV",
"Extend Shock V",
"Extend Shock VI",
"Extend Shock VII",
"Extend Shock VIII",
"Extend Shock IX",
"Extend Shock X",
"Extend Shock XI",
"Extend Shock XII",
"Extend Shock XIII",
"Extend Shock XIV",
"Extend Shock XV",
"Extend Shock XVI",
"Extend Shock XVII",
"Extend Shock XVIII",
"Extend Shock XIX",
"Extend Shock XX",
"Extend Physical Res Down I",
"Extend Physical Res Down II",
"Extend Physical Res Down III",
"Extend Physical Res Down IV",
"Extend Physical Res Down V",
"Extend Physical Res Down VI",
"Extend Physical Res Down VII",
"Extend Physical Res Down VIII",
"Extend Physical Res Down IX",
"Extend Physical Res Down X",
"Extend Physical Res Down XI",
"Extend Physical Res Down XII",
"Extend Physical Res Down XIII",
"Extend Physical Res Down XIV",
"Extend Physical Res Down XV",
"Extend Physical Res Down XVI",
"Extend Physical Res Down XVII",
"Extend Physical Res Down XVIII",
"Extend Physical Res Down XIX",
"Extend Physical Res Down XX",
"Extend Beam Res Down I",
"Extend Beam Res Down II",
"Extend Beam Res Down III",
"Extend Beam Res Down IV",
"Extend Beam Res Down V",
"Extend Beam Res Down VI",
"Extend Beam Res Down VII",
"Extend Beam Res Down VIII",
"Extend Beam Res Down IX",
"Extend Beam Res Down X",
"Extend Beam Res Down XI",
"Extend Beam Res Down XII",
"Extend Beam Res Down XIII",
"Extend Beam Res Down XIV",
"Extend Beam Res Down XV",
"Extend Beam Res Down XVI",
"Extend Beam Res Down XVII",
"Extend Beam Res Down XVIII",
"Extend Beam Res Down XIX",
"Extend Beam Res Down XX",
"Extend Ether Res Down I",
"Extend Ether Res Down II",
"Extend Ether Res Down III",
"Extend Ether Res Down IV",
"Extend Ether Res Down V",
"Extend Ether Res Down VI",
"Extend Ether Res Down VII",
"Extend Ether Res Down VIII",
"Extend Ether Res Down IX",
"Extend Ether Res Down X",
"Extend Ether Res Down XI",
"Extend Ether Res Down XII",
"Extend Ether Res Down XIII",
"Extend Ether Res Down XIV",
"Extend Ether Res Down XV",
"Extend Ether Res Down XVI",
"Extend Ether Res Down XVII",
"Extend Ether Res Down XVIII",
"Extend Ether Res Down XIX",
"Extend Ether Res Down XX",
"Extend Thermal Res Down I",
"Extend Thermal Res Down II",
"Extend Thermal Res Down III",
"Extend Thermal Res Down IV",
"Extend Thermal Res Down V",
"Extend Thermal Res Down VI",
"Extend Thermal Res Down VII",
"Extend Thermal Res Down VIII",
"Extend Thermal Res Down IX",
"Extend Thermal Res Down X",
"Extend Thermal Res Down XI",
"Extend Thermal Res Down XII",
"Extend Thermal Res Down XIII",
"Extend Thermal Res Down XIV",
"Extend Thermal Res Down XV",
"Extend Thermal Res Down XVI",
"Extend Thermal Res Down XVII",
"Extend Thermal Res Down XVIII",
"Extend Thermal Res Down XIX",
"Extend Thermal Res Down XX",
"Extend Electric Res Down I",
"Extend Electric Res Down II",
"Extend Electric Res Down III",
"Extend Electric Res Down IV",
"Extend Electric Res Down V",
"Extend Electric Res Down VI",
"Extend Electric Res Down VII",
"Extend Electric Res Down VIII",
"Extend Electric Res Down IX",
"Extend Electric Res Down X",
"Extend Electric Res Down XI",
"Extend Electric Res Down XII",
"Extend Electric Res Down XIII",
"Extend Electric Res Down XIV",
"Extend Electric Res Down XV",
"Extend Electric Res Down XVI",
"Extend Electric Res Down XVII",
"Extend Electric Res Down XVIII",
"Extend Electric Res Down XIX",
"Extend Electric Res Down XX",
"Extend Gravity Res Down I",
"Extend Gravity Res Down II",
"Extend Gravity Res Down III",
"Extend Gravity Res Down IV",
"Extend Gravity Res Down V",
"Extend Gravity Res Down VI",
"Extend Gravity Res Down VII",
"Extend Gravity Res Down VIII",
"Extend Gravity Res Down IX",
"Extend Gravity Res Down X",
"Extend Gravity Res Down XI",
"Extend Gravity Res Down XII",
"Extend Gravity Res Down XIII",
"Extend Gravity Res Down XIV",
"Extend Gravity Res Down XV",
"Extend Gravity Res Down XVI",
"Extend Gravity Res Down XVII",
"Extend Gravity Res Down XVIII",
"Extend Gravity Res Down XIX",
"Extend Gravity Res Down XX",
"ITM_SKL_IN_FST_TP01_name",
"ITM_SKL_IN_FST_TP02_name",
"ITM_SKL_IN_FST_TP03_name",
"ITM_SKL_IN_FST_TP04_name",
"ITM_SKL_IN_FST_TP05_name",
"ITM_SKL_IN_FST_TP06_name",
"ITM_SKL_IN_FST_TP07_name",
"ITM_SKL_IN_FST_TP08_name",
"ITM_SKL_IN_FST_TP09_name",
"ITM_SKL_IN_FST_TP10_name",
"ITM_SKL_IN_FST_TP11_name",
"ITM_SKL_IN_FST_TP12_name",
"ITM_SKL_IN_FST_TP13_name",
"ITM_SKL_IN_FST_TP14_name",
"ITM_SKL_IN_FST_TP15_name",
"ITM_SKL_IN_FST_TP16_name",
"ITM_SKL_IN_FST_TP17_name",
"ITM_SKL_IN_FST_TP18_name",
"ITM_SKL_IN_FST_TP19_name",
"ITM_SKL_IN_FST_TP20_name",
"Opening Art: Damage Up I",
"Opening Art: Damage Up II",
"Opening Art: Damage Up III",
"Opening Art: Damage Up IV",
"Opening Art: Damage Up V",
"Opening Art: Damage Up VI",
"Opening Art: Damage Up VII",
"Opening Art: Damage Up VIII",
"Opening Art: Damage Up IX",
"Opening Art: Damage Up X",
"Opening Art: Damage Up XI",
"Opening Art: Damage Up XII",
"Opening Art: Damage Up XIII",
"Opening Art: Damage Up XIV",
"Opening Art: Damage Up XV",
"Opening Art: Damage Up XVI",
"Opening Art: Damage Up XVII",
"Opening Art: Damage Up XVIII",
"Opening Art: Damage Up XIX",
"Opening Art: Damage Up XX",
"ITM_SKL_IN_FST_CRTC01_name",
"ITM_SKL_IN_FST_CRTC02_name",
"ITM_SKL_IN_FST_CRTC03_name",
"ITM_SKL_IN_FST_CRTC04_name",
"ITM_SKL_IN_FST_CRTC05_name",
"ITM_SKL_IN_FST_CRTC06_name",
"ITM_SKL_IN_FST_CRTC07_name",
"ITM_SKL_IN_FST_CRTC08_name",
"ITM_SKL_IN_FST_CRTC09_name",
"ITM_SKL_IN_FST_CRTC10_name",
"ITM_SKL_IN_FST_CRTC11_name",
"ITM_SKL_IN_FST_CRTC12_name",
"ITM_SKL_IN_FST_CRTC13_name",
"ITM_SKL_IN_FST_CRTC14_name",
"ITM_SKL_IN_FST_CRTC15_name",
"ITM_SKL_IN_FST_CRTC16_name",
"ITM_SKL_IN_FST_CRTC17_name",
"ITM_SKL_IN_FST_CRTC18_name",
"ITM_SKL_IN_FST_CRTC19_name",
"ITM_SKL_IN_FST_CRTC20_name",
"ITM_SKL_IN_FST_FDEX01_name",
"ITM_SKL_IN_FST_FDEX02_name",
"ITM_SKL_IN_FST_FDEX03_name",
"ITM_SKL_IN_FST_FDEX04_name",
"ITM_SKL_IN_FST_FDEX05_name",
"ITM_SKL_IN_FST_FDEX06_name",
"ITM_SKL_IN_FST_FDEX07_name",
"ITM_SKL_IN_FST_FDEX08_name",
"ITM_SKL_IN_FST_FDEX09_name",
"ITM_SKL_IN_FST_FDEX10_name",
"ITM_SKL_IN_FST_FDEX11_name",
"ITM_SKL_IN_FST_FDEX12_name",
"ITM_SKL_IN_FST_FDEX13_name",
"ITM_SKL_IN_FST_FDEX14_name",
"ITM_SKL_IN_FST_FDEX15_name",
"ITM_SKL_IN_FST_FDEX16_name",
"ITM_SKL_IN_FST_FDEX17_name",
"ITM_SKL_IN_FST_FDEX18_name",
"ITM_SKL_IN_FST_FDEX19_name",
"ITM_SKL_IN_FST_FDEX20_name",
"ITM_SKL_IN_FST_SDEX01_name",
"ITM_SKL_IN_FST_SDEX02_name",
"ITM_SKL_IN_FST_SDEX03_name",
"ITM_SKL_IN_FST_SDEX04_name",
"ITM_SKL_IN_FST_SDEX05_name",
"ITM_SKL_IN_FST_SDEX06_name",
"ITM_SKL_IN_FST_SDEX07_name",
"ITM_SKL_IN_FST_SDEX08_name",
"ITM_SKL_IN_FST_SDEX09_name",
"ITM_SKL_IN_FST_SDEX10_name",
"ITM_SKL_IN_FST_SDEX11_name",
"ITM_SKL_IN_FST_SDEX12_name",
"ITM_SKL_IN_FST_SDEX13_name",
"ITM_SKL_IN_FST_SDEX14_name",
"ITM_SKL_IN_FST_SDEX15_name",
"ITM_SKL_IN_FST_SDEX16_name",
"ITM_SKL_IN_FST_SDEX17_name",
"ITM_SKL_IN_FST_SDEX18_name",
"ITM_SKL_IN_FST_SDEX19_name",
"ITM_SKL_IN_FST_SDEX20_name",
"ITM_SKL_IN_FST_EVA01_name",
"ITM_SKL_IN_FST_EVA02_name",
"ITM_SKL_IN_FST_EVA03_name",
"ITM_SKL_IN_FST_EVA04_name",
"ITM_SKL_IN_FST_EVA05_name",
"ITM_SKL_IN_FST_EVA06_name",
"ITM_SKL_IN_FST_EVA07_name",
"ITM_SKL_IN_FST_EVA08_name",
"ITM_SKL_IN_FST_EVA09_name",
"ITM_SKL_IN_FST_EVA10_name",
"ITM_SKL_IN_FST_EVA11_name",
"ITM_SKL_IN_FST_EVA12_name",
"ITM_SKL_IN_FST_EVA13_name",
"ITM_SKL_IN_FST_EVA14_name",
"ITM_SKL_IN_FST_EVA15_name",
"ITM_SKL_IN_FST_EVA16_name",
"ITM_SKL_IN_FST_EVA17_name",
"ITM_SKL_IN_FST_EVA18_name",
"ITM_SKL_IN_FST_EVA19_name",
"ITM_SKL_IN_FST_EVA20_name",
"ITM_SKL_IN_FST_FPOW01_name",
"ITM_SKL_IN_FST_FPOW02_name",
"ITM_SKL_IN_FST_FPOW03_name",
"ITM_SKL_IN_FST_FPOW04_name",
"ITM_SKL_IN_FST_FPOW05_name",
"ITM_SKL_IN_FST_FPOW06_name",
"ITM_SKL_IN_FST_FPOW07_name",
"ITM_SKL_IN_FST_FPOW08_name",
"ITM_SKL_IN_FST_FPOW09_name",
"ITM_SKL_IN_FST_FPOW10_name",
"ITM_SKL_IN_FST_FPOW11_name",
"ITM_SKL_IN_FST_FPOW12_name",
"ITM_SKL_IN_FST_FPOW13_name",
"ITM_SKL_IN_FST_FPOW14_name",
"ITM_SKL_IN_FST_FPOW15_name",
"ITM_SKL_IN_FST_FPOW16_name",
"ITM_SKL_IN_FST_FPOW17_name",
"ITM_SKL_IN_FST_FPOW18_name",
"ITM_SKL_IN_FST_FPOW19_name",
"ITM_SKL_IN_FST_FPOW20_name",
"ITM_SKL_IN_FST_SPOW01_name",
"ITM_SKL_IN_FST_SPOW02_name",
"ITM_SKL_IN_FST_SPOW03_name",
"ITM_SKL_IN_FST_SPOW04_name",
"ITM_SKL_IN_FST_SPOW05_name",
"ITM_SKL_IN_FST_SPOW06_name",
"ITM_SKL_IN_FST_SPOW07_name",
"ITM_SKL_IN_FST_SPOW08_name",
"ITM_SKL_IN_FST_SPOW09_name",
"ITM_SKL_IN_FST_SPOW10_name",
"ITM_SKL_IN_FST_SPOW11_name",
"ITM_SKL_IN_FST_SPOW12_name",
"ITM_SKL_IN_FST_SPOW13_name",
"ITM_SKL_IN_FST_SPOW14_name",
"ITM_SKL_IN_FST_SPOW15_name",
"ITM_SKL_IN_FST_SPOW16_name",
"ITM_SKL_IN_FST_SPOW17_name",
"ITM_SKL_IN_FST_SPOW18_name",
"ITM_SKL_IN_FST_SPOW19_name",
"ITM_SKL_IN_FST_SPOW20_name",
"ITM_SKL_IN_FST_MIND01_name",
"ITM_SKL_IN_FST_MIND02_name",
"ITM_SKL_IN_FST_MIND03_name",
"ITM_SKL_IN_FST_MIND04_name",
"ITM_SKL_IN_FST_MIND05_name",
"ITM_SKL_IN_FST_MIND06_name",
"ITM_SKL_IN_FST_MIND07_name",
"ITM_SKL_IN_FST_MIND08_name",
"ITM_SKL_IN_FST_MIND09_name",
"ITM_SKL_IN_FST_MIND10_name",
"ITM_SKL_IN_FST_MIND11_name",
"ITM_SKL_IN_FST_MIND12_name",
"ITM_SKL_IN_FST_MIND13_name",
"ITM_SKL_IN_FST_MIND14_name",
"ITM_SKL_IN_FST_MIND15_name",
"ITM_SKL_IN_FST_MIND16_name",
"ITM_SKL_IN_FST_MIND17_name",
"ITM_SKL_IN_FST_MIND18_name",
"ITM_SKL_IN_FST_MIND19_name",
"ITM_SKL_IN_FST_MIND20_name",
"ITM_SKL_IN_FST_DARM01_name",
"ITM_SKL_IN_FST_DARM02_name",
"ITM_SKL_IN_FST_DARM03_name",
"ITM_SKL_IN_FST_DARM04_name",
"ITM_SKL_IN_FST_DARM05_name",
"ITM_SKL_IN_FST_DARM06_name",
"ITM_SKL_IN_FST_DARM07_name",
"ITM_SKL_IN_FST_DARM08_name",
"ITM_SKL_IN_FST_DARM09_name",
"ITM_SKL_IN_FST_DARM10_name",
"ITM_SKL_IN_FST_DARM11_name",
"ITM_SKL_IN_FST_DARM12_name",
"ITM_SKL_IN_FST_DARM13_name",
"ITM_SKL_IN_FST_DARM14_name",
"ITM_SKL_IN_FST_DARM15_name",
"ITM_SKL_IN_FST_DARM16_name",
"ITM_SKL_IN_FST_DARM17_name",
"ITM_SKL_IN_FST_DARM18_name",
"ITM_SKL_IN_FST_DARM19_name",
"ITM_SKL_IN_FST_DARM20_name",
"ITM_SKL_IN_FST_BULLET01_name",
"ITM_SKL_IN_FST_BULLET02_name",
"ITM_SKL_IN_FST_BULLET03_name",
"ITM_SKL_IN_FST_BULLET04_name",
"ITM_SKL_IN_FST_BULLET05_name",
"ITM_SKL_IN_FST_BULLET06_name",
"ITM_SKL_IN_FST_BULLET07_name",
"ITM_SKL_IN_FST_BULLET08_name",
"ITM_SKL_IN_FST_BULLET09_name",
"ITM_SKL_IN_FST_BULLET10_name",
"ITM_SKL_IN_FST_BULLET11_name",
"ITM_SKL_IN_FST_BULLET12_name",
"ITM_SKL_IN_FST_BULLET13_name",
"ITM_SKL_IN_FST_BULLET14_name",
"ITM_SKL_IN_FST_BULLET15_name",
"ITM_SKL_IN_FST_BULLET16_name",
"ITM_SKL_IN_FST_BULLET17_name",
"ITM_SKL_IN_FST_BULLET18_name",
"ITM_SKL_IN_FST_BULLET19_name",
"ITM_SKL_IN_FST_BULLET20_name",
"ITM_SKL_IN_FST_FAKE01_name",
"ITM_SKL_IN_FST_FAKE02_name",
"ITM_SKL_IN_FST_FAKE03_name",
"ITM_SKL_IN_FST_FAKE04_name",
"ITM_SKL_IN_FST_FAKE05_name",
"ITM_SKL_IN_FST_FAKE06_name",
"ITM_SKL_IN_FST_FAKE07_name",
"ITM_SKL_IN_FST_FAKE08_name",
"ITM_SKL_IN_FST_FAKE09_name",
"ITM_SKL_IN_FST_FAKE10_name",
"ITM_SKL_IN_FST_FAKE11_name",
"ITM_SKL_IN_FST_FAKE12_name",
"ITM_SKL_IN_FST_FAKE13_name",
"ITM_SKL_IN_FST_FAKE14_name",
"ITM_SKL_IN_FST_FAKE15_name",
"ITM_SKL_IN_FST_FAKE16_name",
"ITM_SKL_IN_FST_FAKE17_name",
"ITM_SKL_IN_FST_FAKE18_name",
"ITM_SKL_IN_FST_FAKE19_name",
"ITM_SKL_IN_FST_FAKE20_name",
"Melee Draw Surge I",
"Melee Draw Surge II",
"Melee Draw Surge III",
"Melee Draw Surge IV",
"Melee Draw Surge V",
"Melee Draw Surge VI",
"Melee Draw Surge VII",
"Melee Draw Surge VIII",
"Melee Draw Surge IX",
"Melee Draw Surge X",
"Melee Draw Surge XI",
"Melee Draw Surge XII",
"Melee Draw Surge XIII",
"Melee Draw Surge XIV",
"Melee Draw Surge XV",
"Melee Draw Surge XVI",
"Melee Draw Surge XVII",
"Melee Draw Surge XVIII",
"Melee Draw Surge XIX",
"Melee Draw Surge XX",
"Ranged Draw Surge I",
"Ranged Draw Surge II",
"Ranged Draw Surge III",
"Ranged Draw Surge IV",
"Ranged Draw Surge V",
"Ranged Draw Surge VI",
"Ranged Draw Surge VII",
"Ranged Draw Surge VIII",
"Ranged Draw Surge IX",
"Ranged Draw Surge X",
"Ranged Draw Surge XI",
"Ranged Draw Surge XII",
"Ranged Draw Surge XIII",
"Ranged Draw Surge XIV",
"Ranged Draw Surge XV",
"Ranged Draw Surge XVI",
"Ranged Draw Surge XVII",
"Ranged Draw Surge XVIII",
"Ranged Draw Surge XIX",
"Ranged Draw Surge XX",
"Art Draw Surge I",
"Art Draw Surge II",
"Art Draw Surge III",
"Art Draw Surge IV",
"Art Draw Surge V",
"Art Draw Surge VI",
"Art Draw Surge VII",
"Art Draw Surge VIII",
"Art Draw Surge IX",
"Art Draw Surge X",
"Art Draw Surge XI",
"Art Draw Surge XII",
"Art Draw Surge XIII",
"Art Draw Surge XIV",
"Art Draw Surge XV",
"Art Draw Surge XVI",
"Art Draw Surge XVII",
"Art Draw Surge XVIII",
"Art Draw Surge XIX",
"Art Draw Surge XX",
"Danger Surge I",
"Danger Surge II",
"Danger Surge III",
"Danger Surge IV",
"Danger Surge V",
"Danger Surge VI",
"Danger Surge VII",
"Danger Surge VIII",
"Danger Surge IX",
"Danger Surge X",
"Danger Surge XI",
"Danger Surge XII",
"Danger Surge XIII",
"Danger Surge XIV",
"Danger Surge XV",
"Danger Surge XVI",
"Danger Surge XVII",
"Danger Surge XVIII",
"Danger Surge XIX",
"Danger Surge XX",
"High Danger Surge I",
"High Danger Surge II",
"High Danger Surge III",
"High Danger Surge IV",
"High Danger Surge V",
"High Danger Surge VI",
"High Danger Surge VII",
"High Danger Surge VIII",
"High Danger Surge IX",
"High Danger Surge X",
"High Danger Surge XI",
"High Danger Surge XII",
"High Danger Surge XIII",
"High Danger Surge XIV",
"High Danger Surge XV",
"High Danger Surge XVI",
"High Danger Surge XVII",
"High Danger Surge XVIII",
"High Danger Surge XIX",
"High Danger Surge XX",
"Incapacitation Surge I",
"Incapacitation Surge II",
"Incapacitation Surge III",
"Incapacitation Surge IV",
"Incapacitation Surge V",
"Incapacitation Surge VI",
"Incapacitation Surge VII",
"Incapacitation Surge VIII",
"Incapacitation Surge IX",
"Incapacitation Surge X",
"Incapacitation Surge XI",
"Incapacitation Surge XII",
"Incapacitation Surge XIII",
"Incapacitation Surge XIV",
"Incapacitation Surge XV",
"Incapacitation Surge XVI",
"Incapacitation Surge XVII",
"Incapacitation Surge XVIII",
"Incapacitation Surge XIX",
"Incapacitation Surge XX",
"Critical Surge I",
"Critical Surge II",
"Critical Surge III",
"Critical Surge IV",
"Critical Surge V",
"Critical Surge VI",
"Critical Surge VII",
"Critical Surge VIII",
"Critical Surge IX",
"Critical Surge X",
"Critical Surge XI",
"Critical Surge XII",
"Critical Surge XIII",
"Critical Surge XIV",
"Critical Surge XV",
"Critical Surge XVI",
"Critical Surge XVII",
"Critical Surge XVIII",
"Critical Surge XIX",
"Critical Surge XX",
"Crush Surge I",
"Crush Surge II",
"Crush Surge III",
"Crush Surge IV",
"Crush Surge V",
"Crush Surge VI",
"Crush Surge VII",
"Crush Surge VIII",
"Crush Surge IX",
"Crush Surge X",
"Crush Surge XI",
"Crush Surge XII",
"Crush Surge XIII",
"Crush Surge XIV",
"Crush Surge XV",
"Crush Surge XVI",
"Crush Surge XVII",
"Crush Surge XVIII",
"Crush Surge XIX",
"Crush Surge XX",
"Underdog Surge I",
"Underdog Surge II",
"Underdog Surge III",
"Underdog Surge IV",
"Underdog Surge V",
"Underdog Surge VI",
"Underdog Surge VII",
"Underdog Surge VIII",
"Underdog Surge IX",
"Underdog Surge X",
"Underdog Surge XI",
"Underdog Surge XII",
"Underdog Surge XIII",
"Underdog Surge XIV",
"Underdog Surge XV",
"Underdog Surge XVI",
"Underdog Surge XVII",
"Underdog Surge XVIII",
"Underdog Surge XIX",
"Underdog Surge XX",
"Artful Execution Surge I",
"Artful Execution Surge II",
"Artful Execution Surge III",
"Artful Execution Surge IV",
"Artful Execution Surge V",
"Artful Execution Surge VI",
"Artful Execution Surge VII",
"Artful Execution Surge VIII",
"Artful Execution Surge IX",
"Artful Execution Surge X",
"Artful Execution Surge XI",
"Artful Execution Surge XII",
"Artful Execution Surge XIII",
"Artful Execution Surge XIV",
"Artful Execution Surge XV",
"Artful Execution Surge XVI",
"Artful Execution Surge XVII",
"Artful Execution Surge XVIII",
"Artful Execution Surge XIX",
"Artful Execution Surge XX",
"Aura Surge I",
"Aura Surge II",
"Aura Surge III",
"Aura Surge IV",
"Aura Surge V",
"Aura Surge VI",
"Aura Surge VII",
"Aura Surge VIII",
"Aura Surge IX",
"Aura Surge X",
"Aura Surge XI",
"Aura Surge XII",
"Aura Surge XIII",
"Aura Surge XIV",
"Aura Surge XV",
"Aura Surge XVI",
"Aura Surge XVII",
"Aura Surge XVIII",
"Aura Surge XIX",
"Aura Surge XX",
"Overdrive Surge I",
"Overdrive Surge II",
"Overdrive Surge III",
"Overdrive Surge IV",
"Overdrive Surge V",
"Overdrive Surge VI",
"Overdrive Surge VII",
"Overdrive Surge VIII",
"Overdrive Surge IX",
"Overdrive Surge X",
"Overdrive Surge XI",
"Overdrive Surge XII",
"Overdrive Surge XIII",
"Overdrive Surge XIV",
"Overdrive Surge XV",
"Overdrive Surge XVI",
"Overdrive Surge XVII",
"Overdrive Surge XVIII",
"Overdrive Surge XIX",
"Overdrive Surge XX",
"Reinvigorate I",
"Reinvigorate II",
"Reinvigorate III",
"Reinvigorate IV",
"Reinvigorate V",
"Reinvigorate VI",
"Reinvigorate VII",
"Reinvigorate VIII",
"Reinvigorate IX",
"Reinvigorate X",
"Reinvigorate XI",
"Reinvigorate XII",
"Reinvigorate XIII",
"Reinvigorate XIV",
"Reinvigorate XV",
"Reinvigorate XVI",
"Reinvigorate XVII",
"Reinvigorate XVIII",
"Reinvigorate XIX",
"Reinvigorate XX",
"EXP Boost I",
"EXP Boost II",
"EXP Boost III",
"EXP Boost IV",
"EXP Boost V",
"EXP Boost VI",
"EXP Boost VII",
"EXP Boost VIII",
"EXP Boost IX",
"EXP Boost X",
"EXP Boost XI",
"EXP Boost XII",
"EXP Boost XIII",
"EXP Boost XIV",
"EXP Boost XV",
"EXP Boost XVI",
"EXP Boost XVII",
"EXP Boost XVIII",
"EXP Boost XIX",
"EXP Boost XX",
"Visual Cloaking I",
"Visual Cloaking II",
"Visual Cloaking III",
"Visual Cloaking IV",
"Visual Cloaking V",
"Visual Cloaking VI",
"Visual Cloaking VII",
"Visual Cloaking VIII",
"Visual Cloaking IX",
"Visual Cloaking X",
"Visual Cloaking XI",
"Visual Cloaking XII",
"Visual Cloaking XIII",
"Visual Cloaking XIV",
"Visual Cloaking XV",
"Visual Cloaking XVI",
"Visual Cloaking XVII",
"Visual Cloaking XVIII",
"Visual Cloaking XIX",
"Visual Cloaking XX",
"Aural Cloaking I",
"Aural Cloaking II",
"Aural Cloaking III",
"Aural Cloaking IV",
"Aural Cloaking V",
"Aural Cloaking VI",
"Aural Cloaking VII",
"Aural Cloaking VIII",
"Aural Cloaking IX",
"Aural Cloaking X",
"Aural Cloaking XI",
"Aural Cloaking XII",
"Aural Cloaking XIII",
"Aural Cloaking XIV",
"Aural Cloaking XV",
"Aural Cloaking XVI",
"Aural Cloaking XVII",
"Aural Cloaking XVIII",
"Aural Cloaking XIX",
"Aural Cloaking XX",
"Appendage Crusher",
"Crush: Gain TP I",
"Crush: Gain TP II",
"Crush: Gain TP III",
"Crush: Gain TP IV",
"Crush: Gain TP V",
"Crush: Gain TP VI",
"Crush: Gain TP VII",
"Crush: Gain TP VIII",
"Crush: Gain TP IX",
"Crush: Gain TP X",
"Crush: Gain TP XI",
"Crush: Gain TP XII",
"Crush: Gain TP XIII",
"Crush: Gain TP XIV",
"Crush: Gain TP XV",
"Crush: Gain TP XVI",
"Crush: Gain TP XVII",
"Crush: Gain TP XVIII",
"Crush: Gain TP XIX",
"Crush: Gain TP XX",
"Ranged Appendage Damage I",
"Ranged Appendage Damage II",
"Ranged Appendage Damage III",
"Ranged Appendage Damage IV",
"Ranged Appendage Damage V",
"Ranged Appendage Damage VI",
"Ranged Appendage Damage VII",
"Ranged Appendage Damage VIII",
"Ranged Appendage Damage IX",
"Ranged Appendage Damage X",
"Ranged Appendage Damage XI",
"Ranged Appendage Damage XII",
"Ranged Appendage Damage XIII",
"Ranged Appendage Damage XIV",
"Ranged Appendage Damage XV",
"Ranged Appendage Damage XVI",
"Ranged Appendage Damage XVII",
"Ranged Appendage Damage XVIII",
"Ranged Appendage Damage XIX",
"Ranged Appendage Damage XX",
"Terrain Damage Reducer I",
"Terrain Damage Reducer II",
"Terrain Damage Reducer III",
"Terrain Damage Reducer IV",
"Terrain Damage Reducer V",
"Terrain Damage Reducer VI",
"Terrain Damage Reducer VII",
"Terrain Damage Reducer VIII",
"Terrain Damage Reducer IX",
"Terrain Damage Reducer X",
"Terrain Damage Reducer XI",
"Terrain Damage Reducer XII",
"Terrain Damage Reducer XIII",
"Terrain Damage Reducer XIV",
"Terrain Damage Reducer XV",
"Terrain Damage Reducer XVI",
"Terrain Damage Reducer XVII",
"Terrain Damage Reducer XVIII",
"Terrain Damage Reducer XIX",
"Terrain Damage Reducer XX",
"Antispike I",
"Antispike II",
"Antispike III",
"Antispike IV",
"Antispike V",
"Antispike VI",
"Antispike VII",
"Antispike VIII",
"Antispike IX",
"Antispike X",
"Antispike XI",
"Antispike XII",
"Antispike XIII",
"Antispike XIV",
"Antispike XV",
"Antispike XVI",
"Antispike XVII",
"Antispike XVIII",
"Antispike XIX",
"Antispike XX",
"Resistance Reducer I",
"Resistance Reducer II",
"Resistance Reducer III",
"Resistance Reducer IV",
"Resistance Reducer V",
"Resistance Reducer VI",
"Resistance Reducer VII",
"Resistance Reducer VIII",
"Resistance Reducer IX",
"Resistance Reducer X",
"Resistance Reducer XI",
"Resistance Reducer XII",
"Resistance Reducer XIII",
"Resistance Reducer XIV",
"Resistance Reducer XV",
"Resistance Reducer XVI",
"Resistance Reducer XVII",
"Resistance Reducer XVIII",
"Resistance Reducer XIX",
"Resistance Reducer XX",
"Treasure Sensor I",
"Treasure Sensor II",
"Treasure Sensor III",
"Treasure Sensor IV",
"Treasure Sensor V",
"Treasure Sensor VI",
"Treasure Sensor VII",
"Treasure Sensor VIII",
"Treasure Sensor IX",
"Treasure Sensor X",
"Treasure Sensor XI",
"Treasure Sensor XII",
"Treasure Sensor XIII",
"Treasure Sensor XIV",
"Treasure Sensor XV",
"Treasure Sensor XVI",
"Treasure Sensor XVII",
"Treasure Sensor XVIII",
"Treasure Sensor XIX",
"Treasure Sensor XX",
"Untouchable Dash I",
"Untouchable Dash II",
"Untouchable Dash III",
"Untouchable Dash IV",
"Untouchable Dash V",
"Untouchable Dash VI",
"Untouchable Dash VII",
"Untouchable Dash VIII",
"Untouchable Dash IX",
"Untouchable Dash X",
"Untouchable Dash XI",
"Untouchable Dash XII",
"Untouchable Dash XIII",
"Untouchable Dash XIV",
"Untouchable Dash XV",
"Untouchable Dash XVI",
"Untouchable Dash XVII",
"Untouchable Dash XVIII",
"Untouchable Dash XIX",
"Untouchable Dash XX",
"ITM_SKL_IN_HERO_RIDE01_name",
"ITM_SKL_IN_HERO_RIDE02_name",
"ITM_SKL_IN_HERO_RIDE03_name",
"ITM_SKL_IN_HERO_RIDE04_name",
"ITM_SKL_IN_HERO_RIDE05_name",
"ITM_SKL_IN_HERO_RIDE06_name",
"ITM_SKL_IN_HERO_RIDE07_name",
"ITM_SKL_IN_HERO_RIDE08_name",
"ITM_SKL_IN_HERO_RIDE09_name",
"ITM_SKL_IN_HERO_RIDE10_name",
"ITM_SKL_IN_HERO_RIDE11_name",
"ITM_SKL_IN_HERO_RIDE12_name",
"ITM_SKL_IN_HERO_RIDE13_name",
"ITM_SKL_IN_HERO_RIDE14_name",
"ITM_SKL_IN_HERO_RIDE15_name",
"ITM_SKL_IN_HERO_RIDE16_name",
"ITM_SKL_IN_HERO_RIDE17_name",
"ITM_SKL_IN_HERO_RIDE18_name",
"ITM_SKL_IN_HERO_RIDE19_name",
"ITM_SKL_IN_HERO_RIDE20_name",
"Night Vision I",
"Night Vision II",
"Night Vision III",
"Night Vision IV",
"Night Vision V",
"Night Vision VI",
"Night Vision VII",
"Night Vision VIII",
"Night Vision IX",
"Night Vision X",
"Night Vision XI",
"Night Vision XII",
"Night Vision XIII",
"Night Vision XIV",
"Night Vision XV",
"Night Vision XVI",
"Night Vision XVII",
"Night Vision XVIII",
"Night Vision XIX",
"Night Vision XX",
"Focused Evasion I",
"Focused Evasion II",
"Focused Evasion III",
"Focused Evasion IV",
"Focused Evasion V",
"Focused Evasion VI",
"Focused Evasion VII",
"Focused Evasion VIII",
"Focused Evasion IX",
"Focused Evasion X",
"Focused Evasion XI",
"Focused Evasion XII",
"Focused Evasion XIII",
"Focused Evasion XIV",
"Focused Evasion XV",
"Focused Evasion XVI",
"Focused Evasion XVII",
"Focused Evasion XVIII",
"Focused Evasion XIX",
"Focused Evasion XX",
"Fog Screen",
"Rain Screen",
"Lightning Screen",
"Heavy Rain Screen",
"Heat Wave Screen",
"Sandstorm Screen",
"Thunderstorm Screen",
"EM Storm Screen",
"Energy Mist Screen",
"Rising Energy Mist Screen",
"Brimstone Rain Screen",
"Aurora Screen",
"Crimson Aurora Screen",
"Spore Screen",
"Meteor Shower Screen",
"Weather Master I",
"Weather Master II",
"Weather Master III",
"Weather Master IV",
"Weather Master V",
"Weather Master VI",
"Weather Master VII",
"Weather Master VIII",
"Weather Master IX",
"Weather Master X",
"Weather Master XI",
"Weather Master XII",
"Weather Master XIII",
"Weather Master XIV",
"Weather Master XV",
"Weather Master XVI",
"Weather Master XVII",
"Weather Master XVIII",
"Weather Master XIX",
"Weather Master XX",
]