from ..Items import Itm as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/ITM_PreciousList.html
# flake8: noqa
important_items_data: list[Data] = [
Data("Conner's Comm Device"),
Data("Windshield Glass"),
Data("Bobby's Watch"),
Data("Gnarlbranch Sap"),
Data("Legen-dar"),
Data("Smelly Legen-dar"),
Data("Slice of Bread"),
Data("Deep Blue Gem"),
Data("Large Stuffed Lobster"),
Data("Stuffed Lobster"),
Data("Meal Ticket"),
Data("Suid Bones"),
Data("Ma-non Hunting Kit"),
Data("Bronze Blatta Card"),
Data("Bronze Cinicula Card"),
Data("Bronze Petramand Card"),
Data("Silver Simius Card"),
Data("Silver Evello Card"),
Data("Silver Xiphias Card"),
Data("Silver Mortifole Card"),
Data("Gold Nopopotamus Card"),
Data("ITM_PRC022_Name", valid=False),
Data("Natural Pearl"),
Data("ITM_PRC024_Name", valid=False),
Data("ITM_PRC025_Name", valid=False),
Data("ITM_PRC026_Name", valid=False),
Data("ITM_PRC027_Name", valid=False),
Data("ITM_PRC028_Name", valid=False),
Data("ITM_PRC029_Name", valid=False),
Data("ITM_PRC030_Name", valid=False),
Data("ITM_PRC031_Name", valid=False),
Data("White Gold Ore"),
Data("Briggs's Key"),
Data("Fosdyke's Key"),
Data("Moorehouse's Key"),
Data("ITM_PRC036_Name", valid=False),
Data("ITM_PRC037_Name", valid=False),
Data("ITM_PRC038_Name", valid=False),
Data("Quegga's Note"),
Data("ITM_PRC040_Name", valid=False),
Data("ITM_PRC041_Name", valid=False),
Data("Keycard"),
Data("ID Card_1"),
Data("ID Card_2"),
Data("ID Card_3"),
Data("ITM_PRC046_Name", valid=False),
Data("Ajoa's ID card"),
Data("ITM_PRC048_Name", valid=False),
Data("ITM_PRC049_Name", valid=False),
Data("ITM_PRC050_Name", valid=False),
Data("Ice Cream Cake"),
Data("Malyteth's Bottle"),
Data("ITM_PRC053_Name", valid=False),
Data("ITM_PRC054_Name", valid=False),
Data("Nopon Contract"),
Data("ITM_PRC056_Name", valid=False),
Data("Nopon Gemstone"),
Data("ITM_PRC058_Name", valid=False),
Data("ITM_PRC059_Name", valid=False),
Data("ITM_PRC060_Name", valid=False),
Data("Vi Sezha's Bracelet"),
Data("Ge Jewhe's Dagger"),
Data("ITM_PRC063_Name", valid=False),
Data("ITM_PRC064_Name", valid=False),
Data("Ringstone"),
Data("ITM_PRC066_Name", valid=False),
Data("ITM_PRC067_Name", valid=False),
Data("Zazazan's Package"),
Data("Hazardous Container"),
Data("Hazardous Fuel Cell"),
Data("Nio's IOU"),
Data("Sapphire Ring"),
Data("ITM_PRC073_Name", valid=False),
Data("ITM_PRC074_Name", valid=False),
Data("ITM_PRC075_Name", valid=False),
Data("ITM_PRC076_Name", valid=False),
Data("ITM_PRC077_Name", valid=False),
Data("ITM_PRC078_Name", valid=False),
Data("ITM_PRC079_Name", valid=False),
Data("ITM_PRC080_Name", valid=False),
Data("ITM_PRC081_Name", valid=False),
Data("Lumenoa Leaf"),
Data("Gorkwa"),
Data("Run'tonam's Right Arm"),
Data("ITM_PRC085_Name", valid=False),
Data("ITM_PRC086_Name", valid=False),
Data("Troylan's Gorkwa_1"),
Data("ITM_PRC088_Name", valid=False),
Data("ITM_PRC089_Name", valid=False),
Data("White Whale Parts_1"),
Data("ITM_PRC091_Name", valid=False),
Data("ITM_PRC092_Name", valid=False),
Data("ITM_PRC093_Name", valid=False),
Data("Ian's ID Card"),
Data("Nalu's Present"),
Data("Dadapon's Sunglasses"),
Data("Dodonga Treaty"),
Data("Dorian Treaty"),
Data("Wrothian Part"),
Data("Med Kit_1"),
Data("Internment Camp Key"),
Data("ITM_PRC102_Name", valid=False),
Data("Skell License"),
Data("ITM_PRC104_Name", valid=False),
Data("ITM_PRC105_Name", valid=False),
Data("ITM_PRC106_Name", valid=False),
Data("White Whale Parts_2"),
Data("L-002 Power Cable"),
Data("Skell License Certificate"),
Data("ITM_PRC110_Name", valid=False),
Data("ITM_PRC111_Name", valid=False),
Data("ITM_PRC112_Name", valid=False),
Data("ITM_PRC113_Name", valid=False),
Data("Tissue Sample"),
Data("Mia's Comm Device"),
Data("Phosphorus-Tree Seed"),
Data("Container Key"),
Data("ITM_PRC118_Name", valid=False),
Data("ITM_PRC119_Name", valid=False),
Data("ITM_PRC120_Name", valid=False),
Data("Grenade Pizza"),
Data("Frozen Pizza"),
Data("Ajiba's Key"),
Data("Mujiba's Key"),
Data("Dancer's Clothes"),
Data("Crimson Tear"),
Data("ITM_PRC127_Name", valid=False),
Data("ITM_PRC128_Name", valid=False),
Data("ITM_PRC129_Name", valid=False),
Data("ITM_PRC130_Name", valid=False),
Data("ITM_PRC131_Name", valid=False),
Data("ITM_PRC132_Name", valid=False),
Data("ITM_PRC133_Name", valid=False),
Data("ITM_PRC134_Name", valid=False),
Data("New Weapon Blueprint"),
Data("ITM_PRC136_Name", valid=False),
Data("Summoning Goggles"),
Data("Senirapa Water"),
Data("ITM_PRC139_Name", valid=False),
Data("Zirtodiamond"),
Data("Golbogga's Disk"),
Data("ITM_PRC142_Name", valid=False),
Data("Tykki Sap"),
Data("ITM_PRC144_Name", valid=False),
Data("Gray Keycard"),
Data("Rectangular Chest"),
Data("ITM_PRC147_Name", valid=False),
Data("ITM_PRC148_Name", valid=False),
Data("ITM_PRC149_Name", valid=False),
Data("ITM_PRC150_Name", valid=False),
Data("ITM_PRC151_Name", valid=False),
Data("ITM_PRC152_Name", valid=False),
Data("Kuta's Cargo"),
Data("ITM_PRC154_Name", valid=False),
Data("Aerozium"),
Data("Guardian Etherscale"),
Data("ITM_PRC157_Name", valid=False),
Data("ITM_PRC158_Name", valid=False),
Data("ITM_PRC159_Name", valid=False),
Data("ITM_PRC160_Name", valid=False),
Data("ITM_PRC161_Name", valid=False),
Data("ITM_PRC162_Name", valid=False),
Data("Hilal Stronghold Key"),
Data("Mimeosome Left Arm"),
Data("L-002 Experimental Plant"),
Data("Reverend's Journal"),
Data("Flemtide"),
Data("Floatstone Shard"),
Data("Blood-Soaked Beast Fur"),
Data("Law's Pendant"),
Data("Three Swords"),
Data("Pearl Necklace"),
Data("Data Unit FN093"),
Data("Repair Kit"),
Data("Aganeba Alloy"),
Data("Cockpit Wreckage"),
Data("Engine Wreckage"),
Data("Zu Pharg Wreckage"),
Data("Junk"),
Data("Data Unit FN094"),
Data("Mimeosome Head"),
Data("Mimeosome Torso"),
Data("Mimeosome Left Leg"),
Data("Mimeosome Right Leg"),
Data("First Barrier Key"),
Data("ITM_PRC186_Name", valid=False),
Data("Cleansing Moss"),
Data("Locket"),
Data("Star Sand"),
Data("Violet Crystal"),
Data("Emerian Relic"),
Data("Missing Drive"),
Data("Broken Data Probe"),
Data("Heart Stone"),
Data("ITM_PRC195_Name", valid=False),
Data("ITM_PRC196_Name", valid=False),
Data("Mount M'gando Stone"),
Data("Jelly Weeds"),
Data("New-Weapon Remains"),
Data("ITM_PRC200_Name", valid=False),
Data("ITM_PRC201_Name", valid=False),
Data("ITM_PRC202_Name", valid=False),
Data("Sampling Bottle"),
Data("Solar Starship Map"),
Data("Hamburger"),
Data("Hot Dog"),
Data("Data Unit FN095"),
Data("Data Unit FN096"),
Data("Data Unit FN097"),
Data("Practice Data Probe"),
Data("Toxic Chemical Bomb"),
Data("Med Kit_2"),
Data("Noble Silk"),
Data("Data Unit FN098"),
Data("Sword of Legendaryness"),
Data("Unbreakable Sword"),
Data("Voltant"),
Data("Keycard"),
Data("Troylan's Gorkwa_2"),
Data("Traditional Orphean Drug"),
Data("Weapon Test Data"),
Data("Second Barrier Key"),
Data("Third Barrier Key"),
Data("Phogrium"),
Data("Massive Ring Fragment"),
Data("Butte Ruin Fragments"),
Data("North Coast Riddle Rock"),
Data("Communication Data"),
Data("Medical Data"),
]