collepedia_data = ["Ajira Melon", #https://xenoblade.github.io/xbx/bdat/common_ms/ITM_CollectList_ms.html
"Lacey Potato",
"Sadelana Lettuce",
"Mosa Cabbage",
"Keppo Carrot",
"Amidresian Tomato",
"Caseras Mushroom",
"Zandemo Eggplant",
"Flowering Morrow Fern",
"Fodornallow Greens",
"Sibercaseras Mushroom",
"Gubura Cabbage Leaf",
"Shinuyuni Garlic",
"Cosse Bean",
"Beagflea Squash",
"Will Pepper",
"Charupa Leaves",
"Dobobora Broccoli",
"Ruge Daikon",
"Dosoram Bean",
"Yaya Sesame",
"Pale Maize",
"Mizaria Celery",
"Kyatara Onion",
"Charged Cayenne",
"Brambloo Shoot",
"Belzadozebu Scallions",
"Cranjelly",
"Rock-Orange",
"Strawlenny",
"Starlight Apple",
"Mondcherry",
"Sonar Lemon",
"Socha Guava",
"Prapaya",
"Babaco Leaf",
"Amana Durian",
"Lava Mango",
"Sour Plum",
"Bananaleaf",
"Godmelon",
"Suna Watermelon",
"Royal Grape",
"Kiwegg",
"Spiked Pomegranate",
"Shido Persimmon",
"Coldberry",
"White Cassis",
"Emerald Grape",
"Cluster Papaya",
"Gyulali",
"Lava Chestnut",
"Iron Akebi Fruit",
"Mottled Mums",
"Nightmare Pineapple",
"Zesian Fleawort",
"Noranlily",
"Sweet Nerine",
"Kiran Catnip",
"Doga Dandelion",
"Sona Herb",
"Garudo Pellionia Minima",
"Nirvana Jonquil",
"Timid Sunflower",
"Lea Lily",
"Chameleon Creeping Plant",
"Muneria Flower",
"Sekka Cosmos",
"False Cedar",
"Sleeping Amaryllis",
"Jobo Primrose",
"Gudo Rocambole",
"Blast Chard",
"Mya Oats",
"Myuena Cactus",
"Kepha Holly",
"Bude Mugwort",
"Exploding Pansy",
"Sese Lily",
"Antorus Rose",
"Shia Cattleya",
"Poron Tulip",
"Jaharmum",
"Bogano Weed",
"Muranadium",
"Rizattice",
"Coaletri",
"Grinding Squirrel",
"Crawling Bat",
"Golden Sardine",
"Zizi Rabbit",
"Ashizel",
"Rock Armadillo",
"Morphling Flounder",
"Gluttonutan",
"Iguari",
"Mirrored Peacock",
"Continental Jellyfish",
"Doragaroo",
"Phantom Tanuki",
"Denemozumi Mouse",
"Octo-suka",
"Jet Turtle",
"Sand Cucumber",
"Gormless Monkey",
"Fleeting Baboon",
"Diresheep",
"Medusa Squid",
"Beaporge",
"Penginion",
"Gun Snake",
"Demon Boar",
"Dulcet Goose",
"Lava Fox",
"Gibney Jackal",
"Ball Mosquito",
"Stretching Locust",
"Tractor Beetle",
"Multi-speckled Ladybug",
"Meteo Eater",
"Vagabond Ant",
"Assassin Springtail",
"Noctilucent Dragonfly",
"Strobing Horsefly",
"Tenacious Moth",
"Madame Mantis",
"Madness Hornet",
"Pardo Spider",
"Kusakiri Stag Beetle",
"Absop's Swallowtail",
"Fullbelly Gecko",
"Moleworm",
"Imposter Bug",
"Shadow Fly",
"Common Stick Insect",
"Whip Scorpion",
"Slasher Beetle",
"White Sand Beetle",
"Baibai Beetle",
"Glassy Cricket",
"Rainy Cricket",
"Crystal Butterfly",
"Snowy Angelhair",
"Shooting Firefly",
"Abyssal Cricket",
"Cetecegem Beetle",
"Bullet Fly",
"Prickly Cricket",
"Logunie's Driftwood",
"White Iron Sand",
"Fillal Filth",
"Sanelac Pearl",
"Arnacian Orewood",
"Auroran Bone",
"Katoan Leaf",
"Gluttonutan Clay",
"Cane Soil",
"Noka Mirrorstone",
"Galjim Crystal",
"Harnenga Cotton",
"Eternal Moss",
"Wainess Fossil",
"Zedis Twig",
"Exubera Stalactite",
"Silvery Cactaceous Resin",
"Kridokan Air",
"Dring Slick",
"Acton Rock Shards",
"Fullerene Coral",
"Taoman Acid",
"Grandan Rock",
"Jagitos Copper",
"Pomio Spore",
"Cooling Lava",
"Zalon Dirt",
"Rogebra Shockstone",
"Autiga Powder",
"Zagyrin Cragstone",
"Cliord Oil",
"Deflection Shield Mirror",
"Anhydrous Radiator",
"Heatproof Inox Pipe",
"L-002 Fuel Tank",
"L-002 Space Analyzer",
"US-X Space Suit",
"Centrifugal Beam Generator",
"Earthfreezer",
"Nostalgia L-002",
"HI9 Ion Thruster",
"Mk",
 IX Hypercooler
"Gesture Glove",
"3D Printer",
"Cruise Deflector AiR",
"Multi-mirror Solar Drone",
"5th Gen Recycler",
"L-002 Degeneration Reactor",
"Cordless Transformer",
"Hard Skin",
"Decoy DNA",
"L-002 Dagoo Heat Ray",
"A-HAB autonomous AI",
"Solar Wind Converter",
"Oxygen Airbrake",
"Exalting Paint",
"Autoposturizer",
"Planter",
"FN Prototype 3",
"Octopus Regulator",
"Jagged Mortar",
"Acorn Abacus",
"Facewood",
"Hemp Wallet",
"Hummingstone",
"Loathsome Blob",
"Sea Anemone Platter",
"Logunie's Driftwood Boat",
"Shiny Lamp",
"Spine-O-Corrector",
"Thornbox",
"Perished Stone Spear",
"Sandstone Etching",
"Magical Finding Rod",
"Ouroboros Bracelet",
"Drum of Valor",
"Nopolith",
"Yabuyabu Ointment",
"Straw Buoy",
"Spore Balloon",
"Stargazer",
"Camocloak",
"Spirit Wand",
"Chrampoline",
"Sharpening Stone",
"Charred Crock",
"Stone Lens",
"Dark Lantern",
"Icarus Wings",
"Bogano Sleeping Bag",
"Extra-large Cash Box",
"High Accelerator",
"Crush Ring",
"T-ray Light",
"Flecked Bottle",
"Grosium Core",
"Brain Terminal",
"Hexagauge",
"Joadtank",
"Resonating Madonater",
"Ultra Filter",
"Eradicator Eyepiece",
"Sacrificial Reactor",
"Steel Tail Sheath",
"Horned Helmet",
"Warbone",
"Shimmering Skin",
"Detilid Device",
"Missile Wiring",
"Berzerker Unit",
"Thunderbolt Emblem",
"Trying Crown",
"Intelligent Liquid Metal",
"Pan-analysis Chips",
"Savage Claw",
"Elemental Battery",
"Spatial Control Jointer",
"Dithblade Fragment",
"Voltant Scanner",
"Meditation Powder",
"California Sunset",
"Mirage Scope",
"Ancient Allure",
"Goddess's Kiss",
"Gleaming Magnet",
"Fraudulent Mirror",
"Scales of Justice",
"Spherical EM Motor",
"Primitive Colossus Statue",
"Strong Iron",
"Chameleon Sand",
"Maiden's Guardian Star",
"Echo Rock",
"Illogical Etchings",
"Angel Stone",
"Lost Memory Synthesizer",
"Double Helical Salt",
"Brilliant Green Liquid",
"Flowering Egg",
"Queen's Rapture",
"Stone Screw",
"Starmaker",
"Hello Transmitter",
"Affinity Soulchain",
"Mega Muscle Builder",
"Rod of Brutality +10",
"Capricious Kettle",
"Megajolt Rattle",
"Superior Scepter",
"Doom Mask",
"Savage Sketch",
"Book of Death and Rebirth",
]