enemies_data = ["", #https://xenoblade.github.io/xbx/bdat/common_local_us/CHR_EnList.html#348
"Autosentry",
"Autosentry",
"Vita",
"Vita",
"Rexoskell",
"Rexoskell",
"Vasara",
"Vasara",
"Zu Pharg",
"Zu Pharg",
"Almandal",
"Almandal",
"Puge",
"Puge",
"Pugilith",
"Galdr",
"Galdr",
"Galdr",
"Galdr",
"Quo",
"Quo",
"Oc-serv",
"Oc-serv",
"Oc-serv",
"Qmoeva",
"Qmoeva",
"Qmoeva",
"Qmoeva",
"Deva Caladar",
"Caladar",
"Seidr",
"Seidr",
"Seidr",
"Xe-dom",
"Xe-dom",
"Zig",
"Zig",
"Zig",
"Zig",
"Fal-swo",
"Fal-swo",
"Neilnail Albus",
"Neilnail Furvus",
"Prog Ares",
"Skell",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Milsaadi",
"Milsaadi",
"Milsaadi",
"Milsaadi",
"Sylooth",
"Gularth",
"Sylooth",
"Gularth",
"Division Member",
"Division Member",
"Prone",
"Prone",
"Prone",
"Prone",
"Definian",
"Wrothian",
"Wrothian",
"Goetia",
"Dagahn",
"Ryyz",
"Ga Jiarg",
"Ga Buidhe",
"Petramand",
"Scirpo",
"Petramand",
"Petramand",
"Scirpo",
"Forfex",
"Forfex",
"Cinicula",
"Falsaxum",
"Cinicula",
"Falsaxum",
"Vivohast",
"Thallus",
"Thallus",
"Tectinsula",
"Tectinsula",
"Arenatect",
"Arenatect",
"Blatta",
"Blatta",
"Turba",
"Adsecula",
"Papil",
"Adsecula",
"Papil",
"Germivore",
"Germivore",
"Lophid",
"Purgovent",
"Lophid",
"Purgovent",
"Duoguill",
"Scintimure",
"Duoguill",
"Scintimure",
"Aetrygon",
"Xiphias",
"Aetrygon",
"Xiphias",
"Balaena",
"Ceto",
"Balaena",
"Ceto",
"Grex",
"Caro",
"Grex",
"Caro",
"Vigent",
"Virago",
"Vigent",
"Monoceros",
"Progen",
"Monoceros",
"Progen",
"Simius",
"Cantor",
"Simius",
"Cantor",
"Aprica",
"Cervus",
"Aprica",
"Cervus",
"Suid",
"Armored Suid",
"Femina Suid",
"Suid",
"Femina Suid",
"Millesaur",
"Coronid",
"Gradivus, the Headless Emperor",
"Coronid",
"Evello",
"Caecus",
"Caecus",
"Evello",
"Insidia",
"Sphinx",
"Sphinx",
"Chimera Lao",
"Chimera",
"Mortifole",
"Sacrifole",
"Mortifole",
"Mortifole",
"Mortifole",
"Auravis",
"Jacul",
"Auravis",
"Jacul",
"Levitath",
"Levitath",
"Colubrim",
"Millepod",
"Colubrim",
"Millepod",
"Unafulge",
"Visigel",
"Unafulge",
"Visigel",
"Filiavent",
"Filiavent",
"Yggralith",
"Yggralith",
"Telethia",
"Terebra",
"Mephite",
"Terebra",
"Mephite",
"Saltat",
"Liceor",
"Saltat",
"Saltat",
"Saltat",
"Liceor",
"Potamus",
"Potamus",
"Potamus",
"Galdr",
"Galdr",
"Galdr",
"Galdr",
"Oc-serv",
"Qmoeva",
"Qmoeva",
"Qmoeva",
"Qmoeva",
"Seidr",
"Seidr",
"Seidr",
"Xe-dom",
"Zig",
"Zig",
"Zig",
"Zig",
"Forfex",
"Scirpo",
"Blatta",
"Turba",
"Caro",
"Virago",
"Monoceros",
"Caecus",
"Insidia",
"Levitath",
"Mephite",
"Saltat",
"Saltat",
"Saltat",
"Saltat",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Division Member",
"Division Member",
"Division Member",
"Division Member",
"Division Member",
"Division Member",
"Division Member",
"Division Member",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Prone",
"Skell",
"Skell",
"Skell",
"Sylooth",
"Petramand",
"Cinicula",
"Blatta",
"Blatta",
"Scintimure",
"Scintimure",
"Vigent",
"Sacrifole",
"Chimera",
"Sabula",
"Shield Satellis",
"Shield Satellis",
"Shield Satellis",
"Shield Satellis",
"Shield Satellis",
"Shield Satellis",
"Shield Satellis",
"Xern",
"Shrad",
"Ictus",
"Aeviter",
"Ovis",
"Gerrid",
"Lepyx",
"Vesper",
"Murra",
"Dilus",
"Tersqual",
"Skell",
"Skell",
"Skell",
"Skell",
"Skell",
"Skell",
"Skell",
"Skell",
"Origin Blatta",
"Callow Grex",
"Elder Grex",
"Volkampf, the Pursuer",
"Prone Scout",
"Prone Scout",
"Prone",
"Prone Ruffian",
"Prone Ruffian",
"Glennar",
"Prone Destroyer",
"Prone Destroyer",
"Prone Destroyer",
"Marnuck Rook",
"Marnuck Rook",
"Goetia",
"Targeter Zig",
"Targeter Zig",
"Targeter Zig",
"Platoon Qmoeva",
"Platoon Qmoeva",
"Chief Qmoeva",
"Tainted Caro",
"Tainted Caro",
"Tainted Caro",
"Tainted Sphinx",
"Tainted Caro",
"Tainted Scintimure",
"Assault Qmoeva",
"Assault Qmoeva",
"Assault Qmoeva",
"Assault Qmoeva",
"Pursuit Qmoeva",
"Almandal",
"Scout Puge",
"Strike Puge",
"Strike Pugilith",
"Assault Pugilith",
"Galdr",
"Galdr",
"Galdr",
"Impact Galdr",
"Revolver Owl Galdr",
"Galdr",
"Impact Galdr",
"Galdr",
"Galdr",
"Galdr",
"Galdr",
"Assister Quo",
"Drone Knight Quo",
"Quo",
"Quo",
"Beryllium Oc-serv",
"Assault Qmoeva",
"Talon Knight Qmoeva",
"Talon Knight Qmoeva",
"Assault Qmoeva",
"Palace Knight Qmoeva",
"Qmoeva",
"Pursuit Qmoeva",
"Multi Knight Qmoeva",
"Qmoeva",
"Blitz Qmoeva",
"Suppressor Knight Qmoeva",
"Marnuck Soldier",
"Marnuck",
"Marnuck Ruffian",
"Marnuck Grappler",
"Marnuck Gatling",
"Prone Warrior",
"Prone Commander",
"Dagahn",
"Ryyz",
"Wrothian Enacter",
"Wrothian Enacter",
"Wrothian Sneaker",
"Ga Jiarg",
"Ga Buidhe",
"Vasara",
"Deva Caladar",
"Caladar",
"Caladar",
"Zu Pharg",
"Zu Pharg",
"Fal-swo",
"Qmoeva",
"Galdr",
"Fal-swo",
"Qmoeva",
"Galdr",
"Fal-swo",
"Force Seidr",
"Prog Ares",
"Prog Ares",
"Talon Eagle Galdr",
"Revolver Eagle Galdr",
"Guide Eagle Galdr",
"Gun Eagle Galdr",
"Drone King Quo",
"Talon King Qmoeva",
"Talon King Qmoeva",
"Talon King Qmoeva",
"Palace King Qmoeva",
"Multi King Qmoeva",
"Suppressor King Qmoeva",
"Talon King Qmoeva",
"Palace King Qmoeva",
"Multi King Qmoeva",
"Suppressor King Qmoeva",
"Grav Eagle Seidr",
"Orion Xern",
"Vita",
"Vita",
"Shield Satellis",
"Strike Satellis",
"Link Satellis",
"Enhancer Satellis",
"Pursuit Satellis Alpha",
"Pursuit Satellis Beta",
"Pursuit Satellis Gamma",
"Soldier Chimera",
"Lao",
"Lao",
"Queen Chimera",
"Minor Chimera",
"Mezzo Chimera",
"Major Chimera",
"SEN0101_Name",
"SEN0102_Name",
"SEN0103_Name",
"Sphinx",
"SEN0105_Name",
"SEN0106_Name",
"SEN0107_Name",
"Telethia",
"Yggralith",
"Filiavent",
"Filiavent",
"Filiavent",
"Bold Cinicula",
"Little Suid",
"Big Suid",
"Big Suid",
"Devil Mephite",
"HH100: Hierana",
"Wrothian Warrior",
"EN000000_NAME_Dummy",
"Wood Tectinsula",
"Falconine Jacul",
"Bouyant Pugilith",
"Jovial Saltat",
"Briggs",
"Fosdyke",
"Moorehouse",
"Briggs",
"Fosdyke",
"Moorehouse",
"Cross Qmoeva",
"TP351: Tempera",
"Galdr Raven",
"Metal Puge",
"Slab Cinicula",
"Abyssal Blatta",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Lineage",
"EN013203_Q138_A_NAME",
"EN013203_Q138_B_NAME",
"EN013203_Q138_C_NAME",
"BLADE Trooper",
"BLADE Soldier",
"BLADE Sniper",
"Lineage",
"EN013203_Q139_A_NAME",
"EN013203_Q139_B_NAME",
"BLADE Trooper",
"BLADE Sniper",
"Lightning Strike",
"Subdued Arenatect",
"DV482: Duvel",
"Impulse Qmoeva",
"Lineage",
"Raging Cantor",
"Raging Cantor",
"Raging Cantor",
"Raging Cantor",
"Raging Cantor",
"Raging Cantor",
"Ajoa Cantor",
"EN000000_NAME_Dummy",
"Noble Arachnid",
"Oc-serv Seivo",
"EN000000_NAME_Dummy",
"Brutal Prone",
"Brutal Prone",
"Brutal Prone",
"Definian Pawn",
"Blood Despair",
"Stagnant Grex",
"Stagnant Terebra",
"Whimsical Duoguill",
"Grenade Pizza F",
"Rowdy Potamus",
"Clotho Puge",
"Lachesis Puge",
"Atropos Puge",
"TW772: Trinn",
"Twin Qmoeva",
"Last Galdr",
"Ajiba Falgo",
"Mujiba Falgo",
"Meek Suid",
"Vanguard Glennar",
"Gladiator Simius",
"Predator Falsaxum",
"Imp Lophid",
"Galba Vassago",
"Dune Adsecula",
"Garuda Jacul",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Loda Gorida",
"Prone Fighter",
"Leroy's Ire",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Bastion Glennar",
"Prone Fighter",
"Dread Blatta",
"Dread Petramand",
"Dread Cinicula",
"Bruiser Blatta",
"Bruiser Petramand",
"Bruiser Cinicula",
"Odsent",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Odsent",
"Odsent",
"Linker Scirpo",
"Gus",
"BLADE Sniper",
"Unruly Petramand",
"Berserk Prone",
"MG062: Megisia",
"Slovity Pagus",
"Milsaadi Lieutenant",
"Master Milsaadi",
"MG068: Megisia",
"Guard Monoceros",
"Guard Monoceros",
"Guard Monoceros",
"Lowly Terebra",
"Hungry Auravis",
"Strong Auravis",
"Harvey",
"BLADE Trooper",
"BLADE Trooper",
"Faded Nopopotamus",
"Prone Fighter",
"Prone Keeper",
"Jacul Ire",
"Stray Potamus",
"Nopopon Incarnate",
"Napopon Incarnate",
"Nipopon Incarnate",
"Nupopon Incarnate",
"Gi Ziorde",
"Gi Ziorde",
"Gi Ziordo",
"Gi Ziordo",
"Siphon Qmoeva",
"Vanitas Seidr",
"Zo Zazhi",
"Zo Zazhi",
"Milsaadi Spellslinger",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Marnuck Scout",
"Phantom Seidr",
"Sazon Caladar",
"Soghu Caladar",
"De Ezich",
"Naguth Caladar",
"Girhi Caladar",
"Zeulbe Caladar",
"Mortal Jacul",
"Queen Jacul",
"Gu Ladha",
"Ladha Caladar",
"Brute Millepod",
"Ga Bewhe",
"Marnuck Slouch",
"Marnuck Surveillant",
"Zo Zazhi",
"Gigas Nopopotamus",
"Slovity Pagus",
"Gwin",
"Autosentry Mk.II",
"Gi Zang",
"Ozuchi Caladar",
"JS178: Jushe",
"Array Insidia",
"Brazen Falsaxum",
"Parched Terebra",
"Dryland Auravis",
"Grand Lophid",
"Grand Lophid",
"Bio Visigel",
"Bio Visigel",
"Bio Visigel",
"Bio Visigel",
"EN000000_NAME_Dummy",
"Bio Visigel",
"Telethia, the Endbringer",
"Autosentry",
"Autosentry",
"Gold Courage",
"Vigil Forfex",
"Purger Purgovent",
"Black Simius",
"Xe-dom Sarto",
"SG002: Slenna",
"Definian Guard",
"Cliff Galdr",
"ER001: Emeroa",
"HP001: Harriess",
"JD001: Juda",
"Rexoskell",
"Rexoskell",
"DE913: Dieara",
"Gadd",
"BLADE Sniper",
"BLADE Soldier",
"BLADE Trooper",
"Speed Mod Custom Skell",
"Gadd",
"BLADE Sniper",
"BLADE Soldier",
"BLADE Trooper",
"BLADE Trooper",
"Marnuck Hunter",
"Dolba the Wrecker",
"Gadd",
"BLADE Sniper",
"BLADE Something",
"BLADE Something",
"Gi Zang",
"Gi Zang",
"Gi Zang",
"Gi Zang",
"Drove Adsecula",
"Gi Zang",
"Jacul Rage",
"Tectonic Puge",
"MO037: Moore",
"Gi Zang",
"Gi Zang",
"LV757: Lyvia",
"Marnuck Commander",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Marnuck Soldier",
"Marnuck Soldier",
"Marnuck Soldier",
"Matinal Evello",
"Brume Auravis",
"Greedy Forfex",
"EN000000_NAME_Dummy",
"Shallows Grex",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Gwin",
"Gwin",
"Arrow Germivore",
"Arrow Cinicula",
"Rotund Caro",
"Stout Caro",
"Chasm Forfex",
"EN000000_NAME_Dummy",
"Fierce Vigent",
"Grudge Tersqual",
"Telethia, the Endbringer",
"Bizarre Insidia",
"Intimidator Simius",
"Demise Ictus",
"Gleaming Sphinx",
"Dimnet Xiphias",
"Stratospheric Balaena",
"Marnuck",
"Marnuck Soldier",
"Tower Marnuck",
"Gaol Galdr",
"Marnuck Soldier",
"Marnuck Commander",
"Sailing Grex",
"Fighter Grex",
"Ga Buidhe",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Zo Borri",
"Zo Fwar",
"Nameless Caladar",
"Nameless Caladar",
"Nameless Caladar",
"Agile Caecus",
"Hermit Insidia",
"Unyielding Forfex",
"Unyielding Forfex",
"Gale Milsaadi",
"Heinous Blatta",
"Heinous Forfex",
"Zealot Glennar",
"Prone Fighter",
"ST816: Stalio",
"Definian",
"Trigger Scintimure",
"Thieving Dilus",
"Blood-king Gelvo Banth",
"Prone Box",
"Prone Hearthkeeper",
"Soldier Insidia",
"Empress Insidia",
"Gaff Pugilith",
"Menacing Marnuck",
"Marnuck Gunner",
"Guard Qmoeva",
"Marnuck Gunner",
"Assault Galdr",
"Qmoeva Divider",
"Marnuck Crafter",
"Marnuck Analyst",
"Oc-serv Yabar",
"Marnuck Van",
"Assault Puge",
"Marnuck Gunner",
"Shield Galdr",
"Tower Qmoeva",
"Running Shark",
"EN000000_NAME_Dummy",
"BLADE Sniper",
"BLADE Trooper",
"Disaster Vigent",
"Interfearence",
"Alexa Special",
"Trump Arenatect",
"Scout Galdr",
"Scout Qmoeva",
"Mold Caro",
"SN333: Jisanne",
"Milsaadi Corroder",
"Milsaadi Destroyer",
"Hardy Aprica",
"Corpse Sacrifole",
"Colubrim",
"EN000000_NAME_Dummy",
"Enforcer Glennar",
"Marnuck Trooper",
"EN000000_NAME_Dummy",
"Marnuck Quartermaster",
"Marnuck Commander",
"Compulsive Tainted",
"Slovity Pagus",
"Armored Grex",
"Armored Sphinx",
"Cunning Sylooth",
"Daunting Sylooth",
"Gale Qmoeva",
"Sturm Qmoeva",
"Mist Milsaadi",
"Haze Milsaadi",
"Haze Milsaadi",
"Milsaadi Fate",
"Milsaadi Fate",
"Milsaadi Fini",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Potamus",
"Millesaur Leader",
"Millesaur",
"Millesaur",
"Greedy Millesaur",
"Blatta",
"Grex",
"Grex Leader",
"Sphinx A",
"Sphinx B",
"Sphinx C",
"Mephite",
"Unafulge",
"Unafulge",
"Visigel",
"Visigel",
"Colubrim",
"Neilnail Albus",
"Neilnail Furvus",
"Puge A",
"Puge B",
"Caladar",
"Caladar",
"Vasara",
"Phanatos, the Netherlord",
"Xiphias",
"Filiavent",
"Puge A",
"Puge B",
"Qmoeva A",
"Qmoeva B",
"Sabula",
"Quo",
"Quo",
"Quo",
"Quo",
"Qmoeva C",
"Rexoskell",
"Zig A",
"Zig B",
"Zig A",
"Zig A",
"Zig B",
"Almandal",
"Unafulge",
"Marnuck A",
"Marnuck B",
"Monoceros",
"Sabula",
"Sabula",
"Arenatect",
"Petramand",
"Jacul A",
"Jacul B",
"Marnuck A",
"Purgovent",
"Definian",
"Shrad",
"Puge",
"Papil",
"Qmoeva",
"Quo",
"Galdr A",
"Galdr B",
"Galdr C",
"Shrad",
"Puge A",
"Puge B",
"Puge",
"Pugilith",
"Qmoeva A",
"Qmoeva B",
"Scirpo",
"Galdr A",
"Mephite",
"Germivore",
"Vivohast",
"Mephite",
"Seidr",
"Seidr",
"Puge",
"Pugilith",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Seidr A",
"Seidr B",
"Seidr C",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Oc-serv",
"Fal-swo",
"Xe-dom A",
"Xe-dom B",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Oc-serv",
"Oc-serv",
"Oc-serv",
"Oc-serv",
"Fal-swo",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Caro",
"Marnuck A",
"Marnuck B",
"Marnuck C",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Caro",
"Milsaadi A",
"Milsaadi B",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Papil",
"Progen",
"Sylooth A",
"Sylooth B",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Germivore",
"Insidia",
"Thallus",
"Thallus",
"Falsaxum",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Blatta",
"Turba",
"Adsecula",
"Lophid",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Aetrygon",
"Scintimure",
"Balaena",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Potamus",
"Grex Leader",
"Grex",
"Vigent A",
"Vigent B",
"Vigent C",
"Sabula",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Scirpo",
"Mortifole",
"Simius",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Murra",
"Visigel",
"Monoceros",
"Cervus",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Cervus",
"Tersqual",
"Coronid A",
"Coronid B",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Mortifole",
"Insidia",
"Saltat",
"Saltat",
"Saltat",
"Auravis",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Adsecula",
"Murra",
"Levitath",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Xe-dom",
"Prone",
"Qmoeva",
"Qmoeva",
"Millepod",
"Puge",
"Pugilith",
"Xern",
"Shrad",
"Qmoeva",
"Zig A",
"Zig B",
"Quo",
"Qmoeva A",
"Qmoeva B",
"Galdr",
"Zig A",
"Zig B",
"Quo",
"Galdr A",
"Galdr B",
"Galdr C",
"Seidr A",
"Seidr B",
"Seidr C",
"Rexoskell",
"Neilnail Albus",
"Neilnail Furvus",
"Tainted Caro",
"Tainted Scintimure",
"Caladar",
"Xe-dom",
"Xe-dom",
"Scirpo",
"Vesper",
"Sabula",
"Ictus A",
"Ictus B",
"Terebra",
"Grex",
"Lepyx",
"Cinicula",
"Lepyx",
"Potamus",
"Cinicula",
"Blatta",
"Simius",
"Petramand",
"Balaena",
"Cinicula",
"Scirpo",
"Scirpo",
"Scirpo",
"Petramand",
"Duoguill",
"Blatta",
"Petramand Leader",
"Petramand",
"Papil B",
"Papil A",
"Duoguill",
"Lophid",
"Potamus",
"Terebra",
"Qmoeva",
"Prone",
"Prone",
"Qmoeva",
"Prone",
"Skell",
"Petramand",
"Turba",
"Petramand",
"Turba",
"Scirpo",
"Duoguill",
"Blatta",
"Blatta Leader",
"Blatta",
"Scirpo A",
"Scirpo B",
"Terebra",
"Scirpo",
"Blatta",
"Armored Suid",
"Simius Leader",
"Simius",
"Prone Leader",
"Armored Suid",
"Blatta",
"Grex",
"Grex",
"Ovis",
"Grex Leader",
"Grex",
"Cinicula",
"Grex",
"Prone",
"Prone",
"Armored Suid",
"Prone",
"Lepyx",
"Grex Leader",
"Grex",
"Autosentry",
"Prone",
"Prone",
"Prone",
"Turba",
"Petramand",
"Cinicula",
"Turba",
"Lophid",
"Balaena",
"Grex",
"Terebra",
"Duoguill A",
"Duoguill B",
"Blatta A",
"Blatta B",
"Suid",
"Prone",
"Prone",
"Prone",
"Qmoeva",
"Prone",
"Prone",
"Qmoeva",
"Blatta",
"Scirpo",
"Qmoeva A",
"Qmoeva B",
"Qmoeva C",
"Millesaur",
"Terebra",
"Terebra",
"Terebra",
"Terebra",
"Potamus",
"Saltat",
"Forfex",
"Aeviter A",
"Aeviter B",
"Progen A",
"Progen B",
"Progen",
"Scirpo",
"Mortifole",
"Unafulge",
"Scirpo",
"Mortifole",
"Mortifole",
"Suid",
"Femina Suid Leader",
"Suid",
"Saltat",
"Saltat",
"Saltat",
"Saltat",
"Liceor",
"Liceor",
"Liceor",
"Liceor",
"Germivore",
"Tectinsula",
"Suid",
"Femina Suid",
"Suid",
"Femina Suid",
"Tectinsula Leader",
"Tectinsula",
"Saltat Leader",
"Saltat",
"Mortifole",
"Scirpo A",
"Scirpo B",
"Mortifole",
"Mortifole",
"Mortifole",
"Sylooth",
"Papil",
"Papil",
"Dilus Leader",
"Dilus",
"Insidia",
"Virago",
"Sylooth",
"Simius",
"Simius",
"Purgovent Leader",
"Purgovent",
"Virago",
"Progen A",
"Progen C",
"Forfex",
"Dilus",
"Scirpo",
"Insidia",
"Insidia",
"Scirpo Leader",
"Scirpo A",
"Scirpo B",
"Suid A",
"Suid B",
"Femina Suid",
"Progen",
"Levitath",
"Aeviter",
"Germivore",
"Levitath",
"Scirpo",
"Dilus",
"Saltat A",
"Saltat B",
"Saltat",
"Scirpo",
"Scirpo",
"Progen",
"Forfex",
"Germivore",
"Virago",
"Germivore",
"Virago",
"Papil",
"Scirpo",
"Sylooth",
"Insidia",
"Germivore",
"Virago",
"Insidia",
"Mortifole",
"Scirpo",
"Scirpo A",
"Scirpo B",
"Scirpo C",
"Puge",
"Quo",
"Galdr A",
"Galdr B",
"Insidia",
"Dilus",
"Sylooth",
"Levitath",
"Unafulge",
"Aeviter",
"Levitath",
"Vesper",
"Vesper",
"Vesper",
"Grex",
"Grex",
"Marnuck",
"Scintimure",
"Marnuck",
"Marnuck",
"Ceto",
"Aetrygon",
"Aetrygon",
"Aetrygon",
"Potamus",
"Evello",
"Potamus",
"Evello",
"Auravis",
"Adsecula",
"Potamus",
"Aprica",
"Evello",
"Evello",
"Forfex",
"Forfex",
"Forfex",
"Prone",
"Prone",
"Marnuck",
"Prone",
"Marnuck",
"Thallus",
"Adsecula",
"Thallus",
"Potamus",
"Evello",
"Grex",
"Prone",
"Pugilith",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Quo",
"Adsecula",
"Vesper",
"Forfex",
"Forfex",
"Forfex",
"Aetrygon",
"Marnuck",
"Marnuck",
"Vesper",
"Vesper",
"Thallus",
"Adsecula",
"Auravis",
"Marnuck",
"Quo",
"Marnuck",
"Adsecula",
"Adsecula",
"Thallus",
"Auravis",
"Prone",
"Prone B",
"Marnuck",
"Pugilith",
"Marnuck",
"Grex",
"Marnuck",
"Grex",
"Marnuck",
"Aprica",
"Vigent",
"Vigent",
"Vigent",
"Evello",
"Marnuck",
"Fal-swo",
"Fal-swo",
"Marnuck",
"Sphinx",
"Grex",
"Sabula",
"Neilnail Albus",
"Neilnail Furvus",
"Prone",
"Prone A",
"Prone B",
"Prone A",
"Prone B",
"Milsaadi",
"Milsaadi",
"Seidr",
"Definian",
"Caro",
"Puge",
"Qmoeva",
"Marnuck",
"Marnuck",
"Marnuck",
"Seidr",
"Marnuck A",
"Marnuck B",
"Caro",
"Caro",
"Puge",
"Puge",
"Ictus A",
"Ictus B",
"Caecus",
"Tersqual",
"Gularth A",
"Gularth B",
"Scintimure",
"Marnuck A",
"Marnuck B",
"Marnuck C",
"Marnuck A",
"Marnuck B",
"Marnuck C",
"Marnuck Leader",
"Jacul",
"Jacul",
"Jacul",
"Jacul Leader",
"Shrad",
"Scintimure A",
"Scintimure B",
"Turba",
"Turba",
"Turba",
"Marnuck",
"Mephite",
"Mephite",
"Caro",
"Caro",
"Caro",
"Caro",
"Shrad A",
"Shrad B",
"Auravis",
"Mephite",
"Ictus",
"Ictus",
"Definian",
"Shrad",
"Milsaadi",
"Tersqual",
"Seidr",
"Puge",
"Scintimure",
"Qmoeva",
"Ictus",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Marnuck",
"Caecus",
"Caecus",
"Caecus",
"Caecus",
"Insidia",
"Insidia",
"Caecus",
"Caecus",
"Insidia",
"Caecus",
"Mephite",
"Caro",
"Lophid",
"Milsaadi",
"Turba",
"Turba",
"Turba",
"Xern A",
"Xern B",
"Xern C",
"Caecus",
"Turba",
"Seidr",
"Shrad",
"Puge",
"Marnuck",
"Milsaadi",
"Qmoeva",
"Puge",
"Milsaadi",
"Milsaadi",
"Xern",
"Shrad A",
"Shrad B",
"Shrad C",
"Shrad A",
"Shrad B",
"Shrad C",
"Filiavent",
"Filiavent",
"Mephite",
"Gularth",
"Coronid",
"Jacul",
"Murra",
"Milsaadi",
"Qmoeva",
"Puge",
"Puge",
"Gularth",
"Colubrim",
"Scintimure",
"Scintimure",
"Scintimure",
"Marnuck",
"Milsaadi",
"Shrad",
"Milsaadi",
"Mephite",
"Ictus",
"Gularth",
"Definian",
"Definian",
"Seidr",
"Jacul",
"Caecus",
"Tersqual",
"Jacul",
"Milsaadi",
"Filiavent",
"Definian",
"Definian",
"Qmoeva",
"Cantor",
"Cantor",
"Cantor Leader",
"Ovis",
"Arenatect",
"Sacrifole",
"Murra",
"Tersqual",
"Coronid",
"Progen",
"Aeviter",
"Monoceros",
"Monoceros Leader",
"Falsaxum",
"Jacul",
"Jacul",
"Marnuck A",
"Marnuck B",
"Marnuck C",
"Marnuck C",
"Marnuck A",
"Marnuck A",
"Marnuck B",
"Petramand",
"Ictus",
"Cantor",
"Cantor",
"Milsaadi",
"Unafulge",
"Turba",
"Turba Leader",
"Sacrifole",
"Arenatect",
"Murra",
"Murra Leader",
"Zig A",
"Zig B",
"Marnuck A",
"Marnuck B",
"Milsaadi",
"Gu Galda",
"Gi Bordo",
"Da Dorde",
"Zo Zongra",
"Cantor",
"Cantor",
"Visigel",
"Puge",
"Wrothian A",
"Wrothian B",
"Oc-serv",
"Oc-serv",
"Oc-serv",
"Oc-serv",
"Oc-serv",
"Vivohast",
"Vivohast",
"Vivohast Leader",
"Xiphias",
"Puge",
"Pugilith",
"Qmoeva A",
"Qmoeva B",
"Fal-swo",
"Liceor",
"Liceor",
"Ovis",
"Ovis B",
"Ovis C",
"Ovis A",
"Turba",
"Turba A",
"Turba B",
"Ovis",
"Ovis A",
"Ovis B",
"Ovis C",
"Zig",
"Adsecula",
"Arenatect",
"Monoceros",
"Falsaxum",
"Xe-dom",
"Turba",
"Visigel",
"Cervus",
"Virago",
"Unafulge",
"Aeviter",
"Aeviter",
"Sacrifole",
"Sacrifole",
"Xiphias",
"Vivohast",
"Visigel",
"Xe-dom",
"Oc-serv",
"Puge",
"Oc-serv",
"Galdr",
"Puge",
"Pugilith",
"Qmoeva",
"Qmoeva",
"Qmoeva",
"Milsaadi",
"Milsaadi",
"Galdr",
"Zig",
"Zig",
"Goetia",
"Tainted Sphinx",
"Dagahn",
"Ryyz",
"Vasara",
"Deva Caladar",
"Prog Ares",
"Vita",
"Telethia Plume",
"Yggralith",
"Yggralith Zero",
"Filiavent",
"Filiavent",
"Filiavent",
"Nardacyon, the Shadowless",
"Pawn Puge",
"Spear Puge",
"Prototype Puge",
"Lord Puge",
"Pawn Pugilith",
"Lance Pugilith",
"Talon Eagle Galdr",
"Revolver Eagle Galdr",
"Flood Galdr",
"Gun Eagle Galdr",
"Vendura's Galdr",
"Drone Rook Quo",
"Drone Queen Quo",
"Drone King Quo",
"Logistical Support Quo",
"Ataraxia Oc-serv",
"Titanium Oc-serv",
"Talon King Qmoeva",
"Experimental Composite Qmoeva",
"Multi Queen Qmoeva",
"Brave King Qmoeva",
"Multi King Qmoeva",
"Intermediate Arsenal Qmoeva",
"Rebel Queen Qmoeva",
"Suppressor Hermit Qmoeva",
"Suppressor King Qmoeva",
"Support Trainee Qmoeva",
"Daril's Qmoeva",
"Strike Gunner Zig",
"Strike Launcher Zig",
"Revolver Gunner Zig",
"Revolver Launcher Zig",
"Mortar Gunner Zig",
"Mortar Launcher Zig",
"Palace Gunner Zig",
"Thallium Fal-swo",
"Chromium Fal-swo",
"Ji-ett, the Thunderclap",
"Marnuck Admiral",
"Marnuck Sentinel",
"Marnuck Sentinel",
"Marnuck Vanguard",
"Marnuck Vanguard",
"Marnuck Royal",
"Marnuck Gamma",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Delta",
"Marnuck Sentinel",
"Marnuck Windtrooper",
"Daril, the Eradicator",
"Nahum, the Red Hare",
"Nahum, the Red Hare",
"Goliath Sylooth",
"Prone Major",
"Prone Typhoon",
"Prone Trainer",
"Prone Eater",
"Prone Berserker",
"Urd Grex The Cruel",
"Prone Eater",
"Prone Berserker",
"Prone Berserker",
"Prone Savage",
"Prone Vix Griffin",
"Prone Spartan",
"Neodymium Petramand",
"Ytterby Petramand",
"Malium Petramand",
"Caesar, the Hundred-Eyed",
"Grassland Scirpo",
"Grassland Scirpo",
"Grassland Scirpo",
"Tree Scirpo",
"Tree Scirpo",
"Tree Scirpo",
"Green Scirpo",
"Green Scirpo",
"Native Scirpo",
"Wood Scirpo",
"Wood Scirpo",
"Grassland Scirpo",
"Grassland Scirpo",
"Tree Scirpo",
"Green Scirpo",
"Yelena, the Sequestered",
"Lepidolite Scirpo",
"Lepidolite Scirpo",
"Lapis Scirpo",
"Lapis Scirpo",
"Jade Scirpo",
"Jade Scirpo",
"Citrine Scirpo",
"Citrine Scirpo",
"Carnelian Scirpo",
"Carnelian Scirpo",
"Lepidolite Scirpo",
"Lepidolite Scirpo",
"Beach Forfex",
"Beach Forfex",
"Beach Forfex",
"Sea Forfex",
"Sea Forfex",
"Mother Forfex",
"Coral Forfex",
"Coral Forfex",
"Femme Forfex",
"Hydro Forfex",
"Hydro Forfex",
"Big Forfex",
"Beach Forfex",
"Sea Forfex",
"Sven, the Sturdy",
"Tourteau, the Delectable",
"Copper Cinicula",
"Bronze Cinicula",
"Bronze Cinicula",
"Iron Cinicula",
"Heavy Cinicula",
"Eckart, the Indestructible",
"Pure Cinicula",
"Pure Cinicula",
"Young Cinicula",
"Nocto Blatta",
"Nocto Blatta",
"Swift Blatta",
"Swift Blatta",
"Tough Blatta",
"Tough Blatta",
"Black Blatta",
"Black Blatta",
"Dark Blatta",
"Dark Blatta",
"Hell Blatta",
"Casper, the Unhealthy Eater",
"Egg Blatta",
"Lava Blatta",
"Chrysalis Blatta",
"Guise Blatta",
"Young Blatta",
"Mature Blatta",
"Creeping Blatta",
"Sneaking Blatta",
"Stalker Blatta",
"Crawler Blatta",
"Judge Blatta",
"Cursed Blatta",
"Pebble Blatta",
"Pebble Blatta",
"Swift Blatta",
"Swift Blatta",
"Tough Blatta",
"Tough Blatta",
"Black Blatta",
"Black Blatta",
"Dark Blatta",
"Dark Blatta",
"Agito, the Golden",
"Roimi, the Affluent",
"White Blatta",
"Metal Blatta",
"Wootz Blatta",
"Platinum Blatta",
"Diamond Blatta",
"Moon Blatta",
"Lark Turba",
"Miniature Adsecula",
"Miniature Adsecula",
"Miniature Adsecula",
"Shadow Adsecula",
"Shadow Adsecula",
"Shadow Adsecula",
"Shadow Adsecula",
"Savanna Adsecula",
"Savanna Adsecula",
"Savanna Adsecula",
"Photon Adsecula",
"Photon Adsecula",
"Miniature Adsecula",
"Etutanne, the Bloodthirsty",
"Honey Papil",
"Honey Papil",
"Lake Papil",
"Lake Papil",
"River Papil",
"River Papil",
"Caranau, the Water Drake",
"Zeppelin Germivore",
"Saffron Germivore",
"Inferno Ictus",
"Inferno Ictus",
"Immortal Ictus",
"Immortal Ictus",
"Buoyant Lophid",
"Ocean Lophid",
"Ocean Lophid",
"Ocean Lophid",
"Marine Lophid",
"Marine Lophid",
"Marine Lophid",
"Ridill, the Arrogant",
"Cave Duoguill",
"Cave Duoguill",
"Placid Duoguill",
"Placid Duoguill",
"Placid Duoguill",
"Nether Duoguill",
"Nether Duoguill",
"Nether Duoguill",
"Blood Duoguill",
"Nether Duoguill",
"Nether Duoguill",
"Nether Duoguill",
"Nether Duoguill",
"Hephaestus, the Absconder",
"EN050401_NAME_C00",
"Sky Aetrygon",
"Lofty Aetrygon",
"Jet Aetrygon",
"Sea Xiphias",
"Sea Xiphias",
"Coral Xiphias",
"Shatskikh, the Flash",
"Sea Balaena",
"Rajidi, the Cumuliform",
"Valiant Ceto",
"Vanguard Ceto",
"Young Grex",
"Young Grex",
"Young Grex",
"Young Grex",
"Young Grex",
"Young Grex",
"Young Grex",
"Young Grex",
"Bush Grex",
"Bush Grex",
"Bush Grex",
"Bush Grex",
"Bush Grex",
"Giant Grex",
"Giant Grex",
"Giant Grex",
"Lawless Grex",
"Lawless Grex",
"Lawless Grex",
"Lawless Grex",
"Lawless Grex",
"Lawless Grex",
"Young Grex",
"Bush Grex",
"Giant Grex",
"Lawless Grex",
"Dieter, the Epicure",
"EN060303_NAME_E00",
"Celestin, the Spring Storm",
"Young Simius",
"Rock Simius",
"Rock Simius",
"Rock Simius",
"Iron Simius",
"Iron Simius",
"Blitz Simius",
"Blitz Simius",
"Mighty Simius",
"Mighty Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Juvenile Simius",
"Hayreddin, the Territorial",
"Hayreddin, the Territorial",
"Tranquil Aprica",
"Daylight Aprica",
"Brass Suid",
"Brass Suid",
"Brass Suid",
"Iron Suid",
"Iron Suid",
"Iron Suid",
"Steel Suid",
"Steel Suid",
"Steel Suid",
"Adamant Suid",
"Adamant Suid",
"Adamant Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Gugli, the Relentless",
"EN060701_NAME_F00",
"Domestic Armored Suid",
"EN060702_NAME_B00",
"Trained Armored Suid",
"Tough Armored Suid",
"Bogdan, the Dense",
"Brass Femina Suid",
"Brass Femina Suid",
"Brass Femina Suid",
"Iron Femina Suid",
"Iron Femina Suid",
"Iron Femina Suid",
"Steel Femina Suid",
"Steel Femina Suid",
"Steel Femina Suid",
"Bronze Femina Suid",
"Bronze Femina Suid",
"Bronze Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Grassland Ovis",
"Docile Ovis",
"Rogue Ovis",
"Baabara, the Evangelical",
"Stray Ovis",
"Eternal Millesaur",
"Everlasting Millesaur",
"Everlasting Millesaur",
"Luciel, the Eternal",
"Quick Evello",
"Fleet Evello",
"Quick Evello",
"Quick Evello",
"Fleet Evello",
"Fleet Evello",
"Swift Evello",
"Swift Evello",
"Roderick, the Fleet-Footed",
"Durvin, the Perceptive",
"Lugalbanda, the Wanderer-King",
"Wood Lepyx",
"Prairie Lepyx",
"Highland Lepyx",
"Wood Lepyx",
"Sirene, the Lost",
"Plant Mortifole",
"Lake Mortifole",
"Pit Mortifole",
"Pit Mortifole",
"Native Mortifole",
"Origin Mortifole",
"Venomous Mortifole",
"Shadow Mortifole",
"Cave Mortifole",
"Crazed Mortifole",
"Specter Mortifole",
"Reaver Auravis",
"Sky Auravis",
"Welkin Auravis",
"Welkin Auravis",
"Welkin Auravis",
"Reaver Auravis",
"Reaver Auravis",
"Sky Auravis",
"Sky Auravis",
"Highland Auravis",
"Welkin Auravis",
"Bohdan, the Mistral",
"Welkin Levitath",
"Welkin Levitath",
"Sapphire Levitath",
"Sapphire Levitath",
"Eutropio, the Sea Rumble",
"Nocturnal Vesper",
"Nocturnal Vesper",
"Blind Vesper",
"Blind Vesper",
"Dark Vesper",
"Dark Vesper",
"Mortal Vesper",
"Mortal Vesper",
"Ripper Vesper",
"Ripper Vesper",
"Abyssal Vesper",
"Abyssal Vesper",
"Necro, the Cavelord",
"Lake Terebra",
"Lake Terebra",
"Pit Terebra",
"Whirling Terebra",
"Whirling Terebra",
"Whirling Terebra",
"Whirling Terebra",
"Aquatic Terebra",
"Fell Terebra",
"Archibolt, the Revolutionary",
"Jocular Saltat",
"Droll Saltat",
"Sapara, the Laconic",
"Cobalt Saltat",
"Viridian Saltat",
"Saffron Saltat",
"Saffron Saltat",
"Citrine Saltat",
"Citrine Saltat",
"Carnelian Saltat",
"Garnet Saltat",
"Zdenka, the Raucous",
"Amber Saltat",
"Ruby Saltat",
"Stone Potamus",
"Stone Potamus",
"Stone Potamus",
"Rock Potamus",
"Huge Potamus",
"Huge Potamus",
"Huge Potamus",
"Mesgen, the Fairweathered",
"Pebble Blatta",
"Swift Blatta",
"Tough Blatta",
"Hrym Blatta",
"Seeker Blatta",
"Sonic Blatta",
"Prinsipe, the Ravenous",
"Mirror Blatta",
"Camus, the Treasured",
"Natt, the Inestimable",
"Drone Pawn Quo",
"Drone Knight Quo",
"Drone Rook Quo",
"Drone Queen Quo",
"Frontline Medic Quo",
"Thug Mephite",
"Lawless Mephite",
"Evil Mephite",
"Evil Mephite",
"Evil Mephite",
"Evil Mephite",
"Evil Mephite",
"Evil Mephite",
"Evil Mephite",
"Thulium Petramand",
"Samarium Petramand",
"Gadolinium Petramand",
"Erbium Petramand",
"Eisen, the Ebon Rock",
"Scandium Petramand",
"Yttrium Petramand",
"Praseodymium Petramand",
"Europium Petramand",
"EN040110_NAME_E00",
"Holmium Petramand",
"Truppe, the Ceaseless Dark",
"Dysprosium Petramand",
"Terbium Petramand",
"Lutetium Petramand",
"Piernus, the Scorcher",
"Toy Monoceros",
"Pony Monoceros",
"Monoceros Colt",
"Uluora, the Burgeoning",
"EN060401_NAME_F00",
"EN060401_NAME_F00",
"Cliff Monoceros",
"Land Monoceros",
"Volcannon Monoceros",
"Dawid, the Destrier",
"Recluse Adsecula",
"Faded Adsecula",
"Lava Caro",
"Lava Caro",
"Lava Caro",
"Lava Caro",
"Lava Caro",
"Lava Caro",
"Servant Caro",
"Deadland Caro",
"Deadland Caro",
"Kringe, the Hunting Arrow",
"Spaniel, the Obedient",
"Battler Caro",
"Legion Caro",
"Arch Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Lost Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Legion Caro",
"Andrei, the Cunning",
"Blitz Scintimure",
"Thunder Scintimure",
"Lightning Scintimure",
"Eddy, the Electric Heat",
"Rain Scintimure",
"Storm Scintimure",
"Tempest Scintimure",
"Coil, the Never-Ending",
"Cowardly Caecus",
"Thug Caecus",
"Bluff Caecus",
"Cliff Caecus",
"Cliff Caecus",
"Cliff Caecus",
"Cliff Caecus",
"Cliff Caecus",
"Cliff Caecus",
"Pelicollo, the Panzer",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Barrager",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Marnuck Zeta",
"Marnuck Zeta",
"Milsaadi Psycho",
"Milsaadi Rampager",
"Milsaadi Savage",
"Chantai, the Insect Maiden",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Duran, the Draconian",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Imperial",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Gatling",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Guard",
"Marnuck Guard",
"Marnuck Guard",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Elite",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Royal",
"Marnuck Royal",
"Marnuck Royal",
"Marnuck Royal",
"Marnuck Royal",
"Marnuck Royal",
"Marnuck Pulser",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Royal",
"Marnuck Dynamo",
"Marnuck Elite",
"Marnuck Mercenary",
"Marnuck Guard",
"Marnuck Transitioner",
"Marnuck Elite",
"Marnuck Elite",
"Berserker Marnuck",
"Strike Sniper Zig",
"Strike Barrager Zig",
"Strike Gunner Zig",
"Strike Launcher Zig",
"Experimental Compact Zig",
"Revolver Sniper Zig",
"Revolver Barrager Zig",
"Auto Gunner Zig",
"Revolver Launcher Zig",
"Enhanced Search Zig",
"Mortar Sniper Zig",
"Mortar Barrager Zig",
"Mortar Gunner Zig",
"Mortar Launcher Zig",
"Unlimited Output Zig",
"Palace Sniper Zig",
"Palace Barrager Zig",
"Palace Gunner Zig",
"Palace Launcher Zig",
"Enhanced Support Zig",
"Assault Sniper Zig",
"Assault Barrager Zig",
"Assault Gunner Zig",
"Assault Launcher Zig",
"Vulcan Sniper Zig",
"Vulcan Barrager Zig",
"Vulcan Gunner Zig",
"Vulcan Launcher Zig",
"Experimental Second-Gen Zig",
"Howitzer Sniper Zig",
"Howitzer Barrager Zig",
"Howitzer Gunner Zig",
"Howitzer Launcher Zig",
"Enhanced Attack Range Zig",
"Enhanced Sniper Zig",
"Enhanced Barrager Zig",
"Enhanced Gunner Zig",
"Enhanced Launcher Zig",
"Milsaadi Fighter",
"Milsaadi Fighter",
"Milsaadi Hunter",
"Milsaadi Hunter",
"Milsaadi Assassin",
"Milsaadi Assassin",
"Milsaadi Assassin",
"Milsaadi Assassin",
"Milsaadi Assassin",
"Sharnaak, the Technician",
"Coast Visigel",
"Cave Visigel",
"Sea Visigel",
"Razer Visigel",
"Poppy, the Pyromaniac",
"Coal Cinicula",
"Magma Cinicula",
"Lava Cinicula",
"Calore, the Lava Walker",
"Talon Knight Qmoeva",
"Barbed Rook Qmoeva",
"Barbed Queen Qmoeva",
"Barbed King Qmoeva",
"Palace Knight Qmoeva",
"Palace Rook Qmoeva",
"Purger Queen Qmoeva",
"Palace King Qmoeva",
"War Empress Qmoeva",
"War Emperor Qmoeva",
"War Kaizer Qmoeva",
"Urdu's Qmoeva",
"Multi Knight Qmoeva",
"Brave Rook Qmoeva",
"Brave Queen Qmoeva",
"Multi King Qmoeva",
"Suppressor Knight Qmoeva",
"Suppressor Rook Qmoeva",
"True Queen Qmoeva",
"Rebel King Qmoeva",
"Valiant Ceto",
"Vanguard Ceto",
"Polaris, the Firmamental",
"Volcannon Vigent",
"Vainamo, the Bellower",
"Rocket Jacul",
"Storm Jacul",
"Tornado Jacul",
"Jia Mian, the Beloved",
"Blazing Lophid",
"Flame Lophid",
"Blast Lophid",
"Gehenna Lophid",
"Izgnanie, the Smoldering",
"Alithios, the Indignant",
"Talon Owl Galdr",
"Talon Raptor Galdr",
"Talon Eagle Galdr",
"Talon Eagle Galdr",
"Armed Recon Galdr",
"Revolver Owl Galdr",
"Revolver Raptor Galdr",
"Revolver Eagle Galdr",
"Armed Engineer Galdr",
"Chantai's Galdr",
"Guide Owl Galdr",
"Guide Raptor Galdr",
"Guide Eagle Galdr",
"Air Support Galdr",
"Gun Owl Galdr",
"Gun Raptor Galdr",
"Gun Eagle Galdr",
"Armed Destroyer Galdr",
"Gigas Gularth",
"Atlas Gularth",
"Gaia Gularth",
"Ilithios, the Enlightened",
"Enhanced Attack Seidr",
"Armored Cruiser Seidr",
"Enhanced Defense Seidr",
"Enhanced Defense Seidr",
"Sharnaak's Seidr",
"EN070503_NAME_F00",
"Vortice, the Deific Blast",
"Vortice, the Deific Blast",
"Selenium Fal-swo",
"Rhenium Fal-swo",
"Rhenium Fal-swo",
"Rhenium Fal-swo",
"Ya-rhat, the Thundercloud",
"Selenium Oc-serv",
"Tantalum Oc-serv",
"Rhenium Oc-serv",
"Rhenium Oc-serv",
"Rhenium Oc-serv",
"Rhenium Oc-serv",
"Rhenium Oc-serv",
"Na-mulk, the Rebellious",
"Beryllium Oc-serv",
"Bismuth Oc-serv",
"Strontium Xe-dom",
"Strontium Xe-dom",
"Gi-zho, the Iron Deity",
"Gi-zho, the Iron Deity",
"Aquatic Sacrifole",
"Puddle Sacrifole",
"Lake Sacrifole",
"Foul Sacrifole",
"Angelita, the Blade Bouquet",
"Lava Sacrifole",
"Volcannon Sacrifole",
"Vegetal, the Heatcrux",
"Cloud Saltat",
"Zorn, the Wanderer",
"Porter Puge",
"Cavalier Puge",
"Solid Puge",
"Coffin Puge",
"Night Combat Puge",
"Broadsword Pugilith",
"Lance Pugilith",
"Grand Cantor",
"Grand Cantor",
"Warlord Ictus",
"Chieftain Ictus",
"Daimyo Ictus",
"Terenty, the Blademaster",
"Terenty, the Blademaster",
"Orion Xern",
"Leva'el, the Terminus",
"Sentinel Satellis",
"Sentinel Satellis",
"Magma Tersqual",
"Lava Tersqual",
"Volcannon Tersqual",
"Agnes, the Divine-Scaled",
"Fleet Shrad",
"Quick Shrad",
"Quick Shrad",
"Quick Shrad",
"Quick Shrad",
"Swift Shrad",
"Swift Shrad",
"Swift Shrad",
"Swift Shrad",
"Swift Shrad",
"Swift Shrad",
"Jet Shrad",
"Sector Security Shrad",
"Barrager Shrad",
"Rocket Shrad",
"Mach Shrad",
"Experimental Flight Shrad",
"Minion Potamus",
"Brother Potamus",
"Companion Potamus",
"Rodriguez, the Twin-Tusked",
"Egg Blatta",
"Lava Blatta",
"Chrysalis Blatta",
"Guise Blatta",
"Coal Blatta",
"Mature Blatta",
"Stalker Blatta",
"Vampire Blatta",
"Hellion Blatta",
"Cursed Blatta",
"EN061301_NAME_C00",
"EN061301_NAME_C00",
"Bluff Gerrid",
"Bluff Gerrid",
"Land Gerrid",
"Land Gerrid",
"Volcannon Gerrid",
"Volcannon Gerrid",
"Bartley, the Conflagration",
"Silent Murra",
"Quiet Murra",
"Strange Murra",
"Uncanny Murra",
"EN070702_NAME_E00",
"Phosphorous Filiavent",
"Trueno, the Cataclysm",
"WR512: Urdu",
"Luminous Puge",
"Fighter Puge",
"Knight Puge",
"Guardian Puge",
"Lord Puge",
"Dagger Pugilith",
"Knight Pugilith",
"Guardian Pugilith",
"Lord Pugilith",
"High-Output Pugilith",
"Red Master Galdr",
"Lyla's Galdr",
"Magna Galdr",
"Green Lance Galdr",
"Green Lance Galdr",
"Green Lance Galdr",
"Machine Rook Quo",
"Machine Rook Quo",
"Machine Queen Quo",
"Machine King Quo",
"Titanium Oc-serv",
"Titanium Oc-serv",
"Titanium Oc-serv",
"Titanium Oc-serv",
"Oc-serv, the Ancient",
"Tellurium Oc-serv",
"Niobium Oc-serv",
"Thallium Oc-serv",
"Bismuth Oc-serv",
"Bismuth Oc-serv",
"Thallium Oc-serv",
"Talon Queen Qmoeva",
"War Kaizer Qmoeva",
"Striker Qmoeva",
"Palace King Qmoeva",
"Multi Rook Qmoeva",
"Multi Queen Qmoeva",
"Rebel Kaizer Qmoeva",
"Suppressor Rook Qmoeva",
"Suppressor Queen Qmoeva",
"True King Qmoeva",
"Sadar's Qmoeva",
"EN011804_NAME_F00",
"Badul's Seidr",
"Ahama's Seidr",
"Orion Xern",
"Luxaar's Xern",
"Swift Shrad",
"Jet Shrad",
"Hazard Shrad",
"Avaricious Shrad",
"Du-rha, the Imprisoned",
"Molybdenum Xe-dom",
"Bismuth Xe-dom",
"Go-rha, the Guardian Deity",
"Assault Barrager Zig",
"Assault Gunner Zig",
"Assault Launcher Zig",
"Vulcan Barrager Zig",
"Vulcan Gunner Zig",
"Vulcan Launcher Zig",
"Howitzer Barrager Zig",
"Howitzer Gunner Zig",
"Howitzer Launcher Zig",
"Damaged Zig",
"Enhanced Barrager Zig",
"Enhanced Gunner Zig",
"Enhanced Launcher Zig",
"Niobium Fal-swo",
"Rubidium Fal-swo",
"Thallium Fal-swo",
"Stainless Fal-swo",
"Tellurium Fal-swo",
"Chromium Fal-swo",
"Ga-uhl, the Precept-Keeper",
"Marnuck Captain",
"Marnuck Admiral",
"Sadar, the Unhinged",
"Marnuck Sentinel",
"Marnuck Vanguard",
"Marnuck Assaulter",
"Marnuck Elite",
"Marnuck Gamma",
"Marnuck Delta",
"Marnuck Epsilon",
"Ahama, the Covetous",
"Milsaadi Executioner",
"Milsaadi Specter",
"Badul, the One-Eyed",
"Milsaadi Hitman",
"Milsaadi Champion",
"Lyla, the Lustrous",
"Milsaadi Executioner",
"Mountain Sylooth",
"Territorial Sylooth",
"Anselm, the Triumphant",
"Prone Soldier",
"Prone Commander",
"Prone Sorcerer",
"Prone Vix Beta",
"Prone Vix Alpha",
"Prone Vix Delta",
"Lantern Petramand",
"Ceres Petramand",
"Lutetia Petramand",
"Candelario, the Bronze",
"Amrita Scirpo",
"Amrita Scirpo",
"Nectar Scirpo",
"Nectar Scirpo",
"Haoma Scirpo",
"Haoma Scirpo",
"Kvass Scirpo",
"Kvass Scirpo",
"Iolite Forfex",
"Sapphire Forfex",
"Sapphire Forfex",
"Viridian Forfex",
"Viridian Forfex",
"Iolite Forfex",
"Sapphire Forfex",
"Viridian Forfex",
"Tourteau, the Delectable",
"EN040204_NAME_C00",
"Shadow Falsaxum",
"EN040204_NAME_E00",
"Mikulas, the Keystone",
"Translucent Cinicula",
"Light Cinicula",
"Glowing Cinicula",
"Moon Cinicula",
"Translucent Cinicula",
"Light Cinicula",
"Glowing Cinicula",
"Moon Cinicula",
"Thaddaeus, the Ultramafic",
"EN040401_NAME_C00",
"Carrion Vivohast",
"Carrion Vivohast",
"Carrion Vivohast",
"Grand Vivohast",
"Grand Vivohast",
"Lethal Vivohast",
"Lethal Vivohast",
"Lockhart, the Killer of Hope",
"Smalt Arenatect",
"Cerulean Arenatect",
"Turqoise Arenatect",
"Smalt Arenatect",
"Cerulean Arenatect",
"Turqoise Arenatect",
"Man'an, the Water Whisperer",
"Chartreuse Arenatect",
"Saffron Arenatect",
"Topaz Arenatect",
"Antara, the Water Diviner",
"Pebble Blatta",
"Swift Blatta",
"Tough Blatta",
"Mirage Blatta",
"Green Blatta",
"Hell Blatta",
"Egg Blatta",
"Lava Blatta",
"Chrysalis Blatta",
"Guise Blatta",
"Young Blatta",
"Mature Blatta",
"Creeping Blatta",
"Sneaking Blatta",
"Chartreuse Blatta",
"Tranquil Blatta",
"Judge Blatta",
"Azure Blatta",
"Hiro, the Priceless",
"Ald, the Extravagant",
"White Blatta",
"Metal Blatta",
"Wootz Blatta",
"Platinum Blatta",
"Diamond Blatta",
"Crystal Blatta",
"Vorpall, the Sickle-Fanged",
"Crane Turba",
"Crane Turba",
"Crane Turba",
"Sparrow Adsecula",
"Penetrator Adsecula",
"Endeavorer Adsecula",
"Sparrow Adsecula",
"Penetrator Adsecula",
"Endeavorer Adsecula",
"Sparrow Adsecula",
"Penetrator Adsecula",
"Endeavorer Adsecula",
"Photon Adsecula",
"Druid Papil",
"Sorcerer Papil",
"Witch Papil",
"Wizard Papil",
"Magus Papil",
"Magus Papil",
"Magus Papil",
"Magus Papil",
"Magus Papil",
"Gloam Turba",
"Delft Turba",
"Feld, the Indigo-Clad",
"Skulker Germivore",
"Skulker Germivore",
"Echo Germivore",
"Echo Germivore",
"Shadow Germivore",
"Secret Germivore",
"Survivor Germivore",
"Survivor Germivore",
"Lethal Germivore",
"Florence, the Hell Maggot",
"Atreides, the Distinguished",
"Atreides, the Distinguished",
"Sandy Sabula",
"Sandy Sabula",
"Atreides, the Distinguished",
"Gesserith, the Wileworm",
"Sand Aeviter",
"Macabre Aeviter",
"Macabre Aeviter",
"Berthold, the Blue-Eyed",
"Secret Germivore",
"Warlord Ictus",
"Chieftain Ictus",
"Chieftain Ictus",
"Hermit Ictus",
"Hermit Ictus",
"EN041102_NAME_A00",
"EN041102_NAME_A00",
"EN041102_NAME_A00",
"EN050202_NAME_D00",
"EN050202_NAME_E00",
"EN050202_NAME_F00",
"Darling Purgovent",
"Darling Purgovent",
"Darling Purgovent",
"Darling Purgovent",
"Darling Purgovent",
"Albin, the Wicked Meddler",
"Plasma Duoguill",
"Plasma Duoguill",
"Valeriano, the Rolling Thunder",
"EN050304_NAME_C00",
"EN050304_NAME_D00",
"Spore Scintimure",
"Blind Scintimure",
"Zohan, the Thunderbolt",
"EN050305_NAME_C00",
"Glimmering Scintimure",
"Bright Scintimure",
"Statue Scintimure",
"Legato, the Sky Watcher",
"Sky Aetrygon",
"Lofty Aetrygon",
"Jet Aetrygon",
"Ramus, the Supersonic",
"Ripple Xiphias",
"Ruby Xiphias",
"Cave Xiphias",
"Brandys, the Spectral Light",
"Storm Caro",
"Sand Caro",
"Prisoner Caro",
"Little Caro",
"Little Caro",
"Little Caro",
"Little Caro",
"Andrei, the Cunning",
"Berserk Vigent",
"Brutal Vigent",
"Seeker Vigent",
"Goliath, the Stronghold",
"Nether Virago",
"Behemoth, the Netherdweller",
"Shadow Monoceros",
"Viridian Monoceros",
"EN060403_NAME_E00",
"Alexei, the Jade",
"White Progen",
"White Progen",
"Mountain Progen",
"Blaudolch, the Chalcedony",
"Canyon Cantor",
"Canyon Cantor",
"Cave Cantor",
"Cave Cantor",
"Eustachio, the Eccentric",
"Recluse Cantor",
"Leandro, the Sneering",
"Shaman Cervus",
"Old Cervus",
"Asana, the Azure Star",
"Origin Cantor",
"White Ovis",
"White Ovis",
"White Ovis",
"White Ovis",
"White Ovis",
"Wandering Ovis",
"Wandering Ovis",
"Wandering Ovis",
"Native Ovis",
"Native Ovis",
"Native Ovis",
"Clara, the Pure White",
"Native Ovis",
"Wandering Ovis",
"Ancient Coronid",
"Ancient Coronid",
"Frenzied Coronid",
"Ignit, the Ultimate Chaos",
"Poisonous Caecus",
"Villainous Caecus",
"Villainous Caecus",
"Villainous Caecus",
"Villainous Caecus",
"Villainous Caecus",
"Villainous Caecus",
"Villainous Caecus",
"Hell Caecus",
"Andrea, the Famished Hunter",
"Pollen Lepyx",
"Nomad Lepyx",
"Stray Lepyx",
"Giraffin, the Old Hand",
"Macabre Gerrid",
"Macabre Gerrid",
"Evil Gerrid",
"Daemon, the Undertaker",
"Abyssal Sacrifole",
"Giant Sacrifole",
"Giant Sacrifole",
"Mega Sacrifole",
"Mega Sacrifole",
"Dobromila, the Alluring",
"Puddle Sacrifole",
"Lake Sacrifole",
"Foul Sacrifole",
"Pyro Sacrifole",
"Vegetal, the Heatcrux",
"Dazzling Liceor",
"Awakened Liceor",
"Dazzling Liceor",
"Awakened Liceor",
"Canyon Jacul",
"Highland Jacul",
"Canyon Jacul",
"Canyon Jacul",
"Highland Jacul",
"Highland Jacul",
"Radovan, the Sky Baron",
"Young Unafulge",
"Creek Unafulge",
"Creek Unafulge",
"Floating Unafulge",
"Floating Unafulge",
"Dryland Unafulge",
"Dryland Unafulge",
"Lethal Unafulge",
"Lethal Unafulge",
"Abyssal Unafulge",
"Lake Visigel",
"Sapphire Visigel",
"Yune, the Ambusher",
"Lava Unafulge",
"Ruth, the Shunner of Light",
"Spore Filiavent",
"Laurencio, the Fog Bow",
"Pharsis, the Everqueen",
"Hushed Murra",
"Quiet Murra",
"Strange Murra",
"Uncanny Murra",
"Camille, the Immortal",
"Thug Mephite",
"Prankster Mephite",
"Lask, the Unscrupulous",
"Strange Liceor",
"Strange Liceor",
"Strange Liceor",
"Strange Liceor",
"Strange Liceor",
"Glowing Liceor",
"Glowing Liceor",
"Glowing Liceor",
"Dazzling Liceor",
"Stola, the Champion",
"EN090206_NAME_D00",
"Awakened Liceor",
"Divine Liceor",
"Stola, the Unchained",
"Minion Potamus",
"Minion Potamus",
"Minion Potamus",
"Caelum Tersqual",
"Lively Tersqual",
"Latis, the Bristle-Scaled",
"Dagger Puge",
"Border Puge",
"Buster Puge",
"Fighter Pugilith",
"Knight Pugilith",
"Guide Owl Galdr",
"Guide Raptor Galdr",
"Duran's Galdr",
"Drone Knight Quo",
"Rubidium Oc-serv",
"EN011302_NAME_D00",
"Si-el, the Vacuous",
"Palace Knight Qmoeva",
"Infantry Support Qmoeva",
"Go-rha, the Guardian Deity",
"Multi Knight Qmoeva",
"Suppressor Knight Qmoeva",
"Niobium Fal-swo",
"Rubidium Fal-swo",
"Thallium Fal-swo",
"Marnuck Sentinel",
"Marnuck Gamma",
"Colossal Sylooth",
"Colossal Sylooth",
"Colossal Sylooth",
"Colossal Sylooth",
"Goliath Sylooth",
"Goliath Sylooth",
"Brobdingnagian Sylooth",
"Yama, the Obliviator",
"Pyotr, the Shepherd",
"Prone Butcher",
"Prone Butcher",
"Prone Butcher",
"Prone Warrior",
"Prone Owl",
"Prone Butcher",
"Prone Owl",
"Prone Eagle",
"Prone Savage",
"Soma Scirpo",
"Amrita Scirpo",
"Amrita Scirpo",
"Surtr Scirpo",
"Surtr Scirpo",
"Tharros Scirpo",
"Breather Scirpo",
"Native Scirpo",
"Merciful Scirpo",
"Merciful Scirpo",
"Merciful Scirpo",
"Scandium Petramand",
"Holmium Petramand",
"Lepidolite Scirpo",
"Lepidolite Scirpo",
"Pillager Scirpo",
"Pillager Scirpo",
"Carnelian Scirpo",
"Carnelian Scirpo",
"Garnet Scirpo",
"Garnet Scirpo",
"Desdemona, the Subterranean",
"Carmine Forfex",
"Garnet Forfex",
"Ruby Forfex",
"Ocean Forfex",
"Violet Forfex",
"Cobalt Forfex",
"Viridian Forfex",
"Saffron Forfex",
"Schneider, the Cliffpercher",
"Elena, the Infernal",
"Rock Cinicula",
"Rock Cinicula",
"Star Cinicula",
"Rock Cinicula",
"Iron Cinicula",
"Lake Falsaxum",
"Lake Falsaxum",
"Ghillie Falsaxum",
"Ghillie Falsaxum",
"Clemente, the Iron Meteor",
"EN040205_NAME_A00",
"EN040205_NAME_B00",
"Falchion, the Vibrant",
"Mirage Vivohast",
"Echo Thallus",
"Echo Thallus",
"Echo Thallus",
"Echo Thallus",
"False Thallus",
"EN040402_NAME_D00",
"EN040402_NAME_D00",
"Cunning Thallus",
"Pizelle, the Purple Lightning",
"Hermit Tectinsula",
"Hermit Tectinsula",
"Negator Tectinsula",
"Silhouette Tectinsula",
"Silhouette Tectinsula",
"Stealth Tectinsula",
"Banisher Tectinsula",
"Alfombra, the Transcendent",
"Pebble Blatta",
"Blitz Blatta",
"Ogre Blatta",
"Black Blatta",
"Logi Blatta",
"Logi Blatta",
"Squall Blatta",
"Egg Blatta",
"Lava Blatta",
"Chrysalis Blatta",
"Guise Blatta",
"Prairie Blatta",
"Mature Blatta",
"Creeping Blatta",
"Sneaking Blatta",
"Stalwart Blatta",
"Raven Blatta",
"Magus Blatta",
"Joker, the Unknowable",
"Muruse, the Opulent",
"Yuiro, the Luxuriant",
"Dove Turba",
"Dove Turba",
"Lark Turba",
"Kite Turba",
"Tormenta, the Scarlet-Clad",
"Miniature Adsecula",
"Forest Adsecula",
"Forest Adsecula",
"Forest Adsecula",
"Forest Adsecula",
"Forest Adsecula",
"Forest Adsecula",
"Dusk Adsecula",
"Giddy Adsecula",
"Copper Papil",
"Bronze Papil",
"Sacrum, the Noctilucent",
"EN040706_NAME_A00",
"Indigo Turba",
"Violet Germivore",
"Cobalt Germivore",
"Terrible Germivore",
"Terrible Germivore",
"Terrible Germivore",
"Saffron Germivore",
"Saffron Germivore",
"Minor Sabula",
"Crazed Aeviter",
"Balduino, the Wicked-Eyed",
"Balduino, the Wicked-Eyed",
"Tidal Purgovent",
"Electric Scintimure",
"Callous Scintimure",
"Tainted Scintimure",
"Tainted Scintimure",
"Beach Xiphias",
"Ocean Xiphias",
"EN050402_NAME_F00",
"EN050403_NAME_A00",
"Quick Aetrygon",
"Fleet Aetrygon",
"Lunar Ceto",
"Selenic Ceto",
"Tainted Caro",
"Fiendish Virago",
"Ogre Virago",
"Buchwald, the Guardian",
"Hallowed Progen",
"Lightning Progen",
"Sacred Progen",
"Sanctuary Progen",
"Shadow Monoceros",
"Viridian Monoceros",
"Raging Simius",
"Angry Simius",
"Striker Simius",
"Striker Simius",
"Wrathful Simius",
"Punisher Simius",
"Demetrio, the Tempestuous",
"Forest Aprica",
"Forest Aprica",
"Forest Aprica",
"Tranquil Aprica",
"Daylight Aprica",
"EN060601_NAME_F00",
"Oskar, the Summer Squall",
"Pastoral Cervus",
"Seti, the Light of Stars",
"River Suid",
"Forest Suid",
"Hill Suid",
"Miniature Suid",
"Lurker Suid",
"Olegario, the Iron-Helmed",
"River Femina Suid",
"Forest Femina Suid",
"Hill Femina Suid",
"Miniature Femina Suid",
"Lurker Femina Suid",
"Manuelita, the Affectionate",
"Heidi, the Lively",
"Claire, the Sheltered",
"Fernando, the Immovable",
"Sludge Caecus",
"Sludge Caecus",
"Darting Caecus",
"Darting Caecus",
"Drake, the Waypost",
"Spear Insidia",
"Pike Insidia",
"Lambert, the Divine Wind",
"Cardinal Insidia",
"Vermilion Insidia",
"Griffus, the Tartarean",
"Origin Mortifole",
"Lake Mortifole",
"Gardener Mortifole",
"Gardener Mortifole",
"Pit Mortifole",
"Pit Mortifole",
"Native Mortifole",
"Native Mortifole",
"Origin Mortifole",
"Origin Mortifole",
"Yessenia, the Husky-Voiced",
"Mimic Mortifole",
"Mimic Mortifole",
"Mirage Mortifole",
"Ghost Mortifole",
"Shadow Mortifole",
"Grotto Mortifole",
"Callous Mortifole",
"Crusher Mortifole",
"Katerina, the Cliffhanger",
"Wind Auravis",
"Mountain Jacul",
"Scarlet Levitath",
"Antares Levitath",
"Frajeel, the Purgatorial",
"Shuravas, the Enraged",
"Spring Unafulge",
"Drifter Unafulge",
"Planetes, the Torrential",
"Spore Filiavent",
"Telethia, the Endbringer",
"Abyssal Vesper",
"Froste, the Courteous",
"Shinhwa, the Sagacious",
"Mischievous Mephite",
"Impish Mephite",
"Malicious Mephite",
"Gerhardt, the Lone and Proud",
"River Terebra",
"Pond Terebra",
"Nomad Terebra",
"Crusher Terebra",
"Jocular Saltat",
"Aria, the Zauberflöte",
"Jade Saltat",
"Jarosch, the Sensational",
"Merciful Dilus",
"Acid Dilus",
"Hunter Dilus",
"Sarcosuchus, the Iron-Eater",
"Dagger Puge",
"Sword Puge",
"Buster Puge",
"Lance Puge",
"Master Puge",
"Sword Pugilith",
"Buster Pugilith",
"Spear Pugilith",
"Master Pugilith",
"Raider Pugilith",
"Revolver Eagle Galdr",
"Vendura's Galdr",
"Drone King Quo",
"Chromium Oc-serv",
"Zirconium Oc-serv",
"Ro-darm, the Demon Claw",
"Assault Qmoeva",
"Talon Queen Qmoeva",
"Talon King Qmoeva",
"Palace Rook Qmoeva",
"Palace Queen Qmoeva",
"Palace King Qmoeva",
"Multi Rook Qmoeva",
"Multi Queen Qmoeva",
"Multi King Qmoeva",
"Suppressor Rook Qmoeva",
"Rebel Kaizer Qmoeva",
"Suppressor King Qmoeva",
"Nu-rhor, the Dark Deity",
"Strike Sniper Zig",
"Strike Barrager Zig",
"Strike Gunner Zig",
"Strike Launcher Zig",
"Revolver Sniper Zig",
"Revolver Barrager Zig",
"Revolver Gunner Zig",
"Revolver Launcher Zig",
"Mortar Sniper Zig",
"Mortar Barrager Zig",
"Mortar Gunner Zig",
"Mortar Launcher Zig",
"Palace Sniper Zig",
"Palace Barrager Zig",
"Palace Gunner Zig",
"Palace Launcher Zig",
"Chromium Fal-swo",
"Nickel Fal-swo",
"Titanium Fal-swo",
"Zirconium Fal-swo",
"No-dhor, the Shadowcaster",
"Gadaf, the Pulverizer",
"Marnuck Admiral",
"Marnuck General",
"Marnuck Admiral",
"Marnuck General",
"Marnuck Admiral",
"Marnuck General",
"Marnuck Damager",
"Marnuck General",
"Marnuck Admiral",
"Marnuck General",
"Marnuck Admiral",
"Marnuck General",
"Marnuck Admiral",
"Marnuck General",
"Marnuck Admiral",
"Marnuck General",
"Marnuck Scout",
"Marnuck Sentinel",
"Marnuck Vanguard",
"Marnuck Scout",
"Marnuck Vanguard",
"Marnuck Vanguard",
"Marnuck Scout",
"Marnuck Sentinel",
"Marnuck Vanguard",
"Marnuck Scout",
"Marnuck Sentinel",
"Marnuck Guardian",
"Marnuck Scout",
"Marnuck Sentinel",
"Marnuck Vanguard",
"Marnuck Beta",
"Marnuck Gamma",
"Marnuck Delta",
"Canyon Sylooth",
"Highland Sylooth",
"Plateau Sylooth",
"Plateau Sylooth",
"Climati, the Chilling Wind",
"Prone Fighter",
"Prone Warrior",
"Prone Butcher",
"Prone Bully",
"Prone Warrior",
"Prone Berserker",
"Prone Fighter",
"Prone Eater",
"Prone Butcher",
"Prone Bully",
"Prone Warrior",
"Prone Berserker",
"Prone Fighter",
"Prone Eater",
"Prone Purger",
"Prone Bully",
"Prone Warrior",
"Prone Berserker",
"Prone Fighter",
"Prone Eater",
"Prone Butcher",
"Prone Vulture",
"Prone Warrior",
"Prone Berserker",
"Prone Berserker",
"Prone Fighter",
"Prone Eater",
"Prone Butcher",
"Prone Hawk",
"Prone Warrior",
"Prone Berserker",
"Prone Fighter",
"Prone Barbarian",
"Prone Butcher",
"Prone Bully",
"Prone Warrior",
"Prone Berserker",
"Prone Fighter",
"Prone Eater",
"Prone Butcher",
"Prone Bully",
"Prone Fury",
"Prone Berserker",
"Prone Admiral",
"Prone Berserker",
"Prone Fighter",
"Prone Condemned",
"Prone Butcher",
"Prone Bully",
"Prone Savage",
"Prone Berserker",
"EN021001_NAME_A00",
"Prone Vix Guard",
"Prone Savage",
"Prone Brutalizer",
"Prone Fury",
"Prone Spartan",
"Prone Spartan",
"EN021001_NAME_A00",
"Prone Barbarian",
"Prone Vix Crow",
"Prone Brutalizer",
"Prone Fury",
"Prone Spartan",
"EN021001_NAME_A00",
"Prone Barbarian",
"Prone Savage",
"Prone Brutalizer",
"Prone Fury",
"Prone Spartan",
"Vendura, the Spellbinder",
"Dadaan, the Strongest Prone",
"The Dadaan Girls",
"The Dadaan Girls",
"Dadaan Squad Member",
"Dadaan Squad Member",
"Dadaan Squad Member",
"Dadaan Squad Member",
"Dadaan Squad Member",
"Dadaan Squad Member",
"Dadaan Squad Member",
"Dadaan Squad Member",
"Prometheus Petramand",
"Prometheus Petramand",
"Ytterby Petramand",
"Ytterby Petramand",
"Malium Petramand",
"Malium Petramand",
"Logi Scirpo",
"Logi Scirpo",
"Bacchanal Scirpo",
"Bacchanal Scirpo",
"Wood Scirpo",
"Wood Scirpo",
"Logi Scirpo",
"Logi Scirpo",
"Bacchanal Scirpo",
"Bacchanal Scirpo",
"Green Scirpo",
"Green Scirpo",
"Shadow Scirpo",
"Shadow Scirpo",
"Jade Scirpo",
"Jade Scirpo",
"Jade Scirpo",
"Jade Scirpo",
"Shadow Scirpo",
"Shadow Scirpo",
"Jade Scirpo",
"Jade Scirpo",
"Citrine Scirpo",
"Citrine Scirpo",
"Sand Forfex",
"Sand Forfex",
"Land Forfex",
"Land Forfex",
"Dryland Forfex",
"Dryland Forfex",
"Native Forfex",
"Native Forfex",
"Lake Falsaxum",
"Lake Falsaxum",
"Putrid Falsaxum",
"Putrid Falsaxum",
"Shadow Falsaxum",
"Shadow Falsaxum",
"Putrid Falsaxum",
"Putrid Falsaxum",
"Recluse Thallus",
"Recluse Thallus",
"Faded Thallus",
"Faded Thallus",
"Mirage Thallus",
"Mirage Thallus",
"Edgardo, the Carefree",
"Soil Tectinsula",
"Soil Tectinsula",
"Clay Tectinsula",
"Clay Tectinsula",
"Clay Tectinsula",
"Clay Tectinsula",
"Clay Tectinsula",
"Tectonic Tectinsula",
"Tectonic Tectinsula",
"Vittorio, the Battle-Scarred",
"Egg Blatta",
"Zeppelin Blatta",
"Chrysalis Blatta",
"Guise Blatta",
"Young Blatta",
"Mature Blatta",
"Zeppelin Blatta",
"Chrysalis Blatta",
"Guise Blatta",
"Creeping Blatta",
"Striker Blatta",
"Tectonic Blatta",
"Crawler Blatta",
"Dui, the Invaluable",
"Tico, the Precious",
"Viridian Germivore",
"Viridian Germivore",
"Saffron Germivore",
"Saffron Germivore",
"Zeppelin Germivore",
"Zeppelin Germivore",
"Carmine Germivore",
"Carmine Germivore",
"Lomoth, the Beast-Eater",
"Silver Papil",
"Gold Papil",
"Drone Adsecula",
"Drone Adsecula",
"Drone Adsecula",
"Recluse Adsecula",
"Recluse Adsecula",
"Recluse Adsecula",
"Faded Adsecula",
"Faded Adsecula",
"Faded Adsecula",
"Mirage Adsecula",
"Mirage Adsecula",
"Mirage Adsecula",
"Ghost Adsecula",
"Ghost Adsecula",
"Ghost Adsecula",
"Recluse Adsecula",
"Recluse Adsecula",
"Recluse Adsecula",
"Recluse Adsecula",
"Bertrand, the Gorge Scourge",
"Squallo, the Sand Mirer",
"Squallo, the Sand Mirer",
"Valyrian, the Iron Cleaver",
"Frightening Ictus",
"Fearsome Ictus",
"Terrible Ictus",
"Belenguer, the Gunhammer",
"Coral Purgovent",
"Ocean Purgovent",
"Tidal Purgovent",
"Libra, the Long-Lived",
"Bolt Duoguill",
"Nether Duoguill",
"Blood Duoguill",
"Lethal Duoguill",
"Thunder Duoguill",
"Blitz Duoguill",
"Valeriano, the Rolling Thunder",
"Electro Duoguill",
"Plasma Duoguill",
"Valeriano, the Rolling Thunder",
"Quick Aetrygon",
"Fleet Aetrygon",
"Vilem, the Gold-Scaled",
"Sea Balaena",
"Ocean Balaena",
"Lunar Ceto",
"Selenic Ceto",
"Elaine, the Lunar Eclipse",
"Soldier Grex",
"Soldier Grex",
"Hunter Grex",
"Scourer Grex",
"Elder Grex",
"Celedonio, the Battle-Tested",
"Berserk Vigent",
"Berserk Vigent",
"Brutal Vigent",
"Brutal Vigent",
"Barnabas, the Despot",
"Barnabas, the Despot",
"Wise Progen",
"Wise Progen",
"Wise Progen",
"Ancient Progen",
"Ancient Progen",
"Primal Progen",
"Primal Progen",
"Ernest, the Contemplative",
"Land Monoceros",
"Land Monoceros",
"Volcannon Monoceros",
"Volcannon Monoceros",
"Vice Simius",
"Mortal Simius",
"Condemned Simius",
"Diogenes, the Covetous",
"Origin Cantor",
"Wise Aprica",
"Ancient Aprica",
"Primal Aprica",
"Sviatoslav, the Reproachful",
"Violet Cervus",
"Western Suid",
"Bronze Suid",
"Trained Armored Suid",
"EN060702_NAME_D00",
"Adamant Armored Suid",
"Macho Armored Suid",
"Macho Armored Suid",
"Crazed Femina Suid",
"Alba Femina Suid",
"Melanya, the Sound Sleeper",
"EN060707_NAME_A00",
"Prowler Ovis",
"Innocent Ovis",
"Prowler Ovis",
"Innocent Ovis",
"Germaine, the Treasure Keeper",
"Gradivus, the Headless Emperor",
"Wasteland Evello",
"Wasteland Evello",
"Wasteland Evello",
"Grand Evello",
"Grand Evello",
"Ludvik, the Picky Eater",
"Javelin Insidia",
"Javelin Insidia",
"Glaive Insidia",
"Glaive Insidia",
"Halberd Insidia",
"Halberd Insidia",
"Feliciano, the All-Seeing",
"Parasite Gerrid",
"Parasite Gerrid",
"Alba Lepyx",
"Legion Lepyx",
"Giant Lepyx",
"Drone Mortifole",
"Drone Mortifole",
"Drone Mortifole",
"Drone Mortifole",
"Recluse Mortifole",
"Recluse Mortifole",
"Faded Mortifole",
"Faded Mortifole",
"Jindriska, the Serene",
"Poisonous Mortifole",
"Poisonous Mortifole",
"Toxic Mortifole",
"Toxic Mortifole",
"Paralyzing Mortifole",
"Paralyzing Mortifole",
"Eliane, the Unmoved",
"Fluid Jacul",
"Jia Mian, the Beloved",
"Hurricane Auravis",
"Hurricane Auravis",
"Gale Auravis",
"Blast Auravis",
"Typhoon Auravis",
"Tempest Auravis",
"Tempest Auravis",
"Tempest Auravis",
"Tempest Auravis",
"Gotthard, the Intimidating",
"Cataract Levitath",
"Abyssal Levitath",
"Silvestre, the Morning Light",
"Hartmut, the Calamity",
"EN070602_NAME_A00",
"EN070602_NAME_B00",
"Sapphire Visigel",
"Strange Vesper",
"Strange Vesper",
"Uncanny Vesper",
"Uncanny Vesper",
"Mortal Vesper",
"Mortal Vesper",
"Ripper Vesper",
"Ripper Vesper",
"Abyssal Vesper",
"Abyssal Vesper",
"Wild Mephite",
"Impish Mephite",
"Malicious Mephite",
"Prowler Mephite",
"Stray Mephite",
"Driven Mephite",
"Ferdinand, the Fortuitous",
"Nomad Liceor",
"Itinerant Saltat",
"Itinerant Saltat",
"Strange Saltat",
"Gypsy Saltat",
"Quaestor Saltat",
"Wenzel, the Inebriated",
"Island Saltat",
"Native Saltat",
"Mystic Saltat",
"Crested Saltat",
"Cloud Saltat",
"Angry Saltat",
"Hungry Saltat",
"Sorrowful Saltat",
"Rapture Saltat",
"Rapture Saltat",
"Crying Saltat",
"Rolf, the Sonorous",
"Prisoner Saltat",
"Prisoner Saltat",
"Elusive Saltat",
"Fiasco Saltat",
"Imbecile Saltat",
"Sluggish Saltat",
"Rock Potamus",
"Copper Potamus",
"Bronze Potamus",
"EN090503_NAME_A00",
"River Dilus",
"Lake Dilus",
"Highland Dilus",
"Valley Dilus",
"EN090503_NAME_F00",
"Sheldon, the Dentally Challenged",
"Armed Recon Galdr",
"Gadaf's Qmoeva",
"Frontline Surveillance Zig",
"Raging Forfex",
"Raging Forfex",
"Sven, the Sturdy",
"Lazuli Forfex",
"Cursed Blatta",
"Balloon Balaena",
"Wandering Balaena",
"Draken, the Drifting Cloud",
"Beach Balaena",
"Beach Balaena",
"Coral Balaena",
"Shoal Balaena",
"Shoal Balaena",
"Angry Simius",
"Angry Simius",
"Ancient Coronid",
"Xair, the Cerulean Walker",
"Wind Jacul",
"Wind Jacul",
"Stream Jacul",
"Isle Visigel",
"Sapphire Visigel",
"Bressole, the Fugitive",
"Quo",
"Quo",
"Shrad",
"Shrad",
"Galdr",
"Galdr",
"Galdr",
"Galdr",
"Seidr",
"Seidr",
"Seidr",
"Silene The Lost",
"Sven, the Sturdy",
"Roxanne The Mountain Recluse",
"Langul, the Alien Payload",
"EN040102_NAME_N01",
"Megatonne, the Hell Express",
"Oskar, the Summer Squall",
"EN090201_NAME_N01",
"Merciful Dilus",
"Alfombra, the Transcendent",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"EN000000_NAME_Dummy",
"Warlord Ictus",
"Young Grex",
"Bush Grex",
"Giant Grex",
"Rebel Oc-serv",
"Land Caecus",
"Promethium Petramand",
"Shield Satellis",
"Strike Satellis",
"Link Satellis",
"Enhancer Satellis",
"Pursuit Satellis Alpha",
"Pursuit Satellis Beta",
"Pursuit Satellis Gamma",
"Volcannon Sacrifole",
"Silver Suid",
"Silver Suid",
"Little Suid",
"Little Suid",
"Little Suid",
"Silver Femina Suid",
"Silver Femina Suid",
"Silver Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Little Femina Suid",
"Definian Copy",
"Definian Clone",
"Green Lance Galdr",
"Purger Queen Qmoeva",
"Volcannon Cinicula",
"Crested Saltat",
"Island Saltat",
"Mirage Adsecula",
"Marnuck Alpha",
"Gate Puge",
"Fighter Puge",
"Sizzling Visigel",
"Milsaadi Herald",
"Milsaadi Astran",
"Colubrim",
"Elvira, the Talondrake",
"Aquatic Visigel",
"Mighty Virago",
"Callow Virago",
"Intra Monoceros",
"Gi Zang",
"Trump Papil",
"Mirage Adsecula",
"Carmine Vesper",
"Elvira, the Talondrake",
"Elvira, the Talondrake",
"Milsaadi Protobattler",
"Milsaadi Robber",
"Lord Xe-dom",
"Ripper Vesper",
"True King Qmoeva",
"Green Master Galdr",
"Hazard Shrad",
"Avaricious Shrad",
"Conjurer Cervus",
"Marnuck Assaulter",
"Marnuck Assaulter",
"Umbral Adsecula",
"Storm Caro",
"Marnuck Ruffian",
"Marnuck Captain",
"Marnuck Admiral",
"Marnuck Admiral",
"Ocean Balaena",
"Brother Potamus",
"Marnuck General",
"Jade Jacul",
"Wood Potamus",
"Bravo Unafulge",
"Burning Lophid",
"Cursed Adsecula",
"Cursed Adsecula",
"Land Forfex",
"Dryland Forfex",
"Thunder Duoguill",
"Blitz Duoguill",
"Drone Adsecula",
"Recluse Adsecula",
"Raven Turba",
"Europium Petramand",
"Blood Vesper",
"Hell Gerrid",
"Reject Oc-serv",
"Border King Quo",
"Alba Blatta",
"Swift Blatta",
"Tough Blatta",
"Tough Blatta",
"Marnuck Imperial",
"Marnuck Imperial",
"Marnuck Imperial",
"Marnuck Captain",
"Marnuck Blaster",
"Marnuck Grappler",
"Marnuck Admiral",
"Yellow Arenatect",
"Skulker Germivore",
"Crazed Germivore",
"Mist Germivore",
"Survivor Germivore",
"Adonis Turba",
"Magus Papil",
"Dryland Papil",
"Mirage Thallus",
"Mirage Thallus",
"EN040403_NAME_F00",
"EN040403_NAME_F00",
"Ymir Gularth",
"Laser Raptor Seidr",
"Aegis Raptor Seidr",
"Grav Raptor Seidr",
"Laser Eagle Seidr",
"Aegis Eagle Seidr",
"Grav Eagle Seidr",
"Machine Rook Quo",
"Machine Queen Quo",
"Strange Saltat",
"Gypsy Saltat",
"Witless Saltat",
"Caged Saltat",
"Fiasco Saltat",
"Crater Saltat",
"Knight Pugilith",
"Guardian Pugilith",
"Judge Pugilith",
"Egg Blatta",
"Prone Vix Owl",
"Prone Vix Vulture",
"Prone Fury",
"Prone Vix Brutalizer",
"Vendura, the Spellbinder",
"Prone Rampager",
"Prone Judge",
"Prone Slayer",
"Prone Slayer",
"Prone Slayer",
"Prone Bully",
"Prone Vix Prisoner",
"Marnuck Admiral",
"Marnuck Assaulter",
"Marnuck Royal",
"Prone Vix Soldier",
"Beach Xiphias",
"Rust Blatta",
"Hrym Blatta",
"Seeker Blatta",
"Sonic Blatta",
"Buster Emperor Qmoeva",
"Duel Emperor Qmoeva",
"Rebel Emperor Qmoeva",
"Prone Butcher",
"Prone Vix Hawk",
"Furious Simius",
"Furious Simius",
"Remote Puge",
"Remote Pugilith",
"Barbed Remote Qmoeva",
"Milsaadi Guard",
"Marnuck Gatling",
"Marnuck Burster",
"Carnelian Forfex",
"Spinel Forfex",
"Marnuck Support",
"Marnuck Marksman",
"Marnuck Recon",
"Marnuck Captain",
"Marnuck Howitzer",
"Marnuck Crasher",
"Marnuck Mercenary",
"Marnuck Shield Trooper",
"Marnuck Cutthroat",
"Marnuck Loader",
"Marnuck Slayer",
"Marnuck Aspirer",
"Marnuck Hornet",
"Marnuck Admiral",
"Marnuck Minor",
"Marnuck Soldier",
"Marnuck Pawn",
"Marnuck Slugger",
"Marnuck Grappler",
"Marnuck Gatling",
"Marnuck Guard",
"Marnuck Guard",
"Marnuck Imperial",
"Carnelian Forfex",
"Vanguard Ceto",
"Tornado Jacul",
"Coral Balaena",
"Dusk Adsecula",
"Dusk Adsecula",
"Umbral Adsecula",
"Dusk Adsecula",
"Umbral Adsecula",
"Zirconium Oc-serv",
"Wood Scirpo",
"Native Scirpo",
"Citrine Scirpo",
"Adonis Turba",
"Marnuck Jaeger",
"Marnuck Commander",
"Marnuck Evildoer",
"Marnuck Firetrooper",
"Enhanced Defense Seidr",
"Marnuck Grappler",
"Marnuck Grappler",
"Marnuck Grappler",
"Marnuck Converger",
"Servant Caro",
"Servant Caro",
"Servant Caro",
"Hayreddin, the Territorial",
"Tantalum Fal-swo",
"Buster Kaizer Qmoeva",
"Rhenium Oc-serv",
"Rhenium Oc-serv",
"Milsaadi Assassin",
"Marnuck Elite",
"Lost Caro",
"Marnuck Barrager",
"Marnuck Gatling",
"Rocket Jacul",
"Razer Visigel",
"Vanguard Ceto",
"Cavalier Puge",
"Adonis Turba",
"Adonis Turba",
"Adonis Turba",
"Adonis Turba",
"Crusher Mortifole",
"Buster Kaizer Qmoeva",
"Progen",
"Scirpo",
"Marnuck B",
"Shrad",
"Milsaadi Savage",
"Companion Potamus",
"Marnuck Dynamo",
"Arch Caro",
"Arch Caro",
]