from ..Locations import Loc as Data

# https://xenoblade.github.io/xbx/bdat/common_local_us/BTL_EnBook.html
# flake8: noqa
enemies_data: list[Data] = [
Data("Origin Blatta - Prologue"),
Data("Callow Grex - Prologue"),
Data("Elder Grex - Prologue"),
Data("Volkampf, the Pursuer - Chp 2: Story", regions=["Chapter 2"]),
Data("Glennar - Chp 3: Story", regions=["Chapter 3"]),
Data("Goetia - Chp 4: Story", regions=["Chapter 4"]),
Data("Tainted Sphinx - Chp 6: Story", regions=["Chapter 6"]),
Data("Almandal - Chp 7: Story", regions=["Chapter 7"]),
Data("Dagahn - Chp 8: Story", regions=["Chapter 8"]),
Data("Ryyz - Chp 8: Story", regions=["Chapter 8"]),
Data("Wrothian Enacter - Chp 9: Story", regions=["Chapter 9"]),
Data("Wrothian Sneaker - Chp 9: Story", regions=["Chapter 9"]),
Data("Ga Jiarg - Chp 9: Story", regions=["Chapter 9"]),
Data("Ga Buidhe - Chp 9: Story", regions=["Chapter 9"]),
Data("Vasara - Chp 9: Story", regions=["Chapter 9"]),
Data("Deva Caladar - Chp 9: Story", regions=["Chapter 9"]),
Data("Caladar - Chp 9: Story", regions=["Chapter 9"]),
Data("Zu Pharg - Chp 10: Story", regions=["Chapter 10"]),
Data("Prog Ares - Chp 11: Story", regions=["Chapter 11"]),
Data("Vita - Chp 12: Story", regions=["Chapter 12"]),
Data("Shield Satellis - Chp 12: Story", regions=["Chapter 12"]),
Data("Strike Satellis - Chp 12: Story", regions=["Chapter 12"]),
Data("Link Satellis - Chp 12: Story", regions=["Chapter 12"]),
Data("Enhancer Satellis - Chp 12: Story", regions=["Chapter 12"]),
Data("Pursuit Satellis Alpha - Chp 12: Story", regions=["Chapter 12"]),
Data("Pursuit Satellis Beta - Chp 12: Story", regions=["Chapter 12"]),
Data("Pursuit Satellis Gamma - Chp 12: Story", regions=["Chapter 12"]),
Data("Soldier Chimera - Chp 12: Story", regions=["Chapter 12"]),
Data("Lao - Chp 12: Story", regions=["Chapter 12"], required=True),
Data("Queen Chimera - Chp 12: Story", regions=["Chapter 12"]),
Data("Minor Chimera - Chp 12: Story", regions=["Chapter 12"]),
Data("Mezzo Chimera - Chp 12: Story", regions=["Chapter 12"]),
Data("Major Chimera - Chp 12: Story", regions=["Chapter 12"]),
Data("Nardacyon, the Shadowless - Prim: Bedrock Hold - Chp 12", regions=["Chapter 12"]),
Data("Lugalbanda, the Wanderer-King - Noct: Vitriol Cesspool - Chp 12", regions=["Chapter 12"]),
Data("Vortice, the Deific Blast - Caul: MountMgando - Brimstone Rain", regions=["Skell License"]),  # TAJ to aggro
Data("Leva'el, the Terminus - Caul: Cauldros Waters", regions=["Chapter 12"]),
Data("Sentinel Satellis - Caul: Cauldros Waters - Chp 12", regions=["Chapter 12"]),
Data("Atreides, the Distinguished - Sylv: South Silent Sandsea"),
Data("Gesserith, the Wileworm - Sylv: South Silent Sandsea"),
Data("Pharsis, the Everqueen - Sylv: Noctilucent Sphere Interior", depends=["Noctilucent Sphere Interior"]),
Data("Pyotr, the Shepherd - Noct: Narcissus Tree"),
Data("Heidi, the Lively - Noct: Narcissus Tree"),
Data("Claire, the Sheltered - Noct: Narcissus Tree"),
Data("Shuravas, the Enraged - Noct: Suncatch Ravine - Thunderstorm"),  # No skell required from pillar under bridge
Data("Dadaan, the Strongest Prone - Obli: Scabland Fortress - Chp 12", regions=["Chapter 12"]),
Data("The Dadaan Girls - Obli: Scabland Fortress - Chp 12", regions=["Chapter 12"]),
Data("Dadaan Squad Member - Obli: Scabland Fortress - Chp 12", regions=["Chapter 12"]),
Data("Gradivus, the Headless Emperor - Obli: North Coast - Chp 12", regions=["Chapter 12"]),
Data("Telethia, the Endbringer - Noct: Divine Roost", depends=["Divine Roost"]),
Data("HH100: Hierana - Mia Is Missing!", depends=["Mia Is Missing!"]),
Data("Briggs - The Celeste Three", depends=["The Celeste Three"]),
Data("Fosdyke - The Celeste Three", depends=["The Celeste Three"]),
Data("Moorehouse - The Celeste Three", depends=["The Celeste Three"]),
Data("Cross Qmoeva - Frontier Spirit", depends=["Frontier Spirit"]),
Data("Lightning Strike - The Line of Fire", depends=["The Line of Fire"]),
Data("Lineage - Shotgun Diplomacy", depends=["Shotgun Diplomacy"]),  # Accessbile earlier but missable
Data("Brutal Prone - Predator and Prey", depends=["Predator and Prey"]),
Data("Blood Despair - Rise of the Blood Lobster", depends=["Rise of the Blood Lobster"]),
Data("Grenade Pizza F - Murder Most Foul", depends=["Murder Most Foul"]),
Data("Twin Qmoeva - Rites of Ruin", depends=["Rites of Ruin"]),
Data("Ajiba Falgo - Tree-mendous", depends=["Tree-mendous"]),  # Kidnapped: Oll Valdileo
Data("Mujiba Falgo - Tree-mendous", depends=["Tree-mendous"]),  # Kidnapped: Rada Valdileo
Data("Galba Vassago - Here Come the Brides", depends=["Here Come the Brides"]),
Data("Leroy's Ire - Forbidden Love", depends=["Forbidden Love"], valid=False), # One of these two entrys will be missible
Data("Loda Gorida - Forbidden Love", depends=["Forbidden Love"], valid=False), # Should both be false?
Data("Odsent - Training Day", depends=["Training Day"]),
Data("Slovity Pagus_1 - Slovity's Rampage", depends=["Slovitys Rampage"]),
Data("MG062: Megisia - Slovity's Rampage", depends=["Slovitys Rampage"]),
Data("MG068: Megisia - Slovity's Revenge", depends=["Slovitys Revenge"]),
Data("Harvey - Special Delivery", depends=["Special Delivery"]),
Data("Nopopon Incarnate - The Divine Nopopon", depends=["The Divine Nopopon"]), # Quest requires 80% Mira survey
Data("Napopon Incarnate - The Divine Nopopon", depends=["The Divine Nopopon"]),
Data("Nipopon Incarnate - The Divine Nopopon", depends=["The Divine Nopopon"]),
Data("Nupopon Incarnate - The Divine Nopopon", depends=["The Divine Nopopon"]),
Data("Gi Ziorde - Two Warriors", depends=["Two Warriors"]),
Data("EN090503_NAME_F00_1", valid=False),
Data("EN090503_NAME_F00_2", valid=False),
Data("Gi Ziordo - Two Warriors", depends=["Two Warriors"]),
Data("Zo Zazhi - A Dish Served Cold", depends=["A Dish Served Cold"]), 
Data("Sazon Caladar - Leaving the Nest", depends=["Leaving the Nest"]),
Data("Soghu Caladar - Leaving the Nest", depends=["Leaving the Nest"]),
Data("De Ezich - Leaving the Nest", depends=["Leaving the Nest"], valid=False), # Missible depending on option in quest
Data("Naguth Caladar - The Queen Is Dead", depends=["The Queen Is Dead"]),
Data("Girhi Caladar - The Queen Is Dead", depends=["The Queen Is Dead"]),
Data("Zeulbe Caladar - The Queen Is Dead", depends=["The Queen Is Dead"]),
Data("Ladha Caladar - Lend an Ear", depends=["Lend an Ear"], valid=False), # Missible depending on option in quest
Data("Ga Bewhe - Gold Rush", depends=["Gold Rush"]),
Data("Slovity Pagus_2 - The Gauntlet", depends=["The Gauntlet"]),
Data("Gwin_1 - The Gauntlet", depends=["The Gauntlet"]), 
Data("Ozuchi Caladar - The Gauntlet", depends=["The Gauntlet"]),
Data("EN090503_NAME_F00_3", valid=False),
Data("JS178: Jushe - Sun'celeg Rises", depends=["Sunceleg Rises"]),
Data("Gold Courage - A Dubious Operation", depends=["A Dubious Operation"], valid=False), # Missible depending on option in quest
Data("SG002: Slenna - Good Fortun", depends=["Good Fortun"]),
Data("ER001: Emeroa - Definian Downfall", depends=["Definian Downfall"]),
Data("HP001: Harriess - Definian Downfall", depends=["Definian Downfall"]),
Data("JD001: Juda - Definian Downfall", depends=["Definian Downfall"]),
Data("Rexoskell - Definian Downfall", depends=["Definian Downfall"]), # This entry applys to the second (lv54) fight in the mission
Data("DE913: Dieara - Attack on Biahno Hills", depends=["Attack on Biahno Hills"]),
Data("EN090503_NAME_F00_4", valid=False),
Data("Dolba the Wrecker - Professorial", depends=["Professorial"]),
Data("Gadd - Professorial", depends=["Professorial"]), #lv19 Sylvalum version
Data("MO037: Moore - The Duel IV", depends=["The Duel IV"]),
Data("Gi Zang - The Lurker", depends=["The Lurker"]), #lv36 Primordia version
Data("EN090503_NAME_F00_5", valid=False),
Data("LV757: Lyvia - Fortun and Glory", depends=["Fortun and Glory"], valid=False), # Requires Definian Downfall B route to access quest
Data("Gwin_2 - Boot Camp", depends=["Boot Camp"]), # This entry applys to the second (lv46) fight in the mission
Data("ST816: Stalio - Boze's Ignorance", regions=["Chapter 9", "Blade License", "Boze 4"], depends=["Prone Sweet Prone", "Nine Lives"]),  # depends Bozes Ignorance
Data("Blood-king Gelvo Banth - The King of Fear", regions=["Chapter 7", "Blade License", "HB 2", "Noct 25"], depends=["Prone Sweet Prone", "BFFs", "Nine Lives"]), # depends The King of Fear
Data("Running Shark - My Dream", depends=["My Dream"]),
Data("Interfearence - Serial Thriller", depends=["Serial Thriller"]),
Data("Alexa Special - Weaponized", regions=["Chapter 4", "Blade License"]),  # depends Weaponized
Data("SN333: Jisanne - A False Hope", depends=["A False Hope"]),
Data("Pawn Puge - Prim: Seaswept Base"),
Data("Dagger Puge - Obli: Mesa Fortress"),
Data("Sword Puge - Obli: Sea Whisper Valley"),
Data("Buster Puge - Obli: Milligan Supply Base"),
Data("Lance Puge - Obli: Yawning Giant"), 
Data("EN090503_NAME_F00_6", valid=False),
Data("Prototype Puge - Prim: Bedrock Hold"),
Data("EN090503_NAME_F00_7", valid=False),
Data("Knight Puge - Sylv: Lesser Anvil"),
Data("Guardian Puge - Sylv: Badr Basin"),
Data("EN090503_NAME_F00_8", valid=False),
Data("Night Combat Puge - Caul: Ruined City of O'rrh Sim"),
Data("Pawn Pugilith - Prim: Seaswept Base"),
Data("Dagger Pugilith - Sylv: Seabird's Beak"),
Data("Sword Pugilith - Obli: Mesa Fortress"),
Data("EN090503_NAME_F00_9", valid=False),
Data("EN090503_NAME_F00_10", valid=False),
Data("Master Pugilith - Obli: Cliffside Camp"),
Data("Raider Pugilith - Obli: Stoyanov Trail"),
Data("Knight Pugilith - Sylv: South Silent Sandsea"),
Data("Guardian Pugilith - Sylv: Badr Basin"),
Data("EN090503_NAME_F00_11", valid=False),
Data("High-Output Pugilith - Sylv: Badr Stronghold"),
Data("EN090503_NAME_F00_12", valid=False),
Data("Talon Raptor Galdr", valid=False), # Location just says Cauldros, skipping for now
Data("Talon Eagle Galdr - Caul: O'rrh Sim Castle Ruins"),
Data("Armed Recon Galdr - Caul: West Cauldros Waters"),
Data("EN090503_NAME_F00_13", valid=False),
Data("EN090503_NAME_F00_14", valid=False),
Data("Revolver Eagle Galdr - Obli: Jair Fortress"),
Data("Armed Engineer Galdr - Caul: Far Isle of Tzu'o"),
Data("Guide Owl Galdr - Noct: Lotus Keep Building Site"),
Data("Guide Raptor Galdr - Caul: Sunset Falls"),
Data("Guide Eagle Galdr - Caul: O'rrh Sim Watchtowers"),
Data("Air Support Galdr - Caul: Wildcat Fortress"),
Data("EN090503_NAME_F00_15", valid=False),
Data("EN090503_NAME_F00_16", valid=False),
Data("Gun Eagle Galdr - Caul: Bedrock Hold"),
Data("Armed Destroyer Galdr - Caul: Ruined City of O'rrh Sim"),
Data("Lyla's Galdr - Sylv: Hardheart Canyon - Early morning"),
Data("Chantai's Galdr - Caul: O'rrh Sim Castle Ruins - Daytime"),
Data("Duran's Galdr - Noct: Lotus Keep Building Site - Late night"),
Data("EN090503_NAME_F00_17", valid=False),
Data("Green Lance Galdr - Sylv: Lesser Anvil"),
Data("Vendura's Galdr - Sylv: Scabland Fortress - Nighttime"),
Data("Drone Pawn Quo - Caul: FN Site 505"),
Data("Drone Knight Quo - Noct: FN Site 210"),
Data("Drone Rook Quo - Prim: Bedrock Hold"),
Data("Drone Queen Quo - Caul: O'rrh Sim Keep"),
Data("Drone King Quo - Caul: Jair Fortress"), 
Data("Logistical Support Quo - Prim: Bedrock Hold"),
Data("EN090503_NAME_F00_18", valid=False),
Data("Machine Rook Quo - Sylv: Lower Delusian Mountains"),
Data("Machine Queen Quo - Sylv: Lesser Anvil"),
Data("Machine King Quo - Sylv: North Cinderdunes"),
Data("Frontline Medic Quo - Caul: Ganglion Weapons Hanger"),
Data("Rubidium Oc-serv - Noct: Suncatch Ravine"),
Data("EN090503_NAME_F00_19", valid=False),
Data("EN090503_NAME_F00_20", valid=False),
Data("Titanium Oc-serv - Sylv: Banshee Cave"),
Data("Oc-serv, the Ancient - Sylv: Sylvalum Searoad"),
Data("Selenium Oc-serv - Caul: Ruined City of O'rrh Sim"),
Data("Tantalum Oc-serv", valid=False), # Apparently doesn't exist in-game, despite having an entry
Data("Rhenium Oc-serv - Caul: Kitsune Stronghold"),
Data("Na-mulk, the Rebellious - Caul: Ruined City of O'rrh Sim"),
Data("Tellurium Oc-serv - Sylv: Seabird's Beak"),
Data("Niobium Oc-serv - Sylv: South Hardheart Canyon"),
Data("Thallium Oc-serv - Sylv: Badr Stronghold"),
Data("Bismuth Oc-serv - Sylv: FN Site 404"),
Data("Si-el, the Vacuous - Noct: Qing Long Glade"),
Data("Chromium Oc-serv - Obli: Alexander Ridge"),
Data("EN090503_NAME_F00_21", valid=False),
Data("Ro-darm, the Demon Claw - Obli: North Coast"),
Data("Talon Knight Qmoeva - Caul: FN Site 502"),
Data("EN090503_NAME_F00_22", valid=False),
Data("Talon Queen Qmoeva - Sylv: Hilal Stronghold"),
Data("Talon King Qmoeva - Prim: FN Site 110 - Nighttime"),
Data("Infantry Support Qmoeva - Noct: Noctilum Waters"), 
Data("Palace Knight Qmoeva - Noct: FN Site 210"),
Data("EN090503_NAME_F00_23", valid=False),
Data("Palace Queen Qmoeva - Obli: Scabland Fortress"),
Data("Palace King Qmoeva - Sylv: Anvil Rock One"),
Data("Multi Knight Qmoeva - Noct: FN Site 215"),
Data("Multi Rook Qmoeva - Sylv: Lesser Anvil"),
Data("Multi Queen Qmoeva - Sylv: Samuel Incline"),
Data("EN090503_NAME_F00_24", valid=False),
Data("Intermediate Arsenal Qmoeva - Prim: Silent Mire - Nighttime"),
Data("Suppressor Knight Qmoeva - Noct: Everwhelm Falls"),
Data("Suppressor Rook Qmoeva - Caul: FN Site 505"),
Data("Suppressor Queen Qmoeva - Sylv: FN Site 407"),
Data("EN090503_NAME_F00_25", valid=False),
Data("Daril's Qmoeva - Prim: Starfall Basin - Daytime"), # To check: Spawn chapter
Data("EN090503_NAME_F00_26", valid=False),
Data("War Emperor Qmoeva - Caul: O'rrn Sim Keep"),
Data("War Kaizer Qmoeva - Sylv: Anvil Sandplain"),
Data("Urdu's Qmoeva - Caul: Ganglion Antropolis - Late Night"),
Data("Sadar's Qmoeva - Sylv: Lake Ciel - Daytime"),
Data("Enhanced Attack Seidr - Caul: Kitsune Stronghold"),
Data("Armored Cruiser Seidr - Caul: O'rrn Sim Watchtowers - Daytime"),
Data("Enhanced Defense Seidr - Sylv: Arc Rock", depends=["Arc Rock"]),
Data("EN090503_NAME_F00_27", valid=False),
Data("Sharnaak's Seidr - Caul: Ganglion Antropolis"),
Data("Badul's Seidr - Sylv: Cavernous Abyss - Nighttime", depends=["Cavernous Abyss"]),
Data("Ahama's Seidr - Sylv: Anvil Sandplain - Nighttime"),
Data("Orion Xern - Caul: FN Site 505", regions=["Skell License"]),
Data("Luxaar's Xern - Sylv: Arc Rock", depends=["Arc Rock"]),
Data("Fleet Shrad - Caul: White Phosphor Lake"),
Data("Quick Shrad - Caul: FN Site 504"),
Data("Swift Shrad - Caul: Kw'awah Cloister"),
Data("Jet Shrad - Caul: FN Site 516"),
Data("Sector Security Shrad - Caul: Boxtrap Checkpoint"),
Data("EN090503_NAME_F00_28", valid=False),
Data("Rocket Shrad - Caul: FN Site 510"),
Data("Mach Shrad - Caul: Capital Wreckage"),
Data("Experimental Flight Shrad - Caul: Capital Wreckage"),
Data("Du-rha, the Imprisoned - Sylv: Quay Hollows", depends=["Quay Hollows"]),
Data("Strontium Xe-dom - Caul: Ruined City of O'rrn Sim"),
Data("Gi-zho, the Iron Deity - Caul: Kw'arah Villa"),
Data("Molybdenum Xe-dom - Sylv: West Ciel Sandsea"),
Data("Bismuth Xe-dom - Sylv: Needle Rock Sandsea"),
Data("Go-rha, the Guardian Deity - Noct: Yagami's Vista"),
Data("EN090503_NAME_F00_29", valid=False),
Data("Strike Barrager Zig - Obli: Milligan Supply Base"), #maybe flying?
Data("Strike Gunner Zig - Caul: FN Site 511"),
Data("Strike Launcher Zig - Caul: Kitsune Stronghold"), #maybe flying?
Data("Experimental Compact Zig - Caul: Scholes Battlegrounds"), 
Data("EN090503_NAME_F00_30", valid=False),
Data("Revolver Barrager Zig - Caul: Boxtrap Checkpoint"),
Data("Revolver Gunner Zig - Obli: FN Site 307"),
Data("EN090503_NAME_F00_31", valid=False),
Data("Enhanced Search Zig - Caul: Wildcat Fortress"),
Data("Mortar Sniper Zig - Caul: FN Site 502"),
Data("EN090503_NAME_F00_32", valid=False),
Data("Mortar Gunner Zig - Caul: Wildcat Fortress"),
Data("Mortar Launcher Zig - Obli: Jair Fortress"),
Data("Unlimited Output Zig - Caul: Sunset Falls"),
Data("EN090503_NAME_F00_33", valid=False),
Data("Palace Barrager Zig - Caul: FN Site 508"),
Data("EN090503_NAME_F00_34", valid=False),
Data("EN090503_NAME_F00_35", valid=False),
Data("Enhanced Support Zig - Caul: Dragonbone Promontory"),
Data("EN090503_NAME_F00_36", valid=False),
Data("Assault Barrager Zig - Sylv: FN Site 416"),
Data("Assault Gunner Zig - Sylv: Lesser Anvil"),
Data("Assault Launcher Zig - Sylv: Xanadu Overlook"),
Data("Damaged Zig - Sylv: Hilal Stronghold"),
Data("EN090503_NAME_F00_37", valid=False),
Data("Vulcan Barrager Zig - Sylv: Hilal Stronghold"),
Data("Vulcan Gunner Zig - Sylv: FN Site 415"),
Data("Vulcan Launcher Zig - Sylv: FN Site 405", regions=["Skell License"]),  # maybe with jumps
Data("Experimental Second-Gen Zig - Caul: Kitsune Stronghold"),
Data("EN090503_NAME_F00_38", valid=False),
Data("Howitzer Barrager Zig - Caul: O'rrn Sim Castle Ruins"),
Data("Howitzer Gunner Zig - Sylv: Northern Searoad"),
Data("Howitzer Launcher Zig - Sylv: FN Site 401", regions=["Skell License"]),  # very likely with jumps
Data("Enhanced Attack Range Zig - Caul: Ganglion Weapons Hanger"),
Data("EN090503_NAME_F00_39", valid=False),
Data("Enhanced Barrager Zig - Sylv: FN Site 420"),
Data("Enhanced Gunner Zig - Caul: T'phnom Shelf"),
Data("Enhanced Launcher Zig - Sylv: FN Site 415"),
Data("Frontline Surveillance Zig - Sylv: Sylvalum Waters"),
Data("EN090503_NAME_F00_40", valid=False),
Data("EN090503_NAME_F00_41", valid=False),
Data("Rubidium Fal-swo - Sylv: South Hardheart Canyon"),
Data("Thallium Fal-swo - Sylv: Anvil Rock One"),
Data("Ji-ett, the Thunderclap - Prim: South Janpath Plain - Nighttime", regions=["Skell License"]),  # TAJ, maybe not with heavy skells
Data("Selenium Fal-swo - Caul: M'gando Gorge BC"),
Data("Rhenium Fal-swo - Caul: Kw'arah Cloister"), #maybe flying?
Data("Ya-rhat, the Thundercloud - Caul: Kw'arah Cloister"),
Data("Stainless Fal-swo - Sylv: Needle Rock Sandsea - Nighttime"),
Data("Tellurium Fal-swo - Sylv: Delusians North Summit - Nighttime"),
Data("Chromium Fal-swo - Prim: Talon Rock Summit - Nighttime", depends=["Talon Rock Summit"]),
Data("Ga-uhl, the Precept-Keeper - Sylv: Badr Stronghold - Nighttime"),
Data("EN090503_NAME_F00_42", valid=False),
Data("EN090503_NAME_F00_43", valid=False),
Data("Marnuck Admiral - Prim: Bedrock Hold"),
Data("EN090503_NAME_F00_44", valid=False),
Data("Sadar, the Unhinged - Sylv: Hilal Stronghold - Nighttime"),
Data("EN090503_NAME_F00_45", valid=False),
Data("EN090503_NAME_F00_46", valid=False),
Data("EN090503_NAME_F00_47", valid=False),
Data("EN090503_NAME_F00_48", valid=False),
Data("Gadaf, the Pulverizer - Obli: North Ant's Nest"),
Data("EN090503_NAME_F00_49", valid=False),
Data("EN090503_NAME_F00_50", valid=False),
Data("EN090503_NAME_F00_51", valid=False),
Data("EN090503_NAME_F00_52", valid=False),
Data("Duran, the Draconian - Caul: O'rrn Sim Castle Ruins - Daytime"),
Data("EN090503_NAME_F00_53", valid=False),
Data("EN090503_NAME_F00_54", valid=False),
Data("EN090503_NAME_F00_55", valid=False),
Data("EN090503_NAME_F00_56", valid=False),
Data("Daril, the Eradicator - Prim: Castaway Cavern - Nighttime"),
Data("Ahama, the Covetous - Sylv: Cavernous Abyss - Daytime", depends=["Cavernous Abyss"]),
Data("Berserker Marnuck - Caul: O'rrh Sim Castle Ruins"),
Data("Milsaadi Fighter - Caul: Kw'arah Cloister"),
Data("Milsaadi Hunter - Caul: Sunset Falls"),
Data("Milsaadi Assassin - Caul: Kitsune Stronghold"),
Data("Sharnaak, the Technician - Caul: Mount M'gando - Nighttime"),
Data("Milsaadi Executioner - Sylv: Hilal Stronghold"),
Data("Milsaadi Specter - Sylv: Quay Hollows", depends=["Quay Hollows"]),
Data("Badul, the One-Eyed - Sylv: Hilal Stronghold - Daytime"),
Data("EN090503_NAME_F00_57", valid=False),
Data("Milsaadi Rampager - Caul: FN Site 512"),
Data("Milsaadi Savage - Caul: Kitsune Stronghold"),
Data("Chantai, the Insect Maiden - Caul: Forgotten Mining Frigates - Nighttime"),
Data("Milsaadi Hitman - Sylv: Badr Stronghold"),
Data("Milsaadi Champion - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Lyla, the Lustrous - Sylv: Den of the Dead", depends=["Den of the Dead"]),
Data("EN090503_NAME_F00_58", valid=False),
Data("Goliath Sylooth - Noct: Rustpool Banks"),
Data("Brobdingnagian Sylooth - Noct: Middle Hushflood"),
Data("Yama, the Obliviator - Noct: Tripod Rock"),
Data("EN090503_NAME_F00_59", valid=False),
Data("EN090503_NAME_F00_60", valid=False),
Data("Gaia Gularth - Caul: Titan's Table"), #all weather except Brimstone Rain
Data("Ilithios, the Enlightened - Caul: Sunset Falls"), #all weather except Brimstone Rain
Data("Mountain Sylooth - Sylv: Southern Searoad"),
Data("Territorial Sylooth - Sylv: Delusians South Summit"), #maybe flying?
Data("Anselm, the Triumphant - Sylv: Delusians South Summit"), #maybe flying?
Data("Alithios, the Indignant - Caul: M'gando Volcanic Crater - Brimstone Rain"),
Data("Canyon Sylooth - Obli: Victory Rock"),
Data("EN090503_NAME_F00_61", valid=False),
Data("EN090503_NAME_F00_62", valid=False),
Data("Climati, the Chilling Wind - Obli: Central Ibra Ravine"),
Data("EN090503_NAME_F00_63", valid=False),
Data("EN090503_NAME_F00_64", valid=False),
Data("EN090503_NAME_F00_65", valid=False),
Data("EN090503_NAME_F00_66", valid=False),
Data("EN090503_NAME_F00_67", valid=False),
Data("EN090503_NAME_F00_68", valid=False),
Data("EN090503_NAME_F00_69", valid=False),
Data("EN090503_NAME_F00_70", valid=False),
Data("EN090503_NAME_F00_71", valid=False),
Data("EN090503_NAME_F00_72", valid=False),
Data("EN090503_NAME_F00_73", valid=False),
Data("EN090503_NAME_F00_74", valid=False),
Data("EN090503_NAME_F00_75", valid=False),
Data("EN090503_NAME_F00_76", valid=False),
Data("Vendura, the Spellbinder - Obli: Mesa Fortress - Daytime"),
Data("Definian Copy - Caul: Dragonbone Promontory"),
Data("Definian Clone - Caul: Ganglion Antropolis"),
Data("WR512: Urdu - Caul: Ganglion Antropolis - Daytime"),
Data("Neodymium Petramand - Prim: Stonelattice Cavern"),
Data("Ytterby Petramand - Obli: Alexander Ridge"),
Data("Malium Petramand - Obli: East Ibra Ravine"),
Data("Caesar, the Hundred-Eyed - Prim: Stonelattice Cavern"),
Data("Grassland Scirpo - Prim: Roof Rock"),
Data("Tree Scirpo - Prim: Seaswept Rise"),
Data("Green Scirpo - Prim: FN Site 112"),
Data("Wood Scirpo - Prim: Rock Cavern"),
Data("Native Scirpo - Prim: Talon Rock Third Terrane"),
Data("Merciful Scirpo - Noct: Weeping Whitewood"),
Data("Yelena, the Sequestered - Prim: East Janpath Plain"),
Data("EN090503_NAME_F00_77", valid=False),
Data("Lantern Petramand - Sylv: Den of the Dead", depends=["Den of the Dead"]),
Data("Ceres Petramand - Sylv: Cauldros Threshold"),
Data("Lutetia Petramand - Sylv: FN Site 404"),
Data("Candelario, the Bronze - Sylv: Samuel Incline"),
Data("Thulium Petramand - Caul: FN Site 501"),
Data("Samarium Petramand - Caul: Abandoned Bivouac"),
Data("Gadolinium Petramand - Caul: Sunset Falls"),
Data("Erbium Petramand - Caul: Capital Wreckage"),
Data("Eisen, the Ebon Rock - Caul: Ruined City of O'rrn Sim - Nighttime"),
Data("Lepidolite Scirpo - Prim: FN Site 116"),
Data("Lapis Scirpo - Prim: Headwater Cavern"),
Data("Jade Scirpo - Prim: Castaway Cavern"),
Data("Citrine Scirpo - Prim: Northpointe Beach"),
Data("EN090503_NAME_F00_78", valid=False),
Data("Garnet Scirpo - Noct: Weeping Whitewood"),
Data("Desdemona, the Subterranean - Noct: Rustpool Banks"),
Data("Beach Forfex - Prim: FN Site 107"),
Data("Sea Forfex - Prim: Cliffside Beach"),
Data("Coral Forfex - Prim: Northpointe Cove"),
Data("Hydro Forfex - Prim: Sayram Lake"),
Data("Ocean Forfex - Noct: Ensanguined Font"),
Data("Raging Forfex - Prim: NLA Waters"),
Data("Sven, the Sturdy - Prim: NLA Waters"),
Data("Sand Forfex - Obli: Barbarich Desert"),
Data("Land Forfex - Obli: Barbarich Desert"),
Data("EN090503_NAME_F00_79", valid=False),
Data("Native Forfex - Obli: South Coast"),
Data("Tourteau, the Delectable - Prim: Cliffside Beach - Nighttime"),
Data("Violet Forfex - Noct: FN Site 205"),
Data("Cobalt Forfex - Noct: FN Site 222"),
Data("Viridian Forfex - Noct: FN Site 218"),
Data("EN090503_NAME_F00_80", valid=False),
Data("Lazuli Forfex - Sylv: Sylvalum Waters"),
Data("Schneider, the Cliffpercher - Noct: FN Site 212"),
Data("EN090503_NAME_F00_81", valid=False),
Data("EN090503_NAME_F00_82", valid=False),
Data("Nectar Scirpo - Sylv: FN Site 415"),
Data("Haoma Scirpo - Sylv: FN Site 406"),
Data("Kvass Scirpo - Sylv: Hardheart Canyon"),
Data("Elena, the Infernal - Noct: Weeping Whitewood - Dense Fog"),
Data("EN090503_NAME_F00_83", valid=False),
Data("EN090503_NAME_F00_84", valid=False),
Data("Praseodymium Petramand - Caul: Old Ceremonial Hollow"),
Data("Europium Petramand - Prim: Turtle Nest"),
Data("EN090503_NAME_F00_85", valid=False),
Data("EN090503_NAME_F00_86", valid=False),
Data("Truppe, the Ceaseless Dark - Caul: Old Ceremonial Hollow - Nighttime"),
Data("Dysprosium Petramand - Caul: FN Site 505"),
Data("Terbium Petramand - Caul: Sunset Falls"),
Data("Lutetium Petramand - Caul: Ruined City of O'rrn Sim"),
Data("Piernus, the Scorcher - Caul: Ruined City of O'rrn Sim - Daytime"),
Data("EN090503_NAME_F00_87", valid=False),
Data("Copper Cinicula - Prim: South Janpath Plain"),
Data("Bronze Cinicula - Prim: West Janpath Plain"),
Data("Iron Cinicula - Noct: Middle Hushflood"),
Data("EN090503_NAME_F00_88", valid=False),
Data("Eckart, the Indestructible - Prim: Grieving Plains"),
Data("Lake Falsaxum - Obli: North Coast"),
Data("Ghillie Falsaxum - Noct: Middle Hushflood"),
Data("EN090503_NAME_F00_89", valid=False),
Data("EN090503_NAME_F00_90", valid=False),
Data("Clemente, the Iron Meteor - Noct: Nopon Braidbridge"),
Data("EN090503_NAME_F00_91", valid=False),
Data("EN090503_NAME_F00_92", valid=False),
Data("Lava Cinicula - Caul: M'gando Gorge BC"),
Data("Calore, the Lava Walker - Caul: Infernal Ledges"),
Data("EN090503_NAME_F00_93", valid=False),
Data("EN090503_NAME_F00_94", valid=False),
Data("Shadow Falsaxum - Sylv: West Ciel Sandsea"),
Data("EN090503_NAME_F00_95", valid=False),
Data("Mikulas, the Keystone - Sylv: West Ciel Sandsea"),
Data("EN090503_NAME_F00_96", valid=False),
Data("EN090503_NAME_F00_97", valid=False),
Data("Translucent Cinicula - Sylv: East Ciel Sandsea"),
Data("EN090503_NAME_F00_98", valid=False),
Data("Glowing Cinicula - Sylv: Anvil Sandplain"),
Data("EN090503_NAME_F00_99", valid=False),
Data("Thaddaeus, the Ultramafic - Sylv: Lake Ciel"),
Data("EN090503_NAME_F00_100", valid=False),
Data("Falchion, the Vibrant - Noct: FN Site 208"),
Data("EN090503_NAME_F00_101", valid=False),
Data("EN090503_NAME_F00_102", valid=False),
Data("Carrion Vivohast - Sylv: Secluded Lava Lake"),
Data("Grand Vivohast - Sylv: FN Site 414"),
Data("Lethal Vivohast - Sylv: Lake Ciel"),
Data("Lockhart, the Killer of Hope - Sylv: Lake Ciel"),
Data("Echo Thallus - Noct: Canopied Nightwood"),
Data("False Thallus - FN Site 225"),
Data("EN090503_NAME_F00_103", valid=False),
Data("Cunning Thallus - Noct: Rockmole's Burrow"),
Data("Pizelle, the Purple Lightning - Noct: Dead Man's Ingress"),
Data("Recluse Thallus - Obli: Azure Lagoon"),
Data("Faded Thallus - Obli: FN Site 308"),
Data("EN090503_NAME_F00_104", valid=False),
Data("Edgardo, the Carefree - Obli: North Coast"),
Data("Hermit Tectinsula - Noct: Sapphire Table"),
Data("Negator Tectinsula - Noct: Decapotamon"),
Data("Silhouette Tectinsula - Noct: FN Site 205"),
Data("Stealth Tectinsula - Noct: Decapotamon"),
Data("EN090503_NAME_F00_105", valid=False),
Data("EN090503_NAME_F00_106", valid=False),
Data("Soil Tectinsula - Obli: River Isle"),
Data("Clay Tectinsula - Obli: Aaroy Plain"),
Data("Tectonic Tectinsula - Obli: Balance Rock"),
Data("Vittorio, the Battle-Scarred - Obli: River Isle"),
Data("Smalt Arenatect - Sylv: South Ciel Sandsea"),
Data("Cerulean Arenatect - Sylv: Badr Basin"),
Data("Turqoise Arenatect - Sylv: Badr Basin"),
Data("Man'an, the Water Whisperer - Sylv: Lake Ciel"),
Data("EN090503_NAME_F00_107", valid=False),
Data("EN090503_NAME_F00_108", valid=False),
Data("Saffron Arenatect - Sylv: North Cinderdunes"),
Data("Topaz Arenatect - Sylv: Banshee Cave"), #maybe flying?
Data("Antara, the Water Diviner - Sylv: West Cinderdunes"),
Data("Pebble Blatta - Prim: Shadow Rise - Nighttime"),
Data("Swift Blatta - Prim: East Gate Plain"),
Data("Tough Blatta - Prim: FN Site 110"),
Data("Black Blatta - Prim: Rock Cavern"),
Data("Dark Blatta - Prim: Talon Rock Third Terrane"),
Data("Hell Blatta - Prim: FN Site 110"),
Data("Casper, the Unhealthy Eater - Prim: West Gate Plain - Nighttime"),
Data("Egg Blatta - Prim: East Gate Plain - Nighttime"),
Data("Lava Blatta - Prim: Northpointe Beach - Nighttime"),
Data("Chrysalis Blatta - Obli: Leaning Ring"),
Data("Guise Blatta - Sylv: Needle Rock Sandsea"),
Data("Young Blatta - Prim: Talon Rock Third Terrane - Nighttime"),
Data("EN090503_NAME_F00_109", valid=False),
Data("Prinsipe, the Ravenous - Caul: Forgotten Mining Frigates - Nighttime"),
Data("Creeping Blatta - Prim: West Gate Plain - Daytime"),
Data("Sneaking Blatta - Prim: Wonderment Bluff - Daytime"),
Data("Stalker Blatta - Prim: FN Site 112 - Daytime"),
Data("Crawler Blatta - Prim: FN Site 109 - Daytime"),
Data("Judge Blatta - Prim: FN Site 108 - Daytime"),
Data("Cursed Blatta - Prim: Primordia Waters"),
Data("Joker, the Unknowable - Noct: Divine Roost", depends=["Divine Roost"]),
Data("Agito, the Golden - Prim: Shadow Rise - Nighttime"),
Data("Roimi, the Affluent - Prim: Janpath Lake - Nighttime"),
Data("Muruse, the Opulent - Noct: Vitroil Cesspool"),
Data("Yuiro, the Luxuriant - Noct: Great Nail"),
Data("Dui, the Invaluable - Obli: Devil's Colony"),
Data("Tico, the Precious - Obli: Beehive Rock"),
Data("Hiro, the Priceless - Sylv: Sandsprint Cavity - Nighttime", depends=["Sandsprint Cavity"]),
Data("Ald, the Extravagant - Sylv: Quay Hollows"), #maybe flying?
Data("Camus, the Treasured - Caul: Bestial Utopia"),
Data("Natt, the Inestimable - Caul: FN Site 507"),
Data("White Blatta - Prim: Headwater Cavern"),
Data("Metal Blatta - Prim: Headwater Cavern"),
Data("Wootz Blatta - Prim: Castaway Cavern"),
Data("Platinum Blatta - Sylv: Secluded Lava Lake"),
Data("Diamond Blatta - Sylv: Behemoth's Shadows"),
Data("Crystal Blatta - Sylv: Banshee Cave"),
Data("Vorpall, the Sickle-Fanged - Sylv: Banshee Cave"),
Data("Dove Turba - Noct: FN Site 222"),
Data("Lark Turba - Noct: FN Site 217"),
Data("Kite Turba - Noct: Decapotamon"),
Data("Crane Turba - Sylv: Cinderdunes"),
Data("Tormenta, the Scarlet-Clad - Noct: Decapotamon"),
Data("Miniature Adsecula - Prim: Starfall Basin - Nighttime"),
Data("Shadow Adsecula - Prim: Headwater Cavern - Nighttime"),
Data("Savanna Adsecula - Prim: Unicorn Rock"),
Data("Dusk Adsecula - Prim: Northpointe Beach"),
Data("Umbral Adsecula - Prim: Arendt Bridge"),
Data("Photon Adsecula - Prim: Headwater Cliff"),
Data("Etutanne, the Bloodthirsty - Prim: Silent Mire"),
Data("EN090503_NAME_F00_110", valid=False),
Data("Honey Papil - Prim: South Janpath BC - Daytime"),
Data("Lake Papil - Prim: Biahno River - Daytime"),
Data("River Papil - Prim: Janpath Lake - Daytime"),
Data("Silver Papil - Obli: Beehive Rock - Daytime"),
Data("Gold Papil - Obli: Floating Reef", depends=["Floating Reef"]),
Data("EN090503_NAME_F00_111", valid=False),
Data("Drone Adsecula - Obli: Devil's Colony"),
Data("Recluse Adsecula - Obli: Leaning Ring"),
Data("Faded Adsecula - Obli: North Coast"),
Data("Mirage Adsecula - Caul: M'gango Gorge"),
Data("Ghost Adsecula - Obli: East Ibra Ravine"),
Data("Bertrand, the Gorge Scourge - Obli: East Ibra Ravine"),
Data("Druid Papil - Sylv: Seabird's Beak BC - Daytime"),
Data("Sorcerer Papil - Sylv: Seabird's Beak - Daytime"),
Data("Witch Papil - Sylv: South Ciel Sandsea - Daytime"),
Data("Wizard Papil - Sylv: Delusians North Summit - Daytime"),
Data("Magus Papil - Sylv: Lake Ciel - Daytime"),
Data("Sacrum, the Noctilucent - Noct: Whale's Weeper - Nighttime"),
Data("EN090503_NAME_F00_112", valid=False),
Data("Indigo Turba - Noct: Breakwater Narrow"),
Data("EN090503_NAME_F00_113", valid=False),
Data("Adonis Turba - Caul: Forgotten Mining Frigates"),
Data("Delft Turba - Sylv: Secluded Lava Lake"),
Data("EN090503_NAME_F00_114", valid=False),
Data("Feld, the Indigo-Clad - Sylv: Secluded Lava Lake"),
Data("Violet Germivore - Noct: Seabound Coil Tree"),
Data("Cobalt Germivore - Noct: FN Site 217"),
Data("Viridian Germivore - Obli: Sea Whisper Valley"),
Data("Saffron Germivore - Noct: FN Site 224"),
Data("EN090503_NAME_F00_115", valid=False),
Data("Carmine Germivore - Obli: East Ibra Ravine"),
Data("Lomoth, the Beast-Eater - Obli: Primeval Meadow"),
Data("Skulker Germivore - Sylv: Seabird's Beak BC"),
Data("Echo Germivore - Sylv: Seabird's Beak"),
Data("Shadow Germivore - Sylv: Hilal Meadow"),
Data("Secret Germivore - Sylv: Hilal Meadow"),
Data("Survivor Germivore - Sylv: FN Site 414"),
Data("Lethal Germivore - Sylv: Banshee Cave"),
Data("Florence, the Hell Maggot - Sylv: Hilal Meadow - Nighttime"),
Data("Squallo, the Sand Mirer - Obli: Big Arch - Daytime"),
Data("EN090503_NAME_F00_116", valid=False),
Data("EN090503_NAME_F00_117", valid=False),
Data("Sandy Sabula - Sylv: South Slient Sandsea"),
Data("Inferno Ictus - Prim: Roof Rock - Nighttime"),
Data("Immortal Ictus - Prim: Roof Rock - Nighttime"),
Data("Valyrian, the Iron Cleaver - Obli: Alexander Ridge"),
Data("EN090503_NAME_F00_118", valid=False),
Data("Sand Aeviter - Sylv: Hilal Meadow"),
Data("Macabre Aeviter - Sylv: Sandsprint Cavity", depends=["Sandsprint Cavity"]),
Data("Berthold, the Blue-Eyed - Sylv: Sandsprint Cavity", depends=["Sandsprint Cavity"]),
Data("EN090503_NAME_F00_119", valid=False),
Data("Frightening Ictus - Obli: FN Site 309"),
Data("Fearsome Ictus - Obli: Alexander Ridge"),
Data("EN090503_NAME_F00_120", valid=False),
Data("Belenguer, the Gunhammer - Obli: King's falls"),
Data("Warlord Ictus - Caul: Abandoned Bivouac"),
Data("Chieftain Ictus - Sylv: East Ciel Sandsea"),
Data("Daimyo Ictus - Caul: Bestial Utopia"),
Data("Terenty, the Blademaster - Caul: Capital Wreckage"),
Data("Balduino, the Wicked-Eyed - Noct: Sentinel's Nest", depends=["Divine Roost"]),
Data("Flame Lophid - Caul: FN Site 505"),
Data("Blast Lophid - Caul: FN Site 506"),
Data("Burning Lophid - Prim: Molten Hollow"),
Data("Izgnanie, the Smoldering - Caul: Sunset Falls"),
Data("EN090503_NAME_F00_121", valid=False),
Data("EN090503_NAME_F00_122", valid=False),
Data("EN090503_NAME_F00_123", valid=False),
Data("Albin, the Wicked Meddler - Sylv: Lake Ciel - Nighttime"),
Data("Darling Purgovent - Sylv: Lake Ciel - Nighttime"),
Data("Ocean Lophid - Prim: Castaway Cavern"),
Data("Marine Lophid - Prim: Clidside Beach - Daytime"),
Data("Ridill, the Arrogant - Prim: Northpointe Beach"),
Data("Coral Purgovent - Obli: Azure Lagoon"),
Data("Ocean Purgovent - Obli: FN Site 314"),
Data("EN090503_NAME_F00_124", valid=False),
Data("Cave Duoguill - Prim: Headwater Cavern"),
Data("Placid Duoguill - Prim: Slient Mire - Nighttime"),
Data("Nether Duoguill - Prim: Castaway Cavern"),
Data("Blood Duoguill - Prim: FN site 102 - Nighttime"),
Data("Lethal Duoguill - Obli: South Coast"),
Data("Hephaestus, the Absconder - Prim: East Gate Plain - Nighttime"),
Data("Electric Scintimure - Noct: Sato Headwater"),
Data("Blitz Scintimure - Caul: Titan's Table"),
Data("Thunder Scintimure - Caul: Titan's Table"),
Data("EN090503_NAME_F00_125", valid=False),
Data("Eddy, the Electric Heat - Caul: Titan's Table"),
Data("Thunder Duoguill - Obli: FN site 313"),
Data("EN090503_NAME_F00_126", valid=False),
Data("Electro Duoguill - Obli: Floating Reef", depends=["Floating Reef"]),
Data("Plasma Duoguill - Sylv: FN Site 401", regions=["Flight Module"]), #fairly sure this is required since they are in the sea
Data("Valeriano, the Rolling Thunder - Obli: Leaning Ring - Electromagnetic Storm"),
Data("EN090503_NAME_F00_127", valid=False),
Data("EN090503_NAME_F00_128", valid=False),
Data("EN090503_NAME_F00_129", valid=False),
Data("Blind Scintimure - Sylv: Lake Ciel - Spores"),
Data("Zohan, the Thunderbolt - Sylv: Delusians North Summit - Spores", regions=["Skell License"]),  #TAJ
Data("Tainted Scintimure - Noct: Dead Man's Gulch"),
Data("EN090503_NAME_F00_130", valid=False),
Data("Glimmering Scintimure - Sylv: Lower Delusian Mountains"),
Data("Bright Scintimure - Sylv: Northern Searoad"),
Data("Statue Scintimure - Sylv: Anvil Sandplain"),
Data("Legato, the Sky Watcher - Sylv: Behemoth's Shadows"),
Data("Coil, the Never-Ending - Caul: Dragonbone Promontory - Electromagnetic Storm"),  # teleporter
Data("EN090503_NAME_F00_131", valid=False),
Data("Sky Aetrygon - Sylv: Needle Rock Sandsea"),
Data("Lofty Aetrygon - Sylv: Xanadu Overlook"),
Data("EN090503_NAME_F00_132", valid=False),
Data("Ramus, the Supersonic - Sylv: Late Ciel"),
Data("EN090503_NAME_F00_133", valid=False),
Data("Beach Xiphias - Noct: Noctilum Waters"),
Data("Sea Xiphias - Prim: Northpointe Cove"),
Data("Coral Xiphias - Prim: FN Site 120"),
Data("Ocean Xiphias - Noct: FN Site 218"),
Data("EN090503_NAME_F00_134", valid=False),
Data("EN090503_NAME_F00_135", valid=False),
Data("Quick Aetrygon - Obli: FN Site 309"),
Data("Fleet Aetrygon - Obli: Barbarich Desert"),
Data("Vilem, the Gold-Scaled - Obli: Lake Basel"),
Data("EN090503_NAME_F00_136", valid=False),
Data("EN090503_NAME_F00_137", valid=False),
Data("Cave Xiphias - Sylv: Behemoth's Shadows"),
Data("Brandys, the Spectral Light - Sylv: Behemoth's Shadow"),
Data("EN090503_NAME_F00_138", valid=False),
Data("EN090503_NAME_F00_139", valid=False),
Data("Draken, the Drifting Cloud - Prim: Primordia Waters", regions=["Skell License"]),  # TAJ to aggro
Data("EN090503_NAME_F00_140", valid=False),
Data("Valiant Ceto - Caul: FN Site 503 - Nighttime"),
Data("Vanguard Ceto - Caul: Mount M'gando - Nighttime"),
Data("Polaris, the Firmamental - Caul: G'nahan Villa - Nighttime"),
Data("EN090503_NAME_F00_141", valid=False),
Data("Coral Balaena - Prim: La Mancha"), #Maybe flight only?
Data("Sea Balaena - Prim: FN Site 121"),
Data("Ocean Balaena - Obli: Oblivia Waters"),
Data("Rajidi, the Cumuliform - Prim: FN Site 121"),
Data("Lunar Ceto - Noct: Dead Man's Ingress - Nighttime"),
Data("Selenic Ceto - Noct: Qing Long Glade - Nighttime"),
Data("Elaine, the Lunar Eclipse - Obli: Lake Basel - Nighttime"),
Data("Young Grex - Prim: East Gate Plain"),
Data("Bush Grex - Prim: Biahno Grassland"),
Data("Giant Grex - Prim: North Janpath Plain"),
Data("Lawless Grex - Prim: Beasts' Lair"),
Data("Dieter, the Epicure - Prim: Talon Rock Second Terrane"),
Data("EN090503_NAME_F00_142", valid=False),
Data("Lava Caro - Caul: Titan's Table"),
Data("Servant Caro - Sylv: Badr Stronghold"),
Data("Deadland Caro - Caul: Bestial Utopia"),
Data("Kringe, the Hunting Arrow - Caul: Scholes Battlegrounds"),
Data("Tainted Caro - Noct: Dead Man's Gulch"),
Data("Soldier Grex - Obli: FN Site 302"),
Data("Hunter Grex - Obli: Cliffside Camp"),
Data("Scourer Grex - Obli: FN Site 317"),
Data("EN090503_NAME_F00_143", valid=False),
Data("Celedonio, the Battle-Tested - Obli: Keegan Ridge"),
Data("Sand Caro - Sylv: FN Site 416"),
Data("Prisoner Caro - Sylv: Lower Delusian Mountains"),
Data("Spaniel, the Obedient - Caul: O'rrn Sim Castle Ruins - Daytime"),
Data("EN090503_NAME_F00_144", valid=False),
Data("Legion Caro - Caul: FN Site 511 - Daytime"),
Data("Arch Caro - Caul: Wildcast Fortress"),
Data("Lost Caro - Caul: Old Ceremonial Hollow"),
Data("Andrei, the Cunning - Sylv: Lower Delusian Mountains"),
Data("Little Caro - Sylv: Lower Delusian Mountains"),
Data("Berserk Vigent - Obli: Keegan Ridge - Daytime"),
Data("Brutal Vigent  - Obli: Leaning Ring - Daytime"),
Data("Barnabas, the Despot - Obli: Aaroy Plain - Daytime"),
Data("Fiendish Virago - Noct: Qing Long Glade - Daytime"),
Data("EN090503_NAME_F00_145", valid=False),
Data("Buchwald, the Guardian - Noct: Rockmole's Burrow"), #extremely high hp regen
Data("EN090503_NAME_F00_146", valid=False),
Data("Seeker Vigent - Sylv: Banshee Cave"),
Data("Goliath, the Stronghold - Sylv: North Cinderdunes"),
Data("Nether Virago - Sylv: Abyss Reservoir", depends=["Abyss Reservoir"]),
Data("Behemoth, the Netherdweller - Sylv: Abyss Reservoir", depends=["Abyss Reservoir"]),
Data("Volcannon Vigent - Caul: Emerian Battlegrounds"),
Data("Vainamo, the Bellower - Caul: Capital Wreckage"),
Data("Toy Monoceros - Caul: FN Site 505"),
Data("EN090503_NAME_F00_147", valid=False),
Data("Monoceros Colt - Caul: FN Site 502"),
Data("EN090503_NAME_F00_148", valid=False),
Data("Uluora, the Burgeoning - Caul: Emerian Battlegrounds"),
Data("Hallowed Progen - Noct: Middle Hushflood"),
Data("Lightning Progen - Noct: Middle Hushflood"),
Data("Sacred Progen - Noct: Decapotamon"),
Data("Sanctuary Progen - Noct: Twin Hammers"),
Data("Celestin, the Spring Storm - Prim: Headwater Summit"),
Data("EN090503_NAME_F00_149", valid=False),
Data("Viridian Monoceros - Sylv: Shivering Sands"),
Data("EN090503_NAME_F00_150", valid=False),
Data("Alexei, the Jade - Sylv: West Ciel Sandsea"),
Data("Wise Progen - Obli: Oblivia Ingress"),
Data("Ancient Progen - Obli: Aaroy Plain"),
Data("EN090503_NAME_F00_151", valid=False),
Data("Ernest, the Contemplative - Obli: King's Falls"),
Data("Cliff Monoceros - Caul: FN Site 502"),
Data("Land Monoceros - Caul: Kitsune Stronghold"),
Data("Volcannon Monoceros - Caul: Bestial Utopia"),
Data("Dawid, the Destrier - Caul: Emerian Battlegrounds"),
Data("White Progen - Sylv: Seabird's Beak"),
Data("EN090503_NAME_F00_152", valid=False),
Data("Mountain Progen - Sylv: Delusians North Summit"),
Data("Blaudolch, the Chalcedony - Sylv: Seabird's Beak"),
Data("Young Simius - Prim: Sickle Rock Rise - Daytime"),
Data("Rock Simius - Prim: East Gate Plain"),
Data("Iron Simius - Prim: East Janpath Plain"),
Data("Blitz Simius - Prim: East Gate Plain"),
Data("EN090503_NAME_F00_153", valid=False),
Data("Hayreddin, the Territorial - Prim: East Gate Plain"),
Data("Juvenile Simius - Prim: East Gate Plain"),
Data("EN090503_NAME_F00_154", valid=False),
Data("Canyon Cantor - Sylv: Sandsprint Slope - Nighttime"),
Data("Cave Cantor - Sylv: Behemoth's Shadows"),
Data("Origin Cantor - Obli: Demon's Pocket", depends=["Demons Pocket"]),
Data("Eustachio, the Eccentric - Sylv: Behemoth's Shadows"),
Data("Raging Simius - Noct: Rustpool Banks"),
Data("Angry Simius - Noct: Canopied Nightwood"),
Data("Furious Simius - Prim: Primordia Waters"),
Data("Wrathful Simius - Noct: FN Site 225"),
Data("Punisher Simius - Noct: Canopied Nightwood"),
Data("Demetrio, the Tempestuous - Noct: Ensconced Citadel"),
Data("EN090503_NAME_F00_155", valid=False),
Data("Recluse Cantor - Sylv: Delusians South Summit"),
Data("Leandro, the Sneering - Sylv: Behemoth's Shadows"),
Data("EN090503_NAME_F00_156", valid=False),
Data("EN090503_NAME_F00_157", valid=False),
Data("Daylight Aprica - Prim: Biahno Grassland - Daytime"),
Data("EN090503_NAME_F00_158", valid=False),
Data("EN090503_NAME_F00_159", valid=False),
Data("EN090503_NAME_F00_160", valid=False),
Data("Shaman Cervus - Sylv: Delusians North Summit"),
Data("Pastoral Cervus - Noct: Nopon Highroad - Daytime"), #maybe flying?
Data("Seti, the Light of Stars - Noct: Whale's Weeper - Nighttime"),
Data("Wise Aprica - Obli: Keegan Ridge"),
Data("EN090503_NAME_F00_161", valid=False),
Data("Primal Aprica - Obli: FN Site 317"),
Data("Sviatoslav, the Reproachful - Obli: Balance Rock - Rain"),
Data("EN090503_NAME_F00_162", valid=False),
Data("Old Cervus - Sylv: Lake Ciel"),
Data("Asana, the Azure Star - Sylv: Lake Ciel"),
Data("Brass Suid - Prim: West Gate Plain"),
Data("Iron Suid - Prim: Janpath Lake"),
Data("Steel Suid - Prim: Talon Rock Second Terrane"),
Data("Adamant Suid - Prim: FN Site 120 - Daytime"),
Data("Silver Suid - Prim: FN Site 108 - Daytime"),
Data("EN090503_NAME_F00_163", valid=False),
Data("Gugli, the Relentless - Prim: Janpath Lake"),
Data("Megatonne, the Hell Express - Prim: Biahno Grassland"),
Data("Little Suid - Prim: Primordia"),
Data("Domestic Armored Suid - Prim: Seaswept Base"),
Data("EN090503_NAME_F00_164", valid=False),
Data("Trained Armored Suid - Obli: Rooney Cavern"),
Data("EN090503_NAME_F00_165", valid=False),
Data("Tough Armored Suid - Prim: FN Site 103"),
Data("Macho Armored Suid - Obli: Scabland Fortress"),
Data("Bogdan, the Dense - Prim: Seaswept Base"),
Data("Brass Femina Suid - Prim: West Gate Plain - Daytime"),
Data("Iron Femina Suid - Prim: La Mancha"),
Data("Steel Femina Suid - Prim: Talon Rock Second Terrane"),
Data("Bronze Femina Suid - Prim: FN Site 120"),
Data("Silver Femina Suid - Prim: FN Site 108"),
Data("Melanya, the Sound Sleeper - Obli: Oblivia Ingress"),
Data("Little Femina Suid - Prim: West Gate Plain"),
Data("River Suid - Noct: FN Site 209"),
Data("Forest Suid - Noct: Sapphire Table"),
Data("EN090503_NAME_F00_166", valid=False),
Data("Lurker Suid - Noct: FN site 202"),
Data("Olegario, the Iron-Helmed - Noct: Whale's Weeper - Nighttime"),
Data("EN090503_NAME_F00_167", valid=False),
Data("Forest Femina Suid - Noct: Old Dragontail Tree"),
Data("EN090503_NAME_F00_168", valid=False),
Data("EN090503_NAME_F00_169", valid=False),
Data("Manuelita, the Affectionate - Noct: Middle Hushflood"),
Data("Grassland Ovis - Prim: East Gate Plain - Daytime"),
Data("Docile Ovis - Prim: FN Site 114 - Daytime"),
Data("Rogue Ovis - Prim: South Janpath Plain - Daytime"),
Data("EN090503_NAME_F00_170", valid=False),
Data("Baabara, the Evangelical - Prim: South Janpath Plain - Daytime"),
Data("EN090503_NAME_F00_171", valid=False),
Data("EN090503_NAME_F00_172", valid=False),
Data("White Ovis - Sylv: FN Site 415"),
Data("Wandering Ovis - Sylv: Delusians North Summit"),
Data("Native Ovis - Sylv: FN Site 413"),
Data("Clara, the Pure White - Sylv: North Slient Sandsea - Daytime"),
Data("EN090503_NAME_F00_173", valid=False),
Data("Eternal Millesaur - Prim: Sayram Lake"),
Data("Everlasting Millesaur - Prim: Biahno Lake"),
Data("Fernando, the Immovable - Noct: Decapotamon - Daytime"),
Data("Ancient Coronid - Sylv: Lake Ciel"),
Data("Xair, the Cerulean Walker - Sylv: Sylvaluim Waters"),
Data("Luciel, the Eternal - Prim: Janpath Lake"),
Data("Frenzied Coronid - Sylv: Lake Ciel - Crimson Aurora"),
Data("Ignit, the Ultimate Chaos - Sylv: Lake Ciel - Crimson Aurora"),
Data("Quick Evello - Prim: Roof Rock - Daytime"),
Data("Fleet Evello - Prim: FN Site 115"),
Data("Swift Evello - Prim: Talon Rock Second Terrance - Daytime"),
Data("Roderick, the Fleet-Footed - Prim: East Gate Plain - Daytime"),
Data("Cowardly Caecus - Caul: Emerian Battlegrounds"),
Data("Thug Caecus - Caul: FN Site 502"),
Data("EN090503_NAME_F00_174", valid=False),
Data("Cliff Caecus - Caul: T'phnom Shelf"),
Data("Land Caecus - Caul: Ternion Fork"),
Data("Pelicollo, the Panzer - Caul: Ternion Fork"),
Data("Poisonous Caecus - Sylv: Southern Searoad"),
Data("Villainous Caecus - Sylv: FN Site 402"),
Data("EN090503_NAME_F00_175", valid=False),
Data("Andrea, the Famished Hunter - Sylv: West Ciel Sandsea"),
Data("Wasteland Evello - Obli: North Coast - Daytime"),
Data("Grand Evello - Obli: FN Site 312 - Daytime"),
Data("Ludvik, the Picky Eater - Obli: Keegan Ridge - Daytime"),
Data("Spear Insidia - Noct: Sunlit Spring"),
Data("Pike Insidia - Noct: Fukai pass"),
Data("Javelin Insidia - Obli: Aaroy Plain"),
Data("Glaive Insidia - Obli: Victory Rock"),
Data("EN090503_NAME_F00_176", valid=False),
Data("Lambert, the Divine Wind - Noct: Goblin's Narrow"),
Data("Sludge Caecus - Noct: Coil Tree Cape"),
Data("Darting Caecus - Noct: Cascade Isle"),
Data("Drake, the Waypost - Noct: Orochi's Belly"),
Data("EN090503_NAME_F00_177", valid=False),
Data("Vermilion Insidia - Noct: Fukai Pass"),
Data("Griffus, the Tartarean - Noct: Fukai Pass"),
Data("Feliciano, the All-Seeing - Obli: Central Ibra Ravine - Daytime"),
Data("EN090503_NAME_F00_178", valid=False),
Data("Bluff Gerrid - Caul: Adder Byroad"),
Data("Land Gerrid - Caul: Adder Byroad"),
Data("EN090503_NAME_F00_179", valid=False),
Data("Bartley, the Conflagration - Caul: Adder Byroad"),
Data("EN090503_NAME_F00_180", valid=False),
Data("Wood Lepyx - Prim: East Gate Plain"),
Data("Prairie Lepyx - Prim: West Janpath Plain"),
Data("EN090503_NAME_F00_181", valid=False),
Data("EN090503_NAME_F00_182", valid=False),
Data("Sirene, the Lost - Prim: Sickle Rock Rise"),
Data("Pollen Lepyx - Sylv: Needle Rock Sandsea"),
Data("Nomad Lepyx - Sylv: South Ciel Sandsea"),
Data("EN090503_NAME_F00_183", valid=False),
Data("EN090503_NAME_F00_184", valid=False),
Data("Giraffin, the Old Hand - Sylv: South Silent Sandsea"),
Data("Macabre Gerrid - Sylv: Den of the Dead", depends=["Den of the Dead"]),
Data("Evil Gerrid - Sylv: Anvil Sandplain"),
Data("Daemon, the Undertaker - Sylv: Den of the Dead", depends=["Den of the Dead"]),
Data("Plant Mortifole - Prim: Seaswept Ridge"),
Data("Lake Mortifole - Noct: Rustpool Banks"),
Data("Gardener Mortifole - Noct: Canopied Nightwood"),
Data("EN090503_NAME_F00_185", valid=False),
Data("Native Mortifole - Noct: FN Site 216 - Daytime"),
Data("EN090503_NAME_F00_186", valid=False),
Data("Yessenia, the Husky-Voiced - Noct: Garden Spring"),
Data("Abyssal Sacrifole - Sylv: Needle Rock Sandsea"),
Data("Giant Sacrifole - Sylv: Lake Ciel"),
Data("Mega Sacrifole - Sylv: Lake Ciel"),
Data("Dobromila, the Alluring - Sylv: Lake Ciel"),
Data("Drone Mortifole - Obli: Twin Arches"),
Data("Recluse Mortifole - Obli: FN site 318"),
Data("EN090503_NAME_F00_187", valid=False),
Data("Jindriska, the Serene - Obli: Twin Arches"),
Data("Poisonous Mortifole - Obli: Lake Basel"),
Data("EN090503_NAME_F00_188", valid=False),
Data("Toxic Mortifole - Obli: Aaroy Plain"),
Data("EN090503_NAME_F00_189", valid=False),
Data("Eliane, the Unmoved - Obli: FN Site 312"),
Data("EN090503_NAME_F00_190", valid=False),
Data("Grotto Mortifole - Noct: Goblin's Narrow"),
Data("Cave Mortifole - Prim: Castaway Cavern"),
Data("Crusher Mortifole - Noct: Yagami's Vista"),
Data("EN090503_NAME_F00_191", valid=False),
Data("EN090503_NAME_F00_192", valid=False),
Data("Katerina, the Cliffhanger - Noct: Everwhelm Falls"),
Data("Aquatic Sacrifole - Caul: FN Site 515"),
Data("Puddle Sacrifole - Caul: Scholes Battlegrounds"),
Data("Lake Sacrifole - Sylv: Behemoth's Shadows"),
Data("Foul Sacrifole - Caul: Bestial Utopia"),
Data("Angelita, the Blade Bouquet - Caul: M'Gando Mineral Spring"),
Data("Lava Sacrifole - Caul: FN Site 505"),
Data("EN090503_NAME_F00_193", valid=False),
Data("Vegetal, the Heatcrux - Caul: FN Site 506"),
Data("EN090503_NAME_F00_194", valid=False),
Data("Welkin Auravis - Prim: Arendt Bridge"),
Data("Reaver Auravis - Prim: FN Site 109"),
Data("Sky Auravis - Prim: Headwater Summit"),
Data("EN090503_NAME_F00_195", valid=False),
Data("Bohdan, the Mistral - Prim: Unicorn Rock"),
Data("EN090503_NAME_F00_196", valid=False),
Data("Rocket Jacul - Caul: FN Site 509"),
Data("Storm Jacul - Caul: Emerian Battlegrounds"),
Data("Tornado Jacul - Caul: Mount M'gando"),
Data("Jia Mian, the Beloved - Caul: Mount M'gando"),
Data("EN090503_NAME_F00_197", valid=False),
Data("Gale Auravis - Obli: Oblivia Ingress"),
Data("Blast Auravis - Obli: Leaning Ring"),
Data("Typhoon Auravis - Obli: Leaning Ring"),
Data("Tempest Auravis - Obli: FN Site 315"),
Data("Gotthard, the Intimidating - Obli: Yawning Giant"), #maybe flying?
Data("EN090503_NAME_F00_198", valid=False),
Data("Jade Jacul - Sylv: Shivering Sands"),
Data("Canyon Jacul - Sylv: West Ciel Sandsea"),
Data("Mountain Jacul - Noct: Weeping Whitewood - Daytime"),
Data("Radovan, the Sky Baron - Sylv: Lake Ciel - Daytime"),
Data("Welkin Levitath - Prim: East Janpath Plain"),
Data("EN090503_NAME_F00_199", valid=False),
Data("Eutropio, the Sea Rumble - Prim: Seaswept Ridge"),
Data("Cataract Levitath - Obli: Stoyanov Trail"),
Data("Abyssal Levitath - Obli: Keegan Ridge"),
Data("Silvestre, the Morning Light - Obli: Drowning Ring"),
Data("Scarlet Levitath - Noct: Rust Lake - Nighttime"),
Data("Antares Levitath - Noct: Rustpool Banks - Nighttime"),
Data("Frajeel, the Purgatorial - Noct: Divine Roost", depends=["Divine Roost"]),
Data("Elvira, the Talondrake - Prim: Talon Rock Summit", depends=["Talon Rock Summit"]),
Data("EN090503_NAME_F00_200", valid=False),
Data("EN090503_NAME_F00_201", valid=False),
Data("EN090503_NAME_F00_202", valid=False),
Data("Hartmut, the Calamity - Obli: Yawning Giant"), #Doesn't require skells to fight, but recommended?
Data("Spring Unafulge - Noct: Whale's Nostril"),
Data("Floating Unafulge - Sylv: North Slient Sandsea"),
Data("Drifter Unafulge - Noct: FN site 207 - Nighttime"),
Data("Lethal Unafulge - Sylv: South Slient Sandsea"),
Data("Abyssal Unafulge - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Planetes, the Torrential - Noct: Celestial Cleave"), #maybe divine roost?
Data("EN090503_NAME_F00_203", valid=False),
Data("EN090503_NAME_F00_204", valid=False),
Data("EN090503_NAME_F00_205", valid=False),
Data("Lake Visigel - Sylv: Lake Ciel"),
Data("EN090503_NAME_F00_206", valid=False),
Data("Sapphire Visigel - Sylv: Lake Ciel"),
Data("Yune, the Ambusher - Sylv: Seabird's Beak"),
Data("Lava Unafulge - Sylv: Secluded Lava Lake"),
Data("Ruth, the Shunner of Light - Sylv: Secluded Lava Lake"),
Data("Coast Visigel - Caul: FN Site 515"),
Data("Cave Visigel - Caul: Infernal Ledges"),
Data("EN090503_NAME_F00_207", valid=False),
Data("Razer Visigel - Caul: Cauldros Waters"),
Data("Spore Filiavent - Noct: Ensanguined Font - Nighttime"),
Data("Laurencio, the Fog Bow - Sylv: Lake Ciel"),
Data("EN090503_NAME_F00_208", valid=False),
Data("Phosphorous Filiavent - Caul: White Phosphor Lake"),
Data("Trueno, the Cataclysm - Caul: White Phosphor Lake"),
Data("EN090503_NAME_F00_209", valid=False),
Data("Nocturnal Vesper - Prim: East Gate Plain - Nighttime"),
Data("Blind Vesper - Prim: FN Site 107 - Nighttime"),
Data("Dark Vesper - Prim: Castaway Cavern"),
Data("Mortal Vesper - Prim: Molten Hollow"),
Data("Ripper Vesper - Noct: Rockmole's Burrow"),
Data("EN090503_NAME_F00_210", valid=False),
Data("Necro, the Cavelord - Prim: Drop Shaft", depends=["Drop Shaft"]),
Data("Hushed Murra - Sylv: Cleansing Spring"),
Data("Silent Murra - Caul: White Phosphor Lake"),
Data("Quiet Murra - Sylv: Badr Basin"),
Data("Strange Murra - Sylv: FN Site 410"),
Data("Uncanny Murra - Sylv: Sandsprint Cavity", depends=["Sandsprint Cavity"]), #can be accessed without using skell tech
Data("Camille, the Immortal - Sylv: Cleansing Spring"),
Data("Froste, the Courteous - Noct: Vitriol Cesspool"),
Data("Lake Terebra - Prim: Biahno Lake"),
Data("Pit Terebra - Prim: South Janpath Plain"),
Data("Whirling Terebra - Prim: Janpath Lake"),
Data("Shinhwa, the Sagacious - Noct: Decapotamon"),
Data("Mischievous Mephite - Noct: Whale's Nostril"),
Data("Impish Mephite - Obli: Aaroy Plain"),
Data("Malicious Mephite - Noct: Shark's Jaws"),
Data("Gerhardt, the Lone and Proud - Noct: Whale's Nostril"),
Data("EN090503_NAME_F00_211", valid=False),
Data("Pond Terebra - Noct: FN Site 205"),
Data("Nomad Terebra - Noct: Canopied Nightwood"),
Data("Crusher Terebra - Noct: Whale's Weeper"),
Data("EN090503_NAME_F00_212", valid=False),
Data("Fell Terebra - Prim: Northpointe Beach"),
Data("Archibolt, the Revolutionary - Prim: Biahno Lake - Rain"),
Data("Prowler Mephite - Obli: Aaroy Plain"),
Data("Stray Mephite - Obli: FN Site 312"),
Data("EN090503_NAME_F00_213", valid=False),
Data("Ferdinand, the Fortuitous - Obli: Lake Basel"),
Data("EN090503_NAME_F00_214", valid=False),
Data("Lawless Mephite - Caul: Drongo Caravan"),
Data("Evil Mephite - Caul: FN Site 504"),
Data("EN090503_NAME_F00_215", valid=False),
Data("Lask, the Unscrupulous - Sylv: Gehenna Span"),
Data("Jocular Saltat - Noct: Rust Lake"),
Data("Droll Saltat - Prim: Janpath Lake"),
Data("Sapara, the Laconic - Prim: Unicorn Rock"),
Data("EN090503_NAME_F00_216", valid=False),
Data("Strange Liceor - Sylv: Needle Rock Sandsea"),
Data("Glowing Liceor - Sylv: East Ciel Sandsea"),
Data("Dazzling Liceor - Sylv: FN Site 415 "),
Data("Stola, the Champion - Sylv: Seabird's Beak - Crimson Aurora"),
Data("EN090503_NAME_F00_217", valid=False),
Data("Viridian Saltat - Prim: Janpath Lake"),
Data("Saffron Saltat - Prim: Molten Hollow"),
Data("EN090503_NAME_F00_218", valid=False),
Data("Citrine Saltat - Prim: Molten Hollow"),
Data("EN090503_NAME_F00_219", valid=False),
Data("Garnet Saltat - Prim: Fallshorn Isle"),
Data("Zdenka, the Raucous - Prim: Fallshorn Isle"),
Data("EN090503_NAME_F00_220", valid=False),
Data("Ruby Saltat - Prim: Fallshorn Isle"),
Data("Jarosch, the Sensational - Noct: Potter's Rock"),
Data("EN090503_NAME_F00_221", valid=False),
Data("Awakened Liceor - Sylv: FN Site 415 - Rising Energy Mist"),
Data("Divine Liceor - Sylv: Delusions South Summit"),
Data("Stola, the Unchained - Sylv: Delusions South Summit - Rising Energy Mist"),
Data("EN090503_NAME_F00_222", valid=False),
Data("Itinerant Saltat - Obli: Central Ibra Ravine"),
Data("Strange Saltat - Caul: Scholes Battlegrounds - Clear"),
Data("Gypsy Saltat - Caul: Capital Wreckage - Clear"),
Data("EN090503_NAME_F00_223", valid=False),
Data("Island Saltat - Caul: FN Site 505 - Clear"),
Data("Native Saltat - Obli: Lake Basel"),
Data("Mystic Saltat - Obli: King's Falls"),
Data("Crested Saltat - Caul: Mount M'gando - Clear"),
Data("Cloud Saltat - Caul: Mount M'gando - Rainbows"),
Data("Zorn, the Wanderer - Caul: Old Ceremonial Hollow - Rainbows"),
Data("EN090503_NAME_F00_224", valid=False),
Data("EN090503_NAME_F00_225", valid=False),
Data("Sorrowful Saltat - Obli: King's Falls"),
Data("Rapture Saltat - Obli: Primeval Meadow"),
Data("EN090503_NAME_F00_226", valid=False),
Data("Prisoner Saltat - Obli: Primeval Meadow"),
Data("EN090503_NAME_F00_227", valid=False),
Data("Fiasco Saltat - Caul: Scholes Battlegrounds - Clear"),
Data("Imbecile Saltat - Obli: Cryptic Sign"),
Data("Sluggish Saltat - Obli: Floating Reef", depends=["Floating Reef"]),
Data("Bressole, the Fugitive - Obli: Oblivia Waters SE"),
Data("Stone Potamus - Prim: Starfall Basin"),
Data("Rock Potamus - Prim: Biahno River"),
Data("Copper Potamus - Obli: FN Site 309"),
Data("EN090503_NAME_F00_228", valid=False),
Data("Mesgen, the Fairweathered - Prim: Sayram Lake"),
Data("Brother Potamus - Obli: Dorian Caravan"),
Data("Merciful Dilus - Noct: Rustpool Banks"),
Data("Acid Dilus - Noct: FN Site 204"),
Data("Hunter Dilus - Noct: Divine Roost", depends=["Divine Roost"]),
Data("EN090503_NAME_F00_229", valid=False),
Data("EN090503_NAME_F00_230", valid=False),
Data("EN090503_NAME_F00_231", valid=False),
Data("Volcannon Tersqual - Caul: Sunset Falls"),
Data("Agnes, the Divine-Scaled - Caul: FN Site 506"),
Data("EN090503_NAME_F00_232", valid=False),
Data("EN090503_NAME_F00_233", valid=False),
Data("Lake Dilus - Obli: River Isle"),
Data("EN090503_NAME_F00_234", valid=False),
Data("EN090503_NAME_F00_235", valid=False),
Data("EN090503_NAME_F00_236", valid=False),
Data("Sheldon, the Dentally Challenged - Obli: West Ibra Ravine"), #Probably my fav title ngl
Data("EN090503_NAME_F00_237", valid=False),
Data("Lively Tersqual - Sylv: Lake Ciel"),
Data("Latis, the Bristle-Scaled - Sylv: North Silent Sandsea"),
Data("Green Master Galdr - Sylv: Anvil Rock One"),
Data("Experimental Composite Qmoeva - Prim: Talon Rock Summit - Nighttime", depends=["Talon Rock Summit"]),
Data("EN090503_NAME_F00_238", valid=False),
Data("EN090503_NAME_F00_239", valid=False),
Data("EN090503_NAME_F00_240", valid=False),
Data("EN090503_NAME_F00_241", valid=False),
Data("Langul, the Alien Payload - Prim: Seaswept Base"),
Data("Volcannon Cinicula - Caul: Titan's Table"),
Data("Pure Cinicula - Prim: West Janpath Plain"),
Data("Alfombra, the Transcendent - Noct: Humdrum Peaks"),
Data("Minor Sabula - Noct: Suncatch Ravine"),
Data("Crazed Aeviter - Noct: Sentinel's Nest", depends=["Divine Roost"]),
Data("Libra, the Long-Lived, Obli: North Coast"),
Data("Rain Scintimure - Caul: Dragonbone Promontory - Electromagnetic Storm"),
Data("Storm Scintimure - Caul: Forgotten Mining Frigates - Electromagnetic Storm"),
Data("EN090503_NAME_F00_242", valid=False),
Data("Shatskikh, the Flash - Prim: Northpointe Cove"),
Data("Mighty Virago - Sylv: Northern Searoad"),
Data("Callow Virago - Sylv: Northern Searoad"),
Data("Vice Simius - Obli: Big Arch"),
Data("Mortal Simius - Obli: Keegan Ridge"),
Data("EN090503_NAME_F00_243", valid=False),
Data("Diogenes, the Covetous - Obli: Central Ibra Ravine"),
Data("Oskar, the Summer Squall - Noct: Old Dragontail Tree"),
Data("EN090503_NAME_F00_244", valid=False),
Data("EN090503_NAME_F00_245", valid=False),
Data("Stray Ovis - Noct: Vitriol Cesspool", regions=["Chapter 12"]),
Data("EN090503_NAME_F00_246", valid=False),
Data("EN090503_NAME_F00_247", valid=False),
Data("EN090503_NAME_F00_248", valid=False),
Data("Prowler Ovis - Obli: Ruins on the Butte"),
Data("EN090503_NAME_F00_249", valid=False),
Data("Germaine, the Treasure Keeper - Obli: Eddie's Conquest"),
Data("Parasite Gerrid - Obli: North Coast", regions=["Chapter 12"]),
Data("EN090503_NAME_F00_250", valid=False),
Data("Hell Gerrid - Sylv: Quay Hollows"),
Data("EN090503_NAME_F00_251", valid=False),
Data("Mirage Mortifole - Noct: Everwhelm Falls"),
Data("EN090503_NAME_F00_252", valid=False),
Data("EN090503_NAME_F00_253", valid=False),
Data("Poppy, the Pyromaniac - Caul: Infernal Ledges"),
Data("Blood Vesper - Prim: Wonderment Bluff - Nighttime"),
Data("Carmine Vesper - Prim: Drop Shaft", depends=["Drop Shaft"]),
Data("Aria, the Zauberflöte - Noct: Rust Lake"),
Data("Jade Saltat - Noct: Potter's Rock"),
Data("Wenzel, the Inebriated - Obli: Cryptic Sign"),
Data("EN090503_NAME_F00_254", valid=False),
Data("Rolf, the Sonorous - Obli: King's Falls"),
Data("Minion Potamus - Sylv: Cleansing Spring - Daytime"),
Data("Companion Potamus - Caul: Ganglion Antropolis"),
Data("Rodriguez, the Twin-Tusked - Caul: Emerian Battlegrounds"),
Data("Sarcosuchus, the Iron-Eater - Noct: Rust Lake"),
Data("EN090503_NAME_F00_255", valid=False),
Data("Yellow Arenatect - Caul: White Phosphor Lake"),
Data("EN090503_NAME_F00_256", valid=False),
Data("Ymir Gularth - Caul: Titan's Table - Brinstone Rain"),
Data("Laser Raptor Seidr - Sunset Falls", regions=["Flight Module"]), # maybe with less
Data("Aegis Raptor Seidr - Emerian Battlegrounds", regions=["Skell License"]),  # TAJ to aggro
Data("Grav Raptor Seidr - FN Site 508", regions=["Flight Module"]), # maybe with less
Data("EN090503_NAME_F00_257", valid=False),
Data("EN090503_NAME_F00_258", valid=False),
Data("EN090503_NAME_F00_259", valid=False),
Data("Autosentry - Good Neighbors", depends=["Good Neighbors"]),
Data("Autosentry Mk.II - The Gauntlet", depends=["The Gauntlet"]),
Data("Buster Emperor Qmoeva - FN Site 505", regions=["Flight Module"]),  # maybe with less
Data("Duel Emperor Qmoeva - Sunset Falls", regions=["Flight Module"]),  # maybe with less
Data("Rebel Emperor Qmoeva - Dragonbone Promontory", regions=["Flight Module"]),  # maybe with less
Data("EN090503_NAME_F00_260", valid=False),
Data("Forest Aprica - Noct: Garden Spring - Daytime"),
Data("Shoal Balaena - Prim: Primordia Water"),
Data("Support Trainee Qmoeva - Prim: Seaswept Base - Nighttime"),
Data("Caranau, the Water Drake - Prim: Biahno River"),
Data("Highland Lepyx - Prim: Seaswept Rise"),
Data("Nu-rhor, the Dark Deity - Obli: Jair Fortress"),
Data("EN090503_NAME_F00_261", valid=False),
Data("Nickel Fal-swo - Obli: Ruins on the Sandbank"),
Data("EN090503_NAME_F00_262", valid=False),
Data("Zirconium Fal-swo - Obli: Jair Fortress"), #maybe flying
Data("No-dhor, the Shadowcaster - Obli: Lake Basel"),
Data("Gadaf's Qmoeva - Prim: Primordia Waters"),
Data("Sizzling Visigel - Caul: FN Site 505"),
Data("Lord Xe-dom - Prim: Talon Rock Summit", depends=["Talon Rock Summit"]),
Data("Bravo Unafulge - Prim: Molten Hollow"),
Data("Marnuck Commander - Sylv: Hilal Stronghold"),
Data("Marnuck Ruffian - Sylv: Hilal Stronghold"),
Data("Marnuck Slugger - Caul: Wildcat Fortress"),
Data("Marnuck Hornet - Caul: FN Site 511"),
Data("Marnuck Grappler - Caul: Boxtrap Checkpoint"),
Data("Marnuck Jaeger - Prim: FN Site 119"),
Data("Marnuck Blaster - Caul: FN site 502"),
Data("Marnuck Firetrooper - Sylv: Badr Stronghold"),
Data("Marnuck Loader - Sylv: Hilal Stronghold"),
Data("Marnuck Howitzer - Obli: Scabland Fortress"),
Data("Marnuck Minor - Caul: Wildcat Fortress"),
Data("Marnuck Soldier - Caul: FN Site 502"),
Data("Marnuck Vanguard - Obli: Cliffside Camp"),
Data("Marnuck Support - Noct: Lotus Keep Building Site"),
Data("Marnuck Guardian - Obli: FN Site 309"),
Data("Marnuck Marksman - Prim: FN Site 108"),
Data("Marnuck Imperial - Caul: O'rrn Sim Gate"),
Data("Marnuck Burster - Sylv: Anvil Rock One"),
Data("Marnuck Gatling - Caul: Old Ceremonial Hollow"),
Data("Marnuck Slayer - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Marnuck Crasher - Obli: Scabland Fortress"),
Data("Marnuck Pulser - Caul: Old Ceremonial Hollow"),
Data("Marnuck Dynamo - Caul: Bestial Utopia"),
Data("Marnuck Transitioner - Caul: FN Site 511"),
Data("Marnuck Converger - Obli: Jair Fortress"),
Data("Marnuck Recon - Noct: Decapotamon Vista"),
Data("Marnuck Mercenary - Obli: FN Site 309"),
Data("Marnuck Barrager - Caul: FN Site 502"),
Data("Marnuck Pawn - Caul: Far Isle of Tzu'o"),
Data("Marnuck Shield Trooper - Ovli: Ruins on the Sandbank"),
Data("Marnuck Sentinel - Prim: Castaway Cavern"),
Data("Prone Major - Prim: Seaswept Base"),
Data("Prone Warrior - Obli: Mesa Fortress"),
Data("Prone Butcher - Prim: Primordia Waters"),
Data("Prone Eater - Prim: Seaswept Base"),
Data("Prone Soldier - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Prone Typhoon - Prim: Seaswept Base"),
Data("Prone Rampager - Noct: FN Site 211"),
Data("Prone Berserker - Prim: FN Site 119"),
Data("Prone Trainer - Prim: FN Site 119"),
Data("Prone Owl - Noct: Ensconced Citadel"),
Data("Prone Vulture - Obli: FN Site 309"),
Data("Prone Eagle - Noct: Lakeview Stronghold"),
Data("Prone Hawk - Obli: FN Site 305"),
Data("Prone Barbarian - Obli: Mesa Fortress"),
Data("Prone Slayer - Noct: Ensconced Citadel"),
Data("Prone Bully - Noct: Lakeview Stronghold"),
Data("Prone Commander - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Prone Fury - Obli: Alexander Ridge"),
Data("Prone Admiral - Obli: FN Site 307"),
Data("Prone Condemned - Obli: Mesa Fortress"),
Data("Prone Savage - Obli: Scabland Fortress"),
Data("Prone Vix Guard - Obli: Mesa Fortress"),
Data("Prone Vix Beta - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Prone Vix Owl - Obli: Barbarich Desert"),
Data("Prone Vix Vulture - Obli: FN Site 309"),
Data("Prone Vix Crow - Obli: Rooney Cavern"),
Data("Prone Vix Hawk - Prim: Primordia Waters"),
Data("Prone Vix Griffin - Prim: Seaswept Base"),
Data("Prone Vix Alpha - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Prone Vix Prisoner - Noct: Ensconced Citadel"),
Data("Prone Vix Delta - Sylv: Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Prone Vix Brutalizer - Obli: Scabland Fortress"),
Data("Pyro Sacrifole - Sylv: Secluded Lava Lake"),
Data("Gu Ladha - Lend an Ear", depends=["Lend an Ear"], valid=False), #Missible depending on route
Data("Fighter Pugilith - Noct: Lotus Keep Building Site"),
Data("Tantalum Fal-swo - Prim: Bedrock Hold"),
Data("Forest Adsecula - Noct: Breakwater Narrow"),
Data("Sparrow Adsecula - Sylv: FN Site 408"),
Data("Endeavorer Adsecula - Sylv: West Ciel Sandsea"),
Data("Alba Lepyx - Obli: Aaroy Plain"),
Data("Innocent Ovis - Obli: FN Site 302"),
Data("Red Master Galdr - Sylv: Anvil Sandplain", regions=["Flight Module"]),
Data("EN090503_NAME_F00_263", valid=False),
Data("EN090503_NAME_F00_264", valid=False),
Data("Rebel Kaizer Qmoeva - Obli: FN Site 322"),
Data("Prometheus Petramand - Obli: FN Site 318"),
Data("Soma Scirpo - Noct: Cascasde Isle"),
Data("Amrita Scirpo - Noct: Rustpool Banks"),
Data("Logi Scirpo - Obli: Big Arch"),
Data("Surtr Scirpo - Noct: Canopied Nightwood"),
Data("Bacchanal Scirpo - Obli: Stoyanov Trail"),
Data("Tharros Scirpo - Noct: FN Site 217"),
Data("Scandium Petramand - Noct: FN Site 216"),
Data("Holmium Petramand - Noct: Rockmole's Burrow"),
Data("EN090503_NAME_F00_265", valid=False),
Data("Shadow Scirpo - Obli: Devil's Colony"),
Data("Carnelian Scirpo - Noct: Canopied Nightwood"),
Data("Carmine Forfex - Noct: FN Site 209"),
Data("Garnet Forfex - Noct: Tripod Rock"),
Data("Mother Forfex - Prim: Cliffside Beach"),
Data("Ruby Forfex - Noct: Bloodpond Basin"),
Data("Femme Forfex - Prim: FN Site 115"),
Data("Big Forfex - Prim: Beast's Lair - Rain"),
Data("Iolite Forfex - Sylv: Seabird's Beak"),
Data("Sapphire Forfex - Sylv: Seabird's Beak"),
Data("Rock Cinicula - Noct: FN Site 208"),
Data("Putrid Falsaxum - Obli: North Coast"),
Data("Mirage Vivohast - Noct: Nopon Highroad"),
Data("Blitz Blatta - Noct: Whale's Nostril"),
Data("Ogre Blatta - Noct: FN Site 224"),
Data("Mirage Blatta - Sylv: Needle Rock Sandsea"),
Data("Hrym Blatta - Caul: Titan's Table"),
Data("Logi Blatta - Noct: Vitriol Cesspool"),
Data("Seeker Blatta - Caul: Mount M'gando"),
Data("Sonic Blatta - Caul: FN Site 509"),
Data("Zeppelin Blatta - Obli: River Isle"),
Data("Prairie Blatta - Noct: FN Site 211 - Nighttime"),
Data("Coal Blatta - Caul: FN Site 507 - Nighttime"),
Data("Tectonic Blatta - Obli: FN Site 301 - Daytime"),
Data("Chartreuse Blatta - Sylv: Needle Rock BC - Daytime"),
Data("Raven Blatta - Noct: FN Site 210"),
Data("Tranquil Blatta - Sylv: Lower Delusian Mountains - Daytime"),
Data("Vampire Blatta - Caul: FN Site 504"),
Data("Magus Blatta - Noct: Vitriol Cesspool"),
Data("Hellion Blatta - Caul: FN Site 504"),
Data("Azure Blatta - Sylv: Abyss Reservoir", depends=["Abyss Reservoir"]),
Data("Moon Blatta - Prim: Drop Shaft", depends=["Drop Shaft"]),
Data("Mirror Blatta - Caul: Bestial Utopia"),
Data("Copper Papil - Noct: Suncatch Ravine = Daytime"),
Data("Bronze Papil - Noct: Dead Man's Ingress"),
Data("Zeppelin Germivore - Prim: FN Site 108"),
Data("Terrible Germivore - Noct: Qing Long Glade"),
Data("Hermit Ictus - Sylv: Banshee Cave"),
Data("Tidal Purgovent - Noct: Vitriol Cesspool"),
Data("Bolt Duoguill - Obli: North Coast"),
Data("Callous Scintimure - Noct: Middle Hushflood"),
Data("Storm Caro - Sylv: Cauldros Threshold - Nighttime"),
Data("Grand Cantor - Caul: Scholes Battlegrounds"),
Data("Violet Cervus - Obli: Great Washington Isle - Nighttime"),
Data("Western Suid - Obli: Twin Arches"),
Data("Bronze Suid - Obli: Keegan Ridge"),
Data("Adamant Armored Suid - Obli: Scabland Fortress"),
Data("Crazed Femina Suid - Obli: Twin Arches"),
Data("Alba Femina Suid - Obli: Keegan Ridge"),
Data("Origin Mortifole - Noct: FN site 209"),
Data("Pit Mortifole - Prim: Unicorn Rock"),
Data("Callous Mortifole - Noct: Skybound Coil Tree"),
Data("Wind Auravis - Noct: Rustpool Banks - Daytime"),
Data("Fluid Jacul - Obli: Demon's Pocket"),
Data("Highland Jacul - Sylv: Deulsians South Summit"),
Data("Creek Unafulge - Sylv: Seabird's Beak"),
Data("Dryland Unafulge - Sylv: South Ciel Sandsea"),
Data("Strange Vesper - Obli: Devil's Colony"),
Data("Abyssal Vesper - Noct: Suncatch Ravine - Nighttime"),
Data("Uncanny Vesper - Obli: West Ibra Ravine"),
Data("Thug Mephite - Sylv: Secluded Lava Lake"),
Data("Prankster Mephite - Sylv: Gheenna Span"),
Data("Huge Potamus - Prim: Sayram Lake"),
Data("Young Cinicula - Prim: FN Site 117"),
Data("Blazing Lophid - Caul: White Phosphor Lake"),
Data("Gate Puge - Caul: Far Isle of Tzu'o"),
Data("Porter Puge - Caul: FN Site 502"),
Data("Fighter Puge - Caul: White Phosphor Lake"),
Data("Border Puge - Noct: Lotus Keep Building Site"),
Data("Remote Puge - Prim: Primordia Waters North"),
Data("Spear Puge - Prim: Lesser Gemini Bridge"),
Data("Cavalier Puge - Caul: FN Site 508"),
Data("Solid Puge - Caul: FN Site 507"),
Data("EN090503_NAME_F00_266", valid=False),
Data("Broadsword Pugilith - Caul: Ruined City of O'rrn Sim"),
Data("Remote Pugilith - Prim: Primordia Waters North"),
Data("Spear Pugilith - Obli: Milligan Supply Base"),
Data("Judge Pugilith - Caul: Ganglion Antropolis"),
Data("Magna Galdr - Sylv: Anvil Sandplan", regions=["Flight Module"]),
Data("Flood Galdr - Prim: Bedrock Hold"),
Data("Border King Quo - Sylv: Quay Hollows", depends=["Quay Hollows"]),
Data("Reject Oc-serv - Sylv: Quay Hollows", depends=["Quay Hollows"]),
Data("Rebel Oc-serv - Caul: Cauldros Gate"),
Data("Beryllium Oc-serv - Caul: Kw'arah Cloister"),
Data("Barbed Rook Qmoeva - Caul: Abandoned Bivouac"),
Data("Barbed Remote Qmoeva - Prim: Primordia Waters North"),
Data("Barbed Queen Qmoeva - Caul: FN Site 504"),
Data("EN090503_NAME_F00_267", valid=False),
Data("Striker Qmoeva - Sylv: FN Site 415"),
Data("Purger Queen Qmoeva - Caul: O'rrn Sim Castle Ruins", regions=["Skell License"]),  #TAJ to aggro
Data("Brave Rook Qmoeva - Caul: Dragonbone Promontory"),
Data("Brave Queen Qmoeva - Caul: Scholes Battlegrounds"),
Data("Brave King Qmoeva - Prim: Talon Rock Summit", depends=["Talon Rock Summit"]),
Data("True Queen Qmoeva - Caul: Sunset Falls"),
Data("Rebel Queen Qmoeva - Prim: Southern FN Site 101"),
Data("True King Qmoeva - Sylv: Anvil Rock One"),
Data("EN090503_NAME_F00_268", valid=False),
Data("Suppressor Hermit Qmoeva - Prim: FN Site 102"),
Data("Hazard Shrad - Sylv: Badr Stronghold"),
Data("Avaricious Shrad - Sylv: Anvil Rock One"),
Data("Luminous Puge - Sylv: FN Site 415"),
Data("Coffin Puge - Caul: Old Ceremonial Hollow"),
Data("Ataraxia Oc-serv - Prim: Talon Rock Summit", depends=["Talon Rock Summit"]),
Data("EN090503_NAME_F00_269", valid=False),
Data("Auto Gunner Zig - Caul: Adder Byroad"),
Data("EN090503_NAME_F00_270", valid=False),
Data("EN090503_NAME_F00_271", valid=False),
Data("Marnuck Aspirer - Caul: Boxtrap Checkpoint"),
Data("Marnuck Damager - Ovli: Scabland Fortress"),
Data("Marnuck Evildoer - Sylv: FN Site 416"),
Data("Marnuck Cutthroat - Obli: Big Arch"),
Data("Milsaadi Herald - Sylv: Anvil Sandplain"),
Data("Milsaadi Protobattler - Prim: FN Site 110"),
Data("Milsaadi Robber - Prim: FN Site 110"),
Data("Milsaadi Astran - Sylv: Quay Hollows", depends=["Quay Hollows"]),
Data("Prone Purger - Obli: Cliffside Camp"),
Data("Prone Judge - Noct: Lakeview Stronghold"),
Data("Prone Sorcerer - Cavernous Abyss", depends=["Cavernous Abyss"]),
Data("Breather Scirpo - Noct: Weeping Whitewood"),
Data("Pillager Scirpo - Noct: FN Site 205"),
Data("Carnelian Forfex - Sylv: Seabird's Beak"),
Data("Spinel Forfex - Sylv: Seabird's Beak"),
Data("Promethium Petramand - Prim: Stonelattice Cavern"),
Data("Rust Blatta - Caul: FN Site 505"),
Data("Alba Blatta - Obli: Oblivia Ingress"),
Data("Green Blatta - Sylv: Northern Searoad"),
Data("Squall Blatta - Noct: Divine Roost", depends=["Divine Roost"]),
Data("Striker Blatta - Obli: Oblivia Ingress"),
Data("Stalwart Blatta - Noct: Decapotamon"),
Data("Penetrator Adsecula - Sylv: Lake Ciel"),
Data("Giddy Adsecula - Noct: Coil Tree Cape"),
Data("Cursed Adsecula - Prim: Molten Hollow"),
Data("Dryland Papil - Cauldros: Abandoned Bivouac"),
Data("Raven Turba - Prim: Turtle Nest"),
Data("Gloam Turba - Sylv: Secluded Lava Lake"),
Data("Crazed Germivore - Caul: FN Site 516"),
Data("Mist Germivore - Caul: FN Site 509"),
Data("Gehenna Lophid - FN Site 506"),
Data("Striker Simius - Noct: Whale's Gullet"),
Data("Conjurer Cervus - Caul: Bestial Utopia"),
Data("Miniature Suid - Noct: Sapphire Table"),
Data("Miniature Femina Suid - Noct: Goblin's Narrow"),
Data("Volcannon Sacrifole - Caul: Emerian Battlegrounds"),
Data("Stream Jacul - Sylv: NW FN Site 404"),
Data("Aquatic Visigel - Sylv: Noctilucent Sphere Interior", depends=["Noctilucent Sphere Interior"]),
Data("Wild Mephite - Obli: Aaroy Plain"),
Data("Witless Saltat - Caul: Scholes Battlegrounds - Clear"),
Data("Caged Saltat - Caul: Capital Wreckage - Clear"),
Data("Crater Saltat - Caul: Capital Wreckage - Clear"),
Data("Buster Kaizer Qmoeva - Caul: Ganglion Antropolis"),
Data("Durvin, the Perceptive - Prim: Beast's Lair - Daytime"),
Data("Star Cinicula - Noct: Qing Long Glade"),
Data("Nocto Blatta - Prim: North Janpath Plain"),
Data("Wood Potamus - Noct: Whales Nostril BC"),
Data("Buoyant Lophid - Prim: Janpath Lake - Nighttime"),
Data("Young Unafulge - Sylv: Seabird's Beak"),
Data("Marnuck Windtrooper - Prim: Castaway Cavern - Nighttime"),
]
