from ..Locations import Loc as Data

# from helper folder
# flake8: noqa
fn_nodes_data: list[Data] = [
Data("FN Site 101", regions=["Mechanical 5"]),
Data("FN Site 102", regions=["Mechanical 1"]),
Data("FN Site 103", regions=["Mechanical 1"]),
Data("FN Site 104", regions=["Mechanical 3"]),
Data("FN Site 106", regions=["Mechanical 1"]),
Data("FN Site 108", regions=["Mechanical 1"]),
Data("FN Site 107", regions=["Mechanical 1"]),
Data("FN Site 109", regions=["Mechanical 2"], depends=["FN Site 109"]), # Skell with transform 
Data("FN Site 110", regions=["Mechanical 1"], depends=["Talon Rock Summit"]),  # TAJ with Skell
Data("FN Site 111", regions=["Mechanical 1"]),
Data("FN Site 112", regions=["Mechanical 1"]),
Data("FN Site 113", regions=["Mechanical 1"]),
Data("FN Site 114", regions=["Mechanical 1"]),
Data("FN Site 115", regions=["Mechanical 2"]),
Data("FN Site 116", regions=["Mechanical 1"]),
Data("FN Site 117", regions=["Mechanical 1"]),
Data("FN Site 118", regions=["Mechanical 1"]),
Data("FN Site 119", regions=["Mechanical 1"]),
Data("FN Site 120", regions=["Mechanical 3"]),
Data("FN Site 121", regions=["Mechanical 1"]),
Data("FN Site 105", regions=["Mechanical 1"]),
Data("FN Site 201", regions=["Mechanical 3"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Site 202", regions=["Mechanical 2"]),
Data("FN Site 203", regions=["Mechanical 2"]),
Data("FN Site 204", regions=["Mechanical 1"]),
Data("FN Site 205", regions=["Mechanical 1"]),
Data("FN Site 206", regions=["Mechanical 5"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Site 207", regions=["Mechanical 2"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Site 208", regions=["Mechanical 2"]),
Data("FN Site 209", regions=["Mechanical 1"]),
Data("FN Site 210", regions=["Mechanical 2"]),
Data("FN Site 211", regions=["Mechanical 2"]),
Data("FN Site 212", regions=["Mechanical 1"]),
Data("FN Site 213", regions=["Mechanical 4"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Site 214", regions=["Mechanical 2"]),
Data("FN Site 215", regions=["Mechanical 2"]),
Data("FN Site 216", regions=["Mechanical 3"]),
Data("FN Site 217", regions=["Mechanical 2"]),
Data("FN Site 218", regions=["Mechanical 1"]),
Data("FN Site 219", regions=["Mechanical 1"]),
Data("FN Site 220", regions=["Mechanical 2"]),
Data("FN Site 221", regions=["Mechanical 1"]),
Data("FN Site 222", regions=["Mechanical 1"]),
Data("FN Site 223", regions=["Mechanical 1"]),
Data("FN Site 224", regions=["Mechanical 4"]),
Data("FN Site 225", regions=["Mechanical 3"]),
Data("FN Site 206", valid=False),
Data("FN Site 207", valid=False),
Data("FN Site 301", regions=["Mechanical 1"]),
Data("FN Site 302", regions=["Mechanical 1"]),
Data("FN Site 303", regions=["Mechanical 1"]),
Data("FN Site 304", regions=["Mechanical 5"]),
Data("FN Site 305", regions=["Mechanical 1"]),
Data("FN Site 306", regions=["Mechanical 1"]),
Data("FN Site 307", regions=["Mechanical 3"]),
Data("FN Site 308", regions=["Mechanical 2"]),
Data("FN Site 309", regions=["Mechanical 2"]),
Data("FN Site 310", regions=["Mechanical 2"], depends=["FN Site 310"]),  # Needs advanced jumping
Data("FN Site 311", regions=["Mechanical 2"]),
Data("FN Site 312", regions=["Mechanical 2"]),
Data("FN Site 313", regions=["Mechanical 1"]),
Data("FN Site 314", regions=["Mechanical 3"]),
Data("FN Site 315", regions=["Mechanical 3"]),
Data("FN Site 316", regions=["Mechanical 2"]),
Data("FN Site 317", regions=["Mechanical 3"]),
Data("FN Site 318", regions=["Mechanical 2"]),
Data("FN Site 320", regions=["Mechanical 3"], depends=["Floating Reef"]),  # Technically doable with only Skell but very hard
Data("FN Site 321", regions=["Mechanical 2"]),
Data("FN Site 319", regions=["Mechanical 2"]),
Data("FN Site 322", regions=["Mechanical 4"]),
Data("FN Site 313", valid=False),
Data("FN Site 314", valid=False),
Data("FN Site 315", valid=False),
Data("FN Site 401", regions=["Mechanical 2"]),
Data("FN Site 402", regions=["Mechanical 3"]),
Data("FN Site 403", regions=["Mechanical 1"]),
Data("FN Site 404", regions=["Mechanical 5"]),
Data("FN Site 405", regions=["Mechanical 1"]),
Data("FN Site 406", regions=["Mechanical 3"]),
Data("FN Site 407", regions=["Mechanical 4"]),
Data("FN Site 408", regions=["Mechanical 1"]),
Data("FN Site 409", regions=["Mechanical 3"]),
Data("FN Site 410", regions=["Mechanical 4"]),
Data("FN Site 411", regions=["Mechanical 4"]),
Data("FN Site 412", regions=["Mechanical 3"]),
Data("FN Site 413", regions=["Mechanical 3"]),
Data("FN Site 414", regions=["Mechanical 2"]),
Data("FN Site 415", regions=["Mechanical 3"]),
Data("FN Site 416", regions=["Mechanical 3"]),
Data("FN Site 417", regions=["Mechanical 2"]),
Data("FN Site 418", regions=["Mechanical 2"]),
Data("FN Site 419", regions=["Mechanical 5"]),
Data("FN Site 420", regions=["Mechanical 2"]),
Data("FN Site 501", regions=["Mechanical 1"]),
Data("FN Site 502", regions=["Mechanical 1"]),
Data("FN Site 503", regions=["Mechanical 2"]),
Data("FN Site 504", regions=["Mechanical 2"]),
Data("FN Site 505", regions=["Mechanical 2"]),
Data("FN Site 506", regions=["Mechanical 3"]),
Data("FN Site 507", regions=["Mechanical 3"]),
Data("FN Site 508", regions=["Mechanical 2"]),
Data("FN Site 509", regions=["Mechanical 2"]),
Data("FN Site 510", regions=["Mechanical 3"]),
Data("FN Site 511", regions=["Mechanical 2"]),
Data("FN Site 512", regions=["Mechanical 4"]),
Data("FN Site 513", regions=["Mechanical 4"]),
Data("FN Site 514", regions=["Mechanical 3"]),
Data("FN Site 515", regions=["Mechanical 3"]),
Data("FN Site 516", regions=["Mechanical 1"]),
]
# get vein_ids https://xenoblade.github.io/xbx/bdat/common_local_us/SEG_ProbeList.html from game as NodeId
# https://xenoblade.github.io/xbx/bdat/common_local_us/FnetVeinList.html to match name in
# https://xenoblade.github.io/xbx/bdat/common_local_us/FLD_Location.html