from ..Locations import Loc as Data

# from helper folder
# flake8: noqa
fn_nodes_data: list[Data] = [
Data("FN Node 101", regions=["Mechanical 5"]),
Data("FN Node 102", regions=["Mechanical 1"]),
Data("FN Node 103", regions=["Mechanical 1"]),
Data("FN Node 104", regions=["Mechanical 3"]),
Data("FN Node 106", regions=["Mechanical 1"]),
Data("FN Node 108", regions=["Mechanical 1"]),
Data("FN Node 107", regions=["Mechanical 1"]),
Data("FN Node 109", regions=["Mechanical 2"], depends=["FN Site 109"]), # Skell with transform 
Data("FN Node 110", regions=["Mechanical 1"], depends=["Talon Rock Summit"]),  # TAJ with Skell
Data("FN Node 111", regions=["Mechanical 1"]),
Data("FN Node 112", regions=["Mechanical 1"]),
Data("FN Node 113", regions=["Mechanical 1"]),
Data("FN Node 114", regions=["Mechanical 1"]),
Data("FN Node 115", regions=["Mechanical 2"]),
Data("FN Node 116", regions=["Mechanical 1"]),
Data("FN Node 117", regions=["Mechanical 1"]),
Data("FN Node 118", regions=["Mechanical 1"]),
Data("FN Node 119", regions=["Mechanical 1"]),
Data("FN Node 120", regions=["Mechanical 3"]),
Data("FN Node 121", regions=["Mechanical 1"]),
Data("FN Node 105", regions=["Mechanical 1"]),
Data("FN Node 201", regions=["Mechanical 3"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 202", regions=["Mechanical 2"]),
Data("FN Node 203", regions=["Mechanical 2"]),
Data("FN Node 204", regions=["Mechanical 1"]),
Data("FN Node 205", regions=["Mechanical 1"]),
Data("FN Node 206", regions=["Mechanical 5"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 207", regions=["Mechanical 2"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 208", regions=["Mechanical 2"]),
Data("FN Node 209", regions=["Mechanical 1"]),
Data("FN Node 210", regions=["Mechanical 2"]),
Data("FN Node 211", regions=["Mechanical 2"]),
Data("FN Node 212", regions=["Mechanical 1"]),
Data("FN Node 213", regions=["Mechanical 4"], depends=["Divine Roost"]),  # TAJ with Skell
Data("FN Node 214", regions=["Mechanical 2"]),
Data("FN Node 215", regions=["Mechanical 2"]),
Data("FN Node 216", regions=["Mechanical 3"]),
Data("FN Node 217", regions=["Mechanical 2"]),
Data("FN Node 218", regions=["Mechanical 1"]),
Data("FN Node 219", regions=["Mechanical 1"]),
Data("FN Node 220", regions=["Mechanical 2"]),
Data("FN Node 221", regions=["Mechanical 1"]),
Data("FN Node 222", regions=["Mechanical 1"]),
Data("FN Node 223", regions=["Mechanical 1"]),
Data("FN Node 224", regions=["Mechanical 4"]),
Data("FN Node 225", regions=["Mechanical 3"]),
Data("FN Node 206", valid=False),
Data("FN Node 207", valid=False),
Data("FN Node 301", regions=["Mechanical 1"]),
Data("FN Node 302", regions=["Mechanical 1"]),
Data("FN Node 303", regions=["Mechanical 1"]),
Data("FN Node 304", regions=["Mechanical 5"]),
Data("FN Node 305", regions=["Mechanical 1"]),
Data("FN Node 306", regions=["Mechanical 1"]),
Data("FN Node 307", regions=["Mechanical 3"]),
Data("FN Node 308", regions=["Mechanical 2"]),
Data("FN Node 309", regions=["Mechanical 2"]),
Data("FN Node 310", regions=["Mechanical 2"], depends=["FN Site 310"]),  # Needs advanced jumping
Data("FN Node 311", regions=["Mechanical 2"]),
Data("FN Node 312", regions=["Mechanical 2"]),
Data("FN Node 313", regions=["Mechanical 1"]),
Data("FN Node 314", regions=["Mechanical 3"]),
Data("FN Node 315", regions=["Mechanical 3"]),
Data("FN Node 316", regions=["Mechanical 2"]),
Data("FN Node 317", regions=["Mechanical 3"]),
Data("FN Node 318", regions=["Mechanical 2"]),
Data("FN Node 320", regions=["Mechanical 3"], depends=["Floating Reef"]),  # Technically doable with only Skell but very hard
Data("FN Node 321", regions=["Mechanical 2"]),
Data("FN Node 319", regions=["Mechanical 2"]),
Data("FN Node 322", regions=["Mechanical 4"]),
Data("FN Node 313", valid=False),
Data("FN Node 314", valid=False),
Data("FN Node 315", valid=False),
Data("FN Node 401", regions=["Mechanical 2"]),
Data("FN Node 402", regions=["Mechanical 3"]),
Data("FN Node 403", regions=["Mechanical 1"]),
Data("FN Node 404", regions=["Mechanical 5"]),
Data("FN Node 405", regions=["Mechanical 1"]),
Data("FN Node 406", regions=["Mechanical 3"]),
Data("FN Node 407", regions=["Mechanical 4"]),
Data("FN Node 408", regions=["Mechanical 1"]),
Data("FN Node 409", regions=["Mechanical 3"]),
Data("FN Node 410", regions=["Mechanical 4"]),
Data("FN Node 411", regions=["Mechanical 4"]),
Data("FN Node 412", regions=["Mechanical 3"]),
Data("FN Node 413", regions=["Mechanical 3"]),
Data("FN Node 414", regions=["Mechanical 2"]),
Data("FN Node 415", regions=["Mechanical 3"]),
Data("FN Node 416", regions=["Mechanical 3"]),
Data("FN Node 417", regions=["Mechanical 2"]),
Data("FN Node 418", regions=["Mechanical 2"]),
Data("FN Node 419", regions=["Mechanical 5"]),
Data("FN Node 420", regions=["Mechanical 2"]),
Data("FN Node 501", regions=["Mechanical 1"]),
Data("FN Node 502", regions=["Mechanical 1"]),
Data("FN Node 503", regions=["Mechanical 2"]),
Data("FN Node 504", regions=["Mechanical 2"]),
Data("FN Node 505", regions=["Mechanical 2"]),
Data("FN Node 506", regions=["Mechanical 3"]),
Data("FN Node 507", regions=["Mechanical 3"]),
Data("FN Node 508", regions=["Mechanical 2"]),
Data("FN Node 509", regions=["Mechanical 2"]),
Data("FN Node 510", regions=["Mechanical 3"]),
Data("FN Node 511", regions=["Mechanical 2"]),
Data("FN Node 512", regions=["Mechanical 4"]),
Data("FN Node 513", regions=["Mechanical 4"]),
Data("FN Node 514", regions=["Mechanical 3"]),
Data("FN Node 515", regions=["Mechanical 3"]),
Data("FN Node 516", regions=["Mechanical 1"]),
]
# get vein_ids https://xenoblade.github.io/xbx/bdat/common_local_us/SEG_ProbeList.html from game as NodeId
# https://xenoblade.github.io/xbx/bdat/common_local_us/FnetVeinList.html to match name in
# https://xenoblade.github.io/xbx/bdat/common_local_us/FLD_Location.html