from . import Loc as Data

# flake8: noqa
# https://xenoblade.github.io/xbx/bdat/common_local_us/ITM_Blueprint.html
shop_blueprints_data: list[Data] = [
Data("Archetype Sword", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Slair II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Sword II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Blades", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Ralzes", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Blades II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Knife III", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Riv", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Knife II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Paive", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Shield", rules=["Blade License"], depends=["Chapter 1"]),
Data("Advanced Archetype Paive", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Spear", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Parce", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Spear II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Fulge", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Saber", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Fulge II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Assault Rifle III", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Avagar", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Assault Rifle II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Dual Guns", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Gemels", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Dual Guns II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Lastyr II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Raygun", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Lastyr III", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Machine", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Repethe", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Machine II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Sniper Rifle", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Retic", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Sniper Rifle II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Psylans", rules=["Blade License"], depends=["Chapter 1"]),
Data("Archetype Launchers", rules=["Blade License"], depends=["Chapter 1"]),
Data("Advanced Archetype Psylans", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Glaive", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Glaive II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Twins", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Watxes", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Edges II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Edges", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Pokepoke", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Iyst", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Iyst II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Haven", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Haven II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Thudclang", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Bolide", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Jyth", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Lance", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Lightblade", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Lightblade II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Assailer", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Raidrifle", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Dyads", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Dyads III", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Dyads II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Bangbangs", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Sidearm", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Strobe", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Crank", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Ratatatta", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Ziyse", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Trigger", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Thwipper", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Deadsight", rules=["Blade License"], depends=["Chapter 1"]),
Data("Masterstroke Deadsight II", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Saboteurs", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Fwooshers", rules=["Blade License"], depends=["Chapter 1"]),
Data("Original Zorcyses", rules=["Blade License"], depends=["Chapter 1"]),
Data("3276", valid=False),
Data("3277", valid=False),
Data("3278", valid=False),
Data("3279", valid=False),
Data("3280", valid=False),
Data("3281", valid=False),
Data("Six Stars Ritual Bodywear", rules=["Blade License"], depends=["Chapter 1"]),
Data("Six Stars Ritual Band R", rules=["Blade License"], depends=["Chapter 1"]),
Data("Six Stars Ritual Band L", rules=["Blade License"], depends=["Chapter 1"]),
Data("Six Stars Ritual Legwear", rules=["Blade License"], depends=["Chapter 1"]),
Data("Supercivilization Attire", rules=["Blade License"], depends=["Chapter 1"]),
Data("Elite Supercivilization Attire", rules=["Blade License"], depends=["Chapter 1"]),
Data("Black Bunnyband", rules=["Blade License"], depends=["Chapter 1"]),
Data("Red Bunnyband", rules=["Blade License"], depends=["Chapter 1"]),
Data("White Bunnyband", rules=["Blade License"], depends=["Chapter 1"]),
Data("Bunnytop", rules=["Blade License"], depends=["Chapter 1"]),
Data("Bunnycuff R", rules=["Blade License"], depends=["Chapter 1"]),
Data("Bunnycuff L", rules=["Blade License"], depends=["Chapter 1"]),
Data("Bunnyhoppers", rules=["Blade License"], depends=["Chapter 1"]),
Data("Bunnybod", rules=["Blade License"], depends=["Chapter 1"]),
Data("Bunnylink R", rules=["Blade License"], depends=["Chapter 1"]),
Data("Bunnylink L", rules=["Blade License"], depends=["Chapter 1"]),
Data("Reginal Comm", rules=["Blade License"], depends=["Chapter 1"]),
Data("Reginal Plastron", rules=["Blade License"], depends=["Chapter 1"]),
Data("Reginal Bangle R", rules=["Blade License"], depends=["Chapter 1"]),
Data("Reginal Bangle L", rules=["Blade License"], depends=["Chapter 1"]),
Data("Reginal Cords", rules=["Blade License"], depends=["Chapter 1"]),
Data("Regal Comm", rules=["Blade License"], depends=["Chapter 1"]),
Data("Regal Plastron", rules=["Blade License"], depends=["Chapter 1"]),
Data("Regal Bangle R", rules=["Blade License"], depends=["Chapter 1"]),
Data("Regal Bangle L", rules=["Blade License"], depends=["Chapter 1"]),
Data("Regal Cords", rules=["Blade License"], depends=["Chapter 1"]),
Data("Infinite Comm", rules=["Blade License"], depends=["Chapter 1"]),
Data("Infinite Plastron", rules=["Blade License"], depends=["Chapter 1"]),
Data("Infinite Bangle R", rules=["Blade License"], depends=["Chapter 1"]),
Data("Infinite Bangle L", rules=["Blade License"], depends=["Chapter 1"]),
Data("Infinite Cords", rules=["Blade License"], depends=["Chapter 1"]),
Data("True Comm", rules=["Blade License"], depends=["Chapter 1"]),
Data("True Plastron", rules=["Blade License"], depends=["Chapter 1"]),
Data("True Bangle R", rules=["Blade License"], depends=["Chapter 1"]),
Data("True Bangle L", rules=["Blade License"], depends=["Chapter 1"]),
Data("True Cords", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP140SA Hexad-Partican", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP160SA Hexad-Partican", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP180SA Hexad-Partican", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP240SA Zenith-Cannon", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP260SA Zenith-Cannon", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP280SA Zenith-Cannon", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP340GG Zweihand-Q", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP360GG Zweihand-Q", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP380GG Zweihand-Q", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP440ME Trident-Anchor", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP460ME Trident-Anchor", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP480ME Trident-Anchor", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP540GG Electric-Flood", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP560GG Electric-Flood", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP580GG Electric-Flood", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP640ME Voltaic-Tusk", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP660ME Voltaic-Tusk", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP680ME Voltaic-Tusk", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP740SA Antimatter-R", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP760SA Antimatter-R", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP780SA Antimatter-R", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP840SA G-Piledriver", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP860SA G-Piledriver", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP880SA G-Piledriver", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP940GG Dragoon-Lance", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP960GG Dragoon-Lance", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP980GG Dragoon-Lance", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP1040GG Drone-Storm", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP1060GG Drone-Storm", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP1080GG Drone-Storm", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1140SA Deus-Crusher", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1160SA Deus-Crusher", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1180SA Deus-Crusher", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1240ME Barrage-Cloak", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1260ME Barrage-Cloak", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1280ME Barrage-Cloak", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP1340SA Detonation-F", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP1360SA Detonation-F", rules=["Blade License"], depends=["Chapter 1"]),
Data("SRM-USP1380SA Detonation-F", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1440SA Megaflame-B", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1460SA Megaflame-B", rules=["Blade License"], depends=["Chapter 1"]),
Data("SSM-USP1480SA Megaflame-B", rules=["Blade License"], depends=["Chapter 1"]),
Data("91", valid=False),
Data("Formula Zero", rules=["Skell License"], depends=["Chapter 1"]),
Data("118", valid=False),
Data("Urban Lincoln", rules=["Skell License"], depends=["Chapter 1"]),
Data("152", valid=False),
Data("Verus Cain", rules=["Skell License"], depends=["Chapter 1"]),
Data("186", valid=False),
Data("Lailah Queen", rules=["Skell License"], depends=["Chapter 1"]),
Data("220", valid=False),
Data("Inferno Skydon", rules=["Skell License"], depends=["Chapter 1"]),
Data("251", valid=False),
Data("Mastema Reaper", rules=["Skell License"], depends=["Chapter 1"]),
Data("282", valid=False),
Data("Amdusias Hades", rules=["Skell License"], depends=["Chapter 1"]),
Data("284", valid=False),
Data("Ares 70", rules=["Skell License"], depends=["Chapter 1"]),
Data("Ares 90", rules=["Skell License"], depends=["Chapter 1"]),
Data("Police", rules=["Skell License"], depends=["Chapter 1"]),
Data("Dozer", rules=["Skell License"], depends=["Chapter 1"]),
Data("Excavator", rules=["Skell License"], depends=["Chapter 1"]),
Data("Delta Bliss", rules=["Skell License"], depends=["Chapter 1"])
]
