from . import Loc as Data

# flake8: noqa
# https://xenoblade.github.io/xbx/bdat/common_local_us/SHP_WpnDL.html
shop_doll_weapons_data: list[Data] = [
Data("SHM-M120SA Rod_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R120SA M-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R120SA Railgun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M130SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M120SA Beamsaber_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M130SA Rod_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R130SA M-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130SA Railgun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M150SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130SA Beamsaber_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M150SA Rod_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150SA M-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150SA Railgun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M130SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150SA Beamsaber_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M120SA Rod_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R120SA M-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R120SA Railgun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M150SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M120SA Beamsaber_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M130SA Rod_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R130SA M-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130SA Railgun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M130SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130SA Beamsaber_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M150SA Rod_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150SA M-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150SA Railgun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M150SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150SA Beamsaber_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M120SA Rod_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R120SA M-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R120SA Railgun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M131SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M120SA Beamsaber_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M130SA Rod_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R130SA M-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130SA Railgun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M151SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130SA Beamsaber_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M150SA Rod_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150SA M-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150SA Railgun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M131SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150SA Beamsaber_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M220SA Sword_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250SA HB-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R220SA S-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M151SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M220SA V-knuckle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M230SA Sword_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250SA HB-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R230SA S-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M131SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M230SA V-knuckle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M250SA Sword_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250SA HB-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250SA S-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M151SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M250SA V-knuckle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M220SA Sword_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R220SA F-Grenade_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R220SA S-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M152SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M220SA V-knuckle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M230SA Sword_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R230SA F-Grenade_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R230SA S-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M152SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M230SA V-knuckle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M250SA Sword_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250SA F-Grenade_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250SA S-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M152SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M250SA V-knuckle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M220SA Sword_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R220SA F-Grenade_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R220SA S-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M123SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M220SA V-knuckle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M230SA Sword_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R230SA F-Grenade_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R230SA S-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M133SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M230SA V-knuckle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M250SA Sword_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250SA F-Grenade_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250SA S-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M153SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M250SA V-knuckle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M350SA E-Sword_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R220SA F-Grenade_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R350SA Voltnet_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M123SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130GG Ringedge_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M350SA E-Sword_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R230SA F-Grenade_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R350SA Voltnet_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M133SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150GG Ringedge_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M430SA Pile-Bunker_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250SA F-Grenade_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R350SA Voltnet_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M153SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130GG Ringedge_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M450SA Pile-Bunker_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R330SA SHD-Gatling_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R430SA Grenade_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M123SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150GG Ringedge_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M430SA Pile-Bunker_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350SA SHD-Gatling_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R450SA Grenade_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M133SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130GG Ringedge_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M450SA Pile-Bunker_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R330SA SHD-Gatling_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R430SA Grenade_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M153SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150GG Ringedge_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M430SA Pile-Bunker_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350SA SHD-Gatling_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R450SA Grenade_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M124SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130ME Falchion_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-M450SA Pile-Bunker_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R330SA SHD-Gatling_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R430SA Grenade_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M134SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150ME Falchion_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R130SA Machine Gun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350SA SHD-Gatling_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R450SA Grenade_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M154SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130ME Falchion_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R150SA Machine Gun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R450SA SHD-Ray_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M120SA Buster_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M124SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150ME Falchion_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R130SA Machine Gun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R450SA SHD-Ray_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M130SA Buster_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M134SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M130ME Falchion_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R150SA Machine Gun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R450SA SHD-Ray_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150SA Buster_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M154SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M150ME Falchion_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R130SA Machine Gun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R530SA Chaingun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M120SA Buster_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M124SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M250ME Claymore_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R150SA Machine Gun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R550SA Chaingun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M130SA Buster_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M134SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M250ME Claymore_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R250SA E-Machine Gun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R530SA Chaingun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150SA Buster_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M154SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M250ME Claymore_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R250SA E-Machine Gun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R550SA Chaingun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M120SA Buster_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M125SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M350ME Katar_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R320SA Assault_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R530SA Chaingun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M130SA Buster_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M135SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M350ME Katar_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R330SA Assault_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R550SA Chaingun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150SA Buster_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M155SA Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-M350ME Katar_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R350SA Assault_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX130SA G-Buster_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R550SA Hyper-Rail_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M125SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R320SA Cracker-BM_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R320SA Assault_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX150SA G-Buster_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R550SA Hyper-Rail_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M135SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R330SA Cracker-BM_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R330SA Assault_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX130SA G-Buster_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R550SA Hyper-Rail_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M155SA Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350SA Cracker-BM_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R350SA Assault_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX150SA G-Buster_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R650SA Buster-Launcher_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M125SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R320SA Cracker-BM_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R320SA Assault_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX130SA G-Buster_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R650SA Buster-Launcher_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M135SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R330SA Cracker-BM_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R330SA Assault_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX150SA G-Buster_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R650SA Buster-Launcher_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M155SA Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350SA Cracker-BM_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R350SA Assault_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX150SA G2-Buster_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R730SA L-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R130SA Minigun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R320SA Cracker-BM_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R450SA B-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX150SA G2-Buster_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R750SA L-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R150SA Minigun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R330SA Cracker-BM_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R450SA B-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX150SA G2-Buster_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R730SA L-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R130SA Minigun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350SA Cracker-BM_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R450SA B-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX250SA E-Scythe_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R750SA L-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R150SA Minigun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R330GG Cracker-FL_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R550SA E-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX250SA E-Scythe_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R730SA L-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R130SA Minigun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350GG Cracker-FL_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R550SA E-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-MX250SA E-Scythe_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R750SA L-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R150SA Minigun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R330GG Cracker-FL_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R620SA Shotgun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX350SA F-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R730SA F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M110ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350GG Cracker-FL_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R630SA Shotgun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX350SA F-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R750SA F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M120ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R330GG Cracker-FL_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R650SA Shotgun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX350SA F-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R730SA F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M140ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350GG Cracker-FL_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R620SA Shotgun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX330SA F2-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R750SA F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M110ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350ME Cracker-PD_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R630SA Shotgun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX350SA F2-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R730SA F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M120ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350ME Cracker-PD_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R650SA Shotgun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX330SA F2-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R750SA F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M140ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SKM-R350ME Cracker-PD_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SHM-R620SA Shotgun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX350SA F2-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130GG P-Cannon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M110ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R630SA Shotgun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX330SA F2-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150GG P-Cannon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M120ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R650SA Shotgun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX350SA F2-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130GG P-Cannon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M140ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R730SA Sniper_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX430SA B-Gatling_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150GG P-Cannon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M111ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Sniper_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX450SA B-Gatling_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130GG P-Cannon_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M121ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R730SA Sniper_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX430SA B-Gatling_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150GG P-Cannon_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M141ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Sniper_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX450SA B-Gatling_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R220GG Lasergun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M111ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R730SA Sniper_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX430SA B-Gatling_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R230GG Lasergun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M121ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Sniper_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX450SA B-Gatling_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250GG Lasergun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M141ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Firegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX450SA B2-Gatling_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R220GG Lasergun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M111ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Firegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX450SA B2-Gatling_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R230GG Lasergun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M121ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Firegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX450SA B2-Gatling_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250GG Lasergun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M141ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R820SA L-Cannon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX550SA M-Sniper_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R220GG Lasergun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M142ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R830SA L-Cannon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX550SA M-Sniper_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R230GG Lasergun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M142ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R850SA L-Cannon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-RX550SA M-Sniper_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250GG Lasergun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M142ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R820SA L-Cannon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R130GG M-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R330GG H-Arrow_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M123ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R830SA L-Cannon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150GG M-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R350GG H-Arrow_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M143ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R850SA L-Cannon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R130GG M-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R330GG H-Arrow_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M123ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R820SA L-Cannon_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150GG M-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R350GG H-Arrow_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M143ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R830SA L-Cannon_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R130GG M-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R330GG H-Arrow_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M123ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R850SA L-Cannon_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150GG M-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R350GG H-Arrow_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M143ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R950SA E-Cannon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R230GG Voltstorm_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M120GG Javelin_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M124ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R950SA E-Cannon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250GG Voltstorm_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M130GG Javelin_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M144ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1020SA Wiregun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R230GG Voltstorm_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150GG Javelin_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M124ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1030SA Wiregun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250GG Voltstorm_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M120GG Javelin_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M144ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1050SA Wiregun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R230GG Voltstorm_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M130GG Javelin_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M124ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1020SA Wiregun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250GG Voltstorm_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150GG Javelin_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M144ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1030SA Wiregun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350GG SHD-Gravity_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M120GG Javelin_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M145ME Beam-Shield_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1050SA Wiregun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350GG SHD-Gravity_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M130GG Javelin_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M145ME Beam-Shield_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1020SA Wiregun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350GG SHD-Gravity_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150GG Javelin_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-M145ME Beam-Shield_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1030SA Wiregun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R420GG Antipulser_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R430GG Phoenix_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R130ME Needlegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1050SA Wiregun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R430GG Antipulser_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R450GG Phoenix_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R150ME Needlegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M130GG P-Knife_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R450GG Antipulser_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R430GG Phoenix_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R130ME Needlegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M150GG P-Knife_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R420GG Antipulser_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R450GG Phoenix_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R150ME Needlegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M130GG P-Knife_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R430GG Antipulser_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R430GG Phoenix_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R130ME Needlegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M150GG P-Knife_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R450GG Antipulser_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R450GG Phoenix_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SAM-R150ME Needlegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M130GG P-Knife_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R420GG Antipulser_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R530GG F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150GG P-Knife_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R430GG Antipulser_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R550GG F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M250GG B-Claw_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R450GG Antipulser_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R530GG F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M250GG B-Claw_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R451GG Antipulser_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R550GG F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M250GG B-Claw_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R451GG Antipulser_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R530GG F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130GG HB-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R451GG Antipulser_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R550GG F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150GG HB-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R530GG Drone_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R531GG F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130GG HB-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R550GG Drone_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R551GG F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150GG HB-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R530GG Drone_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R531GG F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130GG HB-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R550GG Drone_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R551GG F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150GG HB-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R530GG Drone_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R531GG F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250GG Diskbomb_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R550GG Drone_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R551GG F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250GG Diskbomb_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150ME M-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130ME B-Gatling_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250GG Diskbomb_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150ME M-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150ME B-Gatling_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M130ME Heat-Edge_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150ME M-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130ME B-Gatling_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME Heat-Edge_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250ME Widebeam_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150ME B-Gatling_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M130ME Heat-Edge_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250ME Widebeam_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R130ME B-Gatling_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME Heat-Edge_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R250ME Widebeam_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R150ME B-Gatling_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M130ME Heat-Edge_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R330ME SHD-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250ME S-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME Heat-Edge_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350ME SHD-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250ME S-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME B-Centipede_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R330ME SHD-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-R250ME S-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME B-Centipede_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350ME SHD-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150ME Dragon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME B-Centipede_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R330ME SHD-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150ME Dragon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130ME Bladegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R350ME SHD-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M150ME Dragon_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150ME Bladegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M120ME Heathorn_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M230ME W-Crusher_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130ME Bladegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M130ME Heathorn_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M250ME W-Crusher_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150ME Bladegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M150ME Heathorn_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M230ME W-Crusher_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130ME Bladegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M120ME Heathorn_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M250ME W-Crusher_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150ME Bladegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M130ME Heathorn_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M230ME W-Crusher_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R230ME B-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M150ME Heathorn_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M250ME W-Crusher_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250ME B-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M120ME Heathorn_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M330ME BB-Sword_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R230ME B-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M130ME Heathorn_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M350ME BB-Sword_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250ME B-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-M150ME Heathorn_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M330ME BB-Sword_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R230ME B-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150ME N-Cannon_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M350ME BB-Sword_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250ME B-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150ME N-Cannon_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M330ME BB-Sword_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R350ME B-Sniper_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SSM-R150ME N-Cannon_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("SRM-M350ME BB-Sword_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R350ME B-Sniper_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R550ME Meteor_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R350ME B-Sniper_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R550ME Meteor_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R420ME Firegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R550ME Meteor_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R430ME Firegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R650ME L-Missile_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R450ME Firegun_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R650ME L-Missile_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R420ME Firegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R650ME L-Missile_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R430ME Firegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R720ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R450ME Firegun_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R730ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R420ME Firegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R750ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R430ME Firegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R720ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R450ME Firegun_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R730ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R421SA Short-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R750ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R431SA Short-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R720ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R451SA Short-Rifle_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R730ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R421SA Short-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R750ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R431SA Short-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R721ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R451SA Short-Rifle_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R731ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R421SA Short-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R751ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R431SA Short-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R721ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R451SA Short-Rifle_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R731ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R752SA E-Sniper_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R751ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R752SA E-Sniper_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R721ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R731ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R751ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R752ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R752ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R752ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R733ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R753ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R733ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R753ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R733ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R753ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R734ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R754ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R734ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R754ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R734ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R754ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R755ME F-Wave_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R755ME F-Wave_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R755ME F-Wave_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R430ME Backbomb_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R450ME Backbomb_1", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R430ME Backbomb_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R450ME Backbomb_2", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R430ME Backbomb_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R450ME Backbomb_3", rules=["Blade License", "Skell Frame"], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
]
