from . import Loc as Data

# flake8: noqa
# https://xenoblade.github.io/xbx/bdat/common_local_us/SHP_AmrPC.html
shop_armor_data: list[Data] = [
Data("Survival Headset", rules=[""], depends=["Chapter 1"]),
Data("Survival Shirt", rules=[""], depends=["Chapter 1"]),
Data("Survival Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Survival Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Survival Pants", rules=[""], depends=["Chapter 1"]),
Data("Combat Headset", rules=[""], depends=["Chapter 1"]),
Data("Combat Shirt", rules=[""], depends=["Chapter 1"]),
Data("Combat Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Combat Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Combat Pants", rules=[""], depends=["Chapter 1"]),
Data("Vivid Headset", rules=[""], depends=["Chapter 1"]),
Data("Vivid Shirt", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Pants", rules=[""], depends=["Chapter 1"]),
Data("Valor Headset", rules=[""], depends=["Chapter 1"]),
Data("Valor Shirt", rules=[""], depends=["Chapter 1"]),
Data("Valor Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Valor Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Valor Pants", rules=[""], depends=["Chapter 1"]),
Data("Forza Headset", rules=[""], depends=["Chapter 1"]),
Data("Forza Shirt", rules=[""], depends=["Chapter 1"]),
Data("Forza Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Forza Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Forza Pants", rules=[""], depends=["Chapter 1"]),
Data("Reginal Headset", rules=[""], depends=["Chapter 1"]),
Data("Reginal Shirt", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Pants", rules=[""], depends=["Chapter 1"]),
Data("Survival Visor", rules=[""], depends=["Chapter 1"]),
Data("Survival Vest", rules=[""], depends=["Chapter 1"]),
Data("Survival Guard R", rules=[""], depends=["Chapter 1"]),
Data("Survival Guard L", rules=[""], depends=["Chapter 1"]),
Data("Survival Boots", rules=[""], depends=["Chapter 1"]),
Data("Combat Visor", rules=[""], depends=["Chapter 1"]),
Data("Combat Vest", rules=[""], depends=["Chapter 1"]),
Data("Combat Guard R", rules=[""], depends=["Chapter 1"]),
Data("Combat Guard L", rules=[""], depends=["Chapter 1"]),
Data("Combat Boots", rules=[""], depends=["Chapter 1"]),
Data("Vivid Visor", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vest", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guard R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guard L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Boots", rules=[""], depends=["Chapter 1"]),
Data("Valor Visor", rules=[""], depends=["Chapter 1"]),
Data("Valor Vest", rules=[""], depends=["Chapter 1"]),
Data("Valor Guard R", rules=[""], depends=["Chapter 1"]),
Data("Valor Guard L", rules=[""], depends=["Chapter 1"]),
Data("Valor Boots", rules=[""], depends=["Chapter 1"]),
Data("Forza Visor", rules=[""], depends=["Chapter 1"]),
Data("Forza Vest", rules=[""], depends=["Chapter 1"]),
Data("Forza Guard R", rules=[""], depends=["Chapter 1"]),
Data("Forza Guard L", rules=[""], depends=["Chapter 1"]),
Data("Forza Boots", rules=[""], depends=["Chapter 1"]),
Data("Reginal Visor", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vest", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guard R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guard L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Boots", rules=[""], depends=["Chapter 1"]),
Data("Survival Goggles", rules=[""], depends=["Chapter 1"]),
Data("Survival Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Survival Glove R", rules=[""], depends=["Chapter 1"]),
Data("Survival Glove L", rules=[""], depends=["Chapter 1"]),
Data("Survival Footwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Goggles", rules=[""], depends=["Chapter 1"]),
Data("Combat Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Combat Glove R", rules=[""], depends=["Chapter 1"]),
Data("Combat Glove L", rules=[""], depends=["Chapter 1"]),
Data("Combat Footwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Goggles", rules=[""], depends=["Chapter 1"]),
Data("Vivid Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Glove R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Glove L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Footwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Goggles", rules=[""], depends=["Chapter 1"]),
Data("Valor Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Valor Glove R", rules=[""], depends=["Chapter 1"]),
Data("Valor Glove L", rules=[""], depends=["Chapter 1"]),
Data("Valor Footwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Goggles", rules=[""], depends=["Chapter 1"]),
Data("Forza Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Forza Glove R", rules=[""], depends=["Chapter 1"]),
Data("Forza Glove L", rules=[""], depends=["Chapter 1"]),
Data("Forza Footwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Goggles", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Glove R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Glove L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Footwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Headwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Armor", rules=[""], depends=["Chapter 1"]),
Data("Combat Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Combat Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Combat Legwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Headwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armor", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Legwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Headwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Armor", rules=[""], depends=["Chapter 1"]),
Data("Valor Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Valor Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Valor Legwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Headwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Armor", rules=[""], depends=["Chapter 1"]),
Data("Forza Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Forza Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Forza Legwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Headwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armor", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Legwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Helmet", rules=[""], depends=["Chapter 1"]),
Data("Combat Suit", rules=[""], depends=["Chapter 1"]),
Data("Combat Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Combat Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Combat Leggings", rules=[""], depends=["Chapter 1"]),
Data("Vivid Helmet", rules=[""], depends=["Chapter 1"]),
Data("Vivid Suit", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Leggings", rules=[""], depends=["Chapter 1"]),
Data("Valor Helmet", rules=[""], depends=["Chapter 1"]),
Data("Valor Suit", rules=[""], depends=["Chapter 1"]),
Data("Valor Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Valor Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Valor Leggings", rules=[""], depends=["Chapter 1"]),
Data("Forza Helmet", rules=[""], depends=["Chapter 1"]),
Data("Forza Suit", rules=[""], depends=["Chapter 1"]),
Data("Forza Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Forza Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Forza Leggings", rules=[""], depends=["Chapter 1"]),
Data("Reginal Helmet", rules=[""], depends=["Chapter 1"]),
Data("Reginal Suit", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Leggings", rules=[""], depends=["Chapter 1"]),
Data("Survival Headset", rules=[""], depends=["Chapter 1"]),
Data("Survival Shirt", rules=[""], depends=["Chapter 1"]),
Data("Survival Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Survival Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Survival Pants", rules=[""], depends=["Chapter 1"]),
Data("Combat Headset", rules=[""], depends=["Chapter 1"]),
Data("Combat Shirt", rules=[""], depends=["Chapter 1"]),
Data("Combat Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Combat Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Combat Pants", rules=[""], depends=["Chapter 1"]),
Data("Vivid Headset", rules=[""], depends=["Chapter 1"]),
Data("Vivid Shirt", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Pants", rules=[""], depends=["Chapter 1"]),
Data("Valor Headset", rules=[""], depends=["Chapter 1"]),
Data("Valor Shirt", rules=[""], depends=["Chapter 1"]),
Data("Valor Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Valor Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Valor Pants", rules=[""], depends=["Chapter 1"]),
Data("Forza Headset", rules=[""], depends=["Chapter 1"]),
Data("Forza Shirt", rules=[""], depends=["Chapter 1"]),
Data("Forza Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Forza Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Forza Pants", rules=[""], depends=["Chapter 1"]),
Data("Reginal Headset", rules=[""], depends=["Chapter 1"]),
Data("Reginal Shirt", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Pants", rules=[""], depends=["Chapter 1"]),
Data("Survival Visor", rules=[""], depends=["Chapter 1"]),
Data("Survival Vest", rules=[""], depends=["Chapter 1"]),
Data("Survival Guard R", rules=[""], depends=["Chapter 1"]),
Data("Survival Guard L", rules=[""], depends=["Chapter 1"]),
Data("Survival Boots", rules=[""], depends=["Chapter 1"]),
Data("Combat Visor", rules=[""], depends=["Chapter 1"]),
Data("Combat Vest", rules=[""], depends=["Chapter 1"]),
Data("Combat Guard R", rules=[""], depends=["Chapter 1"]),
Data("Combat Guard L", rules=[""], depends=["Chapter 1"]),
Data("Combat Boots", rules=[""], depends=["Chapter 1"]),
Data("Vivid Visor", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vest", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guard R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guard L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Boots", rules=[""], depends=["Chapter 1"]),
Data("Valor Visor", rules=[""], depends=["Chapter 1"]),
Data("Valor Vest", rules=[""], depends=["Chapter 1"]),
Data("Valor Guard R", rules=[""], depends=["Chapter 1"]),
Data("Valor Guard L", rules=[""], depends=["Chapter 1"]),
Data("Valor Boots", rules=[""], depends=["Chapter 1"]),
Data("Forza Visor", rules=[""], depends=["Chapter 1"]),
Data("Forza Vest", rules=[""], depends=["Chapter 1"]),
Data("Forza Guard R", rules=[""], depends=["Chapter 1"]),
Data("Forza Guard L", rules=[""], depends=["Chapter 1"]),
Data("Forza Boots", rules=[""], depends=["Chapter 1"]),
Data("Reginal Visor", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vest", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guard R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guard L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Boots", rules=[""], depends=["Chapter 1"]),
Data("Survival Goggles", rules=[""], depends=["Chapter 1"]),
Data("Survival Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Survival Glove R", rules=[""], depends=["Chapter 1"]),
Data("Survival Glove L", rules=[""], depends=["Chapter 1"]),
Data("Survival Footwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Goggles", rules=[""], depends=["Chapter 1"]),
Data("Combat Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Combat Glove R", rules=[""], depends=["Chapter 1"]),
Data("Combat Glove L", rules=[""], depends=["Chapter 1"]),
Data("Combat Footwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Goggles", rules=[""], depends=["Chapter 1"]),
Data("Vivid Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Glove R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Glove L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Footwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Goggles", rules=[""], depends=["Chapter 1"]),
Data("Valor Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Valor Glove R", rules=[""], depends=["Chapter 1"]),
Data("Valor Glove L", rules=[""], depends=["Chapter 1"]),
Data("Valor Footwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Goggles", rules=[""], depends=["Chapter 1"]),
Data("Forza Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Forza Glove R", rules=[""], depends=["Chapter 1"]),
Data("Forza Glove L", rules=[""], depends=["Chapter 1"]),
Data("Forza Footwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Goggles", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Glove R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Glove L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Footwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Headwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Armor", rules=[""], depends=["Chapter 1"]),
Data("Combat Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Combat Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Combat Legwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Headwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armor", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Legwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Headwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Armor", rules=[""], depends=["Chapter 1"]),
Data("Valor Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Valor Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Valor Legwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Headwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Armor", rules=[""], depends=["Chapter 1"]),
Data("Forza Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Forza Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Forza Legwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Headwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armor", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Legwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Helmet", rules=[""], depends=["Chapter 1"]),
Data("Combat Suit", rules=[""], depends=["Chapter 1"]),
Data("Combat Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Combat Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Combat Leggings", rules=[""], depends=["Chapter 1"]),
Data("Vivid Helmet", rules=[""], depends=["Chapter 1"]),
Data("Vivid Suit", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Leggings", rules=[""], depends=["Chapter 1"]),
Data("Valor Helmet", rules=[""], depends=["Chapter 1"]),
Data("Valor Suit", rules=[""], depends=["Chapter 1"]),
Data("Valor Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Valor Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Valor Leggings", rules=[""], depends=["Chapter 1"]),
Data("Forza Helmet", rules=[""], depends=["Chapter 1"]),
Data("Forza Suit", rules=[""], depends=["Chapter 1"]),
Data("Forza Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Forza Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Forza Leggings", rules=[""], depends=["Chapter 1"]),
Data("Reginal Helmet", rules=[""], depends=["Chapter 1"]),
Data("Reginal Suit", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Leggings", rules=[""], depends=["Chapter 1"]),
Data("Survival Headset", rules=[""], depends=["Chapter 1"]),
Data("Survival Shirt", rules=[""], depends=["Chapter 1"]),
Data("Survival Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Survival Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Survival Pants", rules=[""], depends=["Chapter 1"]),
Data("Combat Headset", rules=[""], depends=["Chapter 1"]),
Data("Combat Shirt", rules=[""], depends=["Chapter 1"]),
Data("Combat Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Combat Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Combat Pants", rules=[""], depends=["Chapter 1"]),
Data("Vivid Headset", rules=[""], depends=["Chapter 1"]),
Data("Vivid Shirt", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Pants", rules=[""], depends=["Chapter 1"]),
Data("Valor Headset", rules=[""], depends=["Chapter 1"]),
Data("Valor Shirt", rules=[""], depends=["Chapter 1"]),
Data("Valor Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Valor Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Valor Pants", rules=[""], depends=["Chapter 1"]),
Data("Forza Headset", rules=[""], depends=["Chapter 1"]),
Data("Forza Shirt", rules=[""], depends=["Chapter 1"]),
Data("Forza Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Forza Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Forza Pants", rules=[""], depends=["Chapter 1"]),
Data("Reginal Headset", rules=[""], depends=["Chapter 1"]),
Data("Reginal Shirt", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sleeve R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sleeve L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Pants", rules=[""], depends=["Chapter 1"]),
Data("Survival Visor", rules=[""], depends=["Chapter 1"]),
Data("Survival Vest", rules=[""], depends=["Chapter 1"]),
Data("Survival Guard R", rules=[""], depends=["Chapter 1"]),
Data("Survival Guard L", rules=[""], depends=["Chapter 1"]),
Data("Survival Boots", rules=[""], depends=["Chapter 1"]),
Data("Combat Visor", rules=[""], depends=["Chapter 1"]),
Data("Combat Vest", rules=[""], depends=["Chapter 1"]),
Data("Combat Guard R", rules=[""], depends=["Chapter 1"]),
Data("Combat Guard L", rules=[""], depends=["Chapter 1"]),
Data("Combat Boots", rules=[""], depends=["Chapter 1"]),
Data("Vivid Visor", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vest", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guard R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guard L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Boots", rules=[""], depends=["Chapter 1"]),
Data("Valor Visor", rules=[""], depends=["Chapter 1"]),
Data("Valor Vest", rules=[""], depends=["Chapter 1"]),
Data("Valor Guard R", rules=[""], depends=["Chapter 1"]),
Data("Valor Guard L", rules=[""], depends=["Chapter 1"]),
Data("Valor Boots", rules=[""], depends=["Chapter 1"]),
Data("Forza Visor", rules=[""], depends=["Chapter 1"]),
Data("Forza Vest", rules=[""], depends=["Chapter 1"]),
Data("Forza Guard R", rules=[""], depends=["Chapter 1"]),
Data("Forza Guard L", rules=[""], depends=["Chapter 1"]),
Data("Forza Boots", rules=[""], depends=["Chapter 1"]),
Data("Reginal Visor", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vest", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guard R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guard L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Boots", rules=[""], depends=["Chapter 1"]),
Data("Survival Goggles", rules=[""], depends=["Chapter 1"]),
Data("Survival Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Survival Glove R", rules=[""], depends=["Chapter 1"]),
Data("Survival Glove L", rules=[""], depends=["Chapter 1"]),
Data("Survival Footwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Goggles", rules=[""], depends=["Chapter 1"]),
Data("Combat Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Combat Glove R", rules=[""], depends=["Chapter 1"]),
Data("Combat Glove L", rules=[""], depends=["Chapter 1"]),
Data("Combat Footwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Goggles", rules=[""], depends=["Chapter 1"]),
Data("Vivid Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Glove R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Glove L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Footwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Goggles", rules=[""], depends=["Chapter 1"]),
Data("Valor Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Valor Glove R", rules=[""], depends=["Chapter 1"]),
Data("Valor Glove L", rules=[""], depends=["Chapter 1"]),
Data("Valor Footwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Goggles", rules=[""], depends=["Chapter 1"]),
Data("Forza Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Forza Glove R", rules=[""], depends=["Chapter 1"]),
Data("Forza Glove L", rules=[""], depends=["Chapter 1"]),
Data("Forza Footwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Goggles", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Glove R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Glove L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Footwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Headwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Armor", rules=[""], depends=["Chapter 1"]),
Data("Combat Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Combat Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Combat Legwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Headwear", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armor", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Legwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Headwear", rules=[""], depends=["Chapter 1"]),
Data("Valor Armor", rules=[""], depends=["Chapter 1"]),
Data("Valor Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Valor Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Valor Legwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Headwear", rules=[""], depends=["Chapter 1"]),
Data("Forza Armor", rules=[""], depends=["Chapter 1"]),
Data("Forza Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Forza Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Forza Legwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Headwear", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armor", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armwear R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armwear L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Legwear", rules=[""], depends=["Chapter 1"]),
Data("Combat Helmet", rules=[""], depends=["Chapter 1"]),
Data("Combat Suit", rules=[""], depends=["Chapter 1"]),
Data("Combat Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Combat Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Combat Leggings", rules=[""], depends=["Chapter 1"]),
Data("Vivid Helmet", rules=[""], depends=["Chapter 1"]),
Data("Vivid Suit", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Leggings", rules=[""], depends=["Chapter 1"]),
Data("Valor Helmet", rules=[""], depends=["Chapter 1"]),
Data("Valor Suit", rules=[""], depends=["Chapter 1"]),
Data("Valor Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Valor Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Valor Leggings", rules=[""], depends=["Chapter 1"]),
Data("Forza Helmet", rules=[""], depends=["Chapter 1"]),
Data("Forza Suit", rules=[""], depends=["Chapter 1"]),
Data("Forza Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Forza Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Forza Leggings", rules=[""], depends=["Chapter 1"]),
Data("Reginal Helmet", rules=[""], depends=["Chapter 1"]),
Data("Reginal Suit", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mitt R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mitt L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Leggings", rules=[""], depends=["Chapter 1"]),
Data("Survival Veyes", rules=[""], depends=["Chapter 1"]),
Data("Survival Norak", rules=[""], depends=["Chapter 1"]),
Data("Survival Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Survival Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Survival Brogs", rules=[""], depends=["Chapter 1"]),
Data("Combat Veyes", rules=[""], depends=["Chapter 1"]),
Data("Combat Norak", rules=[""], depends=["Chapter 1"]),
Data("Combat Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Combat Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Combat Brogs", rules=[""], depends=["Chapter 1"]),
Data("Vivid Veyes", rules=[""], depends=["Chapter 1"]),
Data("Vivid Norak", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brogs", rules=[""], depends=["Chapter 1"]),
Data("Valor Veyes", rules=[""], depends=["Chapter 1"]),
Data("Valor Norak", rules=[""], depends=["Chapter 1"]),
Data("Valor Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Valor Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Valor Brogs", rules=[""], depends=["Chapter 1"]),
Data("Forza Veyes", rules=[""], depends=["Chapter 1"]),
Data("Forza Norak", rules=[""], depends=["Chapter 1"]),
Data("Forza Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Forza Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Forza Brogs", rules=[""], depends=["Chapter 1"]),
Data("Reginal Veyes", rules=[""], depends=["Chapter 1"]),
Data("Reginal Norak", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brogs", rules=[""], depends=["Chapter 1"]),
Data("Survival Spex", rules=[""], depends=["Chapter 1"]),
Data("Survival Torse", rules=[""], depends=["Chapter 1"]),
Data("Survival Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Survival Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Survival Soales", rules=[""], depends=["Chapter 1"]),
Data("Combat Spex", rules=[""], depends=["Chapter 1"]),
Data("Combat Torse", rules=[""], depends=["Chapter 1"]),
Data("Combat Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Combat Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Combat Soales", rules=[""], depends=["Chapter 1"]),
Data("Vivid Spex", rules=[""], depends=["Chapter 1"]),
Data("Vivid Torse", rules=[""], depends=["Chapter 1"]),
Data("Vivid Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Soales", rules=[""], depends=["Chapter 1"]),
Data("Valor Spex", rules=[""], depends=["Chapter 1"]),
Data("Valor Torse", rules=[""], depends=["Chapter 1"]),
Data("Valor Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Valor Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Valor Soales", rules=[""], depends=["Chapter 1"]),
Data("Forza Spex", rules=[""], depends=["Chapter 1"]),
Data("Forza Torse", rules=[""], depends=["Chapter 1"]),
Data("Forza Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Forza Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Forza Soales", rules=[""], depends=["Chapter 1"]),
Data("Reginal Spex", rules=[""], depends=["Chapter 1"]),
Data("Reginal Torse", rules=[""], depends=["Chapter 1"]),
Data("Reginal Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Soales", rules=[""], depends=["Chapter 1"]),
Data("Combat Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Combat Ryg", rules=[""], depends=["Chapter 1"]),
Data("Combat Brax R", rules=[""], depends=["Chapter 1"]),
Data("Combat Brax L", rules=[""], depends=["Chapter 1"]),
Data("Combat Traves", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ryg", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brax R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brax L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Traves", rules=[""], depends=["Chapter 1"]),
Data("Valor Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Valor Ryg", rules=[""], depends=["Chapter 1"]),
Data("Valor Brax R", rules=[""], depends=["Chapter 1"]),
Data("Valor Brax L", rules=[""], depends=["Chapter 1"]),
Data("Valor Traves", rules=[""], depends=["Chapter 1"]),
Data("Forza Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Forza Ryg", rules=[""], depends=["Chapter 1"]),
Data("Forza Brax R", rules=[""], depends=["Chapter 1"]),
Data("Forza Brax L", rules=[""], depends=["Chapter 1"]),
Data("Forza Traves", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ryg", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brax R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brax L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Traves", rules=[""], depends=["Chapter 1"]),
Data("Combat Casca", rules=[""], depends=["Chapter 1"]),
Data("Combat Raim", rules=[""], depends=["Chapter 1"]),
Data("Combat Guante R", rules=[""], depends=["Chapter 1"]),
Data("Combat Guante L", rules=[""], depends=["Chapter 1"]),
Data("Combat Tythes", rules=[""], depends=["Chapter 1"]),
Data("Vivid Casca", rules=[""], depends=["Chapter 1"]),
Data("Vivid Raim", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guante R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guante L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tythes", rules=[""], depends=["Chapter 1"]),
Data("Valor Casca", rules=[""], depends=["Chapter 1"]),
Data("Valor Raim", rules=[""], depends=["Chapter 1"]),
Data("Valor Guante R", rules=[""], depends=["Chapter 1"]),
Data("Valor Guante L", rules=[""], depends=["Chapter 1"]),
Data("Valor Tythes", rules=[""], depends=["Chapter 1"]),
Data("Forza Casca", rules=[""], depends=["Chapter 1"]),
Data("Forza Raim", rules=[""], depends=["Chapter 1"]),
Data("Forza Guante R", rules=[""], depends=["Chapter 1"]),
Data("Forza Guante L", rules=[""], depends=["Chapter 1"]),
Data("Forza Tythes", rules=[""], depends=["Chapter 1"]),
Data("Reginal Casca", rules=[""], depends=["Chapter 1"]),
Data("Reginal Raim", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guante R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guante L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tythes", rules=[""], depends=["Chapter 1"]),
Data("Survival Veyes", rules=[""], depends=["Chapter 1"]),
Data("Survival Norak", rules=[""], depends=["Chapter 1"]),
Data("Survival Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Survival Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Survival Brogs", rules=[""], depends=["Chapter 1"]),
Data("Combat Veyes", rules=[""], depends=["Chapter 1"]),
Data("Combat Norak", rules=[""], depends=["Chapter 1"]),
Data("Combat Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Combat Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Combat Brogs", rules=[""], depends=["Chapter 1"]),
Data("Vivid Veyes", rules=[""], depends=["Chapter 1"]),
Data("Vivid Norak", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brogs", rules=[""], depends=["Chapter 1"]),
Data("Valor Veyes", rules=[""], depends=["Chapter 1"]),
Data("Valor Norak", rules=[""], depends=["Chapter 1"]),
Data("Valor Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Valor Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Valor Brogs", rules=[""], depends=["Chapter 1"]),
Data("Forza Veyes", rules=[""], depends=["Chapter 1"]),
Data("Forza Norak", rules=[""], depends=["Chapter 1"]),
Data("Forza Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Forza Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Forza Brogs", rules=[""], depends=["Chapter 1"]),
Data("Reginal Veyes", rules=[""], depends=["Chapter 1"]),
Data("Reginal Norak", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brogs", rules=[""], depends=["Chapter 1"]),
Data("Survival Spex", rules=[""], depends=["Chapter 1"]),
Data("Survival Torse", rules=[""], depends=["Chapter 1"]),
Data("Survival Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Survival Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Survival Soales", rules=[""], depends=["Chapter 1"]),
Data("Combat Spex", rules=[""], depends=["Chapter 1"]),
Data("Combat Torse", rules=[""], depends=["Chapter 1"]),
Data("Combat Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Combat Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Combat Soales", rules=[""], depends=["Chapter 1"]),
Data("Vivid Spex", rules=[""], depends=["Chapter 1"]),
Data("Vivid Torse", rules=[""], depends=["Chapter 1"]),
Data("Vivid Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Soales", rules=[""], depends=["Chapter 1"]),
Data("Valor Spex", rules=[""], depends=["Chapter 1"]),
Data("Valor Torse", rules=[""], depends=["Chapter 1"]),
Data("Valor Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Valor Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Valor Soales", rules=[""], depends=["Chapter 1"]),
Data("Forza Spex", rules=[""], depends=["Chapter 1"]),
Data("Forza Torse", rules=[""], depends=["Chapter 1"]),
Data("Forza Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Forza Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Forza Soales", rules=[""], depends=["Chapter 1"]),
Data("Reginal Spex", rules=[""], depends=["Chapter 1"]),
Data("Reginal Torse", rules=[""], depends=["Chapter 1"]),
Data("Reginal Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Soales", rules=[""], depends=["Chapter 1"]),
Data("Combat Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Combat Ryg", rules=[""], depends=["Chapter 1"]),
Data("Combat Brax R", rules=[""], depends=["Chapter 1"]),
Data("Combat Brax L", rules=[""], depends=["Chapter 1"]),
Data("Combat Traves", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ryg", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brax R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brax L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Traves", rules=[""], depends=["Chapter 1"]),
Data("Valor Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Valor Ryg", rules=[""], depends=["Chapter 1"]),
Data("Valor Brax R", rules=[""], depends=["Chapter 1"]),
Data("Valor Brax L", rules=[""], depends=["Chapter 1"]),
Data("Valor Traves", rules=[""], depends=["Chapter 1"]),
Data("Forza Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Forza Ryg", rules=[""], depends=["Chapter 1"]),
Data("Forza Brax R", rules=[""], depends=["Chapter 1"]),
Data("Forza Brax L", rules=[""], depends=["Chapter 1"]),
Data("Forza Traves", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ryg", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brax R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brax L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Traves", rules=[""], depends=["Chapter 1"]),
Data("Combat Casca", rules=[""], depends=["Chapter 1"]),
Data("Combat Raim", rules=[""], depends=["Chapter 1"]),
Data("Combat Guante R", rules=[""], depends=["Chapter 1"]),
Data("Combat Guante L", rules=[""], depends=["Chapter 1"]),
Data("Combat Tythes", rules=[""], depends=["Chapter 1"]),
Data("Vivid Casca", rules=[""], depends=["Chapter 1"]),
Data("Vivid Raim", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guante R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guante L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tythes", rules=[""], depends=["Chapter 1"]),
Data("Valor Casca", rules=[""], depends=["Chapter 1"]),
Data("Valor Raim", rules=[""], depends=["Chapter 1"]),
Data("Valor Guante R", rules=[""], depends=["Chapter 1"]),
Data("Valor Guante L", rules=[""], depends=["Chapter 1"]),
Data("Valor Tythes", rules=[""], depends=["Chapter 1"]),
Data("Forza Casca", rules=[""], depends=["Chapter 1"]),
Data("Forza Raim", rules=[""], depends=["Chapter 1"]),
Data("Forza Guante R", rules=[""], depends=["Chapter 1"]),
Data("Forza Guante L", rules=[""], depends=["Chapter 1"]),
Data("Forza Tythes", rules=[""], depends=["Chapter 1"]),
Data("Reginal Casca", rules=[""], depends=["Chapter 1"]),
Data("Reginal Raim", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guante R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guante L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tythes", rules=[""], depends=["Chapter 1"]),
Data("Survival Veyes", rules=[""], depends=["Chapter 1"]),
Data("Survival Norak", rules=[""], depends=["Chapter 1"]),
Data("Survival Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Survival Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Survival Brogs", rules=[""], depends=["Chapter 1"]),
Data("Combat Veyes", rules=[""], depends=["Chapter 1"]),
Data("Combat Norak", rules=[""], depends=["Chapter 1"]),
Data("Combat Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Combat Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Combat Brogs", rules=[""], depends=["Chapter 1"]),
Data("Vivid Veyes", rules=[""], depends=["Chapter 1"]),
Data("Vivid Norak", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brogs", rules=[""], depends=["Chapter 1"]),
Data("Valor Veyes", rules=[""], depends=["Chapter 1"]),
Data("Valor Norak", rules=[""], depends=["Chapter 1"]),
Data("Valor Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Valor Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Valor Brogs", rules=[""], depends=["Chapter 1"]),
Data("Forza Veyes", rules=[""], depends=["Chapter 1"]),
Data("Forza Norak", rules=[""], depends=["Chapter 1"]),
Data("Forza Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Forza Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Forza Brogs", rules=[""], depends=["Chapter 1"]),
Data("Reginal Veyes", rules=[""], depends=["Chapter 1"]),
Data("Reginal Norak", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tecta R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tecta L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brogs", rules=[""], depends=["Chapter 1"]),
Data("Survival Spex", rules=[""], depends=["Chapter 1"]),
Data("Survival Torse", rules=[""], depends=["Chapter 1"]),
Data("Survival Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Survival Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Survival Soales", rules=[""], depends=["Chapter 1"]),
Data("Combat Spex", rules=[""], depends=["Chapter 1"]),
Data("Combat Torse", rules=[""], depends=["Chapter 1"]),
Data("Combat Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Combat Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Combat Soales", rules=[""], depends=["Chapter 1"]),
Data("Vivid Spex", rules=[""], depends=["Chapter 1"]),
Data("Vivid Torse", rules=[""], depends=["Chapter 1"]),
Data("Vivid Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Soales", rules=[""], depends=["Chapter 1"]),
Data("Valor Spex", rules=[""], depends=["Chapter 1"]),
Data("Valor Torse", rules=[""], depends=["Chapter 1"]),
Data("Valor Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Valor Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Valor Soales", rules=[""], depends=["Chapter 1"]),
Data("Forza Spex", rules=[""], depends=["Chapter 1"]),
Data("Forza Torse", rules=[""], depends=["Chapter 1"]),
Data("Forza Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Forza Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Forza Soales", rules=[""], depends=["Chapter 1"]),
Data("Reginal Spex", rules=[""], depends=["Chapter 1"]),
Data("Reginal Torse", rules=[""], depends=["Chapter 1"]),
Data("Reginal Quantlet R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Quantlet L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Soales", rules=[""], depends=["Chapter 1"]),
Data("Combat Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Combat Ryg", rules=[""], depends=["Chapter 1"]),
Data("Combat Brax R", rules=[""], depends=["Chapter 1"]),
Data("Combat Brax L", rules=[""], depends=["Chapter 1"]),
Data("Combat Traves", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ryg", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brax R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Brax L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Traves", rules=[""], depends=["Chapter 1"]),
Data("Valor Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Valor Ryg", rules=[""], depends=["Chapter 1"]),
Data("Valor Brax R", rules=[""], depends=["Chapter 1"]),
Data("Valor Brax L", rules=[""], depends=["Chapter 1"]),
Data("Valor Traves", rules=[""], depends=["Chapter 1"]),
Data("Forza Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Forza Ryg", rules=[""], depends=["Chapter 1"]),
Data("Forza Brax R", rules=[""], depends=["Chapter 1"]),
Data("Forza Brax L", rules=[""], depends=["Chapter 1"]),
Data("Forza Traves", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tuesta", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ryg", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brax R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Brax L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Traves", rules=[""], depends=["Chapter 1"]),
Data("Combat Casca", rules=[""], depends=["Chapter 1"]),
Data("Combat Raim", rules=[""], depends=["Chapter 1"]),
Data("Combat Guante R", rules=[""], depends=["Chapter 1"]),
Data("Combat Guante L", rules=[""], depends=["Chapter 1"]),
Data("Combat Tythes", rules=[""], depends=["Chapter 1"]),
Data("Vivid Casca", rules=[""], depends=["Chapter 1"]),
Data("Vivid Raim", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guante R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Guante L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Tythes", rules=[""], depends=["Chapter 1"]),
Data("Valor Casca", rules=[""], depends=["Chapter 1"]),
Data("Valor Raim", rules=[""], depends=["Chapter 1"]),
Data("Valor Guante R", rules=[""], depends=["Chapter 1"]),
Data("Valor Guante L", rules=[""], depends=["Chapter 1"]),
Data("Valor Tythes", rules=[""], depends=["Chapter 1"]),
Data("Forza Casca", rules=[""], depends=["Chapter 1"]),
Data("Forza Raim", rules=[""], depends=["Chapter 1"]),
Data("Forza Guante R", rules=[""], depends=["Chapter 1"]),
Data("Forza Guante L", rules=[""], depends=["Chapter 1"]),
Data("Forza Tythes", rules=[""], depends=["Chapter 1"]),
Data("Reginal Casca", rules=[""], depends=["Chapter 1"]),
Data("Reginal Raim", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guante R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Guante L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Tythes", rules=[""], depends=["Chapter 1"]),
Data("Combat Vizard", rules=[""], depends=["Chapter 1"]),
Data("Combat Vestis", rules=[""], depends=["Chapter 1"]),
Data("Combat Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Combat Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Combat Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vizard", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vestis", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Valor Vizard", rules=[""], depends=["Chapter 1"]),
Data("Valor Vestis", rules=[""], depends=["Chapter 1"]),
Data("Valor Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Valor Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Valor Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Forza Vizard", rules=[""], depends=["Chapter 1"]),
Data("Forza Vestis", rules=[""], depends=["Chapter 1"]),
Data("Forza Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Forza Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Forza Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vizard", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vestis", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Combat Vitra", rules=[""], depends=["Chapter 1"]),
Data("Combat Corpus", rules=[""], depends=["Chapter 1"]),
Data("Combat Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Combat Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Combat Plantars", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vitra", rules=[""], depends=["Chapter 1"]),
Data("Vivid Corpus", rules=[""], depends=["Chapter 1"]),
Data("Vivid Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Plantars", rules=[""], depends=["Chapter 1"]),
Data("Valor Vitra", rules=[""], depends=["Chapter 1"]),
Data("Valor Corpus", rules=[""], depends=["Chapter 1"]),
Data("Valor Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Valor Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Valor Plantars", rules=[""], depends=["Chapter 1"]),
Data("Forza Vitra", rules=[""], depends=["Chapter 1"]),
Data("Forza Corpus", rules=[""], depends=["Chapter 1"]),
Data("Forza Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Forza Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Forza Plantars", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vitra", rules=[""], depends=["Chapter 1"]),
Data("Reginal Corpus", rules=[""], depends=["Chapter 1"]),
Data("Reginal Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Plantars", rules=[""], depends=["Chapter 1"]),
Data("Combat Cassida", rules=[""], depends=["Chapter 1"]),
Data("Combat Arma", rules=[""], depends=["Chapter 1"]),
Data("Combat Manus R", rules=[""], depends=["Chapter 1"]),
Data("Combat Manus L", rules=[""], depends=["Chapter 1"]),
Data("Combat Crura", rules=[""], depends=["Chapter 1"]),
Data("Vivid Cassida", rules=[""], depends=["Chapter 1"]),
Data("Vivid Arma", rules=[""], depends=["Chapter 1"]),
Data("Vivid Manus R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Manus L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Crura", rules=[""], depends=["Chapter 1"]),
Data("Valor Cassida", rules=[""], depends=["Chapter 1"]),
Data("Valor Arma", rules=[""], depends=["Chapter 1"]),
Data("Valor Manus R", rules=[""], depends=["Chapter 1"]),
Data("Valor Manus L", rules=[""], depends=["Chapter 1"]),
Data("Valor Crura", rules=[""], depends=["Chapter 1"]),
Data("Forza Cassida", rules=[""], depends=["Chapter 1"]),
Data("Forza Arma", rules=[""], depends=["Chapter 1"]),
Data("Forza Manus R", rules=[""], depends=["Chapter 1"]),
Data("Forza Manus L", rules=[""], depends=["Chapter 1"]),
Data("Forza Crura", rules=[""], depends=["Chapter 1"]),
Data("Reginal Cassida", rules=[""], depends=["Chapter 1"]),
Data("Reginal Arma", rules=[""], depends=["Chapter 1"]),
Data("Reginal Manus R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Manus L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Crura", rules=[""], depends=["Chapter 1"]),
Data("Combat Vizard", rules=[""], depends=["Chapter 1"]),
Data("Combat Vestis", rules=[""], depends=["Chapter 1"]),
Data("Combat Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Combat Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Combat Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vizard", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vestis", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Valor Vizard", rules=[""], depends=["Chapter 1"]),
Data("Valor Vestis", rules=[""], depends=["Chapter 1"]),
Data("Valor Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Valor Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Valor Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Forza Vizard", rules=[""], depends=["Chapter 1"]),
Data("Forza Vestis", rules=[""], depends=["Chapter 1"]),
Data("Forza Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Forza Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Forza Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vizard", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vestis", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Combat Vitra", rules=[""], depends=["Chapter 1"]),
Data("Combat Corpus", rules=[""], depends=["Chapter 1"]),
Data("Combat Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Combat Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Combat Plantars", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vitra", rules=[""], depends=["Chapter 1"]),
Data("Vivid Corpus", rules=[""], depends=["Chapter 1"]),
Data("Vivid Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Plantars", rules=[""], depends=["Chapter 1"]),
Data("Valor Vitra", rules=[""], depends=["Chapter 1"]),
Data("Valor Corpus", rules=[""], depends=["Chapter 1"]),
Data("Valor Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Valor Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Valor Plantars", rules=[""], depends=["Chapter 1"]),
Data("Forza Vitra", rules=[""], depends=["Chapter 1"]),
Data("Forza Corpus", rules=[""], depends=["Chapter 1"]),
Data("Forza Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Forza Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Forza Plantars", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vitra", rules=[""], depends=["Chapter 1"]),
Data("Reginal Corpus", rules=[""], depends=["Chapter 1"]),
Data("Reginal Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Plantars", rules=[""], depends=["Chapter 1"]),
Data("Combat Cassida", rules=[""], depends=["Chapter 1"]),
Data("Combat Arma", rules=[""], depends=["Chapter 1"]),
Data("Combat Manus R", rules=[""], depends=["Chapter 1"]),
Data("Combat Manus L", rules=[""], depends=["Chapter 1"]),
Data("Combat Crura", rules=[""], depends=["Chapter 1"]),
Data("Vivid Cassida", rules=[""], depends=["Chapter 1"]),
Data("Vivid Arma", rules=[""], depends=["Chapter 1"]),
Data("Vivid Manus R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Manus L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Crura", rules=[""], depends=["Chapter 1"]),
Data("Valor Cassida", rules=[""], depends=["Chapter 1"]),
Data("Valor Arma", rules=[""], depends=["Chapter 1"]),
Data("Valor Manus R", rules=[""], depends=["Chapter 1"]),
Data("Valor Manus L", rules=[""], depends=["Chapter 1"]),
Data("Valor Crura", rules=[""], depends=["Chapter 1"]),
Data("Forza Cassida", rules=[""], depends=["Chapter 1"]),
Data("Forza Arma", rules=[""], depends=["Chapter 1"]),
Data("Forza Manus R", rules=[""], depends=["Chapter 1"]),
Data("Forza Manus L", rules=[""], depends=["Chapter 1"]),
Data("Forza Crura", rules=[""], depends=["Chapter 1"]),
Data("Reginal Cassida", rules=[""], depends=["Chapter 1"]),
Data("Reginal Arma", rules=[""], depends=["Chapter 1"]),
Data("Reginal Manus R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Manus L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Crura", rules=[""], depends=["Chapter 1"]),
Data("Combat Vizard", rules=[""], depends=["Chapter 1"]),
Data("Combat Vestis", rules=[""], depends=["Chapter 1"]),
Data("Combat Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Combat Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Combat Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vizard", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vestis", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Valor Vizard", rules=[""], depends=["Chapter 1"]),
Data("Valor Vestis", rules=[""], depends=["Chapter 1"]),
Data("Valor Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Valor Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Valor Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Forza Vizard", rules=[""], depends=["Chapter 1"]),
Data("Forza Vestis", rules=[""], depends=["Chapter 1"]),
Data("Forza Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Forza Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Forza Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vizard", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vestis", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armilla R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armilla L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ocreis", rules=[""], depends=["Chapter 1"]),
Data("Combat Vitra", rules=[""], depends=["Chapter 1"]),
Data("Combat Corpus", rules=[""], depends=["Chapter 1"]),
Data("Combat Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Combat Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Combat Plantars", rules=[""], depends=["Chapter 1"]),
Data("Vivid Vitra", rules=[""], depends=["Chapter 1"]),
Data("Vivid Corpus", rules=[""], depends=["Chapter 1"]),
Data("Vivid Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Plantars", rules=[""], depends=["Chapter 1"]),
Data("Valor Vitra", rules=[""], depends=["Chapter 1"]),
Data("Valor Corpus", rules=[""], depends=["Chapter 1"]),
Data("Valor Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Valor Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Valor Plantars", rules=[""], depends=["Chapter 1"]),
Data("Forza Vitra", rules=[""], depends=["Chapter 1"]),
Data("Forza Corpus", rules=[""], depends=["Chapter 1"]),
Data("Forza Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Forza Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Forza Plantars", rules=[""], depends=["Chapter 1"]),
Data("Reginal Vitra", rules=[""], depends=["Chapter 1"]),
Data("Reginal Corpus", rules=[""], depends=["Chapter 1"]),
Data("Reginal Chiro R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Chiro L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Plantars", rules=[""], depends=["Chapter 1"]),
Data("Combat Cassida", rules=[""], depends=["Chapter 1"]),
Data("Combat Arma", rules=[""], depends=["Chapter 1"]),
Data("Combat Manus R", rules=[""], depends=["Chapter 1"]),
Data("Combat Manus L", rules=[""], depends=["Chapter 1"]),
Data("Combat Crura", rules=[""], depends=["Chapter 1"]),
Data("Vivid Cassida", rules=[""], depends=["Chapter 1"]),
Data("Vivid Arma", rules=[""], depends=["Chapter 1"]),
Data("Vivid Manus R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Manus L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Crura", rules=[""], depends=["Chapter 1"]),
Data("Valor Cassida", rules=[""], depends=["Chapter 1"]),
Data("Valor Arma", rules=[""], depends=["Chapter 1"]),
Data("Valor Manus R", rules=[""], depends=["Chapter 1"]),
Data("Valor Manus L", rules=[""], depends=["Chapter 1"]),
Data("Valor Crura", rules=[""], depends=["Chapter 1"]),
Data("Forza Cassida", rules=[""], depends=["Chapter 1"]),
Data("Forza Arma", rules=[""], depends=["Chapter 1"]),
Data("Forza Manus R", rules=[""], depends=["Chapter 1"]),
Data("Forza Manus L", rules=[""], depends=["Chapter 1"]),
Data("Forza Crura", rules=[""], depends=["Chapter 1"]),
Data("Reginal Cassida", rules=[""], depends=["Chapter 1"]),
Data("Reginal Arma", rules=[""], depends=["Chapter 1"]),
Data("Reginal Manus R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Manus L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Crura", rules=[""], depends=["Chapter 1"]),
Data("Combat Screen", rules=[""], depends=["Chapter 1"]),
Data("Combat Breaker", rules=[""], depends=["Chapter 1"]),
Data("Combat Ward R", rules=[""], depends=["Chapter 1"]),
Data("Combat Ward L", rules=[""], depends=["Chapter 1"]),
Data("Combat Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Screen", rules=[""], depends=["Chapter 1"]),
Data("Vivid Breaker", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ward R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ward L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Valor Screen", rules=[""], depends=["Chapter 1"]),
Data("Valor Breaker", rules=[""], depends=["Chapter 1"]),
Data("Valor Ward R", rules=[""], depends=["Chapter 1"]),
Data("Valor Ward L", rules=[""], depends=["Chapter 1"]),
Data("Valor Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Forza Screen", rules=[""], depends=["Chapter 1"]),
Data("Forza Breaker", rules=[""], depends=["Chapter 1"]),
Data("Forza Ward R", rules=[""], depends=["Chapter 1"]),
Data("Forza Ward L", rules=[""], depends=["Chapter 1"]),
Data("Forza Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Screen", rules=[""], depends=["Chapter 1"]),
Data("Reginal Breaker", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ward R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ward L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Combat Sights", rules=[""], depends=["Chapter 1"]),
Data("Combat Encaser", rules=[""], depends=["Chapter 1"]),
Data("Combat Grip R", rules=[""], depends=["Chapter 1"]),
Data("Combat Grip L", rules=[""], depends=["Chapter 1"]),
Data("Combat Distancers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sights", rules=[""], depends=["Chapter 1"]),
Data("Vivid Encaser", rules=[""], depends=["Chapter 1"]),
Data("Vivid Grip R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Grip L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Distancers", rules=[""], depends=["Chapter 1"]),
Data("Valor Sights", rules=[""], depends=["Chapter 1"]),
Data("Valor Encaser", rules=[""], depends=["Chapter 1"]),
Data("Valor Grip R", rules=[""], depends=["Chapter 1"]),
Data("Valor Grip L", rules=[""], depends=["Chapter 1"]),
Data("Valor Distancers", rules=[""], depends=["Chapter 1"]),
Data("Forza Sights", rules=[""], depends=["Chapter 1"]),
Data("Forza Encaser", rules=[""], depends=["Chapter 1"]),
Data("Forza Grip R", rules=[""], depends=["Chapter 1"]),
Data("Forza Grip L", rules=[""], depends=["Chapter 1"]),
Data("Forza Distancers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sights", rules=[""], depends=["Chapter 1"]),
Data("Reginal Encaser", rules=[""], depends=["Chapter 1"]),
Data("Reginal Grip R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Grip L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Distancers", rules=[""], depends=["Chapter 1"]),
Data("Combat Armet", rules=[""], depends=["Chapter 1"]),
Data("Combat Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Combat Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Combat Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Combat Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armet", rules=[""], depends=["Chapter 1"]),
Data("Vivid Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Vivid Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Valor Armet", rules=[""], depends=["Chapter 1"]),
Data("Valor Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Valor Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Valor Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Valor Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Forza Armet", rules=[""], depends=["Chapter 1"]),
Data("Forza Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Forza Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Forza Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Forza Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armet", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Reginal Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Combat Screen", rules=[""], depends=["Chapter 1"]),
Data("Combat Breaker", rules=[""], depends=["Chapter 1"]),
Data("Combat Ward R", rules=[""], depends=["Chapter 1"]),
Data("Combat Ward L", rules=[""], depends=["Chapter 1"]),
Data("Combat Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Screen", rules=[""], depends=["Chapter 1"]),
Data("Vivid Breaker", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ward R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ward L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Valor Screen", rules=[""], depends=["Chapter 1"]),
Data("Valor Breaker", rules=[""], depends=["Chapter 1"]),
Data("Valor Ward R", rules=[""], depends=["Chapter 1"]),
Data("Valor Ward L", rules=[""], depends=["Chapter 1"]),
Data("Valor Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Forza Screen", rules=[""], depends=["Chapter 1"]),
Data("Forza Breaker", rules=[""], depends=["Chapter 1"]),
Data("Forza Ward R", rules=[""], depends=["Chapter 1"]),
Data("Forza Ward L", rules=[""], depends=["Chapter 1"]),
Data("Forza Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Screen", rules=[""], depends=["Chapter 1"]),
Data("Reginal Breaker", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ward R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ward L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Combat Sights", rules=[""], depends=["Chapter 1"]),
Data("Combat Encaser", rules=[""], depends=["Chapter 1"]),
Data("Combat Grip R", rules=[""], depends=["Chapter 1"]),
Data("Combat Grip L", rules=[""], depends=["Chapter 1"]),
Data("Combat Distancers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sights", rules=[""], depends=["Chapter 1"]),
Data("Vivid Encaser", rules=[""], depends=["Chapter 1"]),
Data("Vivid Grip R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Grip L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Distancers", rules=[""], depends=["Chapter 1"]),
Data("Valor Sights", rules=[""], depends=["Chapter 1"]),
Data("Valor Encaser", rules=[""], depends=["Chapter 1"]),
Data("Valor Grip R", rules=[""], depends=["Chapter 1"]),
Data("Valor Grip L", rules=[""], depends=["Chapter 1"]),
Data("Valor Distancers", rules=[""], depends=["Chapter 1"]),
Data("Forza Sights", rules=[""], depends=["Chapter 1"]),
Data("Forza Encaser", rules=[""], depends=["Chapter 1"]),
Data("Forza Grip R", rules=[""], depends=["Chapter 1"]),
Data("Forza Grip L", rules=[""], depends=["Chapter 1"]),
Data("Forza Distancers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sights", rules=[""], depends=["Chapter 1"]),
Data("Reginal Encaser", rules=[""], depends=["Chapter 1"]),
Data("Reginal Grip R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Grip L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Distancers", rules=[""], depends=["Chapter 1"]),
Data("Combat Armet", rules=[""], depends=["Chapter 1"]),
Data("Combat Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Combat Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Combat Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Combat Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armet", rules=[""], depends=["Chapter 1"]),
Data("Vivid Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Vivid Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Valor Armet", rules=[""], depends=["Chapter 1"]),
Data("Valor Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Valor Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Valor Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Valor Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Forza Armet", rules=[""], depends=["Chapter 1"]),
Data("Forza Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Forza Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Forza Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Forza Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armet", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Reginal Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Combat Screen", rules=[""], depends=["Chapter 1"]),
Data("Combat Breaker", rules=[""], depends=["Chapter 1"]),
Data("Combat Ward R", rules=[""], depends=["Chapter 1"]),
Data("Combat Ward L", rules=[""], depends=["Chapter 1"]),
Data("Combat Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Screen", rules=[""], depends=["Chapter 1"]),
Data("Vivid Breaker", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ward R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ward L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Valor Screen", rules=[""], depends=["Chapter 1"]),
Data("Valor Breaker", rules=[""], depends=["Chapter 1"]),
Data("Valor Ward R", rules=[""], depends=["Chapter 1"]),
Data("Valor Ward L", rules=[""], depends=["Chapter 1"]),
Data("Valor Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Forza Screen", rules=[""], depends=["Chapter 1"]),
Data("Forza Breaker", rules=[""], depends=["Chapter 1"]),
Data("Forza Ward R", rules=[""], depends=["Chapter 1"]),
Data("Forza Ward L", rules=[""], depends=["Chapter 1"]),
Data("Forza Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Screen", rules=[""], depends=["Chapter 1"]),
Data("Reginal Breaker", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ward R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ward L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Trudgers", rules=[""], depends=["Chapter 1"]),
Data("Combat Sights", rules=[""], depends=["Chapter 1"]),
Data("Combat Encaser", rules=[""], depends=["Chapter 1"]),
Data("Combat Grip R", rules=[""], depends=["Chapter 1"]),
Data("Combat Grip L", rules=[""], depends=["Chapter 1"]),
Data("Combat Distancers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Sights", rules=[""], depends=["Chapter 1"]),
Data("Vivid Encaser", rules=[""], depends=["Chapter 1"]),
Data("Vivid Grip R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Grip L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Distancers", rules=[""], depends=["Chapter 1"]),
Data("Valor Sights", rules=[""], depends=["Chapter 1"]),
Data("Valor Encaser", rules=[""], depends=["Chapter 1"]),
Data("Valor Grip R", rules=[""], depends=["Chapter 1"]),
Data("Valor Grip L", rules=[""], depends=["Chapter 1"]),
Data("Valor Distancers", rules=[""], depends=["Chapter 1"]),
Data("Forza Sights", rules=[""], depends=["Chapter 1"]),
Data("Forza Encaser", rules=[""], depends=["Chapter 1"]),
Data("Forza Grip R", rules=[""], depends=["Chapter 1"]),
Data("Forza Grip L", rules=[""], depends=["Chapter 1"]),
Data("Forza Distancers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Sights", rules=[""], depends=["Chapter 1"]),
Data("Reginal Encaser", rules=[""], depends=["Chapter 1"]),
Data("Reginal Grip R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Grip L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Distancers", rules=[""], depends=["Chapter 1"]),
Data("Combat Armet", rules=[""], depends=["Chapter 1"]),
Data("Combat Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Combat Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Combat Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Combat Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Armet", rules=[""], depends=["Chapter 1"]),
Data("Vivid Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Vivid Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Valor Armet", rules=[""], depends=["Chapter 1"]),
Data("Valor Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Valor Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Valor Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Valor Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Forza Armet", rules=[""], depends=["Chapter 1"]),
Data("Forza Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Forza Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Forza Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Forza Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Reginal Armet", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bulwark", rules=[""], depends=["Chapter 1"]),
Data("Reginal Wrest R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Wrest L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Stabilizers", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yii", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiym", rules=[""], depends=["Chapter 1"]),
Data("Valor Yii", rules=[""], depends=["Chapter 1"]),
Data("Valor Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiym", rules=[""], depends=["Chapter 1"]),
Data("Forza Yii", rules=[""], depends=["Chapter 1"]),
Data("Forza Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiym", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yii", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiym", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ayx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Nyx", rules=[""], depends=["Chapter 1"]),
Data("Valor Ayx", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Valor Nyx", rules=[""], depends=["Chapter 1"]),
Data("Forza Ayx", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Forza Nyx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ayx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Nyx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyi", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyum", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyi", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyum", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyi", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyum", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyi", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyum", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yii", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiym", rules=[""], depends=["Chapter 1"]),
Data("Valor Yii", rules=[""], depends=["Chapter 1"]),
Data("Valor Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiym", rules=[""], depends=["Chapter 1"]),
Data("Forza Yii", rules=[""], depends=["Chapter 1"]),
Data("Forza Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiym", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yii", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiym", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ayx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Nyx", rules=[""], depends=["Chapter 1"]),
Data("Valor Ayx", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Valor Nyx", rules=[""], depends=["Chapter 1"]),
Data("Forza Ayx", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Forza Nyx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ayx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Nyx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyi", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyum", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyi", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyum", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyi", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyum", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyi", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyum", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yii", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Yiym", rules=[""], depends=["Chapter 1"]),
Data("Valor Yii", rules=[""], depends=["Chapter 1"]),
Data("Valor Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Valor Yiym", rules=[""], depends=["Chapter 1"]),
Data("Forza Yii", rules=[""], depends=["Chapter 1"]),
Data("Forza Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Forza Yiym", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yii", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yimsel", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiys R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiys L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Yiym", rules=[""], depends=["Chapter 1"]),
Data("Vivid Ayx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Nyx", rules=[""], depends=["Chapter 1"]),
Data("Valor Ayx", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Valor Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Valor Nyx", rules=[""], depends=["Chapter 1"]),
Data("Forza Ayx", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Forza Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Forza Nyx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Ayx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Mayx L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Nyx", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyi", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Vivid Zyum", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyi", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Valor Zyum", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyi", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Forza Zyum", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyi", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyua L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Zyum", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Crest", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Crest", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Crest", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Crest", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Warrior's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Vanquisher's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Overlord's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Mother God's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Crest", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Crest", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Crest", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Crest", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Warrior's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Vanquisher's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Overlord's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Mother God's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Mask", rules=[""], depends=["Chapter 1"]),
Data("Light Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Bracer R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Bracer L", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Sabatons", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Crest", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Crest", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Crest", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Crest", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Gauntlet R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Gauntlet L", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Warrior's Plate", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Warrior's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Warrior's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Vanquisher's Plate", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Vanquisher's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Vanquisher's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Overlord's Plate", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Overlord's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Overlord's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Helm", rules=[""], depends=["Chapter 1"]),
Data("Heavy Mother God's Plate", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Vambrace R", rules=[""], depends=["Chapter 1"]),
Data("Mother God's Vambrace L", rules=[""], depends=["Chapter 1"]),
Data("Heavy Mother God's Greaves", rules=[""], depends=["Chapter 1"]),
Data("Diving Mask", rules=[""], depends=["Chapter 1"]),
Data("Diving Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Diving Band R", rules=[""], depends=["Chapter 1"]),
Data("Diving Band L", rules=[""], depends=["Chapter 1"]),
Data("Diving Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Mask", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Band R", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Band L", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Snorkel", rules=[""], depends=["Chapter 1"]),
Data("Swimsuit Top", rules=[""], depends=["Chapter 1"]),
Data("Swimmer's Band R", rules=[""], depends=["Chapter 1"]),
Data("Swimmer's Band L", rules=[""], depends=["Chapter 1"]),
Data("Swimsuit Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Prime Snorkel", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimsuit Top", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimmer's Band R", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimmer's Band L", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimsuit Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Diving Mask", rules=[""], depends=["Chapter 1"]),
Data("Diving Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Diving Band R", rules=[""], depends=["Chapter 1"]),
Data("Diving Band L", rules=[""], depends=["Chapter 1"]),
Data("Diving Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Mask", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Band R", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Band L", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Snorkel", rules=[""], depends=["Chapter 1"]),
Data("Swimsuit Top", rules=[""], depends=["Chapter 1"]),
Data("Swimmer's Band R", rules=[""], depends=["Chapter 1"]),
Data("Swimmer's Band L", rules=[""], depends=["Chapter 1"]),
Data("Swimsuit Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Prime Snorkel", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimsuit Top", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimmer's Band R", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimmer's Band L", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimsuit Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Diving Mask", rules=[""], depends=["Chapter 1"]),
Data("Diving Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Diving Band R", rules=[""], depends=["Chapter 1"]),
Data("Diving Band L", rules=[""], depends=["Chapter 1"]),
Data("Diving Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Mask", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Band R", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Band L", rules=[""], depends=["Chapter 1"]),
Data("Prime Diving Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Snorkel", rules=[""], depends=["Chapter 1"]),
Data("Swimsuit Top", rules=[""], depends=["Chapter 1"]),
Data("Swimmer's Band R", rules=[""], depends=["Chapter 1"]),
Data("Swimmer's Band L", rules=[""], depends=["Chapter 1"]),
Data("Swimsuit Bottoms", rules=[""], depends=["Chapter 1"]),
Data("Prime Snorkel", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimsuit Top", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimmer's Band R", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimmer's Band L", rules=[""], depends=["Chapter 1"]),
Data("Prime Swimsuit Bottoms", rules=[""], depends=["Chapter 1"]),
]
