from . import Loc as Data

# flake8: noqa
# https://xenoblade.github.io/xbx/bdat/common_local_us/SHP_WpnDL.html
shop_doll_weapons_data: list[Data] = [
Data("SHM-M120SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R120SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R120SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M130SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M120SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M130SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R130SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M150SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M150SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M130SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M120SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R120SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R120SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M150SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M120SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M130SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R130SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M130SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M150SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M150SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M120SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R120SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R120SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M131SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M120SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M130SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R130SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M151SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M150SA Rod", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150SA M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150SA Railgun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M131SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150SA Beamsaber", rules=[""], depends=["Chapter 1"]),
Data("SHM-M220SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250SA HB-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R220SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M151SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M220SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M230SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250SA HB-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R230SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M131SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M230SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M250SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250SA HB-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M151SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M250SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M220SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R220SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R220SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M152SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M220SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M230SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R230SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R230SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M152SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M230SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M250SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M152SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M250SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M220SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R220SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R220SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M123SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M220SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M230SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R230SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R230SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M133SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M230SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M250SA Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250SA S-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-M153SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M250SA V-knuckle", rules=[""], depends=["Chapter 1"]),
Data("SHM-M350SA E-Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R220SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R350SA Voltnet", rules=[""], depends=["Chapter 1"]),
Data("SAM-M123SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130GG Ringedge", rules=[""], depends=["Chapter 1"]),
Data("SHM-M350SA E-Sword", rules=[""], depends=["Chapter 1"]),
Data("SSM-R230SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R350SA Voltnet", rules=[""], depends=["Chapter 1"]),
Data("SAM-M133SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150GG Ringedge", rules=[""], depends=["Chapter 1"]),
Data("SHM-M430SA Pile-Bunker", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250SA F-Grenade", rules=[""], depends=["Chapter 1"]),
Data("SRM-R350SA Voltnet", rules=[""], depends=["Chapter 1"]),
Data("SAM-M153SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130GG Ringedge", rules=[""], depends=["Chapter 1"]),
Data("SHM-M450SA Pile-Bunker", rules=[""], depends=["Chapter 1"]),
Data("SSM-R330SA SHD-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R430SA Grenade", rules=[""], depends=["Chapter 1"]),
Data("SAM-M123SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150GG Ringedge", rules=[""], depends=["Chapter 1"]),
Data("SHM-M430SA Pile-Bunker", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350SA SHD-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R450SA Grenade", rules=[""], depends=["Chapter 1"]),
Data("SAM-M133SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130GG Ringedge", rules=[""], depends=["Chapter 1"]),
Data("SHM-M450SA Pile-Bunker", rules=[""], depends=["Chapter 1"]),
Data("SSM-R330SA SHD-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R430SA Grenade", rules=[""], depends=["Chapter 1"]),
Data("SAM-M153SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150GG Ringedge", rules=[""], depends=["Chapter 1"]),
Data("SHM-M430SA Pile-Bunker", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350SA SHD-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R450SA Grenade", rules=[""], depends=["Chapter 1"]),
Data("SAM-M124SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130ME Falchion", rules=[""], depends=["Chapter 1"]),
Data("SHM-M450SA Pile-Bunker", rules=[""], depends=["Chapter 1"]),
Data("SSM-R330SA SHD-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R430SA Grenade", rules=[""], depends=["Chapter 1"]),
Data("SAM-M134SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150ME Falchion", rules=[""], depends=["Chapter 1"]),
Data("SHM-R130SA Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350SA SHD-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R450SA Grenade", rules=[""], depends=["Chapter 1"]),
Data("SAM-M154SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130ME Falchion", rules=[""], depends=["Chapter 1"]),
Data("SHM-R150SA Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R450SA SHD-Ray", rules=[""], depends=["Chapter 1"]),
Data("SRM-M120SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M124SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150ME Falchion", rules=[""], depends=["Chapter 1"]),
Data("SHM-R130SA Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R450SA SHD-Ray", rules=[""], depends=["Chapter 1"]),
Data("SRM-M130SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M134SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M130ME Falchion", rules=[""], depends=["Chapter 1"]),
Data("SHM-R150SA Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R450SA SHD-Ray", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M154SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M150ME Falchion", rules=[""], depends=["Chapter 1"]),
Data("SHM-R130SA Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R530SA Chaingun", rules=[""], depends=["Chapter 1"]),
Data("SRM-M120SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M124SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M250ME Claymore", rules=[""], depends=["Chapter 1"]),
Data("SHM-R150SA Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R550SA Chaingun", rules=[""], depends=["Chapter 1"]),
Data("SRM-M130SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M134SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M250ME Claymore", rules=[""], depends=["Chapter 1"]),
Data("SHM-R250SA E-Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R530SA Chaingun", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M154SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M250ME Claymore", rules=[""], depends=["Chapter 1"]),
Data("SHM-R250SA E-Machine Gun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R550SA Chaingun", rules=[""], depends=["Chapter 1"]),
Data("SRM-M120SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M125SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M350ME Katar", rules=[""], depends=["Chapter 1"]),
Data("SHM-R320SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-R530SA Chaingun", rules=[""], depends=["Chapter 1"]),
Data("SRM-M130SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M135SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M350ME Katar", rules=[""], depends=["Chapter 1"]),
Data("SHM-R330SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-R550SA Chaingun", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150SA Buster", rules=[""], depends=["Chapter 1"]),
Data("SAM-M155SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-M350ME Katar", rules=[""], depends=["Chapter 1"]),
Data("SHM-R350SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX130SA G-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R550SA Hyper-Rail", rules=[""], depends=["Chapter 1"]),
Data("SAM-M125SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R320SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R320SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX150SA G-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R550SA Hyper-Rail", rules=[""], depends=["Chapter 1"]),
Data("SAM-M135SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R330SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R330SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX130SA G-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R550SA Hyper-Rail", rules=[""], depends=["Chapter 1"]),
Data("SAM-M155SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R350SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX150SA G-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R650SA Buster-Launcher", rules=[""], depends=["Chapter 1"]),
Data("SAM-M125SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R320SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R320SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX130SA G-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R650SA Buster-Launcher", rules=[""], depends=["Chapter 1"]),
Data("SAM-M135SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R330SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R330SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX150SA G-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R650SA Buster-Launcher", rules=[""], depends=["Chapter 1"]),
Data("SAM-M155SA Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R350SA Assault", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX150SA G2-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R730SA L-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-R130SA Minigun", rules=[""], depends=["Chapter 1"]),
Data("SKM-R320SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R450SA B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX150SA G2-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R750SA L-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-R150SA Minigun", rules=[""], depends=["Chapter 1"]),
Data("SKM-R330SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R450SA B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX150SA G2-Buster", rules=[""], depends=["Chapter 1"]),
Data("SRM-R730SA L-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-R130SA Minigun", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350SA Cracker-BM", rules=[""], depends=["Chapter 1"]),
Data("SHM-R450SA B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX250SA E-Scythe", rules=[""], depends=["Chapter 1"]),
Data("SRM-R750SA L-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-R150SA Minigun", rules=[""], depends=["Chapter 1"]),
Data("SKM-R330GG Cracker-FL", rules=[""], depends=["Chapter 1"]),
Data("SHM-R550SA E-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX250SA E-Scythe", rules=[""], depends=["Chapter 1"]),
Data("SRM-R730SA L-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-R130SA Minigun", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350GG Cracker-FL", rules=[""], depends=["Chapter 1"]),
Data("SHM-R550SA E-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-MX250SA E-Scythe", rules=[""], depends=["Chapter 1"]),
Data("SRM-R750SA L-Missile", rules=[""], depends=["Chapter 1"]),
Data("SAM-R150SA Minigun", rules=[""], depends=["Chapter 1"]),
Data("SKM-R330GG Cracker-FL", rules=[""], depends=["Chapter 1"]),
Data("SHM-R620SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX350SA F-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R730SA F-Wave", rules=[""], depends=["Chapter 1"]),
Data("SAM-M110ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350GG Cracker-FL", rules=[""], depends=["Chapter 1"]),
Data("SHM-R630SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX350SA F-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R750SA F-Wave", rules=[""], depends=["Chapter 1"]),
Data("SAM-M120ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R330GG Cracker-FL", rules=[""], depends=["Chapter 1"]),
Data("SHM-R650SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX350SA F-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R730SA F-Wave", rules=[""], depends=["Chapter 1"]),
Data("SAM-M140ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350GG Cracker-FL", rules=[""], depends=["Chapter 1"]),
Data("SHM-R620SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX330SA F2-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R750SA F-Wave", rules=[""], depends=["Chapter 1"]),
Data("SAM-M110ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350ME Cracker-PD", rules=[""], depends=["Chapter 1"]),
Data("SHM-R630SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX350SA F2-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R730SA F-Wave", rules=[""], depends=["Chapter 1"]),
Data("SAM-M120ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350ME Cracker-PD", rules=[""], depends=["Chapter 1"]),
Data("SHM-R650SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX330SA F2-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R750SA F-Wave", rules=[""], depends=["Chapter 1"]),
Data("SAM-M140ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("SKM-R350ME Cracker-PD", rules=[""], depends=["Chapter 1"]),
Data("SHM-R620SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX350SA F2-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130GG P-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SAM-M110ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R630SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX330SA F2-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150GG P-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SAM-M120ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R650SA Shotgun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX350SA F2-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130GG P-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SAM-M140ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R730SA Sniper", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX430SA B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150GG P-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SAM-M111ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Sniper", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX450SA B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130GG P-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SAM-M121ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R730SA Sniper", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX430SA B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150GG P-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SAM-M141ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Sniper", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX450SA B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R220GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M111ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R730SA Sniper", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX430SA B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R230GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M121ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Sniper", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX450SA B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M141ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Firegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX450SA B2-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R220GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M111ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Firegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX450SA B2-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R230GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M121ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R750SA Firegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX450SA B2-Gatling", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M141ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R820SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX550SA M-Sniper", rules=[""], depends=["Chapter 1"]),
Data("SRM-R220GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M142ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R830SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX550SA M-Sniper", rules=[""], depends=["Chapter 1"]),
Data("SRM-R230GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M142ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R850SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-RX550SA M-Sniper", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250GG Lasergun", rules=[""], depends=["Chapter 1"]),
Data("SAM-M142ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R820SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R130GG M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R330GG H-Arrow", rules=[""], depends=["Chapter 1"]),
Data("SAM-M123ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R830SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150GG M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R350GG H-Arrow", rules=[""], depends=["Chapter 1"]),
Data("SAM-M143ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R850SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R130GG M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R330GG H-Arrow", rules=[""], depends=["Chapter 1"]),
Data("SAM-M123ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R820SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150GG M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R350GG H-Arrow", rules=[""], depends=["Chapter 1"]),
Data("SAM-M143ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R830SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R130GG M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R330GG H-Arrow", rules=[""], depends=["Chapter 1"]),
Data("SAM-M123ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R850SA L-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150GG M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R350GG H-Arrow", rules=[""], depends=["Chapter 1"]),
Data("SAM-M143ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R950SA E-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R230GG Voltstorm", rules=[""], depends=["Chapter 1"]),
Data("SRM-M120GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M124ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R950SA E-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250GG Voltstorm", rules=[""], depends=["Chapter 1"]),
Data("SRM-M130GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M144ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1020SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R230GG Voltstorm", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M124ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1030SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250GG Voltstorm", rules=[""], depends=["Chapter 1"]),
Data("SRM-M120GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M144ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1050SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R230GG Voltstorm", rules=[""], depends=["Chapter 1"]),
Data("SRM-M130GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M124ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1020SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250GG Voltstorm", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M144ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1030SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350GG SHD-Gravity", rules=[""], depends=["Chapter 1"]),
Data("SRM-M120GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M145ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1050SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350GG SHD-Gravity", rules=[""], depends=["Chapter 1"]),
Data("SRM-M130GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M145ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1020SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350GG SHD-Gravity", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150GG Javelin", rules=[""], depends=["Chapter 1"]),
Data("SAM-M145ME Beam-Shield", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1030SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R420GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R430GG Phoenix", rules=[""], depends=["Chapter 1"]),
Data("SAM-R130ME Needlegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-R1050SA Wiregun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R430GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R450GG Phoenix", rules=[""], depends=["Chapter 1"]),
Data("SAM-R150ME Needlegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M130GG P-Knife", rules=[""], depends=["Chapter 1"]),
Data("SSM-R450GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R430GG Phoenix", rules=[""], depends=["Chapter 1"]),
Data("SAM-R130ME Needlegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M150GG P-Knife", rules=[""], depends=["Chapter 1"]),
Data("SSM-R420GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R450GG Phoenix", rules=[""], depends=["Chapter 1"]),
Data("SAM-R150ME Needlegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M130GG P-Knife", rules=[""], depends=["Chapter 1"]),
Data("SSM-R430GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R430GG Phoenix", rules=[""], depends=["Chapter 1"]),
Data("SAM-R130ME Needlegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M150GG P-Knife", rules=[""], depends=["Chapter 1"]),
Data("SSM-R450GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R450GG Phoenix", rules=[""], depends=["Chapter 1"]),
Data("SAM-R150ME Needlegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SHM-M130GG P-Knife", rules=[""], depends=["Chapter 1"]),
Data("SSM-R420GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R530GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150GG P-Knife", rules=[""], depends=["Chapter 1"]),
Data("SSM-R430GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R550GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M250GG B-Claw", rules=[""], depends=["Chapter 1"]),
Data("SSM-R450GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R530GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M250GG B-Claw", rules=[""], depends=["Chapter 1"]),
Data("SSM-R451GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R550GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M250GG B-Claw", rules=[""], depends=["Chapter 1"]),
Data("SSM-R451GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R530GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130GG HB-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R451GG Antipulser", rules=[""], depends=["Chapter 1"]),
Data("SRM-R550GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150GG HB-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R530GG Drone", rules=[""], depends=["Chapter 1"]),
Data("SRM-R531GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130GG HB-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R550GG Drone", rules=[""], depends=["Chapter 1"]),
Data("SRM-R551GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150GG HB-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R530GG Drone", rules=[""], depends=["Chapter 1"]),
Data("SRM-R531GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130GG HB-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R550GG Drone", rules=[""], depends=["Chapter 1"]),
Data("SRM-R551GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150GG HB-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R530GG Drone", rules=[""], depends=["Chapter 1"]),
Data("SRM-R531GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250GG Diskbomb", rules=[""], depends=["Chapter 1"]),
Data("SSM-R550GG Drone", rules=[""], depends=["Chapter 1"]),
Data("SRM-R551GG F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250GG Diskbomb", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150ME M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130ME B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250GG Diskbomb", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150ME M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150ME B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M130ME Heat-Edge", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150ME M-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130ME B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME Heat-Edge", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250ME Widebeam", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150ME B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M130ME Heat-Edge", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250ME Widebeam", rules=[""], depends=["Chapter 1"]),
Data("SRM-R130ME B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME Heat-Edge", rules=[""], depends=["Chapter 1"]),
Data("SSM-R250ME Widebeam", rules=[""], depends=["Chapter 1"]),
Data("SRM-R150ME B-Gatling", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M130ME Heat-Edge", rules=[""], depends=["Chapter 1"]),
Data("SSM-R330ME SHD-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250ME S-Missile", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME Heat-Edge", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350ME SHD-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250ME S-Missile", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME B-Centipede", rules=[""], depends=["Chapter 1"]),
Data("SSM-R330ME SHD-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-R250ME S-Missile", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME B-Centipede", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350ME SHD-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150ME Dragon", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-M150ME B-Centipede", rules=[""], depends=["Chapter 1"]),
Data("SSM-R330ME SHD-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150ME Dragon", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130ME Bladegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-R350ME SHD-Missile", rules=[""], depends=["Chapter 1"]),
Data("SRM-M150ME Dragon", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150ME Bladegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-M120ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M230ME W-Crusher", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130ME Bladegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-M130ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M250ME W-Crusher", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150ME Bladegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-M150ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M230ME W-Crusher", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R130ME Bladegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-M120ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M250ME W-Crusher", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R150ME Bladegun", rules=[""], depends=["Chapter 1"]),
Data("SSM-M130ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M230ME W-Crusher", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R230ME B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-M150ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M250ME W-Crusher", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250ME B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-M120ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M330ME BB-Sword", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R230ME B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-M130ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M350ME BB-Sword", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250ME B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-M150ME Heathorn", rules=[""], depends=["Chapter 1"]),
Data("SRM-M330ME BB-Sword", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R230ME B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150ME N-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SRM-M350ME BB-Sword", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R250ME B-Rifle", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150ME N-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SRM-M330ME BB-Sword", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R350ME B-Sniper", rules=[""], depends=["Chapter 1"]),
Data("SSM-R150ME N-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SRM-M350ME BB-Sword", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R350ME B-Sniper", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R550ME Meteor", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R350ME B-Sniper", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R550ME Meteor", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R420ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R550ME Meteor", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R430ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R650ME L-Missile", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R450ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R650ME L-Missile", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R420ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R650ME L-Missile", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R430ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R720ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R450ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R730ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R420ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R750ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R430ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R720ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R450ME Firegun", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R730ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R421SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R750ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R431SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R720ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R451SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R730ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R421SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R750ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R431SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R721ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R451SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R731ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R421SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R751ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R431SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R721ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R451SA Short-Rifle", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R731ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R752SA E-Sniper", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R751ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("SHM-R752SA E-Sniper", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("SRM-R721ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R731ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R751ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R752ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R752ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R752ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R733ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R753ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R733ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R753ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R733ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R753ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R734ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R754ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R734ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R754ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R734ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R754ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R755ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R755ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R755ME F-Wave", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R430ME Backbomb", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R450ME Backbomb", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R430ME Backbomb", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R450ME Backbomb", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R430ME Backbomb", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("", valid=False),
Data("SRM-R450ME Backbomb", rules=[""], depends=["Chapter 1"]),
Data("", valid=False),
Data("", valid=False),
]
