from . import Loc as Data

# flake8: noqa
# https://xenoblade.github.io/xbx/bdat/common_local_us/ITM_Blueprint.html
shop_blueprints_data: list[Data] = [
Data("Archetype Sword", rules=[""], depends=["Chapter 1"]),
Data("Archetype Slair II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Sword II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Blades", rules=[""], depends=["Chapter 1"]),
Data("Archetype Ralzes", rules=[""], depends=["Chapter 1"]),
Data("Archetype Blades II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Knife III", rules=[""], depends=["Chapter 1"]),
Data("Archetype Riv", rules=[""], depends=["Chapter 1"]),
Data("Archetype Knife II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Paive", rules=[""], depends=["Chapter 1"]),
Data("Archetype Shield", rules=[""], depends=["Chapter 1"]),
Data("Advanced Archetype Paive", rules=[""], depends=["Chapter 1"]),
Data("Archetype Spear", rules=[""], depends=["Chapter 1"]),
Data("Archetype Parce", rules=[""], depends=["Chapter 1"]),
Data("Archetype Spear II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Fulge", rules=[""], depends=["Chapter 1"]),
Data("Archetype Saber", rules=[""], depends=["Chapter 1"]),
Data("Archetype Fulge II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Assault Rifle III", rules=[""], depends=["Chapter 1"]),
Data("Archetype Avagar", rules=[""], depends=["Chapter 1"]),
Data("Archetype Assault Rifle II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Dual Guns", rules=[""], depends=["Chapter 1"]),
Data("Archetype Gemels", rules=[""], depends=["Chapter 1"]),
Data("Archetype Dual Guns II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Lastyr II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Raygun", rules=[""], depends=["Chapter 1"]),
Data("Archetype Lastyr III", rules=[""], depends=["Chapter 1"]),
Data("Archetype Machine", rules=[""], depends=["Chapter 1"]),
Data("Archetype Repethe", rules=[""], depends=["Chapter 1"]),
Data("Archetype Machine II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Sniper Rifle", rules=[""], depends=["Chapter 1"]),
Data("Archetype Retic", rules=[""], depends=["Chapter 1"]),
Data("Archetype Sniper Rifle II", rules=[""], depends=["Chapter 1"]),
Data("Archetype Psylans", rules=[""], depends=["Chapter 1"]),
Data("Archetype Launchers", rules=[""], depends=["Chapter 1"]),
Data("Advanced Archetype Psylans", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Glaive", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Glaive II", rules=[""], depends=["Chapter 1"]),
Data("Original Twins", rules=[""], depends=["Chapter 1"]),
Data("Original Watxes", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Edges II", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Edges", rules=[""], depends=["Chapter 1"]),
Data("Original Pokepoke", rules=[""], depends=["Chapter 1"]),
Data("Original Iyst", rules=[""], depends=["Chapter 1"]),
Data("Original Iyst II", rules=[""], depends=["Chapter 1"]),
Data("Original Haven", rules=[""], depends=["Chapter 1"]),
Data("Original Haven II", rules=[""], depends=["Chapter 1"]),
Data("Original Thudclang", rules=[""], depends=["Chapter 1"]),
Data("Original Bolide", rules=[""], depends=["Chapter 1"]),
Data("Original Jyth", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Lance", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Lightblade", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Lightblade II", rules=[""], depends=["Chapter 1"]),
Data("Original Assailer", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Raidrifle", rules=[""], depends=["Chapter 1"]),
Data("Original Dyads", rules=[""], depends=["Chapter 1"]),
Data("Original Dyads III", rules=[""], depends=["Chapter 1"]),
Data("Original Dyads II", rules=[""], depends=["Chapter 1"]),
Data("Original Bangbangs", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Sidearm", rules=[""], depends=["Chapter 1"]),
Data("Original Strobe", rules=[""], depends=["Chapter 1"]),
Data("Original Crank", rules=[""], depends=["Chapter 1"]),
Data("Original Ratatatta", rules=[""], depends=["Chapter 1"]),
Data("Original Ziyse", rules=[""], depends=["Chapter 1"]),
Data("Original Trigger", rules=[""], depends=["Chapter 1"]),
Data("Original Thwipper", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Deadsight", rules=[""], depends=["Chapter 1"]),
Data("Masterstroke Deadsight II", rules=[""], depends=["Chapter 1"]),
Data("Original Saboteurs", rules=[""], depends=["Chapter 1"]),
Data("Original Fwooshers", rules=[""], depends=["Chapter 1"]),
Data("Original Zorcyses", rules=[""], depends=["Chapter 1"]),
Data("3276", valid=False),
Data("3277", valid=False),
Data("3278", valid=False),
Data("3279", valid=False),
Data("3280", valid=False),
Data("3281", valid=False),
Data("Six Stars Ritual Bodywear", rules=[""], depends=["Chapter 1"]),
Data("Six Stars Ritual Band R", rules=[""], depends=["Chapter 1"]),
Data("Six Stars Ritual Band L", rules=[""], depends=["Chapter 1"]),
Data("Six Stars Ritual Legwear", rules=[""], depends=["Chapter 1"]),
Data("Supercivilization Attire", rules=[""], depends=["Chapter 1"]),
Data("Elite Supercivilization Attire", rules=[""], depends=["Chapter 1"]),
Data("Black Bunnyband", rules=[""], depends=["Chapter 1"]),
Data("Red Bunnyband", rules=[""], depends=["Chapter 1"]),
Data("White Bunnyband", rules=[""], depends=["Chapter 1"]),
Data("Bunnytop", rules=[""], depends=["Chapter 1"]),
Data("Bunnycuff R", rules=[""], depends=["Chapter 1"]),
Data("Bunnycuff L", rules=[""], depends=["Chapter 1"]),
Data("Bunnyhoppers", rules=[""], depends=["Chapter 1"]),
Data("Bunnybod", rules=[""], depends=["Chapter 1"]),
Data("Bunnylink R", rules=[""], depends=["Chapter 1"]),
Data("Bunnylink L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Comm", rules=[""], depends=["Chapter 1"]),
Data("Reginal Plastron", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bangle R", rules=[""], depends=["Chapter 1"]),
Data("Reginal Bangle L", rules=[""], depends=["Chapter 1"]),
Data("Reginal Cords", rules=[""], depends=["Chapter 1"]),
Data("Regal Comm", rules=[""], depends=["Chapter 1"]),
Data("Regal Plastron", rules=[""], depends=["Chapter 1"]),
Data("Regal Bangle R", rules=[""], depends=["Chapter 1"]),
Data("Regal Bangle L", rules=[""], depends=["Chapter 1"]),
Data("Regal Cords", rules=[""], depends=["Chapter 1"]),
Data("Infinite Comm", rules=[""], depends=["Chapter 1"]),
Data("Infinite Plastron", rules=[""], depends=["Chapter 1"]),
Data("Infinite Bangle R", rules=[""], depends=["Chapter 1"]),
Data("Infinite Bangle L", rules=[""], depends=["Chapter 1"]),
Data("Infinite Cords", rules=[""], depends=["Chapter 1"]),
Data("True Comm", rules=[""], depends=["Chapter 1"]),
Data("True Plastron", rules=[""], depends=["Chapter 1"]),
Data("True Bangle R", rules=[""], depends=["Chapter 1"]),
Data("True Bangle L", rules=[""], depends=["Chapter 1"]),
Data("True Cords", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP140SA Hexad-Partican", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP160SA Hexad-Partican", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP180SA Hexad-Partican", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP240SA Zenith-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP260SA Zenith-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP280SA Zenith-Cannon", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP340GG Zweihand-Q", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP360GG Zweihand-Q", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP380GG Zweihand-Q", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP440ME Trident-Anchor", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP460ME Trident-Anchor", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP480ME Trident-Anchor", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP540GG Electric-Flood", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP560GG Electric-Flood", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP580GG Electric-Flood", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP640ME Voltaic-Tusk", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP660ME Voltaic-Tusk", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP680ME Voltaic-Tusk", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP740SA Antimatter-R", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP760SA Antimatter-R", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP780SA Antimatter-R", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP840SA G-Piledriver", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP860SA G-Piledriver", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP880SA G-Piledriver", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP940GG Dragoon-Lance", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP960GG Dragoon-Lance", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP980GG Dragoon-Lance", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP1040GG Drone-Storm", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP1060GG Drone-Storm", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP1080GG Drone-Storm", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1140SA Deus-Crusher", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1160SA Deus-Crusher", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1180SA Deus-Crusher", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1240ME Barrage-Cloak", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1260ME Barrage-Cloak", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1280ME Barrage-Cloak", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP1340SA Detonation-F", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP1360SA Detonation-F", rules=[""], depends=["Chapter 1"]),
Data("SRM-USP1380SA Detonation-F", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1440SA Megaflame-B", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1460SA Megaflame-B", rules=[""], depends=["Chapter 1"]),
Data("SSM-USP1480SA Megaflame-B", rules=[""], depends=["Chapter 1"]),
Data("91", valid=False),
Data("Formula Zero", rules=[""], depends=["Chapter 1"]),
Data("118", valid=False),
Data("Urban Lincoln", rules=[""], depends=["Chapter 1"]),
Data("152", valid=False),
Data("Verus Cain", rules=[""], depends=["Chapter 1"]),
Data("186", valid=False),
Data("Lailah Queen", rules=[""], depends=["Chapter 1"]),
Data("220", valid=False),
Data("Inferno Skydon", rules=[""], depends=["Chapter 1"]),
Data("251", valid=False),
Data("Mastema Reaper", rules=[""], depends=["Chapter 1"]),
Data("282", valid=False),
Data("Amdusias Hades", rules=[""], depends=["Chapter 1"]),
Data("284", valid=False),
Data("Ares 70", rules=[""], depends=["Chapter 1"]),
Data("Ares 90", rules=[""], depends=["Chapter 1"]),
Data("Police", rules=[""], depends=["Chapter 1"]),
Data("Dozer", rules=[""], depends=["Chapter 1"]),
Data("Excavator", rules=[""], depends=["Chapter 1"]),
Data("Delta Bliss", rules=[""], depends=["Chapter 1"])
]
