from BaseClasses import Item, ItemClassification

class XenobladeXItem(Item):
    game: str = "XenobladeX"

# Specifies the items you can receive
# The first layer is for the object group
# The second one is for the items itself
# Use a dict to specifiy extra parameters
xenobladeXItems = {
    "Key": {
        "Skell License": {"class": ItemClassification.progression}, 
        "Skell Flight Module": {"class": ItemClassification.progression}, 
        "Frontier Nav": {"class": ItemClassification.progression}, 
        "BLADE Terminal": {"class": ItemClassification.progression}, 
        "Overdrive": {}, 
        "Shop Terminal": {}, 
        "Ls Shop": {}, 
        "AM Terminal": {},
		"Filler": {}, 
    },
    "Field Skill": {
        "Mechanical": {"count": 4, "class": ItemClassification.progression},
        "Biological": {"count": 4, "class": ItemClassification.progression},
        "Archaeological": {"count": 4, "class": ItemClassification.progression},
    },
    "Skell": {
        "Urban 20": {"class": ItemClassification.progression},
		"Formula 30": {},
		"Urban 30": {},
		"Verus 30": {},
		"Lailah 30": {},
		"Inferno 30": {},
		"Mastema 30": {},
		"Amdusias 30": {},
		"Formula 50": {},
		"Urban 50": {},
		"Verus 50": {},
		"Lailah 50": {},
		"Inferno 50": {},
		"Mastema 50": {},
		"Amdusias 50": {},
		"Formula Zero": {},
		"Urban Lincoln": {},
		"Verus Cain": {},
		"Lailah Queen": {},
		"Inferno Skydon": {},
		"Mastema White Reaper": {},
		"Amdusias Hades": {},
		"Ares 70": {},
		"Ares 90": {},
		"Dozer": {},
		"Excavator": {},
		"Police": {},
    },
    "Skell Weapon": {
		"M1x0SA Rod": {},
		"M2x0SA Sword": {},
		"M3x0SA E-Sword": {},
		"M4x0SA Pile-Bunker": {},
		"R1x0SA Machinegun": {},
		"R2x0SA E-Machinegun": {},
		"R3x0SA Assault": {},
		"R4x0SA B-Rifle": {},
		"R4x1SA Short-Rifle": {},
		"R5x0SA E-Rifle": {},
		"R6x0SA Shotgun": {},
		"R7x0SA Sniper": {},
		"R7x2SA E-Sniper": {},
		"R8x0SA Firegun": {},
		"R9x0SA L-Cannon": {},
		"R10x0SA E-Cannon": {},
		"R11x0SA Wiregun": {},
		"M1x0GG P-Knife": {},
		"M2x0GG B-Claw": {},
		"R1x0GG HB-Rifle": {},
		"R2x0GG Diskbomb": {},
		"M1x0ME Heat-Edge": {},
		"M2x0ME B-Centipede": {},
		"R1x0ME Bladegun": {},
		"R2x0ME B-Rifle": {},
		"ARES-DW01x0 M-BLADE": {},
		"ARES-DW01x0 M-BLASTER": {},
		"M1x0SA Buster": {},
		"R1x0SA Railgun": {},
		"R2x0SA S-Missile": {},
		"R3x0SA Voltnet": {},
		"R4x0SA Grenade": {},
		"R5x0SA Hyper-Rail": {},
		"R6x0SA Buster-Launcher": {},
		"R6x0SA L-Missile": {},
		"R7x0SA F-Wave": {},
		"M1x0GG Javelin": {},
		"R1x0GG P-Cannon": {},
		"R2x0GG Lasergun": {},
		"R3x0GG H-Arrow": {},
		"R4x0GG Phoenix": {},
		"R5x0GG F-Wave": {},
		"R5x1GG F-Wave": {},
		"M1x0ME Dragon": {},
		"M2x0ME W-Crusher": {},
		"M3x0ME BB-Sword": {},
		"R1x0ME B-Gatling": {},
		"R2x0ME S-Missile": {},
		"R4x0ME Backbomb": {},
		"R5x0ME Meteor": {},
		"R6x0ME L-Missile": {},
		"R7x0ME F-Wave": {},
		"R7x1ME F-Wave": {},
		"R7x2ME F-Wave": {},
		"R7x3ME F-Wave": {},
		"R7x4ME F-Wave": {},
		"R7x5ME F-Wave": {},
		"XR1x0GA V-Beam": {},
		"XR2x0GA T-Claw": {},
		"XR5x0GA R-Cannon": {},
		"XR21x0GA Rail-Gun": {},
		"XR22x0GA M-Laser": {},
		"XR3x0LA A-Spear": {},
		"ARES-SP02x0 AVATARA": {},
		"ARES-SP02x0 AGNI": {},
		"USP1x0SA Hexad-Partican": {},
		"USP2x0SA Zenith-Cannon": {},
		"USP3x0GG Zweihander-Q": {},
		"USP4x0ME Trident-Anchor": {},
		"USP7x0SA Antimatter-R": {},
		"USP8x0SA G-Piledriver": {},
		"USP9x0GG Dragoon-Lance": {},
		"USP10x0GG Drone-Storm": {},
		"USP13x0SA Detonation-F": {},
		"MX1x0SA G-Buster": {},
		"MX1x0SA G2-Buster": {},
		"MX2x0SA E-Scythe": {},
		"R1x0SA M-Missile": {},
		"R2x0SA HB-Missile": {},
		"R2x0SA F-Grenade": {},
		"R3x0SA SHD-Gatling": {},
		"R4x0SA SHD-Ray": {},
		"R5x0SA Chaingun": {},
		"RX3x0SA F-Rifle": {},
		"RX3x0SA F2-Rifle": {},
		"RX4x0SA B-Gatling": {},
		"RX4x0SA B2-Gatling": {},
		"RX5x0SA M-Sniper": {},
		"R1x0GG M-Missile": {},
		"R2x0GG Voltstorm": {},
		"R3x0GG SHD-Gravity": {},
		"R4x0GG Antipulser": {},
		"R4x1GG Antipulser": {},
		"R5x0GG Drone": {},
		"M1x0ME Heathorn": {},
		"R1x0ME M-Missile": {},
		"R1x0ME N-Cannon": {},
		"R2x0ME Widebeam": {},
		"R3x0ME SHD-Missile": {},
		"XR3x0GA H-Missile": {},
		"XR4x0GA G-Revolver": {},
		"XR6x0R Night-Cage": {},
		"XR7x0GA M-Missile": {},
		"XR23x0GA Spine-Cannon": {},
		"XR24x0GA E-Bubble": {},
		"XR25x0GA B-Bomb": {},
		"XR1x0LA L-Cannon": {},
		"XR2x0LA F-Arrow": {},
		"ARES-SP01x0 VAJRA": {},
		"ARES-SP02x0 AGHASURA": {},
		"USP5x0GG Electric-Flood": {},
		"USP6x0ME Voltaic-Tusk": {},
		"USP11x0SA Deus-Crusher": {},
		"USP12x0ME Barrage-Cloak": {},
		"USP14x0SA Megaflame-B": {},
		"M1x0SA Shield": {},
		"M1x1SA Shield": {},
		"M1x2SA Shield": {},
		"M1x3SA Shield": {},
		"M1x4SA Shield": {},
		"M1x5SA Shield": {},
		"S1x0SA Minigun": {},
		"M1x0ME Beam-Shield": {},
		"M1x1ME Beam-Shield": {},
		"M1x2ME Beam-Shield": {},
		"M1x3ME Beam-Shield": {},
		"M1x4ME Beam-Shield": {},
		"M1x5ME Beam-Shield": {},
		"R1x0ME Needlegun": {},
		"M1x0SA Beamsaber": {},
		"M2x0SA V-Knuckle": {},
		"R3x0SA Cracker-BM": {},
		"M1x0GG Ringedge": {},
		"R3x0GG Cracker-FL": {},
		"Mx10ME Falchion": {},
		"M2x0ME Claymore": {},
		"M3x0ME Katar": {},
		"R3x0ME Cracker-PD": {},
    },
    "Skell Superweapon": {
		"SRM-USP140SA Hexad-Partican": {},
		"SRM-USP160SA Hexad-Partican": {},
		"SRM-USP180SA Hexad-Partican": {},
		"SRM-USP240SA Zenith-Cannon": {},
		"SRM-USP260SA Zenith-Cannon": {},
		"SRM-USP280SA Zenith-Cannon": {},
		"SRM-USP340GG Zweihand-Q": {},
		"SRM-USP360GG Zweihand-Q": {},
		"SRM-USP380GG Zweihand-Q": {},
		"SRM-USP440ME Trident-Anchor": {},
		"SRM-USP460ME Trident-Anchor": {},
		"SRM-USP480ME Trident-Anchor": {},
		"SSM-USP540GG Electric-Flood": {},
		"SSM-USP560GG Electric-Flood": {},
		"SSM-USP580GG Electric-Flood": {},
		"SSM-USP640ME Voltaic-Tusk": {},
		"SSM-USP660ME Voltaic-Tusk": {},
		"SSM-USP680ME Voltaic-Tusk": {},
		"SRM-USP740SA Antimatter-R": {},
		"SRM-USP760SA Antimatter-R": {},
		"SRM-USP780SA Antimatter-R": {},
		"SRM-USP840SA G-Piledriver": {},
		"SRM-USP860SA G-Piledriver": {},
		"SRM-USP880SA G-Piledriver": {},
		"SRM-USP940GG Dragoon-Lance": {},
		"SRM-USP960GG Dragoon-Lance": {},
		"SRM-USP980GG Dragoon-Lance": {},
		"SRM-USP1040GG Drone-Storm": {},
		"SRM-USP1060GG Drone-Storm": {},
		"SRM-USP1080GG Drone-Storm": {},
		"SSM-USP1140SA Deus-Crusher": {},
		"SSM-USP1160SA Deus-Crusher": {},
		"SSM-USP1180SA Deus-Crusher": {},
		"SSM-USP1240ME Barrage-Cloak": {},
		"SSM-USP1260ME Barrage-Cloak": {},
		"SSM-USP1280ME Barrage-Cloak": {},
		"SRM-USP1340SA Detonation-F": {},
		"SRM-USP1360SA Detonation-F": {},
		"SRM-USP1380SA Detonation-F": {},
		"SSM-USP1440SA Megaflame-B": {},
		"SSM-USP1460SA Megaflame-B": {},
		"SSM-USP1480SA Megaflame-B": {},
    },
    "Augment": {
		"Appendage Crusher": {},
		"Brimstone Rain Screen": {},
		"Custom.WP-M-GP": {},
		"Custom.WP-MAG-M": {},
		"Custom.WP-MAG-R": {},
		"Custom.WP-R-GP": {},
		"EM Storm Screen": {},
		"Energy Mist Screen": {},
		"Extend Physical Resistance Down": {},
		"Fog Screen": {},
		"Heat Wave Screen": {},
		"Heavy Rain Screen": {},
		"Melee: TP Gain Up": {},
		"Overdrive Blue Bonus": {},
		"Overdrive Green Bonus": {},
		"Rain Screen": {},
		"Ranged: TP Gain Up": {},
		"Reflect.P-Beam": {},
		"Reflect.P-Electric": {},
		"Reflect.P-Ether": {},
		"Reflect.P-Gravity": {},
		"Reflect.P-Physical": {},
		"Reflect.P-Thermal": {},
		"Reflect: Beam": {},
		"Reflect: Electric": {},
		"Reflect: Ether": {},
		"Reflect: Gravity": {},
		"Reflect: Physical": {},
		"Reflect: Thermal": {},
		"Rising Energy Mist Screen": {},
		"Sandstorm Screen": {},
		"Spore Screen": {},
		"Thunderstorm Screen": {},
		"Weather.E-MIST-RES": {},
		"Weather.EM-STORM-RES": {},
		"Weather.FOG-RES": {},
		"Weather.HEAVY-RAIN-RES": {},
		"Weather.RISING-E-MIST-RES": {},
		"Weather.S-STORM-RES": {},
		"Weather.SPORE-RES": {},
		"Antispike I V X XV XX": {},
		"AppendLost.ATK-UP I V X XV XX": {},
		"AppendLost.EVA-UP I V X XV XX": {},
		"AppendLost.GP I V X XV XX": {},
		"Artful Execution Surge I V X XV XX": {},
		"Arts Draw Surge I V X XV XX": {},
		"Arts.GP I V X XV XX": {},
		"Arts: Gain TP I V X XV XX": {},
		"Arts: Recover HP I V X XV XX": {},
		"AttribueDmg.PHYS I V X XV XX": {},
		"AttributeDmg.BEAM I V X XV XX": {},
		"AttributeDmg.ELEC I V X XV XX": {},
		"AttributeDmg.ETHER I V X XV XX": {},
		"AttributeDmg.GRAV I V X XV XX": {},
		"AttributeDmg.PHYS I V X XV XX": {},
		"AttributeDmg.THERM I V X XV XX": {},
		"Aura Rapid Cooldown I V X XV XX": {},
		"Aura Surge I V X XV XX": {},
		"Aura: Refuel I V X XV XX": {},
		"Aural Cloaking I V X XV XX": {},
		"Back Attack Plus I V X XV XX": {},
		"Beam Attack Plus I V X XV XX": {},
		"Beam Resistance Up I V X XV XX": {},
		"Bind: Refuel I V X XV XX": {},
		"Boost.EVA I V X XV XX": {},
		"Boost.HP-MAX I V X XV XX": {},
		"Boost.M-ACC I V X XV XX": {},
		"Boost.M-ATK I V X XV XX": {},
		"Boost.PTL I V X XV XX": {},
		"Boost.R-ACC I V X XV XX": {},
		"Boost.R-ATK I V X XV XX": {},
		"Chimeroid Criticals Up I V X XV XX": {},
		"Chimeroid Slayer I V X XV XX": {},
		"Cloak.SIGHT I V X XV XX": {},
		"Cloak.SOUND I V X XV XX": {},
		"Cooldown Reducer I V X XV XX": {},
		"Critical Chance Up I V X XV XX": {},
		"Critical Surge I V X XV XX": {},
		"CriticalUp I V X XV XX": {},
		"CritUp.CHIMEROID I V X XV XX": {},
		"CritUp.HUMANOID I V X XV XX": {},
		"CritUp.INSECTOID I V X XV XX": {},
		"CritUp.MECHANOID I V X XV XX": {},
		"CritUp.PISCINOID I V X XV XX": {},
		"CritUp.THEROID I V X XV XX": {},
		"CritUp.ULTRAFAUNA I V X XV XX": {},
		"Crush Surge I V X XV XX": {},
		"Crush.APPEND I V X XV XX": {},
		"Crush.GP I V X XV XX": {},
		"Crush: Gain TP I V X XV XX": {},
		"Custom.WP-ATK I V X XV XX": {},
		"Custom.WP-DESTABLE I V X XV XX": {},
		"Custom.WP-FUEL I V X XV XX": {},
		"Custom.WP-R-RANGE I V X XV XX": {},
		"Custom.WP-SPEED I V X XV XX": {},
		"Custom.WP-STABLE I V X XV XX": {},
		"CutTime.DEBUFF I V X XV XX": {},
		"Damage.APPEND I V X XV XX": {},
		"Damage.GP-GAIN I V X XV XX": {},
		"Danger Surge I V X XV XX": {},
		"Debuff Suppressor I V X XV XX": {},
		"Destabilizer I V X XV XX": {},
		"Draw.OPENING-DMG I V X XV XX": {},
		"Electric Attack Plus I V X XV XX": {},
		"Electric Resistance Up I V X XV XX": {},
		"Ether Attack Plus I V X XV XX": {},
		"Ether Resistance Up I V X XV XX": {},
		"Evasion Boost I V X XV XX": {},
		"Evasion Drive I V X XV XX": {},
		"Evasion Up I V X XV XX": {},
		"EXP Boost I V X XV XX": {},
		"Extend Aura I V X XV XX": {},
		"Extend Beam Resistance Down I V X XV XX": {},
		"Extend Blackout I V X XV XX": {},
		"Extend Blaze I V X XV XX": {},
		"Extend Control I V X XV XX": {},
		"Extend Critical Power I V X XV XX": {},
		"Extend Debuff Resistance Down I V X XV XX": {},
		"Extend Electric Resistance Down I V X XV XX": {},
		"Extend Ether Resistance Down I V X XV XX": {},
		"Extend Fatigue I V X XV XX": {},
		"Extend Gravity Resistance Down I V X XV XX": {},
		"Extend Overdrive I V X XV XX": {},
		"Extend Physical Resistance Down I V X XV XX": {},
		"Extend Shock I V X XV XX": {},
		"Extend Slow Arts I V X XV XX": {},
		"Extend Taunt I V X XV XX": {},
		"Extend Thermal Resistance Down I V X XV XX": {},
		"Extend Virus I V X XV XX": {},
		"Firing Range Up I V X XV XX": {},
		"Focused Evasion I V X XV XX": {},
		"Front Attack Plus I V X XV XX": {},
		"Fuel Efficiency Up I V X XV XX": {},
		"Gravity Attack Plus I V X XV XX": {},
		"Gravity Resistance Up I V X XV XX": {},
		"High Danger Surge I V X XV XX": {},
		"HP Rebound I V X XV XX": {},
		"Humanoid Criticals Up I V X XV XX": {},
		"Humanoid Slayer I V X XV XX": {},
		"Incapacitation Surge I V X XV XX": {},
		"Insectoid Criticals Up I V X XV XX": {},
		"Insectoid Slayer I V X XV XX": {},
		"Jamming I V X XV XX": {},
		"M-Auto.BEAM-DOWN I V X XV XX": {},
		"M-Auto.BLACKOUT I V X XV XX": {},
		"M-Auto.BLAZE I V X XV XX": {},
		"M-Auto.ELEC-DOWN I V X XV XX": {},
		"M-Auto.ETHER-DOWN I V X XV XX": {},
		"M-Auto.FATIGUE I V X XV XX": {},
		"M-Auto.GRAV-DOWN I V X XV XX": {},
		"M-Auto.HP-RECOV I V X XV XX": {},
		"M-Auto.PHYS-DOWN I V X XV XX": {},
		"M-Auto.SHOCK I V X XV XX": {},
		"M-Auto.THERM-DOWN I V X XV XX": {},
		"Magazine Capacity Up I V X XV XX": {},
		"Max GP Drive I V X XV XX": {},
		"Max HP Boost I V X XV XX": {},
		"Max HP Drive I V X XV XX": {},
		"Max HP Up I V X XV XX": {},
		"Max TP Boost I V X XV XX": {},
		"Max TP Up I V X XV XX": {},
		"Mechanoid Criticals Up I V X XV XX": {},
		"Mechanoid Slayer I V X XV XX": {},
		"Melee Accuracy Boost I V X XV XX": {},
		"Melee Accuracy Drive I V X XV XX": {},
		"Melee Accuracy Up I V X XV XX": {},
		"Melee Attack Boost I V X XV XX": {},
		"Melee Attack Drive I V X XV XX": {},
		"Melee Attack Up I V X XV XX": {},
		"Melee Draw Surge I V X XV XX": {},
		"Melee: Beam Resistance Down I V X XV XX": {},
		"Melee: Blackout I V X XV XX": {},
		"Melee: Blaze I V X XV XX": {},
		"Melee: Electric Resistance Down I V X XV XX": {},
		"Melee: Ether Resistance Down I V X XV XX": {},
		"Melee: Fatigue I V X XV XX": {},
		"Melee: Gravity Resistance Down I V X XV XX": {},
		"Melee: Physical Resistance Down I V X XV XX": {},
		"Melee: Recover HP I V X XV XX": {},
		"Melee: Shock I V X XV XX": {},
		"Melee: Thermal Resistance Down I V X XV XX": {},
		"Night Vision I V X XV XX": {},
		"Night.MR-ACC I V X XV XX": {},
		"Nullify Beam Reflect I V X XV XX": {},
		"Nullify Electric Reflect I V X XV XX": {},
		"Nullify Ether Reflect I V X XV XX": {},
		"Nullify Gravity Reflect I V X XV XX": {},
		"Nullify Phys Reflect I V X XV XX": {},
		"Nullify Thermal Reflect I V X XV XX": {},
		"Opening Art: Damage Up I V X XV XX": {},
		"Overdrive Count Up I V X XV XX": {},
		"Overdrive Surge I V X XV XX": {},
		"Overdrive.APPEND-HP I V X XV XX": {},
		"Overdrive.EXTEND I V X XV XX": {},
		"Overdrive.FRAME-HP I V X XV XX": {},
		"Overdrive: Gain TP I V X XV XX": {},
		"Overdrive: Recover HP I V X XV XX": {},
		"Physical Attack Plus I V X XV XX": {},
		"Physical Resistance Up I V X XV XX": {},
		"Piscinoid Criticals Up I V X XV XX": {},
		"Piscinoid Slayer I V X XV XX": {},
		"PositionDmg.ABOVE I V X XV XX": {},
		"PositionDmg.BACK I V X XV XX": {},
		"PositionDmg.FRONT I V X XV XX": {},
		"PositionDmg.SIDE I V X XV XX": {},
		"Potential Boost I V X XV XX": {},
		"Potential Drive I V X XV XX": {},
		"Potential Up I V X XV XX": {},
		"Ranged Accuracy Boost I V X XV XX": {},
		"Ranged Accuracy Drive I V X XV XX": {},
		"Ranged Accuracy Up I V X XV XX": {},
		"Ranged Appendage Damage I V X XV XX": {},
		"Ranged Attack Boost I V X XV XX": {},
		"Ranged Attack Drive I V X XV XX": {},
		"Ranged Attack Up I V X XV XX": {},
		"Ranged Draw Surge I V X XV XX": {},
		"Reflect Damage Up I V X XV XX": {},
		"Reflect.DAMAGE-UP I V X XV XX": {},
		"Reflect.NEG-BEAM I V X XV XX": {},
		"Reflect.NEG-ELECTRIC I V X XV XX": {},
		"Reflect.NEG-ETHER I V X XV XX": {},
		"Reflect.NEG-GRAVITY I V X XV XX": {},
		"Reflect.NEG-PHYS I V X XV XX": {},
		"Reflect.NEG-THERMAL I V X XV XX": {},
		"Reinvigorate I V X XV XX": {},
		"Resist Beam Res Down I V X XV XX": {},
		"Resist Blackout I V X XV XX": {},
		"Resist Blaze I V X XV XX": {},
		"Resist Control I V X XV XX": {},
		"Resist Debuff Res Down I V X XV XX": {},
		"Resist Electric Res Down I V X XV XX": {},
		"Resist Ether Res Down I V X XV XX": {},
		"Resist Fatigue I V X XV XX": {},
		"Resist Flinch I V X XV XX": {},
		"Resist Gravity Res Down I V X XV XX": {},
		"Resist HP Recovery Down I V X XV XX": {},
		"Resist Knockback I V X XV XX": {},
		"Resist Launch I V X XV XX": {},
		"Resist Physical Res Down I V X XV XX": {},
		"Resist Shock I V X XV XX": {},
		"Resist Sleep I V X XV XX": {},
		"Resist Slow Arts I V X XV XX": {},
		"Resist Stagger I V X XV XX": {},
		"Resist Stun I V X XV XX": {},
		"Resist Taunt I V X XV XX": {},
		"Resist Thermal Res Down I V X XV XX": {},
		"Resist Time Bomb I V X XV XX": {},
		"Resist Topple I V X XV XX": {},
		"Resist Virus I V X XV XX": {},
		"Resist.BEAM-DOWN I V X XV XX": {},
		"Resist.BLACKOUT I V X XV XX": {},
		"Resist.BLAZE I V X XV XX": {},
		"Resist.CONTROL I V X XV XX": {},
		"Resist.DEBUFF-DOWN I V X XV XX": {},
		"Resist.ELEC-DOWN I V X XV XX": {},
		"Resist.ETHER-DOWN I V X XV XX": {},
		"Resist.FATIGUE I V X XV XX": {},
		"Resist.FLINCH I V X XV XX": {},
		"Resist.GRAV-DOWN I V X XV XX": {},
		"Resist.KNOCKBACK I V X XV XX": {},
		"Resist.LAUNCH I V X XV XX": {},
		"Resist.PHYS-DOWN I V X XV XX": {},
		"Resist.SHOCK I V X XV XX": {},
		"Resist.SLEEP I V X XV XX": {},
		"Resist.SLOW-ARTS I V X XV XX": {},
		"Resist.STAGGER I V X XV XX": {},
		"Resist.STUN I V X XV XX": {},
		"Resist.TAUNT I V X XV XX": {},
		"Resist.THERM-DOWN I V X XV XX": {},
		"Resist.TIME-BOMB I V X XV XX": {},
		"Resist.TOPPLE I V X XV XX": {},
		"Resist.VIRUS I V X XV XX": {},
		"Resistance Reducer I V X XV XX": {},
		"Secondary CD Reducer I V X XV XX": {},
		"Side Attack Plus I V X XV XX": {},
		"Slayer.CHIMEROID I V X XV XX": {},
		"Slayer.HUMANOID I V X XV XX": {},
		"Slayer.INSECTOID I V X XV XX": {},
		"Slayer.MECHANOID I V X XV XX": {},
		"Slayer.PISCINOID I V X XV XX": {},
		"Slayer.THEROID I V X XV XX": {},
		"Slayer.ULTRAFAUNA I V X XV XX": {},
		"Soft Touch I V X XV XX": {},
		"SpecUp.APP-HP I V X XV XX": {},
		"SpecUp.BEAM-RES I V X XV XX": {},
		"SpecUp.ELEC-RES I V X XV XX": {},
		"SpecUp.ETHER-RES I V X XV XX": {},
		"SpecUp.EVA I V X XV XX": {},
		"SpecUp.FUEL-BIND I V X XV XX": {},
		"SpecUp.FUEL-COST I V X XV XX": {},
		"SpecUp.FUEL-MAX I V X XV XX": {},
		"SpecUp.FUEL-OD I V X XV XX": {},
		"SpecUp.FUEL-PARK I V X XV XX": {},
		"SpecUp.GRAV-RES I V X XV XX": {},
		"SpecUp.HPMAX I V X XV XX": {},
		"SpecUp.M-ACC I V X XV XX": {},
		"SpecUp.M-ATK I V X XV XX": {},
		"SpecUp.PHYS-RES I V X XV XX": {},
		"SpecUp.PTL I V X XV XX": {},
		"SpecUp.R-ACC I V X XV XX": {},
		"SpecUp.R-ATK I V X XV XX": {},
		"SpecUp.THERM-RES I V X XV XX": {},
		"Spike.EVA I V X XV XX": {},
		"Stabilizer I V X XV XX": {},
		"Stun: Barrier I V X XV XX": {},
		"Stun: Decoy I V X XV XX": {},
		"Taunt: Barrier I V X XV XX": {},
		"Taunt: Decoy I V X XV XX": {},
		"Taunt: Supercharge I V X XV XX": {},
		"Terrain Damage Reducer I V X XV XX": {},
		"Thermal Attack Plus I V X XV XX": {},
		"Thermal Resistance Up I V X XV XX": {},
		"Theroid Criticals Up I V X XV XX": {},
		"Theroid Slayer I V X XV XX": {},
		"TimeEx.BEAM-DOWN I V X XV XX": {},
		"TimeEx.BLACKOUT I V X XV XX": {},
		"TimeEx.BLAZE I V X XV XX": {},
		"TimeEx.DEBUFF-DOWN I V X XV XX": {},
		"TimeEx.ELEC-DOWN I V X XV XX": {},
		"TimeEx.ETHER-DOWN I V X XV XX": {},
		"TimeEx.FATIGUE I V X XV XX": {},
		"TimeEx.GRAV-DOWN I V X XV XX": {},
		"TimeEx.PHYS-DOWN I V X XV XX": {},
		"TimeEx.SHOCK I V X XV XX": {},
		"TimeEx.SLEEP I V X XV XX": {},
		"TimeEx.SLOW-ARTS I V X XV XX": {},
		"TimeEx.TAUNT I V X XV XX": {},
		"TimeEx.THERM-DOWN I V X XV XX": {},
		"TimeEx.VIRUS I V X XV XX": {},
		"Topple: Barrier I V X XV XX": {},
		"Topple: Decoy I V X XV XX": {},
		"TP Rebound I V X XV XX": {},
		"Treasure Sensor I V X XV XX": {},
		"Ultrafauna Criticals Up I V X XV XX": {},
		"Ultrafauna Slayer I V X XV XX": {},
		"Underdog Surge I V X XV XX": {},
		"Untouchable Dash I V X XV XX": {},
		"Vantage Attack Plus I V X XV XX": {},
		"Vehicle.APPEND-DEF I V X XV XX": {},
		"Vehicle.DEBUFF-RES I V X XV XX": {},
		"Vehicle.FRAME-DEF I V X XV XX": {},
		"Visual Cloaking I V X XV XX": {},
		"Weapon Attack Power Up I V X XV XX": {},
		"Weather Master I V X XV XX": {},
		"Weather.DAMAGE-RES I V X XV XX": {},
    },
    # Currently unused, because i was too lazy to sort them apart
    "Skell Augment": {}, "Ground Augment": {}, 
    "Class": {
		"Astral Crusader": {},
		"Bastion Warrior": {},
		"Blast Fencer": {},
		"Commando": {},
		"Duelist": {},
		"Enforcer": {},
		"Full Metal Jaguar": {},
		"Galactic Knight": {},
		"Mastermind": {},
		"Partisan Eagle": {},
		"Psycorruptor": {},
		"Samurai Gunner": {},
		"Shield Trooper": {},
		"Striker": {},
		"Winged Viper": {},
    },
    "Art": {
        "Absorber Skin": {},
        "Afterburner": {},
        "Arcing Horn": {},
        "Assault Breaker": {},
        "Assault Hammer": {},
        "Astral Heal": {},
        "Astral Horizon": {},
        "Astral Protection": {},
        "Astral Purge": {},
        "Astrolibrium": {},
        "Atomic Hit": {},
        "Back Slash": {},
        "Balance Breaker": {},
        "Beam Barrage": {},
        "Beam Bomber": {},
        "Black Butterfly": {},
        "Blood Sacrifice": {},
        "Blossom Dance": {},
        "Bombardier": {},
        "Brainjack": {},
        "Bullet Storm": {},
        "Bullet Twister": {},
        "Burning Slash": {},
        "Burst Grenade": {},
        "Chrome Armor": {},
        "Clear Ray": {},
        "Combat Limbo": {},
        "Cool Off": {},
        "Crisis Zone": {},
        "Decoy Round": {},
        "Defensive Stance": {},
        "Dispel": {},
        "Drum Roll": {},
        "Dual Dynamo": {},
        "Eagle Eye": {},
        "Early Bird": {},
        "Electric Surge": {},
        "Energy Source": {},
        "Enhanced Stand": {},
        "Essence Exchange": {},
        "Ether Blast": {},
        "Executioner": {},
        "Fire Carnival": {},
        "First Down": {},
        "Flame Cloak": {},
        "Flame Grenade": {},
        "Flamehand": {},
        "Flash Grenade": {},
        "Full Specs": {},
        "Furious Blast": {},
        "Galactic Cataclysm": {},
        "Geolibrium": {},
        "Ghost Factory": {},
        "Ghost Sniper": {},
        "Ghostwalker": {},
        "Gravity Blast": {},
        "Gravity Cloak": {},
        "Gravity Lunge": {},
        "Grenade Blitz": {},
        "Gunforce": {},
        "Hair Trigger": {},
        "Hawkeye": {},
        "Hellfire": {},
        "Hundred Shells": {},
        "Incendiary Edge": {},
        "Infuriate": {},
        "Intercept": {},
        "Iron Prison": {},
        "Jetstream": {},
        "Killing Machine": {},
        "Last Stand": {},
        "Lightning Cloak": {},
        "Magnum Edge": {},
        "Master Gunner": {},
        "Maximum Voltage": {},
        "Medic Free": {},
        "Mindstorm": {},
        "Missile Volley": {},
        "Myopic Screen": {},
        "Noir Count": {},
        "Novalibrium": {},
        "Offensive Stance": {},
        "Overclock": {},
        "Overwhelm": {},
        "Pathogen Blast": {},
        "Phenomenon": {},
        "Power Dive": {},
        "Primer": {},
        "Quick Cannon": {},
        "Raijin": {},
        "Reality Rift": {},
        "Recuperate": {},
        "Repair": {},
        "Rising Blade": {},
        "Roaring Blade Cyclone": {},
        "Samurai Soul": {},
        "Screamer": {},
        "Secondary Speed": {},
        "Servant Sacrifice": {},
        "Seventh Edge": {},
        "Shadowrunner": {},
        "Shadowstrike": {},
        "Shield Wall": {},
        "Shooting Star": {},
        "Shrapnel": {},
        "Side Slash": {},
        "Sidewinder": {},
        "Sky High": {},
        "Slayonet": {},
        "Sliding Slinger": {},
        "Slit Edge": {},
        "Smooth Recovery": {},
        "Speed Demon": {},
        "Spiral Horn": {},
        "Starfall Blade": {},
        "Starfall Blossom": {},
        "Starfall Rondo": {},
        "Starlight Duster": {},
        "Starlight Kick": {},
        "Stellar Ray": {},
        "Stream Edge": {},
        "Subterfuge": {},
        "Supershield": {},
        "Tacit Censure": {},
        "Takedown Shot": {},
        "Thermal Payload": {},
        "Thirsty Edge": {},
        "Titan Recharge": {},
        "Tornado Blade": {},
        "Trash Talk": {},
        "Trident Buster": {},
        "Ultraslash": {},
        "Upper Hand": {},
        "Violent Streak": {},
        "Vortex": {},
        "Wild Down": {},
        "Wild Smash": {},
        "Zero Zero": {},
    },
    "Skill": {
        "Steel Flesh": {},
        "Unwavering Courage": {},
        "Flame Trigger": {},
        "Mighty Muscle": {},
        "Combat Presence": {},
        "Dismantler": {},
        "CQC Master": {},
        "Auto Melee Boost": {},
        "Iron Knuckle": {},
        "Healing Aura": {},
        "Weapon Guard": {},
        "Blazing Auto": {},
        "Theroid Slayer": {},
        "Yamato Spirit": {},
        "Conflagrant Edge": {},
        "Aggro Boost": {},
        "Fortified Flesh": {},
        "Grand Procession": {},
        "Thermal Shield": {},
        "Topple Topper": {},
        "Shield Screen": {},
        "Rising Renewal": {},
        "Long Topple": {},
        "Trauma Tension": {},
        "Dirty Fighter": {},
        "Stand Strong": {},
        "Machine Gunner": {},
        "Heatseeker": {},
        "Double Spike": {},
        "Double Reflect": {},
        "Agile Gunslinger": {},
        "Steady Hand": {},
        "Boosted Bullets": {},
        "Background Noise": {},
        "Combo Gunner": {},
        "Third Eye": {},
        "Master Edge": {},
        "Aura Burst": {},
        "Deep Fang": {},
        "Mortal Enemy": {},
        "Trigger Happy": {},
        "Lifeline": {},
        "Mindscape": {},
        "Hellhound": {},
        "Night Vision": {},
        "Zero Lapse": {},
        "Red Zone": {},
        "Crisis Catalyst": {},
        "Blood Carnival": {},
        "Phantom Counter": {},
        "Killshot": {},
        "Electric Guard": {},
        "Electric Boost": {},
        "Knock 'n' Shock": {},
        "Fleet Feet": {},
        "Piscinoid Slayer": {},
        "Long Shot": {},
        "Unstoppable": {},
        "Quick Reload": {},
        "Conductive Strike": {},
        "Electric Flesh": {},
        "TP Overdrive": {},
        "Inner Search": {},
        "Beam Boost": {},
        "Beam Guard": {},
        "Buff Heal": {},
        "Healing Touch": {},
        "High Tension": {},
        "Beauty Sleep": {},
        "Brain Wall": {},
        "Gentle Approach": {},
        "King's Decree": {},
        "Extra Armor": {},
        "Feather Touch": {},
        "Unpleasant Dream": {},
        "Core Crusher": {},
        "Ether Guard": {},
        "Gravity Boost": {},
        "Well-Weathered": {},
        "Appendage Erosion": {},
        "Resistant Flesh": {},
        "Tactical Analyst": {},
        "King's Boon": {},
        "Secondary Accelerator": {},
        "Ether Boost": {},
        "Mechanoid Slayer": {},
        "Knight's Soul": {},
        "Aura Assault": {},
        "Buff Extender": {},
        "Supreme Sword": {},
        "Gravity Guard": {},
        "Fast Forward": {},
        "Stellar Entry": {},
        "Synchrony": {},
    },
    "Heart": {
        "Celica Heart": {"count": 5},
        "Doug Heart": {"count": 5},
        "Elma Heart": {"count": 5},
        "Frye Heart": {"count": 5},
        "Gwin Heart": {"count": 5, "class": ItemClassification.progression},
        "Hope Heart": {"count": 5},
        "Irina Heart": {"count": 5},
        "L Heart": {"count": 5},
        "Lao Heart": {"count": 5, "class": ItemClassification.progression},
        "Lin  Heart": {"count": 5},
        "Mia  Heart": {"count": 5},
        "Murderess  Heart": {"count": 5},
        "Nagi  Heart": {"count": 5},
        "Phog  Heart": {"count": 5},
    },
    # Needs verification, source was not credible
    "Data Probe": {
        "Mining G1": {"count": 20, "class": ItemClassification.progression},
        "Mining G2": {"count": 24},
        "Mining G3": {"count": 7},
        "Mining G4": {"count": 15},
        "Mining G5": {"count": 9},
        "Mining G6": {"count": 9},
        "Mining G7": {"count": 4},
        "Mining G8": {"count": 23},
        "Mining G9": {"count": 10},
        "Mining G10": {"count": 4},

        "Research G1": {"count": 3, "class": ItemClassification.progression},
        "Research G2": {"count": 4},
        "Research G3": {"count": 2},
        "Research G4": {"count": 6},
        "Research G5": {"count": 7},
        "Research G6": {"count": 3},

        "Booster G1": {"count": 3},
        "Booster G2": {"count": 3},
        "Storage": {"count": 11, "class": ItemClassification.progression},
        "Duplicator": {"count": 4},

        "Fuel Recovery": {"count": 3},
        "Melee Attack": {"count": 3},
        "Ranged Attack": {"count": 3},
        "EZ Debuff": {"count": 3},
        "Attribute Resistance": {"count": 3},
    },
}

def create_items(self):
    id = self.base_id
    for itemGroupName, itemGroup in xenobladeXItems.items():
        for itemName, item in itemGroup:
            # itemName = "[" + itemGroupName + "] "
            count = item["count"] if "count" in item else 1
            itemClassification = item["class"] if "class" in item else ItemClassification.useful
            for idx in range(count):
                appendix = " #" + str(idx) if idx > 1 else ""
                self.multiworld.itempool += XenobladeXItem(itemName + appendix, itemClassification, id, self.player)
                id += 1
