from __future__ import annotations
from BaseClasses import Location

class XenobladeXLocation(Location):
    game: str = "XenobladeX"

    # override constructor to automatically mark event locations as such
    def __init__(self, player: int, name = "", code = None, parent = None):
        super(XenobladeXLocation, self).__init__(player, name, code, parent)
        if code is None:
            self.event = True
            self.locked = True


xenobladeXLocations: dict[str, dict[str, set[str] | dict[str, int]]] = {
    "Segment": { # 693
        "Irina 2nd Heart-to-Heart (5, 0, -5)": {},
        "L 3rd Heart-to-Heart (5, 1, -6)": {},
        "Murderess 5th Heart-to-Heart (5, 2, -7)": {},
        "Affinity Shift: Wendy (5, 3, -8)": {},
        "Nagi 5th Heart-to-Heart (5, 4, -9)": {},
        "Hector H.B. Birtwhistle (6, -2, -4)": {},
        "Hope Springs Eternal (6, -1, -5)": {},
        "The Miracle Maker (6, 0, -6)": {},
        "The Divine Nopopon (6, 1, -7)": {},
        "A Great Divide (6, 2, -8)": {},
        "The Bug Whisperer (6, 3, -9)": {},
        "Shotgun Diplomacy (7, -2, -5)": {},
        "Affinity Shift: Letrick (7, -1, -6)": {},
        "Rites of Ruin (7, 0, -7)": {},
        "Definian Love (7, 1, -8)": {},
        "Affinity Shift: Phoskeran (7, 2, -9)": {},
        "n955 (8, -3, -5)": {},
        "n957 (8, -2, -6)": {},
        "A Fateful Choice (8, -1, -7)": {},
        "The Journey Begins (8, 0, -8)": {},
        "Hope 1st Heart-to-Heart (8, 1, -9)": {},
        "Celica 5th Heart-to-Heart (0, 8, -8)": {},
        "Nagi 2nd Heart-to-Heart (0, 9, -9)": {},
        "The Gauntlet (0, 10, -10)": {},
        "Two Warriors (0, 11, -11)": {},
        "Data Probe Challenge (0, 12, -12)": {},
        "Good Fortun (1, 2, -3)": {},
        "Celica 4th Heart-to-Heart (1, 4, -5)": {},
        "New in New LA (1, 5, -6)": {},
        "Celica (1, 6, -7)": {},
        "Yardley Scheme (1, 7, -8)": {},
        "Off the Record (Biological) (1, 8, -9)": {},
        "Boot Camp (1, 9, -10)": {},
        "n880 (1, 10, -11)": {},
        "A Girl Wings (1, 11, -12)": {},
        "Muimui Meltdown (2, -1, -1)": {},
        "Turf War (2, 0, -2)": {},
        "Doug 2nd Heart-to-Heart (2, 1, -3)": {},
        "A Proper Chopper (2, 2, -4)": {},
        "Murderess 3rd Heart-to-Heart (2, 3, -5)": {},
        "Forest Foray (2, 4, -6)": {},
        "Pollution Solution (2, 5, -7)": {},
        "Good Neighbors (2, 7, -9)": {},
        "Irina 4th Heart-to-Heart (2, 8, -10)": {},
        "Lin 1st Heart-to-Heart (2, 9, -11)": {},
        "Data Probe Breakthrough (2, 10, -12)": {},
        "Data Probe Revolution (2, 11, -13)": {},
        "Elma 1st Heart-to-Heart (3, -1, -2)": {},
        "Lone Survivors (3, 0, -3)": {},
        "Entrepreneurial Spirit (3, 1, -4)": {},
        "Child of Mira (3, 2, -5)": {},
        "n345 (3, 3, -6)": {},
        "Orphe Pluck (3, 4, -7)": {},
        "Data Probe Progress (3, 5, -8)": {},
        "Data Probe Evolution (3, 6, -9)": {},
        "The Pip-Squeak (3, 7, -10)": {},
        "Professorial (aka The Disappearance of Doctor B) (3, 8, -11)": {},
        "Rise of the Blood Lobster (3, 9, -12)": {},
        "Mia 3rd Heart-to-Heart (3, 10, -13)": {},
        "Hope 3rd Heart-to-Heart (4, -1, -3)": {},
        "Pack It In (4, 0, -4)": {},
        "Irina 1st Heart-to-Heart (4, 1, -5)": {},
        "Frye 5th Heart-to-Heart (4, 4, -8)": {},
        "Alexa (4, 6, -10)": {},
        "This Fair City (4, 7, -11)": {},
        "Mystery Man (5, -2, -3)": {},
        "The Voltant Visionary (5, -1, -4)": {},
        "Affinity Shift: Horonalderon (5, 0, -5)": {},
        "Frye Christoph (5, 3, -8)": {},
        "The Good Thief (5, 4, -9)": {},
        "Going Viral (0, 0, 0)": {},
        "Gwin 5th Heart-to-Heart (0, 1, -1)": {},
        "Alien Nation (0, 2, -2)": {},
        "Lin 2nd Heart-to-Heart (0, 3, -3)": {},
        "Mia 4th Heart-to-Heart (0, 4, -4)": {},
        "Bozé Lowes (0, 5, -5)": {},
        "Celica 3rd Heart-to-Heart (1, 0, -1)": {},
        "n347 (1, 1, -2)": {},
        "Stop, Thief! (1, 2, -3)": {},
        "A Dubious Operation (1, 3, -4)": {},
        "Mia 2nd Heart-to-Heart (1, 4, -5)": {},
        "n659 (1, 5, -6)": {},
        "Phog 4th Heart-to-Heart (2, 0, -2)": {},
        "A Hero Ride (2, 1, -3)": {},
        "Better Latte Than Never (2, 2, -4)": {},
        "Doug 4th Heart-to-Heart (2, 3, -5)": {},
        "Affinity Shift: Quiquat (2, 4, -6)": {},
        "Lin 4th Heart-to-Heart (3, -1, -2)": {},
        "Emotion Commotion (3, 0, -3)": {},
        "The Matchmaker (3, 1, -4)": {},
        "Definian Downfall (3, 2, -5)": {},
        "Irina 5th Heart-to-Heart (3, 3, -6)": {},
        "Affinity Shift: Veverta (3, 4, -7)": {},
        "Nine Lives (4, -1, -3)": {},
        "Renewed Will (4, 0, -4)": {},
        "No Ma-non Need Apply (4, 1, -5)": {},
        "L 4th Heart-to-Heart (4, 2, -6)": {},
        "Nagi 3rd Heart-to-Heart (4, 3, -7)": {},
        "Sparking a Smile (5, -2, -3)": {},
        "Unsatisfied Customer (5, -1, -4)": {},
        "The Fashionista (5, 0, -5)": {},
        "Planetary Pioneer (Part III) (5, 1, -6)": {},
        "Yelv (5, 2, -7)": {},
        "The Sword of Legendaryness (6, 0, -6)": {},
        "Murderess 2nd Heart-to-Heart (6, 1, -7)": {},
        "Serial Thriller (6, 2, -8)": {},
        "Frye 4th Heart-to-Heart (7, -1, -6)": {},
        "My Angel, My Lana (7, 0, -7)": {},
        "n909 (7, 1, -8)": {},
        "Hope 5th Heart-to-Heart (8, -3, -5)": {},
        "Trade Agreement (8, -2, -6)": {},
        "The Ties That Bind (8, -1, -7)": {},
        "L 1st Heart-to-Heart (8, 0, -8)": {},
        "Affinity Shift: Beats (8, 1, -9)": {},
        "Murder Most Foul (9, -3, -6)": {},
        "Wrothian Innovation (9, -2, -7)": {},
        "Hope 2nd Heart-to-Heart (10, -4, -6)": {},
        "A Dish Served Cold (10, -3, -7)": {},
        "Elma 3rd Heart-to-Heart (10, -2, -8)": {},
        "Fitting In (5, 6, -11)": {},
        "Professor B Return (6, -3, -3)": {},
        "Gold Rush (6, -2, -4)": {},
        "Frye 1st Heart-to-Heart (6, 2, -8)": {},
        "Bottoms Up (6, 3, -9)": {},
        "The Repair Job (0, 1, -1)": {},
        "Lin Lee Koo (0, 2, -2)": {},
        "A Day in the Life (1, 0, -1)": {},
        "Then and Now (1, 1, -2)": {},
        "To Serve Nopon (1, 2, -3)": {},
        "Elma 5th Heart-to-Heart (2, 0, -2)": {},
        "Nagi Time (2, 1, -3)": {},
        "A Challenger Approaches (3, -1, -2)": {},
        "Nagi 4th Heart-to-Heart (3, 0, -3)": {},
        "We Were Soldiers (3, 1, -4)": {},
        "Elma (4, -1, -3)": {},
        "Two Peas in a Pod (4, 0, -4)": {},
        "Fathers and Sons (5, -2, -3)": {},
        "Complete All Story Missions (5, -1, -4)": {},
        "BFFs (5, 0, -5)": {},
        "Prospective Partners (6, -2, -4)": {},
        "A Friend in Need (6, -1, -5)": {},
        "Phog 1st Heart-to-Heart (0, 0, 0)": {},
        "Circle of Life (0, 1, -1)": {},
        "Phog Christoph (0, 2, -2)": {},
        "Lin 5th Heart-to-Heart (0, 3, -3)": {},
        "The Duel (Part II) (0, 6, -6)": {},
        "Off the Record (Archaeological) (0, 4, -4)": {},
        "Kentaro Nagi (1, 6, -7)": {},
        "Phog 3rd Heart-to-Heart (0, 5, -5)": {},
        "Cavern Crushers (2, 5, -7)": {},
        "Attack on Biahno Hills (2, 6, -8)": {},
        "n348 (0, 6, -6)": {},
        "Dead Men Tell No Tales (3, 4, -7)": {},
        "Prone Sweet Prone (3, 5, -8)": {},
        "Gwin 2nd Heart-to-Heart (0, 7, -7)": {},
        "n349 (3, 6, -9)": {},
        "Gwin 1st Heart-to-Heart (4, 0, -4)": {},
        "Irina 3rd Heart-to-Heart (4, 1, -5)": {},
        "Doug Barrett (4, 2, -6)": {},
        "n661 (4, 3, -7)": {},
        "Manhunt (4, 4, -8)": {},
        "Spy Games (4, 5, -9)": {},
        "Rescue at the Ensconced Citadel (4, 6, -10)": {},
        "The Ultimate Price (4, 7, -11)": {},
        "The Handy Ma-non (5, -1, -4)": {},
        "My Dream (5, 0, -5)": {},
        "Affinity Shift: Cedric (5, 1, -6)": {},
        "The Nopon Heir (5, 2, -7)": {},
        "Lcirufe L (5, 3, -8)": {},
        "That In-Credible! (5, 4, -9)": {},
        "Reporting for Duty (5, 5, -10)": {},
        "A False Hope (5, 6, -11)": {},
        "Planetary Pioneer (Part II) (5, 7, -12)": {},
        "Affinity Shift: Nopopon (5, 8, -13)": {},
        "Mamma Mia! (6, -2, -4)": {},
        "Mia Grows Up (6, -1, -5)": {},
        "Brotherly Love (6, 0, -6)": {},
        "Doug 5th Heart-to-Heart (6, 1, -7)": {},
        "L Conundrum (6, 2, -8)": {},
        "Booming Business (6, 3, -9)": {},
        "Lend an Ear (6, 4, -10)": {},
        "Setting Forth (6, 5, -11)": {},
        "Nagi 1st Heart-to-Heart (6, 6, -12)": {},
        "Planetary Pioneer (Part IV) (7, -3, -4)": {},
        "Waste Not, Want Not (7, -2, -5)": {},
        "Skell License (7, -1, -6)": {},
        "Herbivores, Unite! (1, 1, -2)": {},
        "Frye 2nd Heart-to-Heart (7, 0, -7)": {},
        "House of Cards (7, 1, -8)": {},
        "White Lifehold (7, 2, -9)": {},
        "BLADE Level Basics (7, 3, -10)": {},
        "Soldier of the Harriers (7, 4, -11)": {},
        "The Probe-fessional (7, 5, -12)": {},
        "The Duel (Part III) (7, 6, -13)": {},
        "The Little Rich Girl (8, -3, -5)": {},
        "Lao Huang (8, -2, -6)": {},
        "Gwin Evans (8, -1, -7)": {},
        "City Saviors (8, 0, -8)": {},
        "Close Comrades (8, 1, -9)": {},
        "Planetary Pioneer (Part I) (8, 2, -10)": {},
        "Affinity Shift: Wolf (8, 3, -11)": {},
        "Ovah and Out (8, 4, -12)": {},
        "Cooking Schooled (8, 5, -13)": {},
        "Mia Is Missing! (8, 6, -14)": {},
        "A Present for Hope (1, 2, -3)": {},
        "Unknown Assailant (9, -3, -6)": {},
        "Frontier Spirit (9, -2, -7)": {},
        "Lin 3rd Heart-to-Heart (9, -1, -8)": {},
        "Close Encounters (9, 0, -9)": {},
        "The Root of All Evil (9, 1, -10)": {},
        "Irina Akulov (9, 2, -11)": {},
        "Sharon Murderess Effinger (9, 3, -12)": {},
        "Myles to Go (10, 0, -10)": {},
        "The Celeste Three (1, 3, -4)": {},
        "Slovity Rampage (11, -1, -10)": {},
        "Blitzkrieg (11, 0, -11)": {},
        "Forbidden Love (0, 2, -2)": {},
        "No-show Nenceleg (0, 3, -3)": {},
        "L 5th Heart-to-Heart (1, 4, -5)": {},
        "Gorkwa Games (1, 1, -2)": {},
        "House Call (1, 2, -3)": {},
        "A New Life (2, 0, -2)": {},
        "Here Come the Brides (2, 1, -3)": {},
        "The Unbreakable Sword (2, 2, -4)": {},
        "A Grim Undertaking (3, 0, -3)": {},
        "Celica 2nd Heart-to-Heart (1, 5, -6)": {},
        "L 2nd Heart-to-Heart (3, 2, -5)": {},
        "The Lurker (4, 2, -6)": {},
        "Snipe Hunt (5, 1, -6)": {},
        "Mia (5, 2, -7)": {},
        "Doug 3rd Heart-to-Heart (1, 6, -7)": {},
        "Sunceleg Rises (6, 0, -6)": {},
        "Affinity Shift: Zurranik (6, 2, -8)": {},
        "The Membership (6, 3, -9)": {},
        "Tree-mendous (6, 4, -10)": {},
        "Elma 4th Heart-to-Heart (7, 2, -9)": {},
        "The Old Gods (7, 3, -10)": {},
        "An Ancient Legend (7, 4, -11)": {},
        "Training Day (8, 1, -9)": {},
        "The Art of War (8, 2, -10)": {},
        "Slovity Revenge (8, 3, -11)": {},
        "The Party Line (9, 1, -10)": {},
        "Gwin 3rd Heart-to-Heart (2, -1, -1)": {},
        "Frye 3rd Heart-to-Heart (2, 0, -2)": {},
        "The Line of Fire (2, 1, -3)": {},
        "Hope Alanzi (2, 2, -4)": {},
        "Planetary Pioneer (Part V) (2, 3, -5)": {},
        "Gwin 4th Heart-to-Heart (2, 4, -6)": {},
        "Mia 5th Heart-to-Heart (2, 5, -7)": {},
        "Hope 4th Heart-to-Heart (2, 6, -8)": {},
        "Phog 5th Heart-to-Heart (3, -1, -2)": {},
        "Foggy Dilemma (3, 0, -3)": {},
        "Murderess 1st Heart-to-Heart (3, 1, -4)": {},
        "Murderess 4th Heart-to-Heart (3, 2, -5)": {},
        "n660 (3, 3, -6)": {},
        "Doug 1st Heart-to-Heart (3, 4, -7)": {},
        "Bread and a Circus (3, 5, -8)": {},
        "Elma 2nd Heart-to-Heart (4, -2, -2)": {},
        "New Frontier (4, -1, -3)": {},
        "Off the Record (Mechanical) (4, 0, -4)": {},
        "Mia 1st Heart-to-Heart (4, 1, -5)": {},
        "Affinity Shift: Caroline (4, 2, -6)": {},
        "Alex Last Stand (4, 3, -7)": {},
        "Phog 2nd Heart-to-Heart (4, 4, -8)": {},
        "Affinity Shift: Konluarb (4, 5, -9)": {},
        "Lakeside Getaway (5, -2, -3)": {},
        "Water Woes (5, -1, -4)": {},
        "Nagi Time (10, -1, -9)": {},
        "Close Encounters (10, -3, -7)": {},
        "FN Site 113 (10, -4, -6)": {},
        "Shatskikh, the Flash (10, 0, -10)": {},
        "Welcome Back, Conner (10, 1, -11)": {},
        "FN Site 114 (10, 2, -12)": {},
        "FN Site 115 (11, -1, -10)": {},
        "Caesar, the Hundred-Eyed (1, 1, -2)": {},
        "Here Come the Brides (11, 0, -11)": {},
        "treasure1111-12 (11, 1, -12)": {},
        "treasure1112-13 (11, 2, -13)": {},
        "An Ancient Legend (11, 3, -14)": {},
        "treasure112-1-11 (12, -1, -11)": {},
        "We Were Soldiers (12, -2, -10)": {},
        "Snipe Hunt (1, 2, -3)": {},
        "Etutanne, the Bloodthirsty (12, 0, -12)": {},
        "Hephaestus, the Absconder (12, 1, -13)": {},
        "FN Site 116 (12, 2, -14)": {},
        "treasure113-1-12 (13, -1, -12)": {},
        "treasure113-4 (1, 3, -4)": {},
        "FN Site 117 (13, 0, -13)": {},
        "Nine Lives (13, 1, -14)": {},
        "treasure1132-15 (13, 2, -15)": {},
        "Gugli, the Relentless (14, -1, -13)": {},
        "treasure114-2-12 (14, -2, -12)": {},
        "Luciel, the Eternal (14, 0, -14)": {},
        "Eutropio, the Sea Rumble (14, 1, -15)": {},
        "A Dubious Operation (14, 2, -16)": {},
        "Training Day (15, -1, -14)": {},
        "FN Site 118 (15, -2, -13)": {},
        "Muimui Meltdown (15, -3, -12)": {},
        "A False Hope (15, 0, -15)": {},
        "FN Site 119 (15, 1, -16)": {},
        "Bogdan, the Dense (15, 2, -17)": {},
        "FN Site 120 (16, -1, -15)": {},
        "Stop, Thief! (16, -2, -14)": {},
        "treasure116-3-13 (16, -3, -13)": {},
        "Ji-ett, the Thunderclap (16, 0, -16)": {},
        "Rajidi, the Cumuliform (17, -2, -15)": {},
        "FN Site 121 (17, -3, -14)": {},
        "FN Site 101 (2, 1, -3)": {},
        "treasure122-4 (2, 2, -4)": {},
        "FN Site 103 (2, 3, -5)": {},
        "treasure124-6 (2, 4, -6)": {},
        "Celestin, the Spring Storm (2, 5, -7)": {},
        "The Repair Job (2, 6, -8)": {},
        "FN Site 102 (2, 7, -9)": {},
        "The Queen Is Dead (3, 1, -4)": {},
        "treasure132-5 (3, 2, -5)": {},
        "Zdenka, the Raucous (3, 3, -6)": {},
        "treasure134-7 (3, 4, -7)": {},
        "FN Site 104 (3, 5, -8)": {},
        "treasure136-9 (3, 6, -9)": {},
        "FN Site 105 (4, 0, -4)": {},
        "Sapara, the Laconic (4, 1, -5)": {},
        "A Day in the Life (4, 2, -6)": {},
        "FN Site 106 (4, 3, -7)": {},
        "Haywire! (4, 4, -8)": {},
        "treasure145-9 (4, 5, -9)": {},
        "Forbidden Love (4, 6, -10)": {},
        "Bohdan, the Mistral (5, 1, -6)": {},
        "treasure152-7 (5, 2, -7)": {},
        "Cinicula Assault (5, 3, -8)": {},
        "Renewed Will (5, 4, -9)": {},
        "FN Site 107 (5, 5, -10)": {},
        "treasure156-11 (5, 6, -11)": {},
        "treasure160-6 (6, 0, -6)": {},
        "FN Site 108 (6, 1, -7)": {},
        "The Lurker (6, 2, -8)": {},
        "Eckart, the Indestructible (6, 3, -9)": {},
        "Casper, the Unhealthy Eater (6, 4, -10)": {},
        "FN Site 109 (7, -1, -6)": {},
        "Ridill, the Arrogant (7, -2, -5)": {},
        "Necro, the Cavelord (7, 0, -7)": {},
        "Experimental Composite Qmoeva (7, 1, -8)": {},
        "FN Site 110 (7, 2, -9)": {},
        "City Saviors (7, 3, -10)": {},
        "FN Site 111 (8, -1, -7)": {},
        "treasure180-8 (8, 0, -8)": {},
        "treasure181-9 (8, 1, -9)": {},
        "Dieter, the Epicure (8, 2, -10)": {},
        "The Good Thief (9, -1, -8)": {},
        "treasure19-2-7 (9, -2, -7)": {},
        "Daril, the Eradicator (9, -3, -6)": {},
        "treasure190-9 (9, 0, -9)": {},
        "FN Site 112 (9, 1, -10)": {},
        "Mesgen, the Fairweathered (9, 2, -11)": {},
        "treasure21012-22 (10, 12, -22)": {},
        "treasure21013-23 (10, 13, -23)": {},
        "Data Miner (10, 14, -24)": {},
        "FN Site 223 (10, 4, -14)": {},
        "FN Site 224 (10, 5, -15)": {},
        "Buchwald, the Guardian (10, 6, -16)": {},
        "FN Site 225 (10, 8, -18)": {},
        "FN Site 201 (3, 2, -5)": {},
        "FN Site 202 (3, 5, -8)": {},
        "treasure236-9 (3, 6, -9)": {},
        "FN Site 203 (3, 7, -10)": {},
        "treasure239-12 (3, 9, -12)": {},
        "A Fateful Choice (4, 1, -5)": {},
        "FN Site 205 (4, 10, -14)": {},
        "Froste, the Courteous (4, 11, -15)": {},
        "The Nopon Heir (4, 2, -6)": {},
        "Planetes, the Torrential (4, 3, -7)": {},
        "House Call (4, 4, -8)": {},
        "Pyotr, the Shepherd (4, 5, -9)": {},
        "Prospective Partners (4, 6, -10)": {},
        "treasure247-11 (4, 7, -11)": {},
        "FN Site 204 (4, 8, -12)": {},
        "Frontier Spirit (4, 9, -13)": {},
        "Telethia, the Endbringer (5, -1, -4)": {},
        "FN Site 206 (5, 0, -5)": {},
        "Joker, the Unknowable (5, 1, -6)": {},
        "The Voltant Visionary (5, 10, -15)": {},
        "FN Site 209 (5, 11, -16)": {},
        "Frajeel, the Purgatorial (5, 2, -7)": {},
        "FN Site 207 (5, 3, -8)": {},
        "The Art of War (5, 4, -9)": {},
        "FN Site 208 (5, 5, -10)": {},
        "Rescue at the Ensconced Citadel (5, 6, -11)": {},
        "My Dream (5, 7, -12)": {},
        "Katerina, the Cliffhanger (5, 8, -13)": {},
        "Schneider, the Cliffpercher (5, 9, -14)": {},
        "treasure260-6 (6, 0, -6)": {},
        "Dodonga Caravan (6, 10, -16)": {},
        "Circle of Life (6, 3, -9)": {},
        "FN Site 210 (6, 4, -10)": {},
        "treasure265-11 (6, 5, -11)": {},
        "FN Site 211 (6, 6, -12)": {},
        "No-show Nenceleg (6, 7, -13)": {},
        "FN Site 212 (6, 8, -14)": {},
        "treasure269-15 (6, 9, -15)": {},
        "FN Site 213 (7, 0, -7)": {},
        "A Proper Chopper (7, 13, -20)": {},
        "FN Site 217 (7, 14, -21)": {},
        "Manhunt (7, 3, -10)": {},
        "FN Site 214 (7, 4, -11)": {},
        "Demetrio, the Tempestuous (7, 5, -12)": {},
        "FN Site 215 (7, 6, -13)": {},
        "treasure277-14 (7, 7, -14)": {},
        "Close Comrades (7, 8, -15)": {},
        "FN Site 216 (7, 9, -16)": {},
        "Lone Survivors (8, 10, -18)": {},
        "FN Site 219 (8, 12, -20)": {},
        "Sarcosuchus, the Iron-Eater (8, 13, -21)": {},
        "treasure2814-22 (8, 14, -22)": {},
        "Dead Men Tell No Tales (8, 3, -11)": {},
        "Murder Most Foul (8, 4, -12)": {},
        "Elena, the Infernal (8, 5, -13)": {},
        "Griffus, the Tartarean (8, 6, -14)": {},
        "FN Site 218 (8, 7, -15)": {},
        "Adventure! (8, 8, -16)": {},
        "Tormenta, the Scarlet-Clad (8, 9, -17)": {},
        "FN Site 220 (9, 10, -19)": {},
        "treasure2911-20 (9, 11, -20)": {},
        "FN Site 221 (9, 12, -21)": {},
        "Missing in Action (9, 13, -22)": {},
        "FN Site 222 (9, 14, -23)": {},
        "Desdemona, the Subterraanean (9, 15, -24)": {},
        "treasure295-14 (9, 5, -14)": {},
        "treasure296-15 (9, 6, -15)": {},
        "The Duel (Part II) (9, 7, -16)": {},
        "Clemente, the Iron Meteor (9, 8, -17)": {},
        "treasure299-18 (9, 9, -18)": {},
        "treasure305-5 (0, 5, -5)": {},
        "FN Site 301 (0, 6, -6)": {},
        "treasure310-1-9 (10, -1, -9)": {},
        "Ferdinand, the Fortuitus (10, -2, -8)": {},
        "FN Site 316 (10, -3, -7)": {},
        "treasure310-4-6 (10, -4, -6)": {},
        "Bread and a Circus (10, 0, -10)": {},
        "Climati, the Chilling Wind (10, 1, -11)": {},
        "treasure3102-12 (10, 2, -12)": {},
        "Shotgun Diplomacy (10, 3, -13)": {},
        "FN Site 317 (10, 4, -14)": {},
        "Silvestre, the Morning Light (10, 5, -15)": {},
        "treasure311-1-10 (11, -1, -10)": {},
        "treasure311-2-9 (11, -2, -9)": {},
        "Dorian Caravan (11, -3, -8)": {},
        "treasure311-4-7 (11, -4, -7)": {},
        "Feliciano, the All-Seeing (11, 0, -11)": {},
        "FN Site 318 (11, 1, -12)": {},
        "treasure3112-13 (11, 2, -13)": {},
        "treasure3113-14 (11, 3, -14)": {},
        "FN Site 319 (11, 4, -15)": {},
        "treasure312-1-11 (12, -1, -11)": {},
        "FN Site 321 (12, -2, -10)": {},
        "Vilem, the Gold-Scaled (12, -3, -9)": {},
        "FN Site 320 (12, -4, -8)": {},
        "Bertrand, the Gorge Scourge (12, 0, -12)": {},
        "treasure3124-16 (12, 4, -16)": {},
        "treasure313-1-12 (13, -1, -12)": {},
        "The Trading Floor (13, -2, -11)": {},
        "FN Site 322 (14, -1, -13)": {},
        "Spy Games (14, -2, -12)": {},
        "Melanya, the Sound Sleeper (1, 5, -6)": {},
        "Sunceleg Rises (1, 6, -7)": {},
        "FN Site 302 (2, 4, -6)": {},
        "Gotthard, the Intimidating (2, 5, -7)": {},
        "treasure326-8 (2, 6, -8)": {},
        "FN Site 303 (2, 7, -9)": {},
        "treasure332-5 (3, 2, -5)": {},
        "Germaine, the Treasure Keeper (3, 3, -6)": {},
        "treasure334-7 (3, 4, -7)": {},
        "FN Site 304 (3, 5, -8)": {},
        "treasure336-9 (3, 6, -9)": {},
        "Vendura, the Spellbinder (3, 7, -10)": {},
        "Libra, the Long-Lived (4, 1, -5)": {},
        "FN Site 305 (4, 2, -6)": {},
        "Jindriska, the Serene (4, 3, -7)": {},
        "Barnabas, the Despot (4, 4, -8)": {},
        "A Dish Served Cold (4, 5, -9)": {},
        "treasure346-10 (4, 6, -10)": {},
        "Prone Sweet Prone (4, 7, -11)": {},
        "Edgardo, the Carefree (5, 0, -5)": {},
        "treasure351-6 (5, 1, -6)": {},
        "Squallo, the Sand-Mirer (5, 2, -7)": {},
        "treasure353-8 (5, 3, -8)": {},
        "Foggy Dilemma (5, 4, -9)": {},
        "FN Site 306 (5, 5, -10)": {},
        "treasure356-11 (5, 6, -11)": {},
        "FN Site 307 (5, 7, -12)": {},
        "FN Site 308 (6, -1, -5)": {},
        "Ro-darm, the Demon Claw (6, 0, -6)": {},
        "Slovity Rampage (6, 1, -7)": {},
        "FN Site 309 (6, 2, -8)": {},
        "Mayday (6, 3, -9)": {},
        "treasure364-10 (6, 4, -10)": {},
        "Hartmut, the Calamity (6, 5, -11)": {},
        "Valeriano, the Rolling Thunder (6, 6, -12)": {},
        "A Friend in Need (6, 7, -13)": {},
        "treasure37-1-6 (7, -1, -6)": {},
        "treasure370-7 (7, 0, -7)": {},
        "Ernest, the Comptemplative (7, 1, -8)": {},
        "Celedonio, the Battle-Tested (7, 2, -9)": {},
        "treasure373-10 (7, 3, -10)": {},
        "Vittorio, the Battle-Scarred (7, 4, -11)": {},
        "treasure375-12 (7, 5, -12)": {},
        "Mighty Mia (7, 6, -13)": {},
        "treasure377-14 (7, 7, -14)": {},
        "The Duel (Part I) (8, -1, -7)": {},
        "FN Site 310 (8, -2, -6)": {},
        "FN Site 311 (8, 0, -8)": {},
        "Rolf, the Sonorous (8, 1, -9)": {},
        "Ludvik, the Picky Eater (8, 2, -10)": {},
        "FN Site 312 (8, 3, -11)": {},
        "A Grim Undertaking (8, 4, -12)": {},
        "FN Site 313 (8, 5, -13)": {},
        "treasure386-14 (8, 6, -14)": {},
        "FN Site 314 (8, 7, -15)": {},
        "A Challenger Approaches (9, -1, -8)": {},
        "Elaine, the Lunar Eclipse (9, -2, -7)": {},
        "The Little Rich Girl (9, -3, -6)": {},
        "FN Site 315 (9, 0, -9)": {},
        "treasure391-10 (9, 1, -10)": {},
        "Then and Now (9, 2, -11)": {},
        "Eliane, the Unmoved (9, 3, -12)": {},
        "Sviatoslav, the Reproachful (9, 4, -13)": {},
        "A Great Divide (9, 5, -14)": {},
        "treasure410-1-9 (10, -1, -9)": {},
        "FN Site 418 (10, -2, -8)": {},
        "Clara, the Pure White (10, -3, -7)": {},
        "Leaving the Nest (10, -4, -6)": {},
        "Orphe Pluck (10, 0, -10)": {},
        "FN Site 419 (10, 1, -11)": {},
        "treasure4102-12 (10, 2, -12)": {},
        "treasure4103-13 (10, 3, -13)": {},
        "treasure411-1-10 (11, -1, -10)": {},
        "treasure411-2-9 (11, -2, -9)": {},
        "The Sword of Legendaryness (11, 0, -11)": {},
        "treasure4110-11 (1, 10, -11)": {},
        "treasure4111-12 (11, 1, -12)": {},
        "FN Site 420 (12, -1, -11)": {},
        "Oc-serv, the Ancient (12, 0, -12)": {},
        "FN Site 401 (1, 5, -6)": {},
        "treasure416-7 (1, 6, -7)": {},
        "Yune, the Ambusher (1, 9, -10)": {},
        "Stola, the Champion (2, 10, -12)": {},
        "treasure422-4 (2, 2, -4)": {},
        "Behemoth, the Netherdweller (2, 3, -5)": {},
        "Lesson from the Grave (2, 4, -6)": {},
        "Predator and Prey (2, 5, -7)": {},
        "FN Site 402 (2, 6, -8)": {},
        "treasure427-9 (2, 7, -9)": {},
        "Bottoms Up (2, 8, -10)": {},
        "FN Site 403 (2, 9, -11)": {},
        "FN Site 404 (3, 2, -5)": {},
        "treasure433-6 (3, 3, -6)": {},
        "Alexei, the Jade (3, 4, -7)": {},
        "treasure435-8 (3, 5, -8)": {},
        "Castle in the Sky (3, 6, -9)": {},
        "FN Site 405 (3, 7, -10)": {},
        "Florence, the Hell Maggot (3, 8, -11)": {},
        "Antara, the Water Diviner (4, 0, -4)": {},
        "treasure441-5 (4, 1, -5)": {},
        "Plans of Attack (4, 2, -6)": {},
        "FN Site 406 (4, 3, -7)": {},
        "Radovan, the Sky Baron (4, 4, -8)": {},
        "Laurencio, the Fog Bow (4, 5, -9)": {},
        "Asana, the Azura Star (4, 6, -10)": {},
        "The Line of Fire (4, 7, -11)": {},
        "Damaged Zig (4, 8, -12)": {},
        "treasure45-1-4 (5, -1, -4)": {},
        "Unknown Assailant (5, -2, -3)": {},
        "FN Site 407 (5, 0, -5)": {},
        "Candelario, the Bronze (5, 1, -6)": {},
        "treasure452-7 (5, 2, -7)": {},
        "Soldier of the Harriers (5, 3, -8)": {},
        "FN Site 408 (5, 4, -9)": {},
        "Hair Apparent (5, 5, -10)": {},
        "treasure456-11 (5, 6, -11)": {},
        "treasure457-12 (5, 7, -12)": {},
        "FN Site 409 (5, 8, -13)": {},
        "Luxaar Xern (6, -1, -5)": {},
        "FN Site 410 (6, -2, -4)": {},
        "treasure460-6 (6, 0, -6)": {},
        "Law and Orders (6, 1, -7)": {},
        "treasure462-8 (6, 2, -8)": {},
        "Serial Thriller (6, 3, -9)": {},
        "treasure464-10 (6, 4, -10)": {},
        "FN Site 411 (6, 5, -11)": {},
        "Its-a Mia! (6, 6, -12)": {},
        "treasure467-13 (6, 7, -13)": {},
        "Good Fortun (7, -1, -6)": {},
        "treasure47-2-5 (7, -2, -5)": {},
        "FN Site 412 (7, 0, -7)": {},
        "Gesserith, the Wileworm (7, 1, -8)": {},
        "FN Site 413 (7, 2, -9)": {},
        "Ramus, the Supersonic (7, 3, -10)": {},
        "Ignit, the Ultimate Chaos (7, 4, -11)": {},
        "Lockhart, the Killer of Hope (7, 5, -12)": {},
        "treasure476-13 (7, 6, -13)": {},
        "treasure48-1-7 (8, -1, -7)": {},
        "treasure48-2-6 (8, -2, -6)": {},
        "treasure48-3-5 (8, -3, -5)": {},
        "treasure480-8 (8, 0, -8)": {},
        "treasure481-9 (8, 1, -9)": {},
        "Manan, the Water Whisperer (8, 2, -10)": {},
        "treasure483-11 (8, 3, -11)": {},
        "Thaddaeus, the Ultramafic (8, 4, -12)": {},
        "FN Site 414 (8, 5, -13)": {},
        "treasure486-14 (8, 6, -14)": {},
        "The Duel (Part III) (9, -1, -8)": {},
        "Special Delivery (9, -2, -7)": {},
        "FN Site 415 (9, -3, -6)": {},
        "treasure49-4-5 (9, -4, -5)": {},
        "FN Site 416 (9, 0, -9)": {},
        "Brotherly Love (9, 1, -10)": {},
        "Sadar Qmoeva (9, 2, -11)": {},
        "FN Site 417 (9, 3, -12)": {},
        "treasure494-13 (9, 4, -13)": {},
        "treasure510-1-9 (10, -1, -9)": {},
        "treasure510-2-8 (10, -2, -8)": {},
        "A Present for Hope (10, -3, -7)": {},
        "FN Site 510 (10, -4, -6)": {},
        "treasure5100-10 (10, 0, -10)": {},
        "FN Site 511 (10, 1, -11)": {},
        "treasure5102-12 (10, 2, -12)": {},
        "FN Site 512 (10, 3, -13)": {},
        "Terenty, the Blademaster (11, -1, -10)": {},
        "FN Site 513 (11, -2, -9)": {},
        "treasure511-3-8 (11, -3, -8)": {},
        "treasure5110-11 (11, 0, -11)": {},
        "Until the End (11, 1, -12)": {},
        "Gi-zho, the Iron Deity (11, 2, -13)": {},
        "Sharnaak, the Technician (12, -1, -11)": {},
        "The Queen Is Dead (12, -2, -10)": {},
        "Jia Mian, the Beloved (12, -3, -9)": {},
        "Alex Last Stand (12, 0, -12)": {},
        "FN Site 514 (12, 1, -13)": {},
        "treasure5122-14 (12, 2, -14)": {},
        "FN Site 515 (13, -1, -12)": {},
        "treasure513-2-11 (13, -2, -11)": {},
        "treasure513-3-10 (13, -3, -10)": {},
        "treasure513-4 (1, 3, -4)": {},
        "The Unbreakable Sword (13, -4, -9)": {},
        "treasure514-3-11 (14, -3, -11)": {},
        "FN Site 516 (14, -4, -10)": {},
        "treasure515-6 (1, 5, -6)": {},
        "FN Site 501 (2, 2, -4)": {},
        "Supplies Surprise (2, 4, -6)": {},
        "FN Site 502 (2, 5, -7)": {},
        "treasure526-8 (2, 6, -8)": {},
        "treasure531-4 (3, 1, -4)": {},
        "Gorkwa Games (3, 3, -6)": {},
        "Sparking a Smile (3, 4, -7)": {},
        "Slovity Revenge (3, 5, -8)": {},
        "FN Site 503 (4, 2, -6)": {},
        "treasure543-7 (4, 3, -7)": {},
        "Kringe, the Hunting Arrow (4, 4, -8)": {},
        "treasure545-9 (4, 5, -9)": {},
        "treasure550-5 (5, 0, -5)": {},
        "The Bodyguard (5, 1, -6)": {},
        "My Angel, My Lana (5, 2, -7)": {},
        "treasure553-8 (5, 3, -8)": {},
        "FN Site 504 (5, 4, -9)": {},
        "Definian Downfall (6, -1, -5)": {},
        "FN Site 505 (6, 0, -6)": {},
        "treasure561-7 (6, 1, -7)": {},
        "FN Site 506 (6, 2, -8)": {},
        "Coil, the Never-Ending (6, 3, -9)": {},
        "treasure564-10 (6, 4, -10)": {},
        "Prinsipe, the Ravenous (6, 5, -11)": {},
        "The Old Gods (6, 6, -12)": {},
        "Mia Is Missing! (7, -1, -6)": {},
        "The Duel (Part IV) (7, 0, -7)": {},
        "Chantai Galdr (7, 1, -8)": {},
        "treasure572-9 (7, 2, -9)": {},
        "To Serve Nopon (7, 3, -10)": {},
        "Rites of Ruin (7, 4, -11)": {},
        "FN Site 507 (7, 5, -12)": {},
        "Black Lifehold (7, 6, -13)": {},
        "Eisen, the Ebon Rock (8, -1, -7)": {},
        "treasure580-8 (8, 0, -8)": {},
        "Lionhearted (8, 1, -9)": {},
        "FN Site 508 (8, 2, -10)": {},
        "Pelicollo, the Panzer (8, 3, -11)": {},
        "treasure584-12 (8, 4, -12)": {},
        "treasure585-13 (8, 5, -13)": {},
        "FN Site 509 (9, -1, -8)": {},
        "Chantai, the Insect Maiden (9, -2, -7)": {},
        "Armored Cruiser Seidr (9, 0, -9)": {},
        "Duran, the Draconian (9, 1, -10)": {},
        "Ilithios, the Enlightened (9, 2, -11)": {},
        "treasure593-12 (9, 3, -12)": {},
        "treasure594-13 (9, 4, -13)": {},
    },
    "Collectopedia": { #300
        "Ajira Melon": {},
        "Cranjelly": {},
        "Starlight Apple": {},
        "Sweet Nerine": {},
        "Golden Sardine": {},
        "Keppo Carrot": {},
        "Arnacian Orewood": {},
        "Hummingstone": {},
        "Anhydrous Radiator": {},
        "Kiran Catnip": {},
        "Crawling Bat": {},
        "Zizi Rabbit": {},
        "Zesian Fleawort": {},
        "Ancient Allure": {},
        "Hemp Wallet": {},
        "Grosium Core": {},
        "Stretching Locust": {},
        "Multi-speckled Ladybug": {},
        "Centrifugal Beam Generator": {},
        "Vagabond Ant": {},
        "Amidresian Tomato": {},
        "Nirvana Jonquil": {},
        "Coaletri": {},
        "Rizattice": {},
        "Meditation Powder": {},
        "High Accelerator": {},
        "Fillal Filth": {},
        "Sanelac Pearl": {},
        "Flecked Bottle": {},
        "Noranlily": {},
        "Grinding Squirrel": {},
        "Logunie Driftwood": {},
        "Crush Ring": {},
        "Acorn Abacus": {},
        "Ball Mosquito": {},
        "Facewood": {},
        "Auroran Bone": {},
        "Heatproof Inox Pipe": {},
        "Rock-Orange": {},
        "Sadelana Lettuce": {},
        "Mondcherry": {},
        "Doga Dandelion": {},
        "Ashizel": {},
        "T-ray Light": {},
        "Tractor Beetle": {},
        "Deflection Shield Mirror": {},
        "White Iron Sand": {},
        "Mosa Cabbage": {},
        "Sonar Lemon": {},
        "Meteo Eater": {},
        "Assassin Springtail": {},
        "US-X Space Suit": {},
        "Jagged Mortar": {},
        "Sona Herb": {},
        "Goddess Kiss": {},
        "California Sunset": {},
        "L-002 Fuel Tank": {},
        "Mirage Scope": {},
        "Garudo Pellionia Minima": {},
        "L-002 Space Analyzer": {},
        "Lacey Potato": {},
        "Strawlenny": {},
        "Socha Guava": {},
        "Timid Sunflower": {},
        "Babaco Leaf": {},
        "False Cedar": {},
        "Iguari": {},
        "Bananaleaf": {},
        "Godmelon": {},
        "Nostalgia L-002": {},
        "Zandemo Eggplant": {},
        "Mk. IX Hypercooler": {},
        "Sleeping Amaryllis": {},
        "Flowering Morrow Fern": {},
        "Rock Armadillo": {},
        "Fodornallow Greens": {},
        "Resonating Madonater": {},
        "Morphling Flounder": {},
        "Loathsome Blob": {},
        "Gesture Glove": {},
        "Logunie Driftwood Boat": {},
        "Sour Plum": {},
        "Eternal Moss": {},
        "Primitive Colossus Statue": {},
        "Lea Lily": {},
        "Noctilucent Dragonfly": {},
        "Strobing Horsefly": {},
        "Gleaming Magnet": {},
        "Fraudulent Mirror": {},
        "Galjim Crystal": {},
        "Hexagauge": {},
        "Spherical EM Motor": {},
        "Madame Mantis": {},
        "Pardo Spider": {},
        "Brain Terminal": {},
        "3D Printer": {},
        "Madness Hornet": {},
        "Lava Mango": {},
        "Mirrored Peacock": {},
        "Sibercaseras Mushroom": {},
        "HI9 Ion Thruster": {},
        "Sea Anemone Platter": {},
        "Gluttonutan": {},
        "Harnenga Cotton": {},
        "Absop Swallowtail": {},
        "Continental Jellyfish": {},
        "Tenacious Moth": {},
        "Katoan Leaf": {},
        "Prapaya": {},
        "Caseras Mushroom": {},
        "Noka Mirrorstone": {},
        "Joadtank": {},
        "Cane Soil": {},
        "Shiny Lamp": {},
        "Kusakiri Stag Beetle": {},
        "Muneria Flower": {},
        "Sekka Cosmos": {},
        "Scales of Justice": {},
        "Earthfreezer": {},
        "Gluttonutan Clay": {},
        "Chameleon Creeping Plant": {},
        "Amana Durian": {},
        "Gubura Cabbage Leaf": {},
        "Doragaroo": {},
        "Magical Finding Rod": {},
        "Multi-mirror Solar Drone": {},
        "5th Gen Recycler": {},
        "L-002 Degeneration Reactor": {},
        "Imposter Bug": {},
        "Sand Cucumber": {},
        "Shadow Fly": {},
        "Common Stick Insect": {},
        "Angel Stone": {},
        "Myuena Cactus": {},
        "Jet Turtle": {},
        "Dobobora Broccoli": {},
        "Phantom Tanuki": {},
        "Thornbox": {},
        "Sandstone Etching": {},
        "Wainess Fossil": {},
        "Will Pepper": {},
        "Royal Grape": {},
        "Silvery Cactaceous Resin": {},
        "Nopolith": {},
        "Denemozumi Mouse": {},
        "Fullbelly Gecko": {},
        "Jobo Primrose": {},
        "Horned Helmet": {},
        "Echo Rock": {},
        "Illogical Etchings": {},
        "Slasher Beetle": {},
        "Kepha Holly": {},
        "Shinuyuni Garlic": {},
        "Octo-suka": {},
        "Blast Chard": {},
        "Suna Watermelon": {},
        "Spine-O-Corrector": {},
        "Whip Scorpion": {},
        "Fleeting Baboon": {},
        "Spiked Pomegranate": {},
        "Kridokan Air": {},
        "Cosse Bean": {},
        "Zedis Twig": {},
        "Kiwegg": {},
        "Beagflea Squash": {},
        "Charupa Leaves": {},
        "Eradicator Eyepiece": {},
        "Ultra Filter": {},
        "Gudo Rocambole": {},
        "Steel Tail Sheath": {},
        "Exubera Stalactite": {},
        "Warbone": {},
        "Ouroboros Bracelet": {},
        "Chameleon Sand": {},
        "Mya Oats": {},
        "Perished Stone Spear": {},
        "Lost Memory Synthesizer": {},
        "Moleworm": {},
        "Strong Iron": {},
        "Maiden Guardian Star": {},
        "Drum of Valor": {},
        "Sacrificial Reactor": {},
        "Cruise Deflector AiR": {},
        "Gormless Monkey": {},
        "Bude Mugwort": {},
        "White Sand Beetle": {},
        "Taoman Acid": {},
        "Shia Cattleya": {},
        "Pomio Spore": {},
        "Crystal Butterfly": {},
        "Snowy Angelhair": {},
        "Spore Balloon": {},
        "Starmaker": {},
        "Jagitos Copper": {},
        "Dosoram Bean": {},
        "Dring Slick": {},
        "Trying Crown": {},
        "Cluster Papaya": {},
        "Straw Buoy": {},
        "Ruge Daikon": {},
        "Coldberry": {},
        "Grandan Rock": {},
        "Spirit Wand": {},
        "Intelligent Liquid Metal": {},
        "Baibai Beetle": {},
        "Yabuyabu Ointment": {},
        "Cordless Transformer": {},
        "Decoy DNA": {},
        "Mizaria Celery": {},
        "Flowering Egg": {},
        "Hard Skin": {},
        "White Cassis": {},
        "Camocloak": {},
        "L-002 Dagoo Heat Ray": {},
        "A-HAB autonomous AI": {},
        "Acton Rock Shards": {},
        "Shimmering Skin": {},
        "Brilliant Green Liquid": {},
        "Missile Wiring": {},
        "Berzerker Unit": {},
        "Thunderbolt Emblem": {},
        "Beaporge": {},
        "Sese Lily": {},
        "Diresheep": {},
        "Stargazer": {},
        "Affinity Soulchain": {},
        "Rainy Cricket": {},
        "Double Helical Salt": {},
        "Pale Maize": {},
        "Penginion": {},
        "Detilid Device": {},
        "Shido Persimmon": {},
        "Yaya Sesame": {},
        "Medusa Squid": {},
        "Emerald Grape": {},
        "Fullerene Coral": {},
        "Glassy Cricket": {},
        "Hello Transmitter": {},
        "Queen Rapture": {},
        "Stone Screw": {},
        "Exploding Pansy": {},
        "Antorus Rose": {},
        "Zalon Dirt": {},
        "Rod of Brutality +10": {},
        "Icarus Wings": {},
        "Megajolt Rattle": {},
        "Extra-large Cash Box": {},
        "Superior Scepter": {},
        "Savage Sketch": {},
        "Iron Akebi Fruit": {},
        "Exalting Paint": {},
        "Oxygen Airbrake": {},
        "Spatial Control Jointer": {},
        "Planter": {},
        "Rogebra Shockstone": {},
        "Dithblade Fragment": {},
        "Voltant Scanner": {},
        "Book of Death and Rebirth": {},
        "Solar Wind Converter": {},
        "Savage Claw": {},
        "Autoposturizer": {},
        "Cooling Lava": {},
        "Charred Crock": {},
        "Lava Chestnut": {},
        "Capricious Kettle": {},
        "Poron Tulip": {},
        "Zagyrin Cragstone": {},
        "Jaharmum": {},
        "Cliord Oil": {},
        "Dark Lantern": {},
        "Shooting Firefly": {},
        "Kyatara Onion": {},
        "Gyulali": {},
        "Brambloo Shoot": {},
        "Mottled Mums": {},
        "Nightmare Pineapple": {},
        "Dulcet Goose": {},
        "Pan-analysis Chips": {},
        "Sharpening Stone": {},
        "Autiga Powder": {},
        "Octopus Regulator": {},
        "Belzadozebu Scallions": {},
        "Gibney Jackal": {},
        "Abyssal Cricket": {},
        "Chrampoline": {},
        "Gun Snake": {},
        "Bogano Sleeping Bag": {},
        "Bullet Fly": {},
        "Stone Lens": {},
        "Cetecegem Beetle": {},
        "Charged Cayenne": {},
        "Demon Boar": {},
        "Prickly Cricket": {},
        "Lava Fox": {},
        "Bogano Weed": {},
        "Muranadium": {},
        "Elemental Battery": {},
        "Mega Muscle Builder": {},
        "FN Prototype 3": {},
        "Doom Mask": {},
    },
    "Scenic Viewpoint": { # 15
        "Arc Rock": {},
        "Atop the Giant Ring": {},
        "Azure Lagoon": {},
        "Beneath Orrh Sim Keep": {},
        "Cascade Isle": {},
        "Decapotamon Vista": {},
        "Headwater Cliff": {},
        "Kintrees": {},
        "Mgando Volcanic Crater": {},
        "Mount Edge Peak": {},
        "Orrh Sim Castle Ruins": {},
        "Skygazer Atrium": {},
        "Talon Rock Prominence": {},
        "White Phosphor Lake": {},
        "Yagami Vista": {},
    },
    "Unexplored Territory": { # 26
        "Abyss Reservoir": {},
        "Bandit Refuge": {},
        "Beachside Trove": {},
        "Behemoth Shadows": {},
        "Crater Oasis": {},
        "Cryptic Sign": {},
        "Ensanguined Font": {},
        "Ganglion Antropolis": {},
        "Great Washington Isle": {},
        "Idyll Beach": {},
        "Infernal Ledges": {},
        "Kwarah Cloister": {},
        "Mgando Mineral Spring": {},
        "Millstone Ridge": {},
        "Noctilucent Sphere Interior": {},
        "Orochi Belly": {},
        "Primeval Meadow": {},
        "Quay Hollows": {},
        "Rock Cavern": {},
        "Sandsprint Cavity": {},
        "Sentinel Nest": {},
        "Stonelattice Cavern": {},
        "Turtle Nest": {},
        "Whale Weeper": {},
        "Wonderment Bluff": {},
        "Xanadu Overlook": {},
    },
}

xenobladeXLocationGroups = {
    "Administrative District": {},
    "BLADE Barracks": {},
    "Commercial District": {},
    "Industrial District": {},
    "Ma-non Ship": {},
    "Residential District": {},
    "Primordia": {},
    "Noctilum": {},
    "Oblivia": {},
    "Sylvalum": {},
    "Cauldros": {},

    "Affinity Mission": {},
    "Mission": {},
    "Tyrant": {},
    "FN Probe": {},
    "Treasure": {},
}

def create_location_event(world, region_name, location_name, player):
    """Create a location event"""
    region = world.get_region(region_name, player)
    location_event = XenobladeXLocation(player, location_name, None, region)
    region.locations += [location_event]
    return location_event
